### ISSUE TITLE
Android adds permission even though i dont use phone number functions. (READ_PHONE_STATE)

### ISSUE THREAD

**Issue by Mura7** [react-native-community/react-native-device-info#1000]
I don't use phone number function but package automatically add of permission. I don't want use that permission `(READ_PHONE_STATE)`. How can i solve?

```
"react-native": "0.61.5",
"react-native-device-info": "^5.5.5",
```

**Comment by mikehardy** [comment]
https://github.com/react-native-community/react-native-device-info/issues?q=is%3Aissue+READ_PHONE_STATE+is%3Aclosed
