### ISSUE TITLE
DeviceInfo is empty {} , while using DeviceInfo.getDeviceCountry() 

### ISSUE THREAD

**Issue by jeevankumarkanuganti** [react-native-community/react-native-device-info#1001]
let countrycode =  **DeviceInfo**.getDeviceCountry() ;

DeviceInfo is empty {}

**Comment by mikehardy** [comment]
The example shows it works, run it.
If you have evidence to the contrary you should supply that in the form of a minimal reproducible example app on github

**Comment by jeevankumarkanuganti** [comment]
Release notes says the getdevicecountry is been removed

BREAKING CHANGE: remove is24Hour, getTimezone, isAutoTimeZone and isAutoDateAndTime, getDeviceLocale, **getDeviceCountry**, getPreferredLocales
This was the result of a survey. It removes API duplication in the react-native-community modules
Related PR: https://github.com/react-native-community/react-native-localize/pull/65
Use yarn add https://github.com/mikehardy/react-native-localize.git

as suggested i had integrated "react-native-localize" package but it is not giving me the device country . 
the device is in India but the response i am getting is "US"

any suggestions pls?

**Comment by mikehardy** [comment]
@jeevankumarkanuganti take it up with react-native-localize as it is implemented there now

**Comment by jeevankumarkanuganti** [comment]
@mikehardy ,

i had implemented "react-native-localize" but not getting the current device countryCode.

My device is in India but i am getting response as "US" instead of "IN".

Code :
 "RNLocalize.getCountry()"

**Comment by mikehardy** [comment]
@jeevankumarkanuganti I was clear. Take it up in that repository.

**Comment by jeevankumarkanuganti** [comment]
@mikehardy ,

Thanks for your response.

I took clone of the repository.

I observed the "RNLocalize.getCountry()" is giving me the mobile language country code.

settings > Languages  & Input > languages

In this is the settings has English(U.S) it is giving response as "US" and if the setting is English(India) then response of "RNLocalize.getCountry()" is "IN".

but i am looking for the device Country Code which is working before in "react-native-device-info" package. it was giving me the Exact device CountryCode but now it is removed in the package and instructed to use the "react-native-localize" which is not giving me the exact country code as before.


can you. , please help me with this?

**Comment by mikehardy** [comment]
@jeevankumarkanuganti I cannot be more clear.

OPEN AN ISSUE IN THAT REPOSITORY.

STOP POSTING HERE.
