### ISSUE TITLE
Android Build flavor as string

### ISSUE THREAD

**Issue by LonelyCpp** [react-native-community/react-native-device-info#1004]
# Feature Request

A function to get the android build flavor name.

## Why it is needed
The only build config data available in react native is `__DEV__`. On android, build flavor setting is a way to enable / disable certain app features or the way the app behaves in general. Since react native handles all the app features on the JS side, access to this info is critical. 

## Possible implementation
Implementing this will be a very simple change as android provides build flavor names from BuildConfig.FLAVOR. 
iOS of course has no concept of build flavor, so it will be a no-op on ios

If this is something that the library would have, I will raise a PR 😄

**Comment by mikehardy** [comment]
Sure. I could see this being a constant / sync even as people would need it to do very very basic project setup things (you'll see a block of a few of those when you go into the Java to add it, so there is a pattern to follow).

**Comment by mikehardy** [comment]
Please remember to add docs and example usage that explain and demonstrate it - that's also how I test new features (checking the new example usage) so it's vital. Also, add a changelog entry with a new minor (5.6.0) and add your handle in there -> free internet points :trophy:  :smile:

**Comment by avonipenti** [comment]
Any updates on this feature request?

**Comment by mikehardy** [comment]
Not that I'm aware of - if you do a search on README (to see if API exists) and issues list / PR list and it comes empty: that's the status

**Comment by tamlyn** [comment]
This might not be as straightforward as it would seem:

- As mentioned above, the flavour is available to apps in `BuildConfig.FLAVOR` and is not exposed on `android.os.Build`.
- `BuildConfig` is a special class which is generated by Gradle and is in the same package as the app (i.e. for `com.example`, the fully qualified class name would be `com.example.BuildConfig`).
- But `react-native-device-info` is a library and it doesn't have access to the application's `BuildConfig`.
- It might be possible to use reflection to load `BuildConfig` but that requires knowing the Java package name of the app (which is not necessarily the same as the `applicationId`).

I'm not an Android dev though so hopefully I've missed something.
