### ISSUE TITLE
There are multiple dependencies with different sources for `RNDeviceInfo` in `Podfile`

### ISSUE THREAD

**Issue by macorifice** [react-native-community/react-native-device-info#1005]
I have specified in my pod:
pod 'RNDeviceInfo', :path => '../node_modules/react-native-simple-device-info'

I'm getting error:
[!] There are multiple dependencies with different sources for `RNDeviceInfo` in `Podfile`:

- RNDeviceInfo (from `../node_modules/react-native-device-info`)
- RNDeviceInfo (from `../node_modules/react-native-simple-device-info`)
Any solution ?

**Comment by mikehardy** [comment]
This is rude, but, don't use modules that behave poorly enough in the ecosystem to use another module's name. That's just bad form on so many levels @itchingpixels 👎 

Open source puts the onus on the developers to collaborate, if they don't, what can I do, as a maintainer? Simply recommend you purge that package and not use it.
