### ISSUE TITLE
#ASK How to get Device fixed ID?

### ISSUE THREAD

**Issue by rinoarmadiaz** [react-native-community/react-native-device-info#1006]
# Question

Hi, i recently use getUniqueId for getting an unique id /devices,
but i have a different case, since i have several apps that connects into the same database but it seems using getUniqueId will generate different id for different apps even on the same device.

It doesn't suit with my case, i need to retrieve a device id that really unique for the device itself for android & ios. 

any suggestion? thanks

**Comment by mikehardy** [comment]
Hi there - I am not sure that's really possible. Maybe at the app layer with a combo of userid and device fingerprint. You can read more in our issues https://github.com/react-native-community/react-native-device-info/issues?q=is%3Aissue+unique+id+  but also just looking at the documentation for the underlying APIs you are using (and the links in the docs where I have put warnings) is illuminating
