### ISSUE TITLE
Problem getting version - Different version between google play and app - ¡Help!

### ISSUE THREAD

**Issue by vojeda** [react-native-community/react-native-device-info#1008]
Hello guys!

I have googled but I have not found anything related. Something strange is happening with the versions of the application that are being saved in the database.

I uploaded version 2.2 on April 27 but today a user whose version is 2.0 was registered, which is very strange since only 2.2 appears in the Play Store. (See image)

![image](https://user-images.githubusercontent.com/9805049/80669347-2af7a900-8a72-11ea-8a84-0d42253a9d99.png)

I use react-native-device-info (Version ^ 0.21.5 ") to capture the version with the DeviceInfo.getVersion () method. Could it be that the version I use is very old? I have noticed something similar not only in this case if not that with other devices too. Could it be a problem with google?

Please help if you have any ideas.

Thank you!!!

**Comment by mikehardy** [comment]
Your version is incredibly old, yes, but it is not as if the getVersion code is very complicated. It's not doing anything special and has not changed in nature with new releases

I would suspect that someone has the old APK somehow (APKPure, or swapping it via bluetooth or similar). It is not difficult at all to get an old APK for almost any app.

**Comment by vojeda** [comment]
Thanks for your answer @mikehardy 

Although the APK has been distributed for testing, I think I have not sent it to anyone who has Android 4.3, that's why I find it very strange. I thought that it could have something of the method that the version is not calculated well or that Google gives the option of downloading older apps to users with older devices, but I think this is not the case either.

Keep investigating.

Thank you!

**Comment by mikehardy** [comment]
All of those APIs have emulator images I believe, though the ones with up to date Play Services implementations only go back to API18 or so I think. That may be good enough for you to test / reproduce (or not reproduce, which is also an interesting result)
