### ISSUE TITLE
Cannot build example app - "Task 'installDebug' not found in project ':app'."

### ISSUE THREAD

**Issue by whenmoon** [react-native-community/react-native-device-info#1010]
# Bug

I cannot build example the app - I am getting the error 

> Task 'installDebug' not found in project ':app

I have tried pretty much everything I can find on the web including updating `local.properties`, cleaning the gradle cache, opening the project from Android studio and cleaning and building from there, creating variant builds.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 141.17 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.7.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: x.x.x

## Steps To Reproduce

1. clone the repo, `cd` to repo, `npm install`, `react-native run-android`
2.
...

Describe what you expected to happen:

1. Example app to build successfully. 
2.

**Comment by mikehardy** [comment]
I don't believe react-native as an executable in your `$PATH` or global packages is generally supported anymore? And it indicates that it didn't find it in your debug output above anyway so I'm not sure how that worked for you? I think the command should be `yarn android` or `npm run android`. That's what I tested just now when attempting to reproduce.

...and it installed fine for me, I can't reproduce

`npx react-native-clean-project` maybe? Or if you are creating variant builds then the name will have the variant in it, like installDevDebug or installVariantDebug

It crashed immediately on Android with a flipper issue 🤦  but that's a different problem.

**Comment by whenmoon** [comment]
Thanks - none of the above worked for me. I will carry on trying to get it to work.

**Comment by mikehardy** [comment]
ok - if you determine a root cause I'll be very curious. There's usually a reason - but obviously if I can't reproduce I'm not much help, sorry
