### ISSUE TITLE
add listener for updates to DeviceInfo.isHeadphonesConnected() 

### ISSUE THREAD

**Issue by aaronfg** [react-native-community/react-native-device-info#1013]
# Feature Request

Add way to listen for changes to the **isHeadphonesConnected**() value. 

## Why it is needed

Currently, if the user plugs in/unplugs their wired headset or turns off/on their BT headset after the component has loaded, no event is fired. 

The value of **DeviceInfo.isHeadphonesConnected()** only updates on the next render of the component.

## Possible implementation

Ideally this would be a new hook.

### Code sample

```ts
const headphonesConnected = useIsHeadphonesConnected();
```

**Comment by mikehardy** [comment]
PRs happily accepted! Otherwise this will sit

**Comment by schie** [comment]
@mikehardy, I'll take this one.
