### ISSUE TITLE
Is it possible to get deviceInfoPhone number for IOS

### ISSUE THREAD

**Issue by jeffrey-anglyeds** [react-native-community/react-native-device-info#1015]
# Feature request

Get IOS device phone number

it is for registration page, I need to validate the phone number via the tagged number in the device. it works for Android , but it seem like it doesn't work for IOS.

**Comment by mikehardy** [comment]
First you must ask "is it even possible", and the answer is that it is not
iOS does not let you get the phone number. The user will have to type it in

**Comment by mikehardy** [comment]
https://stackoverflow.com/questions/193182/programmatically-get-own-phone-number-in-ios
