### ISSUE TITLE
Do we need to ask permission from User?

### ISSUE THREAD

**Issue by santuparashetti** [react-native-community/react-native-device-info#1016]
Hi There,

I am planning to use most of the APIs from the list. But I have doubt regarding user permission. Any of APIs do need permission from Users like to use the camera we ask permission when the app starts. Like that any of these API needs permission from User so later on Google should not suspend the app from the store.

Thanks in advance.

**Comment by mikehardy** [comment]
I'm not sure what your question is? The APIs mention permissions where important. You can search on the word. If the README API documentation is incorrect in anyway please post a PR that contains the changes to make it match your findings
