### ISSUE TITLE
Getting Error while compiling my react native project in android studio react native project

### ISSUE THREAD

**Issue by nuestrovincent** [react-native-community/react-native-device-info#1018]
# Question

I dont know if i miss something to install any dependencies.
Im Getting Error while compiling my react native project in android studio.

![Caasdsadsadpture](https://user-images.githubusercontent.com/35127343/82114760-38f73a80-9791-11ea-8a58-3264d5112501.PNG)

Here is my device info
run: react-native info
![details](https://user-images.githubusercontent.com/35127343/82114813-870c3e00-9791-11ea-9045-6f4711e0ad15.PNG)

Please Send Help, thank you everyone. Newbie here and I am willing to learn

**Comment by mikehardy** [comment]
You have java errors in an unrelated module I think, hard to say, posting images is terrible form on github, hard to read them
