### ISSUE TITLE
getFreeDiskStorage get Inaccurate value

### ISSUE THREAD

**Issue by chen735623058** [react-native-community/react-native-device-info#1019]
## Summary

|             |     |
| ----------- | --- |
| Version     | 5.5.6   |
| Affected OS | iOS   |
| OS Version  | 13.3  |

## Current behavior

I use getfreediskstorage to get the remaining space size of IOS. The returned space is 62178807808, but the system shows that the remaining space is 72g.
## Expected behavior

我希望得到的剩余空间大小和系统显示的一致
I want the remaining space to be the same size as the system display

**Comment by mikehardy** [comment]
Hi there! This is a duplicate of #338 and saw some attention in #350 but no response was received from the contributor.

Contribute a PR that alters the behaviour to solve #338 and we'll merge it in

Thanks!

**Comment by chen735623058** [comment]
Thank you very much. I will wait for your merge

**Comment by chen735623058** [comment]
@mikehardy Thank you very much. I will wait for your merge

**Comment by mikehardy** [comment]
@chen735623058 sorry - we have had a misunderstanding - I am not taking any action on this. This is a community driven repository. Someone needs to contribute the feature in a working condition *then* I will merge it. No one has done that yet. It could be you! :-)
