### ISSUE TITLE
getCarrier returns 'Carrier' string on iOS device

### ISSUE THREAD

**Issue by ramyareye** [react-native-community/react-native-device-info#1021]
# Bug report

## Summary

getCarrier works well on android but on iOS I only get "Carrier" string as result!

**Comment by mikehardy** [comment]
So if I'm your co-worker and I come up to you, as the maintainer of some software and say that, what do you do? You ask for some more information right? Think of all the information you need to troubleshoot this problem, and give me that please :-)

module version, react-native version, ios version, simulator or real device etc (test both)

Then we can have a look, as this is the first report I've gotten on this API

**Comment by ramyareye** [comment]
Hi, you're right :)

I updated module to latest: `"react-native-device-info": "^5.5.8"`
React Native is 0.61.5
iOS 13.3.1
in device return "Carrier" and in emulator returns "unknown" string!

I even checked issues, google and source codes but I couldn't find anything about it!

**Comment by mikehardy** [comment]
May be that they tightened that one down or it requires permission or similar. But, good that it is returning the standard value for unknown. 

You can see for yourself what it is doing and set breakpoints etc. It's not complicated, but must not be getting a response from the underlying API

https://github.com/react-native-community/react-native-device-info/blob/2222ee0bfc9300d35204bc8d4252638d76cb0ed4/ios/RNDeviceInfo/RNDeviceInfo.m#L290-L301

**Comment by jamesst20** [comment]
Seems to not be specific to this lib
https://forums.developer.apple.com/thread/81745

Apparently it could be just returning the carrier name that the phone is locked into.

**Comment by ramyareye** [comment]
@jamesst20 so there is no way to have Carrier name in this case ? Thanks

**Comment by mikehardy** [comment]
If the code is correct and this is what the API returns, there's nothing we can do - this module is just the messenger in this case, tentatively closing as my read of that doc indicates it's the underlying API / OS

**Comment by jamesst20** [comment]
> @jamesst20 so there is no way to have Carrier name in this case ? Thanks

Can't tell :(

iOS is a very closed environment. If you figure a way to do it natively, then it can be implemented in this library just fine
