### ISSUE TITLE
getUniqueId returns different values for different apps on the same device 

### ISSUE THREAD

**Issue by djohnsonkc** [react-native-community/react-native-device-info#1022]
Just a heads up that in using getUniqueId() in 3 different apps that I'm developing and testing on my iOS device, the value returned is different on the same device for each of the 3 separate apps. Should this method be returning the same UDID value on iOS devices?

Any suggestions?

Thanks!

**Comment by mikehardy** [comment]
You MUST read the docs in the API and linked from the API here and understand the privacy implications in the area you are in.

Short answer: you have unreasonable expectations vs current privacy concerns, and the results you experience are normal.

**Comment by djohnsonkc** [comment]
I think I lot of folks may be assuming, like me, that getUniqueId would return the real device UDID. It might be good to update the doc to have a disclaimer that links to the details. Just a suggestion. Is it safe to assume that the getUniqueID value for a given app on a device will always return the same value? Thanks.

**Comment by mikehardy** [comment]
PRs to the docs very happily accepted! I have no perspective on what a new user would expect or not anymore so anyone with fresh eyes coming into it would be best suited, really. Github PR workflow for text files is all in browser and super easy
