### ISSUE TITLE
Add a method for getting signature of app.

### ISSUE THREAD

**Issue by HessiPard** [react-native-community/react-native-device-info#1023]
# Feature request
Hi, thanks for this great package.
it would be nice to add a simple method for getting signature of the app.

## Why it is needed
For security reason and check if the app is decompressed and sign again with different certificate.

There are cloner apps in store that clone a fresh copy of your app in user device and user can enter the app as a new user. for some kind of apps like games it could break your analytics data and other metrics.

Some of these cloners uses this technique to create same app as yours but with different signature.
## Possible implementation
A simple method that get your trusted signature value (Developer hard code this value in the app) and compare it with run-time returned value would be enough for check the integrity of the app.

### Code sample
```
@RequiresApi(api = Build.VERSION_CODES.P)
@ReactMethod
  public void checkSignature(int trustedValue, Promise promise) {
    try {
	  Signature[] signatures = null;
	  PackageManager pm = this.reactContext.getPackageManager();
	  signatures = pm.getPackageInfo(this.reactContext.getPackageName(), PackageManager.GET_SIGNING_CERTIFICATES).signingInfo.getSigningCertificateHistory();
	  int value = 1;
	  for (Signature signature : signatures) {
		value *= signature.hashCode();
	  }
      promise.resolve(value == trustedValue);
    }
    catch (Exception ex) {
      ex.printStackTrace();
      promise.reject(null, ex.getMessage());
    }
  }
```

**Comment by mikehardy** [comment]
That's app related, not device-related. You might like a different package. I also do this package over here: https://github.com/mikehardy/react-native-update-apk/blob/eb04c572cc5b3701ce5279c68618e5069fd70385/example/App.js#L191-L197

But there are others

**Comment by mikehardy** [comment]
(PRs over there happily accepted, and if I recall from last time I looked there was at least one other module in react-native that handled APK stuff, I'm sure they'd do PRs if the API didn't fit either)

**Comment by valascus** [comment]
@mikehardy Sorry to bring this to life, but I need a package that does exactly this. That package (react-native-update-apk) suits even less then this just to get that information. Also, I didn't find any package that does this: "Gets the current app signature". If you did find one, can you please indicate me? Otherwise, I think it would be a good feature. Thank you

**Comment by mikehardy** [comment]
Package info is not device info, that's pretty clear. If react-native-update-apk doesn't suit, propose something *there* that does, happy to collaborate, but separation of concerns is an important software concept, I am and will follow it unapologetically
