### ISSUE TITLE
Cannot get my phone number

### ISSUE THREAD

**Issue by suupham2506** [react-native-community/react-native-device-info#1025]
# Bug report

## Environment info

`react-native info` output:

```bash
# return unknown
```

Library version: 5.6.1

## Steps to reproduce

1. …
2. …

Describe what you expected to happen:

1. …
2. …

**Comment by mikehardy** [comment]
Not nearly enough info to debug. What mobile OS and version? Are permissions granted etc?
Pretend I am your employee, and I bring you this problem. Ask me all the questions you need to in order to troubleshoot it.

We can reopen this if you put all that info you need in here.
