### ISSUE TITLE
Support for 24hour/12hour time format check

### ISSUE THREAD

**Issue by tanya-marych** [react-native-community/react-native-device-info#1032]
# Feature request

In previous versions of package the was possibility to check system time format, which is not available in 5.6.1

## Why it is needed

it would really nice to have this method `is24Hour`
Due to discussion [there](https://github.com/react-native-community/react-native-device-info/issues/290) looks like it is possible to add it

## Possible implementation

is available in discussion [there](https://github.com/react-native-community/react-native-device-info/issues/290)

**Comment by mikehardy** [comment]
This API migrated to another package that works well, it will not return here:

https://github.com/react-native-community/react-native-device-info/wiki/V2-to-V3-Migration-Guide

BREAKING CHANGE: remove is24Hour, getTimezone, isAutoTimeZone and isAutoDateAndTime, getDeviceLocale, getDeviceCountry, getPreferredLocales

    This was the result of a survey. It removes API duplication in the react-native-community modules
    This is released in react-native-localize 1.2.0 - their README has the APIs to use native-localize.git and reference their new APIs usesAutoTimeZone + usesAutoDateAndTime (this should be released soon)
