### ISSUE TITLE
hasNotch() return false on Blackview A30

### ISSUE THREAD

**Issue by pebehb** [react-native-community/react-native-device-info#1036]
# Bug report
hasNotch() return false on Blackview A30

## Environment info
"react-native-device-info": "^5.6.1"

`react-native info` output:

DeviceInfo.hasNotch();

```bash
false
```

Library version: 5.6.1

## Summary
The device isn't listed in devicesWithNotch
I found that some others Blackview models have the notch, like BV9600(all versions), please add them too

**Comment by mikehardy** [comment]
PRs happily accepted - hasNotch additions are 100% community driven

**Comment by tronin** [comment]
@pebehb could you attach `DeviceInfo.getBrand()` and `DeviceInfo.getModel()` for your device?

**Comment by pebehb** [comment]
> 
> 
> @pebehb could you attach `DeviceInfo.getBrand()` and `DeviceInfo.getModel()` for your device?

getBrand: "Blackview", getModel: "A30"

**Comment by mikehardy** [comment]
you can see the 5.6.4 release for a patch link showing exactly how to PR them
