### ISSUE TITLE
java.lang.InternalError: Invoking -get2 with bad arg 0, type 'Ljava/lang/String;' not instance of 'Lorg/apache/harmony/security/x509/AuthorityKeyIdentifier;'

### ISSUE THREAD

**Issue by luolin2611** [react-native-community/react-native-device-info#1044]
## Hi ! App crash problem occurred when I configured Android, The error message is as follows.

```
java.lang.InternalError: Invoking -get2 with bad arg 0, type 'Ljava/lang/String;' not instance of 'Lorg/apache/harmony/security/x509/AuthorityKeyIdentifier;'
        at com.learnium.RNDeviceInfo.RNDeviceModule.sendEvent(RNDeviceModule.java:849)
        at com.learnium.RNDeviceInfo.RNDeviceModule.access$700(RNDeviceModule.java:66)
        at com.learnium.RNDeviceInfo.RNDeviceModule$1.onReceive(RNDeviceModule.java:112)
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:891)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5539)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
```

## I install the steps
```
1. npm install --save react-native-device-info
2. react-native link react-native-device-info
```
## My ReactNative version and Android configuration information
```
react-native-cli: 2.0.1
react-native: 0.62.2


ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 20
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
}
```

**Comment by mikehardy** [comment]
Hi there! Can you provide the package.json for your app, and ideally if you could reproduce this in public repo built off the example app that would help. The last couple times this happened I think it was a versioning issue, and I have a vague memory that it was related to an ejected app using ExpoKit

**Comment by luolin2611** [comment]
> Hi there! Can you provide the package.json for your app, and ideally if you could reproduce this in public repo built off the example app that would help. The last couple times this happened I think it was a versioning issue, and I have a vague memory that it was related to an ejected app using ExpoKit



Hi ! Thank you for your answer.

### 1. The contents of my package.json are as follows
```
{
  "name": "NetEasyCharge",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.6.1",
    "@react-navigation/drawer": "^5.8.4",
    "@react-navigation/native": "^5.6.1",
    "@react-navigation/stack": "^5.6.2",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-chart-kit": "^6.3.0",
    "react-native-device-info": "^5.6.2",
    "react-native-elements": "^2.0.4",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-image-picker": "^2.3.2",
    "react-native-orientation-locker": "^1.1.8",
    "react-native-reanimated": "^1.9.0",
    "react-native-safe-area-context": "^3.0.7",
    "react-native-screens": "^2.9.0",
    "react-native-shadow-cards": "^1.0.2",
    "react-native-svg": "^12.1.0",
    "react-native-swipe-list-view": "^3.1.3",
    "react-native-table-component": "^1.2.1",
    "react-native-vector-icons": "^7.0.0",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "7.10.4",
    "@babel/runtime": "7.10.4",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "24.9.0",
    "eslint": "6.8.0",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.58.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

### 2.I did not use Expo Kit

**Comment by mikehardy** [comment]
You are pretty up to date, hmm :thinking: 

I investigated this as thoroughly as I know how, but I'm reading the associated Java code along with that stack trace, and I simply have no idea how that could have happened.

Argument zero to the emit function is definitely supposed to be a string, and we are definitely sending one in

This looks like some sort of seriously corrupted internal state in the app somehow, but I have no good guess as to why or how :shrug:  I am sorry

**Comment by luolin2611** [comment]
> You are pretty up to date, hmm 🤔
> 
> I investigated this as thoroughly as I know how, but I'm reading the associated Java code along with that stack trace, and I simply have no idea how that could have happened.
> 
> Argument zero to the emit function is definitely supposed to be a string, and we are definitely sending one in
> 
> This looks like some sort of seriously corrupted internal state in the app somehow, but I have no good guess as to why or how 🤷 I am sorry



Haha, yes, I used the latest version of ReactNative. Although I haven't solved it, I really appreciate your reply and help. I hope that some other friends can solve it together!!

**Comment by mikehardy** [comment]
well, react-native 0.63.1 is out now ;-), but I want to be clear: I don't think that is the problem or that an update will affect it. Either someone will know something from personal experience or if you could make a clean repro we could find it maybe

**Comment by luolin2611** [comment]
> well, react-native 0.63.1 is out now ;-), but I want to be clear: I don't think that is the problem or that an update will affect it. Either someone will know something from personal experience or if you could make a clean repro we could find it maybe

🤣 🤣     Yes, it has reached 0.63.1, I try to reproduce it with the latest version, thank you!!
