### ISSUE TITLE
isEmulator and getDeviceName not returning

### ISSUE THREAD

**Issue by ManveeYew** [react-native-community/react-native-device-info#1046]
I just updated react-native-device-info to the latest version 5.6.2 and isEmulator and getDeviceName is not returning like usual. I got this instead '_nativeInterface.default.getDeviceName is not a function'. Any idea whats happening here? this is how i use it 'const deviceName = DeviceInfo.getDeviceName();'
## Summary

|             |     |
| ----------- | --- |
| React | 16.8.6 |
| React Native | 0.60.5 |
| React Native Device Info | 5.6.2 |

## Current behavior

After updated to version 5.6.2 i get this for isEmulator and getDeviceName
![Screenshot 2020-07-17 at 10 32 34 AM](https://user-images.githubusercontent.com/30171840/87742248-e67ddd00-c818-11ea-859b-a9fde7518210.png)

## Expected behavior

I should getting String as return.

**Comment by mikehardy** [comment]
Please follow the migration guides, the API signatures have changed and they return promises now
That is the classic presentation of an unresolved Promise when you print it directly to console.log
Use async/await or the xxSync() versions of the APIs
