### ISSUE TITLE
Execution failed for task ':react-native-device-info:javaPreCompileDebug'.

### ISSUE THREAD

**Issue by peyman-hakemi** [react-native-community/react-native-device-info#1048]
# Bug report

## Summary

my project was OK cupple days ago, then i start the project with react-native run-android and my build failed.

* What went wrong:
> Execution failed for task ':react-native-device-info:javaPreCompileDebug'.
> Could not resolve all files for configuration ':react-native-device-info:debugCompileClasspath'.
   > Could not find installreferrer-1.1.2.aar (com.android.installreferrer:installreferrer:1.1.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/installreferrer/installreferrer/1.1.2/installreferrer-1.1.2.aar

## Environment info

    "react-native": "0.62.2",
    "Library version": "^5.5.8",

## what i tried and not worked
gradlew clean

**Comment by mikehardy** [comment]
Looks like it's there, not sure what's wrong

https://maven.google.com/web/index.html#com.android.installreferrer:installreferrer:1.1.2
