### ISSUE TITLE
I am using office laptop , i m not getting DeviceId from this code

### ISSUE THREAD

**Issue by next-gen-2020** [react-native-community/react-native-device-info#1049]
# Question

**Comment by next-gen-2020** [comment]
import DeviceInfo from 'react-native-device-info';
 
import { getUniqueId, getManufacturer } from 'react-native-device-info';
let deviceId = DeviceInfo.getDeviceId();

![Screenshot_1595245511](https://user-images.githubusercontent.com/62024745/87934716-34127800-caad-11ea-8a57-c2274458b909.png)

**Comment by mikehardy** [comment]
The error message is pretty clear.
Looks like you haven't installed the module correctly.
