### ISSUE TITLE
NativeModule.RNDeviceInfo is null

### ISSUE THREAD

**Issue by dpisarevskiy** [react-native-community/react-native-device-info#1052]
Hello! Using Expo: "^38.0.0", "react-native": "^0.62.2", with managed workflow(without folders ios, android) got this error 
error: @react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null

How can I fix this, I can't move project to bare workflow(with ios, android)

**Comment by mikehardy** [comment]
Classic failure to auto-link most likely.
You'll have to ask Expo, if you use Expo in your project. I believe they have their own device info module.
For this module, if you can reproduce it using the example app, we can reopen and troubleshoot
