### ISSUE TITLE
Trying to getDeviceName returns null

### ISSUE THREAD

**Issue by BND10706** [react-native-community/react-native-device-info#1053]
get the following error on my ios Device using react-native vs .62

i am trying to call getDeviceName.

I am not using Pods,

Error: @react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null. To fix this issue try these steps:
  • For react-native <= 0.59: Run `react-native link react-native-device-info` in the project root.
  • Rebuild and re-run the app.
  • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
  If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-device-info

<global>
    nativeInterface.ts:14:4
loadModuleImplementation
    require.js:321:11
<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:154575:59
loadModuleImplementation
    require.js:321:11
<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:152695:42
loadModuleImplementation
    require.js:321:11
<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:134023:56
loadModuleImplementation
    require.js:321:11
<global>
    AppEntry.js:3
loadModuleImplementation
    require.js:321:11
guardedLoadModule
    require.js:201:44
global code
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:158176:3

**Comment by mikehardy** [comment]
react-native >= 0.60 is pod based now, How can you run it without pods? I'm honestly unaware it's even possible. This is not a supported configuration

**Comment by BND10706** [comment]
I guess I mean I did not install anything different. Im running the expo CLI.

**Comment by mikehardy** [comment]
Expo has it's own device info thing I think, I would try to stay inside the expo module ecosystem if I was using expo

https://docs.expo.io/versions/v38.0.0/sdk/device/

Troubleshooting Expo related problems is nearly impossible as they lag their releases and versioning becomes a dependency mess
