### ISSUE TITLE
getSerialNumberSync api error?

### ISSUE THREAD

**Issue by M45ter** [react-native-community/react-native-device-info#1056]
# Bug report
when android SDK < 26, getSerialNumberSync() always return "unknown"?

> public String getSerialNumberSync() {
>     try {
>       if (Build.VERSION.SDK_INT >= 26) {
>         if (getReactApplicationContext().checkCallingOrSelfPermission(Manifest.permission.READ_PHONE_STATE) == PackageManager.PERMISSION_GRANTED) {
>           return Build.getSerial();
>         }
>       }
>     } catch (Exception e) {
>       // This is almost always a PermissionException. We will log it but return unknown
>       System.err.println("getSerialNumber failed, it probably should not be used: " + e.getMessage());
>     }
>     return "unknown";
>   }
> 

## Environment info

`react-native info` output:

```bash
# "react-native": "0.62.2",
# "react-native-device-info": "^5.5.7",
```

**Comment by mikehardy** [comment]
I fixed your code block so it was readable - triple-backticks are your friend https://www.markdownguide.org/extended-syntax#syntax-highlighting

The API is only available from API26 on. https://developer.android.com/reference/android/os/Build#getSerial()

**Comment by M45ter** [comment]
this is better?
```java
if (Build.VERSION.SDK_INT >= 26) {
...
} else {
     return Build.SERIAL;
}
```

**Comment by mikehardy** [comment]
Please read the docs for the API you propose: https://developer.android.com/reference/android/os/Build#SERIAL

> A hardware serial number, if available. Alphanumeric only, case-insensitive. This field is always set to Build#UNKNOWN.

So, no, that won't help. Getting hardware identifiers is a losing proposition, you're fighting the operating systems now. They don't want to give you hardware identifiers. My best advice is to stop trying. Use something like Firebase Instance ID or similar

**Comment by M45ter** [comment]
ok, thanks

**Comment by stewartmcgown** [comment]
We're deploying a lot of Sunmi V2 devices, which allow access to the serial number via BUILD.SERIAL. I don't see a reason to not have the else statement and return BUILD.SERIAL if it isn't unknown?

**Comment by stewartmcgown** [comment]
In case someone stumbles across this from Google and is in the same very specific sitation:

Add this to`patches/react-native-device-info+7.0.2.patch`:
```
--- a/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
+++ b/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
@@ -655,6 +655,8 @@
         if (getReactApplicationContext().checkCallingOrSelfPermission(Manifest.permission.READ_PHONE_STATE) == PackageManager.PERMISSION_GRANTED) {
           return Build.getSerial();
         }
+      } else {
+        return Build.SERIAL;
       }
     } catch (Exception e) {
       // This is almost always a PermissionException. We will log it but return unknown
```
Grab these two packages:

```
"patch-package": "^6.2.2",
"postinstall-postinstall": "^2.1.0",
```

Then add a postinstall script:

```
"scripts": {
   ...,
  "postinstall": "patch-package"
}
```

**Comment by mikehardy** [comment]
Fascinating, I suppose if some hardware is actually returning it (quite unexpected / contrary to the API docs...) adding an else would be acceptable. If you PR it I'll merge it @stewartmcgown

**Comment by stewartmcgown** [comment]
I should add that this is specifically on Android 7, which the devices are stuck on. I understand this is the last version where BUILD.SERIAL was populated Vs getSerial

**Comment by stewartmcgown** [comment]
@mikehardy tiny pr submitted!

**Comment by mikehardy** [comment]
all PRs are might! :laughing: - thanks
