### ISSUE TITLE
Is there a way to get the device name when using an emulator?

### ISSUE THREAD

**Issue by jauggy** [react-native-community/react-native-device-info#1060]
When I tried  DeviceInfo.getDeviceName() it returned something like AOSP on IA Emulator. I want to get something descriptive of the device type e.g. Pixel 2. Is this possible?

**Comment by mikehardy** [comment]
No - you can trace the code and see the APIs we use, they are what the system provides.
The emulator is always just an emulator, the "device" you select for emulators is literally only skin deep. It affects the frame, the resolution, and whether Play Store is available for the device but that's it, none of the internals
