### ISSUE TITLE
react-native-device-info NativeModule.RNDeviceInfo is null 

### ISSUE THREAD

**Issue by AlessioCamm** [react-native-community/react-native-device-info#1066]
I got this error : 
@react-native-community/react-native-device-info NativeModule.RNDeviceInfo is null 
![Simulator Screen Shot - iPhone 11 - 2020-08-25 at 17 29 03](https://user-images.githubusercontent.com/22292009/91194488-7bb5a080-e6f8-11ea-80a2-3403f6730f78.png)
On iOS (not test on Android)

Someone as a solution ? I Tried a lot of things

`react-native-cli: 2.0.1`
`react-native: 0.60.6`
`macOS 10.15.6`

**Comment by mikehardy** [comment]
If the native device is null, you have unsuccessfully integrated the module.
It is not linked for some reason, and nothing will work.
You may examine the example app (or it's construction script https://github.com/react-native-community/react-native-device-info/blob/master/refresh-example.sh) to see how to integrate properly
