### ISSUE TITLE
How are Android device types determined in the getDeviceType method

### ISSUE THREAD

**Issue by Solly74** [react-native-community/react-native-device-info#1067]
I searched for this with not much luck but I'd like to know what the constraints are for determining what is a tablet vs handset vs tv?

I am aware of the screen sizes in Manifest but want to know what this library uses as constraints or parameters please?

**Comment by mikehardy** [comment]
It's open source, just follow the code?

https://github.com/react-native-community/react-native-device-info/blob/f617863017dce0daf623504e7987652561f4ee49/src/index.ts#L1121-L1129

to ios https://github.com/react-native-community/react-native-device-info/blob/f617863017dce0daf623504e7987652561f4ee49/ios/RNDeviceInfo/RNDeviceInfo.m#L105-L113

to android https://github.com/react-native-community/react-native-device-info/blob/f617863017dce0daf623504e7987652561f4ee49/android/src/main/java/com/learnium/RNDeviceInfo/resolver/DeviceTypeResolver.java#L29-L93

**Comment by Solly74** [comment]
Apologies! I should've. Thank you 👍
