### ISSUE TITLE
Doesn't work on windows vNext - e.g. getApplicationName() returns Cannot read property 'appName' of undefined

### ISSUE THREAD

**Issue by exotexot** [react-native-community/react-native-device-info#1070]
I cannot get Device Info to work in an react-native-windows environment.

I feel like I might have trouble understanding how to properly integrate dependencies for react-native-windows. Am I correct that there are no special linking steps required (e.g. comparing to https://react-native-community.github.io/async-storage/docs/link#windows) ?

When I run console.log(DeviceInfo.getApplicationName()) I'm getting an error:

C:\dev\...\node_modules\react-native-windows\Libraries\Core\ExceptionsManager.js:76 TypeError: Cannot read property 'appName' of undefined

System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 7.04 GB / 15.97 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.6.30128.74 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: ^4.12.0 => 4.12.0
    react: 16.11.0 => 16.11.0
    react-native: ^0.62.0-0 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by mikehardy** [comment]
Hi there! Sorry, I have no react-native-windows setup, and this is new functionality from @tero-paananen  in #1059 - any solution will have to come via a collaboration between you

**Comment by tero-paananen** [comment]
I am using my PR and it works. I try to test release v6.0.1 soon

**Comment by tero-paananen** [comment]
I cloned from the master version 6.0.1 and managed to run windows example app by following these https://github.com/react-native-community/react-native-device-info/blob/master/example/win-how-to-build.md

**Comment by tero-paananen** [comment]
You are missing line `PackageProviders.Add(new RNDeviceInfo.ReactPackageProvider());` from your `App.xaml.cs` 

(I removed that line and start to get same error than you)

**Comment by exotexot** [comment]
So I'm not linking the package correctly. I'm using the c++ version of react-native-windows, so I have no App.xaml.cs file, but a App.xaml which holds App.cpp where I'm linking packages like so:

PackageProviders().Append(winrt::ReactNativeAsyncStorage::ReactPackageProvider());
PackageProviders().Append(winrt::ReactNativeNetInfo::ReactPackageProvider());

To follow in that fashion I added: 
PackageProviders().Append(winrt::RNDeviceInfo::ReactPackageProvider());

and also added the reference to my solution and also added the pch.cpp

#include "winrt/ReactNativeAsyncStorage.h"
#include "winrt/ReactNativeNetInfo.h"
#include "winrt/RNDeviceInfo.h"

![device-info-error](https://user-images.githubusercontent.com/10153413/92027495-ec953200-ed62-11ea-9054-cf348210d385.PNG)

**Comment by tero-paananen** [comment]
I managed to build C++ app using this C# module but it does not start

- add referene to `RNDeviceInfo`
- build x64 debug app once (after that winrt/RNDeviceInfo.h can be found)
- `#include "winrt/RNDeviceInfo.h"` into pch.h
- `using namespace winrt::RNDeviceInfo;` into App.cpp
- `PackageProviders().Append(winrt::RNDeviceInfo::ReactPackageProvider());` into App.cpp before` InitializeComponent();`

App builds but execution fails into 
```
Exception thrown at 0x00007FF92683A719 in HelloCS.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x0000006DD96F97B8.
Exception thrown at 0x00007FF92683A719 in HelloCS.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
```
I did not found solution this yet. Help needed.

**Comment by exotexot** [comment]
Hi Tero I found a solution and got it running!

Basically by following the same steps as: https://react-native-community.github.io/async-storage/docs/link/#windows

Open your solution in Visual Studio.

Right click Solution icon in Solution Explorer > Add > Existing Project. Select \node_modules\react-native-device-info\windows\RNDeviceInfo\RNDeviceInfo.csproj

Add a reference to RNDeviceInfo in your main application project.
Right click main application project > Add > Reference... Check RNDeviceInfo from Solution Projects.

(Here, as you suggested I build the application)

Add #include "winrt/RNDeviceInfo.h" to pch.h.
Add PackageProviders().Append(winrt::RNDeviceInfo::ReactPackageProvider()); before InitializeComponent(); in app.cpp.

Heres one more important step. After having had troubles using the C# version of RNFS, I came across this article: https://devblogs.microsoft.com/oldnewthing/20200615-00/?p=103868 which suggests, in a mixed c++/c# scenario, to set the minimum windows version to Windows 10, Build 15063.

To do so:

Right click on your C# solution (RNDeviceInfo) -> Properties. In the Library tab under Targeting set the Min version accordingly. 

![rndi-minsdk](https://user-images.githubusercontent.com/10153413/92093925-2c483200-edd4-11ea-9c4c-52338021a711.png)

After that it worked for me :)
Trying the same approach for your sensitive info module and will report back afterwards.

**Comment by tero-paananen** [comment]
Interesting, i hope that will help us!

So rn-device-info has currently  `<TargetPlatformMinVersion>10.0.16299.0</TargetPlatformMinVersion>`  and we should set is lower 15063. I will check that myself also and make new PR about that change

**Comment by mikehardy** [comment]
Thank you @tero-paananen and @exotexot for collaborating on this ! I will happily merge anything to get react-native-windows going, I want the platform to work well for everyone I just don't have a windows rig (yet?) to test so your efforts are vital :bow:

**Comment by tero-paananen** [comment]
See the PR   https://github.com/react-native-community/react-native-device-info/pull/1072

**Comment by mikehardy** [comment]
https://github.com/react-native-community/react-native-device-info/releases/tag/v6.0.2
