### ISSUE TITLE
getSerialNumber() not working

### ISSUE THREAD

**Issue by PrantikMondal** [react-native-community/react-native-device-info#1071]
# Bug report
const serialNumber = DeviceInfo.getSerialNumber();
I am receiving serialNumber value is unknown all the time.
My test device are:  Samsung M10, Huawei honor 7x, One Plus 7t. 

Version used: 
react: 16.9.0,
react-native: 0.61.5
react-native-device-info-2 : 0.1.1

**Comment by mikehardy** [comment]
working exactly as documented, for reasons linked:

https://github.com/react-native-community/react-native-device-info#getserialnumber

**Comment by PrantikMondal** [comment]
> working exactly as documented, for reasons linked:
> 
> https://github.com/react-native-community/react-native-device-info#getserialnumber

Not working for me. It is showing me this error: 
[TypeError: undefined is not a function]

Other functions are working fine. If there was any installation or linking issue then other function should not work. But for me, except this getSerialNumber(), other is working fine. So please keep open this issue until get a solution.

**Comment by mikehardy** [comment]
No, it will remain closed until you can provide a reproduction based on the example https://github.com/react-native-community/react-native-device-info/blob/master/example/App.js#L172 - which works last time I ran it (just before last release)

**Comment by NgocUyen297** [comment]
As far as I know, retrieving the serial number of the device has been restricted due to certain policies regarding sensitive information, and you need to provide specific permissions to access the serial number. Otherwise, in some cases, it will return the value "unknown."
Document: 
https://developer.android.com/reference/android/os/Build#getSerial()
