### ISSUE TITLE
BundleID

### ISSUE THREAD

**Issue by badredaha** [react-native-community/react-native-device-info#1074]
Hi,

In the documentation the BundleId a string but when i tested the bundleId is a Promise !

**Comment by mikehardy** [comment]
You may have old version installed?

https://github.com/react-native-community/react-native-device-info/blob/0808195a3b905ead1350fadb50fbf1b67a26f69f/src/index.ts#L282-L292

https://github.com/react-native-community/react-native-device-info/blob/0808195a3b905ead1350fadb50fbf1b67a26f69f/example/App.js#L76

It is a string

**Comment by abdelwehed** [comment]
Hello,

I had the same problem and i upgraded to the latest version, and when i did that the value becomes undefined.
let bundleId = DeviceInfo.getBundleId(); ==> bundleId undefined !

**Comment by mikehardy** [comment]
Reproduce it with the example please
