### ISSUE TITLE
Possible bug in getFreeDiskStorageSync?

### ISSUE THREAD

**Issue by VioletChow** [react-native-community/react-native-device-info#1076]
# Question

I believe there is something wrong in the following codes of RNDeviceModule. getFreeDiskStorageSync

`long rootAvailableBlocks = getTotalAvailableBlocks(dataDir, intApiDeprecated);
      long rootBlockSize = getBlockSize(rootDir, intApiDeprecated);
      double rootFree = BigInteger.valueOf(rootAvailableBlocks).multiply(BigInteger.valueOf(rootBlockSize)).doubleValue();

      long dataAvailableBlocks = getTotalAvailableBlocks(rootDir, intApiDeprecated);
      long dataBlockSize = getBlockSize(dataDir, intApiDeprecated);
      double dataFree = BigInteger.valueOf(dataAvailableBlocks).multiply(BigInteger.valueOf(dataBlockSize)).doubleValue();`

`long rootAvailableBlocks = getTotalAvailableBlocks(dataDir, intApiDeprecated);`

`long dataAvailableBlocks = getTotalAvailableBlocks(rootDir, intApiDeprecated);`

The values of dataDir is assigned to rootAvailableBlocks while the values of rootDir is assigned to dataAvailableBlocks, it is intended or it is a bug?

**Comment by mikehardy** [comment]
Probably a bug - however, in this case did we get lucky since in the end we just add them together? Either way, PRs happily accepted!

**Comment by violetchow2611** [comment]
Since they're multiplying the wrong block size, so it may be incorrect. I've submitted a PR to fix this.

**Comment by mikehardy** [comment]
Yeah, I realized that later as I was drifting off to sleep :sweat_smile: - I think we are lucky in that the block size will almost always be the same, so no one likely saw symptoms of the error, but I do agree it's an error. Thanks so much for the PR!
