### ISSUE TITLE
Function hasNotch

### ISSUE THREAD

**Issue by Ilya1995** [react-native-community/react-native-device-info#1080]
"react-native": "0.62.2"
"react-native-device-info": "^6.0.4"

device - Pixel_3_XL_API29

hasNotch() - false

**Comment by mikehardy** [comment]
Hi there! This module depends entirely on community contributions, if there is a device missing in the notch support device table, you'll need to submit a PR to add it, examples are in the list of merged pull requests - it's quite easy, but I don't add them myself, I just merge PRs. Cheers
