### ISSUE TITLE
typescript: getPowerState promise return type is an empty object

### ISSUE THREAD

**Issue by ferdicus** [react-native-community/react-native-device-info#1081]
# Question
Thanks for this repo 🎉 
I've checked the open issue and stackoverflow however couldn't find any tickets concerning this. 
If there is anything open, I would be grateful if you could point me towards it and am sorry for opening this ticket 🙇 

------

While using `device-info` I noticed, that the return type for `getPowerState` is defined as 
`export declare function getPowerState(): Promise<{}>;` within `index.d.ts`

which leads to a warning when used like this:
```js
  const { batteryLevel, lowPowerMode, batteryState } = await getPowerState();
```
Warning reads as follows: `Property 'batteryLevel' does not exist on type '{}'.`

Here is where the export is defined in `src/index.ts`:
https://github.com/react-native-community/react-native-device-info/blob/f617863017dce0daf623504e7987652561f4ee49/src/index.ts#L1069-L1074

Shouldn't it rather be:
`export declare function getPowerState(): Promise<PowerState> | {};` 
as it is for `usePowerState`?

`export declare function usePowerState(): PowerState | {};`

Thanks in advance and again, sorry if this is know 🙇

**Comment by mikehardy** [comment]
Hi there! thanks for opening this - it does seem like it should be as you say, with an `PowerState | {}`, if you post a PR we can merge it

**Comment by ferdicus** [comment]
> Hi there! thanks for opening this - it does seem like it should be as you say, with an `PowerState | {}`, if you post a PR we can merge it

Thanks @mikehardy, opened PR https://github.com/react-native-community/react-native-device-info/pull/1082
