### ISSUE TITLE
DRYing up index code base

### ISSUE THREAD

**Issue by schie** [react-native-community/react-native-device-info#1085]
# Feature request
Reduce long-windedness and redundancy of the source code in the index file.

## Why it is needed
There is a recurring pattern in the source code that can be be made less verbose.
While this is not _needed_ per se, it is very tedious, long-winded, and redundant logic.
There is also a small discussion about this issue [here](https://github.com/react-native-community/react-native-device-info/pull/1083).

The below example represents the vast majority of the getters in the file.

```ts
let someMemoValue;
export async function getSomething() {
  if (Platform.OS == 'x' || Platform.OS == 'y' || ...) {
    someMemoValue = await RNDeviceInfo.getSomething();
  } else {
    someMemoValue = SOME_DEFAULT_VALUE;
  }
  return someMemoValue;
}

export function getSomethingSync() {
  if (Platform.OS == 'x' || Platform.OS == 'y' || ...) {
    someMemoValue = RNDeviceInfo.getSomethingSync();
  } else {
    someMemoValue = SOME_DEFAULT_VALUE;
  }
  return someMemoValue;
}

```

## Possible implementation

To somewhat solve this tedium and redundancy, I propose a convenience function that generates the Async and Sync functions.

### Code sample

The following snippet shows how the previous code sample could be rewritten w/out any breaking changes.

```ts
export const [getSomething, getSomethingSync] = getSupportedPlatformInfoFunctions({
  getter: () => RNDeviceInfo.getSomething(),
  syncGetter: () => RNDeviceInfo.getSomethingSync(),
  defaultValue: SOME_DEFAULT_VALUE,
  supportedPlatforms: ['android', 'ios', ...],
});
```

_Note: I went with passing in `getter` and `syncGetter` functions to_
- avoid having to pass around more strings
- avoid being overly terse
- avoid being, possibly, more error-prone

The function, `getSupportedPlatformInfoFunctions` , could also bet expanded to include the `useOnMount` hooks, but that's a bit out-of-scope for what I want to do, for meow. 

<hr />
<br/>
If we're cool with this implementation or with some minor tweaks, I'll make a PR soon that'll include a rewrite of one or two sets of the existing getters.
<br/>
<br/>
Thoughts?

**Comment by mikehardy** [comment]
Seems like a fine first cut at it, one of those kind of obvious in hindsight / after you see it sort of things, but I clearly did not think of it :-). Would love to see what it looks like in practice, seems like it will be a nice little table for each bit of info vs the fluffy if/else chunks in there now
