### ISSUE TITLE
getUniqueID is equal to UUID ? 

### ISSUE THREAD

**Issue by Moji0098** [react-native-community/react-native-device-info#1087]
uuid format is similar to e.g. : _6c84fb90-12c4-11e1-840d-7b25c5ee775a_
but getUniqueID output is similar to e.g. : _d9af09d7e68041ea_

some body help me to define  :)

**Comment by mikehardy** [comment]
They are what they are. Define what? The APIs are documented and return identifiers you may use in the way the documents say you may use them. If you want a more specific answer it will likely be either use-case or project-specific, and will vary by platform so you will need to be very specific

**Comment by Moji0098** [comment]
thanks for your reply dude :)
i have a question ! do u know how about an uuid format and length ?

**Comment by mikehardy** [comment]
Make no assumptions on format and length unless you want to depend on the internal implementation, which is not a good software programming practice

**Comment by Moji0098** [comment]
then uuid has not special format ? DeviceInfo.getUniqueID() give me uuid that i want ?

**Comment by mikehardy** [comment]
In the API it is documented to return a string. It's a unique string for the device. You can read as much into that or as little as you want.

**Comment by IamNotHuman** [comment]
@mikehardy I think that what @Moji0098 is trying to say is that. Why getUniqueID is not returning a UUID v4 (16 bytes or 128 bits) when calling it form Android? The answer is that IOS does standardises it’s self with that unique identifier but Android does not. Thats why you get 2 diffrent formats depending on the platform.
