### ISSUE TITLE
getDeviceID for iOS

### ISSUE THREAD

**Issue by mykelaballe** [react-native-community/react-native-device-info#1093]
# what does the value after the "iPhone.." in getDeviceID? We tried using iPhone 6s and it showed "IPhone8, 1" and also on an iPhone 7 device, it showed "iPhone9, 3'

**Comment by mikehardy** [comment]
Is this a bug report? It's a large-bold statement, which reads oddly as a question or bug report.

If there's a problem please post a reproduction based on the example app, or even better a PR

It's open source, you can see here:

https://github.com/react-native-community/react-native-device-info/blob/50d62fb6d843a017a3c5eaa8b3057d7fe1dea6fb/ios/RNDeviceInfo/RNDeviceInfo.m#L165-L269
