### ISSUE TITLE
RNDeviceInfo_batteryLevelIsLow fire multiple times when battery is low in IOS

### ISSUE THREAD

**Issue by vishgoel007** [react-native-community/react-native-device-info#1094]
# Question
Currently `RNDeviceInfo_batteryLevelIsLow` fire multiple times when battery is low and its state level changes. But what i want is `RNDeviceInfo_batteryLevelIsLow` fire only when battery becomes low (i.e below 20%) and don't fire again when batter state level changes even when batter is considered low. 
Is it possible to achieve via this library if yes how can i achieve that ?

Thanks in advance.

**Comment by mikehardy** [comment]
The library itself doesn't store state, so it's not possible for the library to know if it ever triggered that the level was low.

If you require "fire once and only once for low battery" you'll need a project-specific state solution, like ReSub or redux or similar that listens to this specific RNDeviceInfo event as well as the more general battery level, and does the low battery state toggle that's appropriate for your app
