### ISSUE TITLE
Is listeners work even if app is killed in IOS ?

### ISSUE THREAD

**Issue by vishgoel007** [react-native-community/react-native-device-info#1096]
# Question
Is listeners like (RNDeviceInfo_batteryLevelDidChange, RNDeviceInfo_batteryLevelIsLow, RNDeviceInfo_powerStateDidChange) work if app is in killed state in IOS ?

What i want is to listen to those listeners in background when app is killed and do some actions.

Thank you in advance.

**Comment by mikehardy** [comment]
@vishgoel007 how did it go when you tried it?

**Comment by vishgoel007** [comment]
@mikehardy It didn't work.

**Comment by mikehardy** [comment]
Then it doesn't work
There is a great deal of information on line about what exactly will wake up your app in the background on iOS and what won't, device info changes like this will not. High priority cloud messages, occasional background refresh, VOIP calls, Geolocation updates - those will do it
