### ISSUE TITLE
Device CountryName always returns locale code

### ISSUE THREAD

**Issue by imbudhiraja** [react-native-community/react-native-device-info#139]
Here is my code:
import DeviceInfo from 'react-native-device-info';
let country_Name = DeviceInfo.getDeviceCountry();
console.log(country_Name); // US

**Comment by abhideepmallick** [comment]
@imbudhiraja could you solve this? Facing similar issue.

**Comment by machour** [comment]
Closing this as no feedback was provided.

**Comment by smithaitufe** [comment]
I experience this in Android.

**Comment by machour** [comment]
Thanks for the feedback @smithaitufe !
Want to submit a PR for this?

**Comment by smithaitufe** [comment]
@machour I will try to look into it to see how we can resolve it

**Comment by garavm** [comment]
I too face the same issue.

I tested with multiple devices(mobile phones) from same location(India) and the country is not unique.

The below device shows country as `IN`
```
Device: Redmi
Model: Redmi Y1
Android Version: 7.1.2
```
The below device shows country as `US`
```
Device: Moto
Model: Moto G4 Plus
Android Version: 7.0
```

**Comment by imbudhiraja** [comment]
This issues occurs due to the phone language selected in setting. If selected lang is English(US) it return country as USA , if selected lang is English(IN) it will return India.

Thanks

**Comment by garavm** [comment]
Okay thanks

**Comment by ashokkumar88** [comment]
@imbudhiraja then how to know the actual device country?

**Comment by imbudhiraja** [comment]
@ashokkumar88 you can get this information from geographical location of devices. In that case you always get mobile device current location.

**Comment by ziyafenn** [comment]
I believe this issue shouldn't be closed as device country shouldn't be based on locale. On android, the country is based on Google accounts country. This needs to be fixed.

**Comment by mikehardy** [comment]
I'm going to tag this for #307 as it would be a breaking API change to rename it, but yes "getDeviceCountry()" makes you think it is geographic location, not locale selection.

**Comment by mikehardy** [comment]
This is based on locale and that's all we can do unless we use location services, which we are not going to do, there are other projects that do that well

thinking further, there is another react-native-community project that handles localization better and this isn't really device specific, we should remove these completely in device-info 2.0 in favor of this module: https://github.com/react-native-community/react-native-localize

For actual location you should use the location APIs

**Comment by mikehardy** [comment]
Running a poll with a proposal to defer to @react-native-community/react-native-localize package where this is likely handled better https://github.com/react-native-community/react-native-device-info/issues/627

**Comment by shivamtiwari8736** [comment]
> @ashokkumar88 you can get this information from geographical location of devices. In that case you always get mobile device current location.

HI @imbudhiraja How to do this. I need to fetch country code of the country in which device is being operated.

**Comment by mikehardy** [comment]
@shivamtiwari8736 if you want the country of the locale the device is set to - we moved that API to the react-native-localize package per the v2->v3 changelog in the wiki 

The word "operated" to me means "a device being used by a user" as a current thing, so if the user is from Costa Rica (their locale is set to es-CR) you will get that from react-native-localize, even if they are traveling temporarily to Ecuador (es-EC). To get the actual country they are in you will need to use something GPS/Location based, which is out of scope for this package

**Comment by cisplRejjak** [comment]
> getDeviceCountry not working

**Comment by mikehardy** [comment]
@cisplRejjak Closed issue. Removed API. Documented in the changelog, migration guide and release notes. Discussed in the comment above the one you posted.
