### ISSUE TITLE
ios: getUserAgent not same as real user agent !

### ISSUE THREAD

**Issue by atteia** [react-native-community/react-native-device-info#142]
hello
I get user agent 
`Mozilla/5.0 (iPhone; CPU iPhone OS 10_1 like Mac OS X) AppleWebKit/602.2.14 (KHTML, like Gecko) Mobile/14B72`
when using your **DeviceInfo.getUserAgent()**

but the real useragent which posted to Apache is 
`AppName/1 CFNetwork/808.1.4 Darwin/16.3.0`

can I get the real one ?

**Comment by mikehardy** [comment]
I believe this is related to how we get the user agent. Whether it's using native networking primitives within react-native, or using webviews. We get the WebView, this is covered elsewhere but if you want the react-native primitive response you'd need a new API. Either way, resolving this is very stale and it's covered elsewhere
