### ISSUE TITLE
Remove Print Stack Trace When There is No Permission for Bluetooth

### ISSUE THREAD

**Issue by vinayan3** [react-native-community/react-native-device-info#164]
https://github.com/rebeccahughes/react-native-device-info/blob/master/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L109 

This print statement is alarming when you are using `adb logcat` debugging.

**Comment by machour** [comment]
Yes, I'm all for removing those debug statements, but we still need a way to show them to the developer as a hint if something went wrong..
Maybe document that fact?

**Comment by mikehardy** [comment]
in #307 as we convert to Promises, we can just reject with the error message

**Comment by mikehardy** [comment]
I just implemented this for v3
