### ISSUE TITLE
tvOS / Apple TV support

### ISSUE THREAD

**Issue by alexthegoodman** [react-native-community/react-native-device-info#170]
Are there any plans to integrate this with tvOS? RN supports this officially now, and I'm betting that this implementation won't take too much time. Thoughts?

**Comment by alexthegoodman** [comment]
For any other curious individuals, a good guy helped out here: https://github.com/react-native-community/react-native-svg/issues/304#issuecomment-293257574

**Comment by machour** [comment]
Seems like a sound idea.

**Comment by mikehardy** [comment]
https://github.com/react-native-community/react-native-device-info/pull/235
