### ISSUE TITLE
getBuildNumber() returns 1 when my build # in xcode is 4

### ISSUE THREAD

**Issue by agersoncgps** [react-native-community/react-native-device-info#209]
<img width="358" alt="screenshot 2017-08-29 20 26 08" src="https://user-images.githubusercontent.com/336441/29849985-595822f4-8cf8-11e7-8955-466a0dffbe33.png">

**Comment by agersoncgps** [comment]
To fix this change line 184 in RNDeviceInfo.m to 

`@"buildNumber": [[NSBundle mainBundle] objectForInfoDictionaryKey: (NSString *)kCFBundleVersionKey],`

**Comment by mikehardy** [comment]
I just pulled master and tested this, I can't reproduce. I get the correct build number (from Info.plist::CFBundleVersion indicentally - manual or XCode changes to the file worked)
