### ISSUE TITLE
getBuildNumber() returns string in iOS and number in Android

### ISSUE THREAD

**Issue by grifotv** [react-native-community/react-native-device-info#214]
It would be nice to keep it consistent. Should the method `getBuildNumber()` return a string or a number?

**Comment by adyanced** [comment]
In my case the returned buildNumber is alway added by 0x100000. So versionCode 6 will be displayed as  1048582. I read the code and find it's not dute to react-native-device-info, maybe a bug of android sdk.
My project's info:
    compileSdkVersion 25
    buildToolsVersion "25.0.3"

**Comment by leethree** [comment]
Agree it should be consistent. Returning a number on Android doesn't match both the documentation and the flow typings.

**Comment by ericlewis** [comment]
Ideally, this should always return a number I think. In case developers would like to operate on it's value.

**Comment by mikehardy** [comment]
Just merged the change that makes them both string, will go in v3
