### ISSUE TITLE
Time zone never updates

### ISSUE THREAD

**Issue by testshallpasswork** [react-native-community/react-native-device-info#215]
I found an issue where if you change the device's timezone and then do `DeviceInfo.getTimezone()` it will result in the time zone it was originally when app initially loaded and not the changed timezone.

react-native-device-info: **0.9.8**
react-native: **0.46.3**
Platform: **iOS and Android**

**Comment by machour** [comment]
This is a know limitation of the current version.
Version 1.0.0 will ship with events (#307)
Closing this issue for now.

**Comment by testshallpasswork** [comment]
For anyone that's curious, my workaround was creating a separate bridge module to query the time zone each time vs. only initially as this package does.

**Comment by machour** [comment]
Thank you @testshallpasswork. Is this work publicly available?

**Comment by testshallpasswork** [comment]
It is not but if interest is high I can share some details or post a gist.

**Comment by machour** [comment]
It definitely is for me :)

**Comment by testshallpasswork** [comment]
Ok, here are the highlights: 

```objective-c
// iOS bridge
//  ....
RCT_EXPORT_METHOD(getTimeZone:(RCTResponseSenderBlock)callback)
{
  callback(@[@{@"timeZone": [self timeZone]}]);
}
- (NSString*)timeZone
{
  NSTimeZone *localTimeZone = [NSTimeZone localTimeZone];
  return localTimeZone.name;
}
// ...
```
```java
// Android bridge
// ...
@ReactMethod
public void getTimeZone(final Callback callback) {
    try {
        WritableMap map = Arguments.createMap();
        map.putString("timeZone", TimeZone.getDefault().getID());
        callback.invoke(map);
    } catch (Exception e) {
        WritableMap map = Arguments.createMap();
        map.putString("error", "Sorry, could not get time zone. Please try again.");
        callback.invoke(map);
    }
}
// ...
```
```javascript
// react-native side
// ...
const TimeZoneManager = NativeModules.TimeZoneManager;
// ...
function getTimeZone(callback) {
  TimeZoneManager.getTimeZone(res => callback(res.timeZone));
}
// ...
```

**Comment by sam1463** [comment]
@testshallpasswork @machour any chance we could get this feature into the library before the next major version number, maybe by adding it as a separate method from the current synchronous `getTimeZone` method? It would be really helpful to have this.

**Comment by machour** [comment]
@sam1463 I wouldn't mind adding it if a PR was submitted :)

**Comment by sam1463** [comment]
@testshallpasswork would you mind submitting a PR with your workaround?

**Comment by testshallpasswork** [comment]
I ran into some issues with the react-native-device-info-test repo. I will spin up a fresh react-native project to test then push changes. Sorry for delay.

**Comment by sam1463** [comment]
@testshallpasswork any update on this?

**Comment by mikehardy** [comment]
The best course is to migrate to react-native-localize which already implements this with a listener for change events so you can re-fetch if and only if the timezone updates: https://github.com/react-native-community/react-native-localize#gettimezone

**Comment by mikehardy** [comment]
https://github.com/react-native-community/react-native-device-info/issues/627
