### ISSUE TITLE
Check if app is on TestFlight/Google Play Beta

### ISSUE THREAD

**Issue by lucasbento** [react-native-community/react-native-device-info#228]
***This is a feature request, please let me know whether it's valid for the project or not.***

---

### Description

A simply function that returns `true` if the app has been downloaded through TestFlight or Google Play Beta, e.g. `isTesting()`.

The use-case is that I want to print out errors on screen if it's on TestFlight and `Build Configuration === 'Release'` but not on production (downloaded from store).

**Comment by maxkomarychev** [comment]
I was recently looking for a way to check this too. It looks like this is a good project to place such functionality.

**Comment by GantMan** [comment]
I wrote this forever ago:  https://github.com/GantMan/react-native-siren

It might be useful.  I haven't updated it in a while.

**Comment by markhomoki** [comment]
Would be nice to have a function to check this. I am not sure if it is possible tho.

**Comment by agates4** [comment]
For those searching for a solution, here is the solution for iOS TestFlight. I am unaware of any google play solution. 

In your Xcode workspace, create a file `ProdChecker.h`
```
#ifndef prodChecker_h
#define prodChecker_h

#import <React/RCTBridgeModule.h>

@interface ProdChecker : NSObject <RCTBridgeModule>
@end

#endif /* prodChecker_h */
```

In your Xcode workspace, create a file `ProdChecker.m`
```
#import "ProdChecker.h"

@implementation ProdChecker

RCT_EXPORT_MODULE();

RCT_REMAP_METHOD(isTestflight, resolver: (RCTPromiseResolveBlock)resolve
                 rejecter:(RCTPromiseRejectBlock)reject)
{
  NSURL *receiptURL = [[NSBundle mainBundle] appStoreReceiptURL];
  NSString *receiptURLString = [receiptURL path];
  BOOL isRunningTestFlightBeta =  ([receiptURLString rangeOfString:@"sandboxReceipt"].location != NSNotFound);
  if(isRunningTestFlightBeta) {
    NSString *thingToReturn = @"TESTFLIGHT";
    resolve(thingToReturn);
  } else {
    NSString *thingToReturn = @"PRODUCTION";
    resolve(thingToReturn);
  }
}

@end
```

Those are the files needed to call the objective-c functions from react native. The function above will determine if the app is on the App Store or on TestFlight.

And now the react-native implementation:

```
import { NativeModules } from 'react-native';
const ProdChecker = NativeModules.ProdChecker;
```

```
RegisterManager.isTestflight().then(val => {
    if(val != "TESTFLIGHT") {
        // app is in production on App Store, not TestFlight
        // execute all production specific code here 
    }
})
```

This way, you'll be able to tell if the app is in production or not.

**Comment by kirill-konshin** [comment]
Bump...

**Comment by machour** [comment]
@kirill-konshin I'm not sure what you're expecting from this bump.. you could submit a PR instead.

**Comment by kirill-konshin** [comment]
I expect that 1 year old issue will be brought to your attention :) which could be annoying but that's the best I could do now. If I could do a PR I would do it in a first place  :) unfortunately, I don't know the right solution, especially for Google Play.

**Comment by machour** [comment]
Well, that makes two of us :)

**Comment by jiaxw32** [comment]
> sandboxReceipt

the  appStoreReceiptURL of  ad-hoc or dev app also contains '"sandboxReceipt" string, so there is a little falut, refer to the answer https://stackoverflow.com/questions/18282326/how-can-i-detect-if-the-currently-running-app-was-installed-from-the-app-store/18619270

**Comment by toddpi314** [comment]
@agates4  solution worked really well. Thanks man.

@kirill-konshin & @machour, you guy's crack me up.

**Comment by kirill-konshin** [comment]
¯\_(ツ)_/¯

**Comment by mikehardy** [comment]
I don't want this module to skew off towards checking all sorts of software things, especially not when others are already doing that work ;-)

https://www.npmjs.com/package/react-native-test-flight

**Comment by tmaly1980** [comment]
@mikehardy There's still no solution for Google, so that package doesn't help that. Seems like nobody has been able to find even a low-level way to do it with Google, short of querying the Play API for the package and version (whether it's on a production or beta/alpha track). 

Personally, I think a reasonable workaround for having modifications in the app based on where it was downloaded is to add a toggle button in the app itself (ie user settings, etc) to manually do whatever the app would do if it were in beta (ie switch to a staging server, etc). If that's not an option then I've also used configuration files that submitted the app for review knowing it was in test mode (such as for credit card transactions, Apple Pay, etc) and then used CodePush to update the config later on into production after it's been approved.

**Comment by mikehardy** [comment]
My projects typically have a versioning scheme where alphas and betas have detected ranges in a pattern, so the app simply knows based on it's internal version whether it is alpha or beta, then with a well-defined release system alphas and betas only go out on the right channels? You could also potentially use Firebase remote config, along with code-push etc. Lots of ways to handle it. But none available via this package ;-)

**Comment by robertherber** [comment]
Could the `getInstallReferrer` function be used for this on Android?

**Comment by mikehardy** [comment]
not that I'm aware of. It will just return the name of the system packager if I understand + remember correctly. You can test this by publishing the information from rn-update-apk about the installed package

**Comment by tmaly1980** [comment]
@robertherber The Google Play Beta version actually is installed through the Play Store app after the user either opts-in to the beta testing or is added to a predefined list of authorized users. There is no separate Testflight-like app for Android. 

I'm still convinced the simplest way to handle this (such as for using different APIs) is to have a toggle button somewhere in the app (in a user settings screen?) for internal/test users after they login. Or have some sort of tapping backdoor (ie tap on some text 10 times) similar to how Google Developer mode is enabled on Android phones.

**Comment by chreck** [comment]
There is one possible way to determine if the app was installed over Google Play Store and a testing track or production build. Or if it was installed directly from a local or CI build. You would need to setup on Google Play Console an upload key and that Google Play Store then changes the certificate when it is uploaded to Google Play console. You can read the certificate in the app itself. See https://github.com/WesBunton/MyCertificates . And by that at least you can check if it is the upload key or the store key. If it is the upload key you can be sure that its not the production or testing track. 

I have not tested it directly but will try it out in the future.
