### ISSUE TITLE
Required dispatch_sync to load constants for RNDeviceInfo. This may lead to deadlocks

### ISSUE THREAD

**Issue by compojoom** [react-native-community/react-native-device-info#260]
I'm getting this warning on 0.49.5
`Required dispatch_sync to load constants for RNDeviceInfo. This may lead to deadlocks`

Everything seems to function fine, but I'm wondering what does this exactly mean?

**Comment by maxkomarychev** [comment]
There is also this warning in console:

```
Module RNDeviceInfo requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
```

**Comment by Shinichi52** [comment]
+1

**Comment by xavieramoros** [comment]
+1

RN 0.48.4

**Comment by kainolophobia** [comment]
This warning only appears when we call a function from the RNDeviceInfo module in our initial render stage.

I'm guessing this has something to do with the synchronous nature of the call (in our case:  'getUniqueID'), resulting in the whole app locking up until the function returns.

**Comment by sospedra** [comment]
+1 

RN v0.49.5

**Comment by rskull** [comment]
Same issue.

RN v0.52.1

**Comment by machour** [comment]
How did you do your linking?

**Comment by idlework** [comment]
@machour same error for me and I added it manually.

**Comment by simonemarinelli** [comment]
+1

**Comment by machour** [comment]
We're using react-native-device-info on gitpoint and I've never seen the problem, so not sure how to reproduce it.

Nevertheless, I did some digging and this might be the solution? 
  https://github.com/facebook/react-native/issues/11196#issuecomment-298376877

Let me know

**Comment by haystome** [comment]
@compojoom move the **libRNDeviceInfo.a** to the bottom of **linked frameworks and libraries**
<img width="591" alt="screen shot 2018-02-20 at 2 38 07 am" src="https://user-images.githubusercontent.com/12714580/36402471-79c0a778-15e7-11e8-825f-df20bca49796.png">

**Comment by toblerpwn** [comment]
@haystome & others, note that I do not have `libRNDeviceInfo.a` in my project at all (and it is not importable). It was installed via Cocoapods & `react-native link`. Is this expected / known? Any thoughts?

**Comment by haystome** [comment]
@toblerpwn  for me : when I run  react-native link I can't found the **libRNDeviceInfo.a** in the **linked frameworks and libraries**, so I added it manually from **node_modules**
sometimes  **react-native link** didn't add all files or make all changes .

**Comment by compojoom** [comment]
well, I was on a really old version - 0.12.1. Upgrading to 0.15.3 fixes the issue for me. Closing the issue.

**Comment by antseburova** [comment]
Updating the library or moving the libRNDeviceInfo.a to the bottom of linked frameworks and libraries did not help in my case

**Comment by haystome** [comment]
@antoinerousseau  did you tried to ullink and link the pakges? 
[see this ](https://github.com/rebeccahughes/react-native-device-info/issues/260#issuecomment-367146615)

**Comment by sospedra** [comment]
solutions does not work

**Comment by haystome** [comment]
@sospedra  it works for me, also make sure that the pods loaded into your project.

**Comment by toblerpwn** [comment]
Huh...my issue actually came BACK after working for a few loads @ https://github.com/rebeccahughes/react-native-device-info/issues/260#issuecomment-367146615.

So, I concur, I still have the issue, and actually still don't have the library showing in Xcode. I'll post more if I have any new discoveries...

**Comment by RevanScript** [comment]
0.16.0 issue is still here

**Comment by thatjuan** [comment]
Issue is still present in 0.21.4.

**Comment by alexfoxy** [comment]
Issue still present 0.21.4

**Comment by sdunster** [comment]
I assume this is racy - I could reproduce it a few mins ago but not anymore. Perhaps in a future version everything the module does should be done via promise/callback?

**Comment by hiddentao** [comment]
Seeing this too

**Comment by psegalen** [comment]
I think I found how to resolve this issue: the issue is caused by the fact that the module requires the main queue (https://github.com/rebeccahughes/react-native-device-info/blob/master/ios/RNDeviceInfo/RNDeviceInfo.m#L31) while the app's loading, it seems to be wrong for some reason so we need the `requiresMainQueueSetup` to return `NO`.

Unfortunately doing so would cause a crash since when the lib loads it needs to be in the UI Thread because it silently instantiate a UIWebView to get the device User Agent.

IMHO we should defer this task and transform the `userAgent` field into a `getUserAgent` method (like `isPinOrFingerprintSet` and `getBatteryLevel`), it would allow us to achieve lazy loading for this property, solving this issue.

> @machour do you think it would be ok if I submit such a PR?

**Comment by machour** [comment]
Hi @psegalen, by all means yes. 
This will be a bc breaking release though, we'll need to semver that properly

**Comment by maxkomarychev** [comment]
Also the current way of getting user agent is now deprecated. New version is async: https://developer.apple.com/documentation/uikit/uiwebview/1617963-stringbyevaluatingjavascriptfrom?language=objc

**Comment by psegalen** [comment]
@machour PR #442 is ready to be tested, I didn't modify the changelog since I don't know what you want to do with the semver (I guess the changelog will have to be modified in the process).
I integrated the new way of getting user agent @maxkomarychev suggested

**Comment by maxkomarychev** [comment]
looks like we have a solution in #442, great job @psegalen !

**Comment by psegalen** [comment]
I've spotted a bug with my fix, I'm checking how to work around it:
```
Main Thread Checker: UI API called on a background thread: -[UIApplication preferredContentSizeCategory]
PID: 48076, TID: 4619700, Thread name: com.facebook.react.JavaScript, Queue name: com.apple.root.default-qos.overcommit, QoS: 21
Backtrace:
4   Seize                               0x000000010e9f9736 -[RNDeviceInfo fontScale] + 86
...
```

**Comment by psegalen** [comment]
This line (https://github.com/rebeccahughes/react-native-device-info/blob/master/ios/RNDeviceInfo/RNDeviceInfo.m#L207) must be executed from the main thread. 😞 
I'll have to lazy load that one too, changing the return type from `number` to `Promise<number>`, would that be ok @machour & @maxkomarychev?

**Comment by maxkomarychev** [comment]
@psegalen can we bring back `requiresMainQueueSetup `?

I see no problem with module being initialized on main thread in general.

The bigger problem is to have `dispatch_sync` called on main thread *from* main thread (which I'm assuming what was wrong with webview operation) which we solved.

**Comment by psegalen** [comment]
@maxkomarychev you're right, I didn't think about this but I've just tested: bringing back `requiresMainQueueSetup` return value to `YES` no longer triggers the yellow box, I'm pushing a commit on the PR.

**Comment by psegalen** [comment]
Unfortunately, yellow box has returned, it occurs way less often but it still occurs from time to time.
It seems that nothing in a module init process should ask to run on main thread... 😢

**Comment by xntop** [comment]
solutions does not work
Same issue.
RN v0.52.1

**Comment by luskin** [comment]
Still an issue on RN v0.56.0

**Comment by zedtux** [comment]
For me the YellowBox is now showing this warning since I upgraded from RN 0.55.4 to 0.56.

**Comment by cyb3rsalih** [comment]
Warning still there.   `React Native 0.57.3`

**Comment by viv3kk** [comment]
Warning still there. React Native 0.57.3

**Comment by karaoak** [comment]
Warning still there. React Native 0.57.4

**Comment by ahmetabdi** [comment]
:( same

**Comment by tayfunyasar** [comment]
Same here. React Native 0.57.7

**Comment by roisafirorichard** [comment]
Warning still exist, React Native 0.57.1

**Comment by jeffbonasso-ambifi** [comment]
For me I initially had it as a Pod and I got the warning. By removing it as a Pod and manually linking it, the warning went away.

**Comment by roysG** [comment]
Same Here 0.58

**Comment by machour** [comment]
Someone need to open a PR for this, and the PR to get merged before the problem goes away.
Locking this conversation to avoid more "same here with RN x.xx" comments.

**Comment by mikehardy** [comment]
The PR #260 from @psegalen (and review from @maxkomarychev) should help, and will go with the Promise API breaking change for v2. It's obvious this is an important issue given the number of participants - it'll get done

**Comment by mikehardy** [comment]
iOS implementation of promises is on v3 committing as soon as I fuzz check it. It lets me turn the requiresMainQueueSetup return to 'NO' and I believe solves this.
