### ISSUE TITLE
Possibility to get time format

### ISSUE THREAD

**Issue by samanthacampisi** [react-native-community/react-native-device-info#264]
Hello, I was just wondering if there's any way to obtain the device's time format (if they're using 24h or not) 

Thank you.

**Comment by gomdolkim** [comment]
I am also looking for how to get `Date and Time` format on android and iOS. It seems there is no library on react-native. 
Do you guys have any idea and have plan to implement this?

**Comment by gomdolkim** [comment]
@samanthacampisi I just checked it on the PR. 

this code has been merged to master 5 days ago. 
https://github.com/rebeccahughes/react-native-device-info/pull/265

and you can play with the following command. 
npm install https://github.com/rebeccahughes/react-native-device-info.git --save
