### ISSUE TITLE
pod install RNDeviceInfo but also React - there are several files providing this module (react-native)

### ISSUE THREAD

**Issue by dann1609** [react-native-community/react-native-device-info#303]
If I run pod install command it install RNDeviceInfo and React. So if I try to run project again it show me this message:

tries to require 'react-native', but there are several files providing this module. you can delete or fix them.

![captura de pantalla 2018-01-31 a la s 8 52 48 a m](https://user-images.githubusercontent.com/7472461/35626591-2cf7484e-0664-11e8-8c79-c16126382854.png)

**Comment by machour** [comment]
Hi @dann1609, had a look at similar issues and a lot of them suggest `rm -rf node_modules; watchman watch-del-all; yarn; yarn start --reset-cache`. Did you try this usual sh*tfix commands ? 😄

**Comment by dann1609** [comment]
it solve the issue, but each time I run pod install issues start again.

**Comment by machour** [comment]
I'm really not familiar with Pods. Could you give this solution a go? 
  https://github.com/invertase/react-native-firebase/issues/414#issuecomment-331128610

If it does, feel free to open a PR to propose the change!

**Comment by machour** [comment]
Fixed in 0.21.1

**Comment by richchurcher** [comment]
@machour note that now the fix has been undone in 0.21.5, this problem is recurring so you may want to reopen the ticket.

**Comment by HighSoftWare96** [comment]
I've solved the problem by doing:
1. Removed the line referring the package in the PodFile
2. Run 'pod install' in the /ios folder
3. npm install --save react-native-device-info 
4. react-native link react-native-device-info
5. npm install
6. npm start -- --reset-cache
7. Compiled and run on Xcode

**Comment by kotarCreative** [comment]
@machour Is there an ETA on when this is going to be fixed? React 11 is deprecated and breaks the build.

**Comment by machour** [comment]
@kotarCreative I'm not a pod user so I won't be the one who fixes this problem. Feel free to send a PR addressing the issue!

**Comment by mikehardy** [comment]
The last comment in #586 contains what I believe is the best current advice for pod users, and will be included in a documentation update. I'm not aware of Pod or non-Pod issues with this module at this point, and the example demonstrates it working
