### ISSUE TITLE
Enhancing the documentation

### ISSUE THREAD

**Issue by machour** [react-native-community/react-native-device-info#306]
I just rewrote the README.md file to make it a bit more readable and be able to write implementation details for each API member.

Here's what still needs to be done:

- [ ] Do some archeology in npm to complete the **Since** column in the compatibility matrix
- [ ] Add output examples where there's currently a question mark
- [x] Add a troubleshooting section
- [x] Go through the [issues with the doc tag](https://github.com/rebeccahughes/react-native-device-info/issues?q=is%3Aissue+is%3Aopen+label%3Adocs) and write up the relevant bits of documentation

Feel free to take any of these tasks (or chunks of a task) and open a PR to help! (make sure you comment here before).

Thank you 🙏

**Comment by mikehardy** [comment]
Once the example is merged #589 could take screenshots of an iOS and Android emulator with the output there

**Comment by mikehardy** [comment]
I'm not saying it can't be better, but honestly your initial effort was great @machour - I think this can be enhanced over time, but it's pretty sweet now.
