### ISSUE TITLE
Android missing permissions lint error

### ISSUE THREAD

**Issue by modularity** [react-native-community/react-native-device-info#310]
I have a project built with react-native@0.52.2 and react-native-device-info@0.14.0 and the android build keeps failing with a lint error under react-native-device-info. It says

>  ../../src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:54: Missing permissions required by WifiManager.getConnectionInfo: android.permission.ACCESS_WIFI_STATE
> 
>   51   private WifiInfo getWifiInfo() {
>   52     if ( this.wifiInfo == null ) {
>   53       WifiManager manager = (WifiManager) reactContext.getApplicationContext().getSystemService(Context.WIFI_SERVICE);
>   54       this.wifiInfo = manager.getConnectionInfo();
>   55     }
>   56     return this.wifiInfo;
> 
> ../../src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:201: Missing permissions required by TelephonyManager.getLine1Number: android.permission.READ_PHONE_STATE or android.permission.READ_SMS or android.permission.READ_PHONE_NUMBERS
> 
>  198             getCurrentActivity().checkCallingOrSelfPermission(Manifest.permission.READ_SMS) == PackageManager.PERMISSION_GRANTED ||
>  199             getCurrentActivity().checkCallingOrSelfPermission("android.permission.READ_PHONE_NUMBERS") == PackageManager.PERMISSION_GRANTED)) {
>  200         TelephonyManager telMgr = (TelephonyManager) this.reactContext.getApplicationContext().getSystemService(Context.TELEPHONY_SERVICE);
>  201         constants.put("phoneNumber", telMgr.getLine1Number());
>  202     }
>  203     constants.put("carrier", this.getCarrier());

My project shouldn't actually be needing any additional permissions as I'm only calling getUniqueID(), getSystemName(), getSystemVersion(), getVersion(), getBrand(), and getManufacturer(). Any suggestions on addressing this? I had this error with react-native-device-info@0.12.1 too.

**Comment by machour** [comment]
Hi @modularity and thank you for reporting this issue.

It seems like the problem was introduced when `getIPAddress()` and `getMACAddress()` were added in 0.12.0. We should definitely check the permission *before* attempting to retrieve these infos. 

I'll try to ship a fix during this week, meanwhile, you can try downgrading to 0.11.0.

**Comment by davidmessem** [comment]
Any progress on this? I'm having the same issue

**Comment by machour** [comment]
Hi @davidmessem, still no progress on my end. 
Do you want to open a PR to speed up things?

**Comment by anjasnewbie** [comment]
I have error like this too when gradlew
`MissingPermission: Missing Permissions
../../src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:54: Missing permissions required by WifiManager.getConnectionInfo: android.permission.ACCESS_WIFI_STATE

  51   private WifiInfo getWifiInfo() {
  52     if ( this.wifiInfo == null ) {
  53       WifiManager manager = (WifiManager) reactContext.getApplicationContext().getSystemService(Context.WIFI_SERVICE);
  54       this.wifiInfo = manager.getConnectionInfo();
  55     }
  56     return this.wifiInfo;

../../src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:201: Missing permissions required by TelephonyManager.getLine1Number: android.permission.READ_PHONE_STATE or android.permission.READ_SMS or android.permission.READ_PHONE_NUMBERS

 198             getCurrentActivity().checkCallingOrSelfPermission(Manifest.permission.READ_SMS) == PackageManager.PERMISSION_GRANTED ||
 199             getCurrentActivity().checkCallingOrSelfPermission("android.permission.READ_PHONE_NUMBERS") == PackageManager.PERMISSION_GRANTED)) {
 200         TelephonyManager telMgr = (TelephonyManager) this.reactContext.getApplicationContext().getSystemService(Context.TELEPHONY_SERVICE);
 201         constants.put("phoneNumber", telMgr.getLine1Number());
 202     }
 203     constants.put("carrier", this.getCarrier());
`
I try to add in manifest
`    <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/> 
    <uses-permission android:name="android.permission.READ_PHONE_NUMBERS"/>
    <uses-permission android:name="android.permission.READ_SMS"/>`

but still get error

**Comment by chocnut** [comment]
yep I'm encountered this issue too on android sdk 26.

**Comment by mikehardy** [comment]
#590 merged, fixed
