### ISSUE TITLE
Make it build with iOS App Extensions

### ISSUE THREAD

**Issue by robertherber** [react-native-community/react-native-device-info#347]
## Summary

|             |     |
| ----------- | --- |
| Version     | 17.3   |
| Affected OS | ios   |
| OS Version  | 11.2   |

## Current behavior

When using `react-native-device-info` in an iOS App Extension it fails to build because sharedApplication is referenced once `RNDeviceInfo.m:207`:

`
'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.
`

## Expected behavior

Would love for it to be able to build. And since it's only one line I'm guessing it could be potentially simple. Not an Objective-C pro though - so I don't know how! :)

**Comment by machour** [comment]
Thank you for logging this issue! Not an objective-c guy neither, so any help would be appreciated :)

**Comment by mikehardy** [comment]
This may be fixed shortly - has a PR in feedback stage
