### ISSUE TITLE
Add check for disk encryption

### ISSUE THREAD

**Issue by nicolegrinstead** [react-native-community/react-native-device-info#373]
## Description

Add a check to determine whether or not the disk is encrypted. 
(On iOS having screen lock enabled automatically enables disc encryption, but on android pin / fingerprint is a different setting from disc encryption.)
It looks like on android DevicePolicyManager getStorageEncryptionStatus() will return the encryption status. (https://developer.android.com/reference/android/app/admin/DevicePolicyManager.html)

## Use Case

If the app wants to determine the health / security of the device disc encryption is an important metric.

**Comment by machour** [comment]
Hi @nicolegrinstead and thank you for logging this. 
Do you want to work on a PR for this new feature?

**Comment by nicolegrinstead** [comment]
Hey @machour, yes I'm happy to work on a PR for this feature, but I may be a while before I have the time to submit one.

**Comment by machour** [comment]
Great!

**Comment by vadakr** [comment]
[Full-disk encryption is NOT allowed since Android 10](https://source.android.com/docs/security/features/encryption) (in favor of file-based encryption). This issue was closed without any explanation, so I hope this helps others.

**Comment by mikehardy** [comment]
Oh very interesting @vadakr - I was mostly closing it just as it went stale, before we had an automated stale bot, there had not been activity for more than a year which (as a maintainer) means "no one cares" + "invest your time elsewhere". Did not even know that FDE was no longer possible, thanks for the info
