### ISSUE TITLE
'RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by gitsad** [react-native-community/react-native-device-info#377]
After simple linking.

This error drives me crazy.
Versions:
React Native 0.52
react-native-device-info: 0.21.4

**Comment by machour** [comment]
Hi @gitsad, we recently removed the React pod dependency.
Could you try with 0.21.0 ?

**Comment by gitsad** [comment]
ok, I will try

**Comment by gitsad** [comment]
on 0.20.0 pods fetching React 0.11 which causing conflicts and built end with fail

**Comment by gitsad** [comment]
I would like to have only device id for firebase integration. Why simple things are always so hard 😞.

**Comment by gitsad** [comment]
Ok I have managed that and it seems it works. I incorrectly linked lib **(Via CocoaPods doesn't work, it causing React conflicts)**. Sorry for the wrong first response on your solution but I'm just a little bit puzzled when after ejecting with expo the integration with fcm went to hell and I have to revert all my changes to make the project without expo, only plain react native and from that moment I has a little bit mess in native and js source code.

**Comment by machour** [comment]
No worries, we've all been there. If your project is public, I can try to have a look at the mess. 

So is the latest version of react-native-device-info working for you?

**Comment by gitsad** [comment]
the latest, unfortunately, no, but **0.20.0** yes. Thanks for help! 🥂

**Comment by machour** [comment]
Alright, I guess I'll be rolling back the pod change then. ☕ (9am here :D)

**Comment by gitsad** [comment]
In addition, On Android works fine with automatic linking without any error on 0.20.0 in my case at least 👍

**Comment by eirabie** [comment]
Getting the same error

Versions:
React Native 0.54.4
react-native-device-info: 0.21.4

**Comment by DungBuiDeveloper** [comment]
i still get same issues plz help me @gitsad

**Comment by DungBuiDeveloper** [comment]
lib is so hard for install , maybe author not try install...

**Comment by machour** [comment]
@DungBuiDeveloper yes, the library was developed blindly, then maintained by people changing random letters in the source code without testing them.

**Comment by machour** [comment]
@gitsad @DungBuiDeveloper just rolled back the pod change. Does 0.21.5 works better for you?

**Comment by DungBuiDeveloper** [comment]
i think one LIB perfect for you only mix pods and link , and them work. any issues not good . i'm here fix bug 2 days and now i still can't run & build xcode workspace

**Comment by machour** [comment]
that doesn't tell me if you tried 0.21.5.

**Comment by DungBuiDeveloper** [comment]
yes sir i will try

**Comment by DungBuiDeveloper** [comment]
https://gyazo.com/54034d1114c12c3c0244ca3ad3a06856
@machour :D i do'nt know this issue but now build sucess OMG

**Comment by richeterre** [comment]
To be fair, from what I've seen these problems would probably not exist if Facebook had built iOS support in RN around CocoaPods in the first place – which is, after all, _the_ dependency resolver of choice for iOS projects.

Now what happens is that RN comes bundled with its own React + friends, but those aren't known to CocoaPods and thus cannot be resolved against libraries such as this one, which also depend on React but _do_ have a podspec. The end result is either missing dependencies (this issue), or duplicate imports 💥

**Comment by mikehardy** [comment]
I'm closing this as we have an example people can use now, and the docs for pods will be updated soon with the results of the last comment here #586 / https://github.com/react-native-community/react-native-device-info/issues/586#issuecomment-476945422 - I have a firebase app with this module working well with a Podfile that looks like the one in the comment, I know it's possible
