### ISSUE TITLE
Linker fails with ld: library not found for -lRNDeviceInfo

### ISSUE THREAD

**Issue by c-brooks** [react-native-community/react-native-device-info#378]
## Summary

|             |     |
| ----------- | --- |
| Version     | 0.21.4   |
| Affected OS | MacOS Sierra  |
| OS Version  | 10.12.6   |

## Current behavior

when building the project for release:
```
xcodebuild "-project" "ios/FleetFox.xcodeproj" "-scheme" "FleetFox" "-configuration" "Release" "archive" "-verbose" | xcpretty
```
The linker fails with:
```
ld: library not found for -lRNDeviceInfo
```

## Expected behavior
It should build without errors. Downgrading the package to 0.21.1 fixes the problem.

**Comment by realtebo** [comment]
@gongmingqm10 thanks, now I'll try and report here the result. 

But... what's the cause? Did i something wrong?

**Comment by machour** [comment]
This is due to the change made in #374. Sorry for the inconvenience folks, I'll add a new entry in the troubleshooting section.

**Comment by realtebo** [comment]
> remove the old DeviceInfo.xcodeproj and add it manually from the related node_modules.

I removed RNDeviceInfo.xcodeproj from 'library' folder on the left panel. I selectioned, then Edit -> delete.

Also, in Targets -> Build Phaese -> Linke Binary With Libraries I removed the row `libRnDeviceInfo.a` 

But how to readd it? Sorry but I never used xcode :(
There is not edit  -> add

**Comment by machour** [comment]
In XCode, in the project navigator:

Right click Libraries
Add Files to [your project's name]
Go to node_modules/react-native-device-info
Add the .xcodeproj file

**Comment by realtebo** [comment]
my xcode doesn't allow me to selected the .xcodeproj file, but only the upper ios folder... 

![image](https://user-images.githubusercontent.com/1268699/38081956-9de120e4-3345-11e8-8dd1-a6d188875c08.png)

**Comment by realtebo** [comment]
Sorry for posting again, but I downgraded to 0.21.1 but I got 

TypeError: Cannot read property 'uniqueId' of undefined 

I tried with console.log to understand and I ended with dumping DeviceInfo.getUniqueID();

ƒ getUniqueID() {
      return RNDeviceInfo.uniqueId;
    }

The error is that RNDeviceInfo is null !

What am I doing wrong?

```
TypeError: Cannot read property 'uniqueId' of undefined
    at Object.getUniqueID (blob:http://localhost:8081/958364d9-04cd-45a0-83f6-06759d303d91:72914:27)
    at getDeviceId (blob:http://localhost:8081/958364d9-04cd-45a0-83f6-06759d303d91:72681:50)
    at _callee$ (blob:http://localhost:8081/958364d9-04cd-45a0-83f6-06759d303d91:72553:72)
    at tryCatch (blob:http://localhost:8081/958364d9-04cd-45a0-83f6-06759d303d91:16768:19)
    at Generator.invoke [as _invoke] (blob:http://localhost:8081/958364d9-04cd-45a0-83f6-06759d303d91:16941:24)
    at Generator.prototype.(anonymous function) [as next] (blob:http://localhost:8081/958364d9-04cd-45a0-83f6-06759d303d91:16811:23)
    at tryCatch (blob:http://localhost:8081/958364d9-04cd-45a0-83f6-06759d303d91:16768:19)
    at invoke (blob:http://localhost:8081/958364d9-04cd-45a0-83f6-06759d303d91:16844:22)
    at blob:http://localhost:8081/958364d9-04cd-45a0-83f6-06759d303d91:16872:13
    at tryCallTwo (blob:http://localhost:8081/958364d9-04cd-45a0-83f6-06759d303d91:16106:7)
```

**Comment by machour** [comment]
@realtebo can you check if the lib is in Linked frameworks and libraries?
<img width="1263" alt="screen shot 2018-03-29 at 4 22 07 pm" src="https://user-images.githubusercontent.com/304450/38097475-695db076-336d-11e8-9190-c7da0f85fcca.png">

**Comment by omnikitty** [comment]
Same problem here. Though I re-added the xcode project from node_modules and tried all the other suggestions, I couldn't get rid of the library not found error. 
The only solution that worked was downgrading to 0.21.1. Hope a fix comes soon!

**Comment by Gentlee** [comment]
1) Xcode -> Libraries -> remove RNDeviceInfo.xcodeproj
2) react-native link react-native-device-info

**Comment by ryekerjh** [comment]
I have tried all above suggestions and hve been unsuccessful in getting the error to go away. I installed v0.21.1, I tried to remove that file in xCode, but since the xCode update I cant find that file, tried running `react-native link react-native-device-info` after unlinking, tried clearing the cache and uninstalling and reinstalling npm packages. I am running `"react": "^16.3.1"` and `"react-native": "^0.55.3"`

**Comment by br4nnigan** [comment]
just the usual rn fuckery

**Comment by WowJesse** [comment]
> 2\. react-native link react-native-device-info

your way no error, but getVersion get error

**Comment by mikehardy** [comment]
There is an example now that shows how to do this with a refresh-example.sh script that builds it fresh any time. You can look at that to see how to initialize the module in your project. Linker problems are always install/link issues at this point

**Comment by eladams** [comment]
Try changing the deployment target of Libraries/RNDeviceInfo to 9.0 if this applicable for your app in general.

**Comment by mikehardy** [comment]
@eladams I am not sure what your comment is in reference to? this is a closed issue more than a month ago at this point ?

**Comment by zyestin** [comment]
![image](https://user-images.githubusercontent.com/51897571/92085891-0767b500-edfc-11ea-93df-3addf614a2a2.png)
add path `"${PODS_CONFIGURATION_BUILD_DIR}/RNDeviceInfo"` to the top of `Library Search Paths` ，then build successfully~

**Comment by mikehardy** [comment]
@zyestin I would propose that is only necessary for projects that are broken in some fundamental way with respect to auto-linking
