### ISSUE TITLE
Building without Play Services?

### ISSUE THREAD

**Issue by Rudloff** [react-native-community/react-native-device-info#381]
## Description

It seems that this library can't be built for Android without Play Services:
```
   > A problem occurred configuring project ':react-native-device-info'.
      > You have not accepted the license agreements of the following SDK components:
        [Google Repository].
```

Would it be possible to have an option to build without the `play-services-gcm` dependency? (Even if it means that some functionnalities won't work.)

## Use Case

The Play Services dependency prevents any app using this library from being included in free software repositories like [F-Droid](https://f-droid.org/).

(I see [here](https://github.com/rebeccahughes/react-native-device-info/pull/334) that there was already some discussion about this. The use case back then seemed to be that people wanted to use a different GCM version which is a little bit different.)

**Comment by Rudloff** [comment]
Unfortunately, I don't think I have enough experience with the Play Services to do this without breaking things for people that do use them 😕

**Comment by Rudloff** [comment]
I don't know if it can help you but here is what we used to remove Play services when building an app that uses react-native-device-info 0.14.0:
```bash
sed -i -e '/com.google.android.gms.iid.InstanceID.getInstance/d' node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
sed -i -e '/play-services/d' node_modules/react-native-device-info/android/build.gradle
```

**Comment by mikehardy** [comment]
GCM is only used for the instanceID, #60 should be used instead, during #307 implementation

This is covered in other spots enough I can close this here

**Comment by jnnkB** [comment]
@mikehardy Is this going to be in [v4](https://github.com/react-native-device-info/react-native-device-info/projects/2)?

**Comment by mikehardy** [comment]
We are on v8 now? Why would anything happen on v4? 🤔

**Comment by jnnkB** [comment]
Yeah you right. Just looked at https://github.com/react-native-device-info/react-native-device-info/issues/60 which is still tagged with the v4 version. Should have looked at the project a bit longer.
