### ISSUE TITLE
Avoid mixing CommonJS and ESM

### ISSUE THREAD

**Issue by novemberborn** [react-native-community/react-native-device-info#388]
## Summary

|             |     |
| ----------- | --- |
| Version     | v0.17 and newer   |
| Affected OS | N/A   |
| OS Version  | N/A   |

## Current behavior

As of #339 the `import` keyword is used to load `Platform` and `NativeModules` from `react-native`. However the file then uses `module.exports` to export the getters.

This trips up the `eslist-plugin-import` package, specifically the [`import/default` rule](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/default.md). It (rightly, IMHO) recognizes `react-native-device-info` as using ESM, but then fails to find a default export.

## Expected behavior

`import/default` finds a default export. `deviceinfo.js` is changed to use `export default` rather than `module.exports = `.

I haven't checked to what extend this impacts type definitions, and thus whether this would be a breaking change.

I can do a PR for this if you're happy making this change.

**Comment by machour** [comment]
Hi @novemberborn

Thank you for spotting this! I'll gladly merge a PR that set things straight

**Comment by mikehardy** [comment]
If this is still an issue and you want to propose a PR please mention, otherwise I'm closing this
