### ISSUE TITLE
ios: startup incurs UIWebView creation costs

### ISSUE THREAD

**Issue by EmielM** [react-native-community/react-native-device-info#394]
When doing some simple profiling I noticed a complete UIWebView is created and torn down when launching an app with `react-native-device-info`. Apparently, someone thought [it was a good idea](https://github.com/rebeccahughes/react-native-device-info/blob/master/ios/RNDeviceInfo/RNDeviceInfo.m#L175) to use a complete UIWebView environment to determine a device's user agent.

For your reference: a UIWebView is expensive. It incurs 10s of megabytes worth of allocations loading things like sqlite storage backends and other stuff you really don't need. I would suggest to find another way to determine the user agent on iOS, or otherwise load the property lazily.

**Comment by mikehardy** [comment]
https://github.com/react-native-community/react-native-device-info/pull/442 should fix this
