### ISSUE TITLE
eslint-plugin-import error

### ISSUE THREAD

**Issue by jay1337** [react-native-community/react-native-device-info#403]
## Summary

|             |     |
| ----------- | --- |
| Version     | `react-native-device-info@0.21.5`   |
| Affected OS | NA   |
| OS Version  | NA   |

## Current behavior

`eslint-plugin-import@2.11.0` detects an error when importing the module
`import DeviceInfo from 'react-native-device-info';`

## Expected behavior

No error

## Why

I think that `eslint-plugin-import` finds an `import` statement in `deviceinfo.js` so it expects that the module uses `export` statements. `deviceinfo.js` should use only `import` and `export` or only `require(...)` and `module.exports`.

**Comment by machour** [comment]
Hi and thank you for logging this. 
Could you share the actual error message?

**Comment by jay1337** [comment]
This rule is triggered : https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/default.md

`No default export found in module. (import/default)`

**Comment by machour** [comment]
@peacechen could you possibly have a look at this?

**Comment by peacechen** [comment]
Thanks @jay1337 for posting the error details.

Based on the eslint error, changing this line should fix it:
https://github.com/rebeccahughes/react-native-device-info/blob/master/deviceinfo.js#L12

From
```
module.exports = {
```

To
```
export {
```

@jay1337   Would you mind trying that locally?  Edit `node_modules/react-native-device-info/deviceinfo.js` and try building again.

**Comment by jay1337** [comment]
@peacechen you have to use `export default {`, it solves eslint issue.

**Comment by schumannd** [comment]
Will this fixed be merged in the future?

**Comment by machour** [comment]
We were just missing a PR, and here you are :)

**Comment by machour** [comment]
0.22.3 is out with this fix, thank you all!

**Comment by machour** [comment]
This seem to be causing troubles: #468 
/cc @jay1337 @peacechen

**Comment by schumannd** [comment]
I did not encounter these issues. Are they fixed by using `import DeviceInfo from 'react-native-device-info';` instead of other forms of importing this package?

**Comment by eshikerya** [comment]
@schumannd nope. starting from 0.22.2 it is broken. any type of import give an error

**Comment by schumannd** [comment]
Yes, I should have tested alternative ways of importing the module as well. Maybe we can find a way to enable both old and new import styles?

Maybe something like:
```
const obj = {
  ...
}
export default obj;
module.exports = obj;
```
?

What import styles do break right now?

**Comment by peacechen** [comment]
Would testing for `module` be safer, or is that even necessary?
`module && module.exports = obj`

TBH I recommend supporting only `import` and drop support for `require`.  It's less maintenance hassle, and there's no compelling reason to support require in RN-land.

**Comment by schumannd** [comment]
I agree. It is a breaking change in a minor version update, so OP of #468 has a point.

**Comment by mikehardy** [comment]
I think enough time has gone by with this change in place it's okay to close - and there's an example for folks to look at it in case they are having problems
