### ISSUE TITLE
`phoneNumber` should not be a constant

### ISSUE THREAD

**Issue by rcorrie** [react-native-community/react-native-device-info#416]
## Summary
If `READ_PHONE_STATE` permission is granted at runtime, the `phoneNumber` constant never get's updated.

This happens because `phoneNumber` gets set once (initially) and `getPhoneNumber` just returns the constant, even if it's stale.

|             |     |
| ----------- | --- |
| Version     |  all  |
| Affected OS | android   |
| OS Version  | all  |

## Current behavior

Start app for first time. Ask user for `READ_PHONE_STATE` permissions. Then call `getPhoneNumber`. Returns null, even though you have granted the permissions.

## Expected behavior

Start app for first time. Ask user for `READ_PHONE_STATE` permissions. Then call `getPhoneNumber`. Returns the phone number (if available).

**Comment by machour** [comment]
Definitely, thank you @rcorrie !
Will be shipped in #307

**Comment by mikehardy** [comment]
This is implemented on v3 now
