### ISSUE TITLE
getDeviceLocale() unexpected behavior on iOS device

### ISSUE THREAD

**Issue by mikeartfay** [react-native-community/react-native-device-info#420]
## Summary
Return values for the `getDeviceLocale()` API do not match the API documentation on iOS version 11.0+, only when running on a physical device. Behavior works as expected in the iOS simulator.

|             |     |
| ----------- | --- |
| Version     | 0.21.5  |
| Affected OS | iOS   |
| OS Version  | 11.0+  |

## Current behavior

Given: Running on a physical iOS device, OS level >= 11.0
When: Using the `getDeviceLocale()` API
Then: The return value is in the {language-country} format (e.g. en-US).

## Expected behavior
The return value should match the API documentation and return a language code only (e.g. en).

## Notes
This appears to be an issue with `[NSLocale preferredLanguages]` in iOS 11.0+.

**Comment by gpawlik** [comment]
Just FYI this behaviour is going to be normalised in the version `1.0.0` according to this PR: https://github.com/rebeccahughes/react-native-device-info/pull/354

**Comment by mikehardy** [comment]
Running a poll with a proposal to defer to @react-native-community/react-native-localize package where this is likely handled better https://github.com/react-native-community/react-native-device-info/issues/627

**Comment by mikehardy** [comment]
https://github.com/react-native-community/react-native-device-info/issues/627
