### ISSUE TITLE
IOS DeviceInfo.getModel() is undefined in Iphone 6 - 11.4 

### ISSUE THREAD

**Issue by mrkhanakia** [react-native-community/react-native-device-info#437]
## Summary

|             |     |
| ----------- | --- |
| Version     | 0.21.5  |
| Affected OS | IOS   |
| OS Version  | 11.4  |

## Current behavior

TypeError: Cannot read property 'model' of undefined when i use DeviceInfo.getModel()

**Comment by mikehardy** [comment]
I'm closing this as stale but if it persists please reopen it, with more data on versions used of the software, and a code snippet if you have it. I also suggest looking at the example and trying it, as it should work
