### ISSUE TITLE
Detect users calendar settings

### ISSUE THREAD

**Issue by wvddrss** [react-native-community/react-native-device-info#441]
## Description

Ability to detect the device calendar settings on iOS.

## Use Case

When iOS devices have a different type of calendar set, non-gregorian for example. We should be able to detect this setting so we change date notation.

**Comment by mikehardy** [comment]
Android after API24 has different calendar types too. This is user setting similar to locale that I could see this package supporting, but it would need more interest and a PR. I'm going to close this for now but if someone submitted a promise-based PR that implemented it that would be great

**Comment by mikehardy** [comment]
Running a poll with a proposal to defer to @react-native-community/react-native-localize package where this is likely handled better https://github.com/react-native-community/react-native-device-info/issues/627
