### ISSUE TITLE
clang: error: no such file or directory: libRNDeviceInfo.a

### ISSUE THREAD

**Issue by creative-git** [react-native-community/react-native-device-info#446]
|             |     |
| ----------- | --- |
| Version     | v0.21.1   |
| Affected OS | iOS   |
| OS Version  | RN 0.55   |

## Current behavior
When i try to build or archive my project in xCode, i get the following:

`clang: error: no such file or directory: '/Users/creative/Library/Developer/Xcode/DerivedData/PROJECT_NAME-bafoidfjyrtxuchdgsrpxhifyibq/Build/Intermediates.noindex/ArchiveIntermediates/PROJECT_NAME/BuildProductsPath/Release-iphoneos/libRNDeviceInfo.a'`

However, the project is compiling successfully using `react-native run-ios`

## Expected behavior
SHOULD BUILD SUCCESSFULLY

**Comment by navata** [comment]
I have a same issue. I can't find libRNDeviceInfo.a ?

**Comment by ABelkin** [comment]
+1

**Comment by hugopretorius72** [comment]
Same issue, any ideas?

**Comment by machour** [comment]
Hey @barjas, any updates on this?

**Comment by hatyaiapp** [comment]
me too, and I have error for **RNDeviceInfo.m** too

**Comment by barjas** [comment]
@machour, not solved for me yet,

**Comment by OdaDaisuke** [comment]
I have a same issue. Are there any way of build RNDeviceInfo?

**Comment by OdaDaisuke** [comment]
maybe

```shell
$ cd ios
$ pod install
```

**Comment by janhesters** [comment]
I tried `pod install` and it doesn't work.

```

Showing All Messages
:-1: no such file or directory: '/Users/jan/Library/Developer/Xcode/DerivedData/my_app-afriooowgjvwhpgjoxyzihfenkmr/Build/Products/Debug-iphonesimulator/libRNDeviceInfo.a'
```

But it is in my pods:
<img width="694" alt="screenshot 2019-01-02 at 12 29 05" src="https://user-images.githubusercontent.com/31096420/50590165-0ee9f480-0e8a-11e9-964a-89b31b6e0dd7.png">

And it's linked:

<img width="682" alt="screenshot 2019-01-02 at 12 29 52" src="https://user-images.githubusercontent.com/31096420/50590190-26c17880-0e8a-11e9-85a6-f54626e4ed22.png">

So same issue here 😦

**Comment by hcliff** [comment]
if you check the build dir it's not installing the same way as other libs, poking around as to why

<img width="700" alt="image" src="https://user-images.githubusercontent.com/481457/51387696-3d70fc00-1b27-11e9-8ab2-1a8a36aabf8b.png">

**Comment by hcliff** [comment]
for me this seems to have been caused by conflicts with `npm link` and also using cocoapods. I resolved this by `rm -rf  ./ios` and rerunning `pod install` (without npm link). 
@cbrwizard were you also using cocoapods?

**Comment by cbrwizard** [comment]
@hcliff yes. I haven't tried your steps though.
I think RNDeviceInfo has the same issue sometimes for unknown reasons

**Comment by ricardodantas** [comment]
I have the same issue. :(

**Comment by mikehardy** [comment]
There is an example app now that cleanly builds and executes (and you may even archive it if you like). Please check it out, build it, and see how it goes. Compare it to your project and slowly feed the changes in if you have problems. Don't forget to link.

There will be updated pod documentation soon but the last comment here has a recommendation for your Project podfile if you're using Cocoapods, it also works #586

**Comment by ThomasLarge** [comment]
I have had the same issue and after reading though a lot of issues I found as I am using pods and the workspace there is a issue when you use react native link 

This basically adds two projects to your project one is the node_modules and one is coming from the pod file. 

To fix I removed the links from the node_modules and these where the ones that was linked into the libraries on xCode. Shut everything down ran a clean and relink the pod files with xCode and it worked 🙌 

If anyone is still having the issue I can try and help you out!

**Comment by StarkAndy** [comment]
Hi @ThomasLarge  need help still facing the same issue !

**Comment by ThomasLarge** [comment]
@StarkAndy When you open your project in xcode go to -> build phases -> Link binary with libraries. When you search for libRNDeviceInfo.a do you see two? and what are the paths?

**Comment by avwingz** [comment]
@ThomasLarge Hey I'm having trouble with libRNCPushNotificationIOS.a which is in my Linked Binary with Libraries. There's only 1 instance of the file. Error:
Undefined symbols for architecture armv7
> Symbol: _OBJC_CLASS_$_RNCPushNotificationIOS
> Referenced from: objc-class-ref in AppDelegate.o

**Comment by ThomasLarge** [comment]
@avwingz I'm sorry I haven't seen this one so not sure what the issue could be

**Comment by say95** [comment]
> @ThomasLarge Hey I'm having trouble with libRNCPushNotificationIOS.a which is in my Linked Binary with Libraries. There's only 1 instance of the file. Error:
> Undefined symbols for architecture armv7
> 
> > Symbol: _OBJC_CLASS_$_RNCPushNotificationIOS
> > Referenced from: objc-class-ref in AppDelegate.o

@avwingz Hey, I am also facing the same issue RNC Push Notifications, were you able to fix this issue?

**Comment by avwingz** [comment]
@say95 I had to downgrade the pushnotificationios library as well as the react native version to 0.59. Hopefully that helps, not a very common error

**Comment by rohithramachandran** [comment]
> @ThomasLarge Hey I'm having trouble with libRNCPushNotificationIOS.a which is in my Linked Binary with Libraries. There's only 1 instance of the file. Error: Undefined symbols for architecture armv7
> 
> > Symbol: _OBJC_CLASS_$_RNCPushNotificationIOS
> > Referenced from: objc-class-ref in AppDelegate.o

I also have this problem now. Can somebody help ?

**Comment by mikehardy** [comment]
When I have seen errors during Xcode compile where it is complaining of the directory not even existing it's an ARCH exclusion hack as a fix. I had to do this in our react-native-firebase e2e tests, you'll have to experiment to land on something that works for you but this is what we do: https://github.com/invertase/react-native-firebase/blob/3d5d00d6b1ed7cf9e1afbe62f16b1c77e2bf7693/tests/ios/Podfile#L52-L54
