### ISSUE TITLE
[question] Where can I find all possible timezones that getTimezone() return?

### ISSUE THREAD

**Issue by SilencerWeb** [react-native-community/react-native-device-info#461]
I'm wondering where can I find all possible timezones that `getTimezone()` return? I want to use returned value with `Intl.DateTimeFormat`, but `Intl.DateTimeFormat` accept timezones only in this pattern: `Area/Location(/Location)*`, so I want to be sure that `getTimezone()` will not return something like `NZ` or `Universal` as `moment.js` does.

**Comment by mikehardy** [comment]
You'll have to follow the underlying APIs:

java.util.TimeZone (as implemented in Android, and may vary by API and/or vendor updates):
https://github.com/react-native-community/react-native-device-info/blob/master/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L374

Same but on the iOS side:
https://github.com/react-native-community/react-native-device-info/blob/master/ios/RNDeviceInfo/RNDeviceInfo.m#L212

**Comment by mikehardy** [comment]
Running a poll with a proposal to defer to @react-native-community/react-native-localize package where this is likely handled better https://github.com/react-native-community/react-native-device-info/issues/627
