### ISSUE TITLE
Get iPhone Model Number

### ISSUE THREAD

**Issue by winadiw** [react-native-community/react-native-device-info#464]
## Description

Get iPhone Model Number. For example in iPhone X: A1865, A1901, A1902 (Japan)

## Use Case
To identify if the device mobile data (4G especially) can work or not. Because some device have CDMA network.

**Comment by mikehardy** [comment]
According to this, the string we return is sufficient for you to tell CDMA or GSM or 4G etc

https://stackoverflow.com/questions/11197509/how-to-get-device-make-and-model-on-ios
