### ISSUE TITLE
add screenshots in manual linking instructions

### ISSUE THREAD

**Issue by SilencerWeb** [react-native-community/react-native-device-info#465]
Could you add screenshots in manual linking instructions? I think it would be very helpful for newbies because it is pretty hard to understand the plain text if you are doing it first or second time.

Especially, this part in manual linking instruction for iOS:

> In XCode, in the project navigator, select your project.
> - Add the libRNDeviceInfo.a from the deviceinfo project to your project's Build Phases ➜ Link Binary With Libraries
> - Click .xcodeproj file you added before in the project navigator and go the Build Settings tab. Make sure All is toggled on (instead of Basic).
> - Look for Header Search Paths and make sure it contains both $(SRCROOT)/../react-native/React and $(SRCROOT)/../../React
> - Mark both as recursive (should be OK by default).

**Comment by luisggc** [comment]
you can find further instructions here:
https://facebook.github.io/react-native/docs/linking-libraries-ios

**Comment by mikehardy** [comment]
Closing this, anyone can create docs on the wiki if they like, otherwise the official FB docs will be better as they stay up to date.
