### ISSUE TITLE
Battery percentage in decimal is not accurate

### ISSUE THREAD

**Issue by manju-ms** [react-native-community/react-native-device-info#467]
## Summary

|             |     |
| ----------- | --- |
| Version     | 0.18.0   |
| Affected OS | android and ios   |
| OS Version  | android 5 and above and ios 10 and above   |

## Current behavior

When we use DeviceInfo.getBatteryLevel() it will return the value in in decimal that one if we convert to percentage it is not accurate to the decimal level. 

## Expected behavior

Battery level must be accuraate to the decimal level.

**Comment by Mahaswami** [comment]
Basically it is either giving

1.00000019 OR 1.99999989. We don't get a decimal value like 1.1, 1.2 etc.

**Comment by machour** [comment]
@IjzerenHein could you give this issue a look? :pray:

**Comment by machour** [comment]
Can you try latest versions ? We shipped changes in 0.27.1 regarding battery & ios

**Comment by mikehardy** [comment]
For me battery level is still what looks like a classic IEEE floating point representation error, right now on my phone it is '0.920000016689whatever'

**Comment by mikehardy** [comment]
This is intrinsic to javascript, I just did a deep-dive on it. Javascript numbers are floating-point and that's that. What you see is how Javascript thinks about the number. Format it as you like for display purposes (rounding, .toPrecision(), whatever) but we can't change the way the language handles the number type, it's intrinsic, sorry.
