### ISSUE TITLE
library not found for -lRNDeviceInfo-tvOS : troubleshooting guide unclear

### ISSUE THREAD

**Issue by vmarquet** [react-native-community/react-native-device-info#482]
From troubleshooting part in README:

```
[ios] - ld: library not found for -lRNDeviceInfo-tvOS

Seems to be a bug caused by react-native link. You can manually delete libRNDeviceInfo-tvOS.a in Xcode -> [Your iOS build target] -> Build Phrases -> Link Binary with Libraries.
```

I don't understand what  `Xcode -> [Your iOS build target]` is supposed to mean, like what buttons I'm supposed to follow. Please add a screenshot or details where the buttons are (navbar, ...)

**Comment by MistyRain5** [comment]
Remove the libRNDeviceInfo-tvOS.a from your project's Build Phases ➜ Link Binary With Libraries

**Comment by machour** [comment]
@vmarquet Feel free to send a PR adding the screenshot if you figured it out :)
