### ISSUE TITLE
Add Android Manifest.permission.ACCESS_NOTIFICATION_POLICY?

### ISSUE THREAD

**Issue by dbarner1** [react-native-community/react-native-device-info#487]
## Description
I've found no other react-native module that allows us to easily *read* the state of push notification grant access on android.  I thought `react-native-device-info` was perfect, as it seems in `RNDeviceModule.java` you're capturing other states in the device, like `Manifest.permission.READ_PHONE_STATE`.

Perhaps this would be a good location to fetch, and float the return of `Manifest.permission. ACCESS_NOTIFICATION_POLICY` to `react-native` layer?  

## Use Case
Our app would like to understand if the user has disabled notification permission.

**Comment by mikehardy** [comment]
I would like this as well. Feel free to propose a PR with a Promise return value and I'll work with you to merge it

**Comment by dbarner1** [comment]
@mikehardy Thanks.  Wish I could...still ramping up in Java. :)

Anyone else able to help us?

**Comment by mikehardy** [comment]
Maybe someone else will take interest. I'm interested but still have a pile of PRs to look through and want to generate a v2.0 that Promise-ifies the API to stop using constants (immediately fix half the bugs logged here just with the switch).

Then after that maybe :-)

**Comment by mikehardy** [comment]
I think react-native-permissions handles this for iOS, or it is supposed to and we are just now trying to get this module into react-native-community. Just yesterday I did successfully integrate that API for iOS but it does not handle the android side. But for permissions that's the module to go to

**Comment by mikehardy** [comment]
until then maybe https://github.com/Eaffy/react-native-android-notification-permission#readme

**Comment by dbarner1** [comment]
Thanks.  fwiw, haven't had luck with
https://github.com/Eaffy/react-native-android-notification-permission#readme
 to-date.

**Comment by mikehardy** [comment]
Hmm - that's useful feedback, I won't recommend it again then - haven't tried it personally so that was a guess. Hopefully we can get react-native-permissions into react-native-community and add these powers to it, as it already works well for iOS
