### ISSUE TITLE
Android dependency 'com.android.support:support-v4' has different version for the compile (26.1.0) and runtime (27.1.1) classpath. You should manually set the same version via DependencyResolution

### ISSUE THREAD

**Issue by meiqi1992** [react-native-community/react-native-device-info#492]
## Summary

|             |     |
| ----------- | --- |
| Version     | ?   |
| Affected OS | ?   |
| OS Version  | ?   |

## Expected behavior

Android dependency 'com.android.support:support-v4' has different version for the compile (26.1.0)
and runtime (27.1.1) classpath. You should manually set the same version via DependencyResolution

  react-native 0.57.0
  gradle:3.1.4

**Comment by io-pan** [comment]
This as well:

(nothing in subprojects)
```
allprojects {
    configurations.all {
        resolutionStrategy.force "com.android.support:support-v4:26.1.0"
    }
```

even better since with previous answer I had
```
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\dev\app\SOL\android\build.gradle' line: 39

* What went wrong:
A problem occurred configuring project ':react-native-maps'.
> Android tasks have already been created.
  This happens when calling android.applicationVariants,
  android.libraryVariants or android.testVariants.
  Once these methods are called, it is not possible to
  continue configuring the model.
```

**Comment by ddaaggeett** [comment]
@io-pan's suggestion is perfect. i believe this issue is good to close.
`~/android/build.gradle`
```
...
allprojects {
    ...
    configurations.all {
        resolutionStrategy.force "com.android.support:support-v4:26.1.0"
    }
}
```

**Comment by chrisregner** [comment]
What worked with me is adding @io-pan 's suggestion and adding `google()`:

![screen shot 2019-03-07 at 12 28 13 pm](https://user-images.githubusercontent.com/26005158/53932451-9e06c900-40d4-11e9-9379-cbcce1594d26.png)

**Comment by machour** [comment]
Closed as resolved. Feel free to improve the troubleshooting section :)
