### ISSUE TITLE
getDeviceLocale returning invalid language code for France

### ISSUE THREAD

**Issue by peterdev6** [react-native-community/react-native-device-info#501]
## Summary

|             |     |
| ----------- | --- |
| Version     | latest   |
| Affected OS | ios   |
| OS Version  |  11.4.1  |

## Current behavior

Set the device language to be French(France) and `DeviceInfo.getDeviceLocale()` returns `fr-US`

## Expected behavior
Should get `fr-FR` instead of `fr-US`

**Comment by mikehardy** [comment]
We will be working with react-native-localize to make sure locale support is 1st class - you should investigate migrating to their APIs for locale information. That said, I think we get this info raw from the device, so it's possible that there is just a very unexpected locale code, but it's coming from the device and we're just serving it up...

**Comment by mikehardy** [comment]
https://github.com/react-native-community/react-native-device-info/issues/627
