### ISSUE TITLE
[!] Unable to find a specification for `React` depended upon by `RNDeviceInfo`

### ISSUE THREAD

**Issue by rafbc** [react-native-community/react-native-device-info#502]
## Summary

|             |     |
| ----------- | --- |
| Version     |  0.22.6  |
| React Native | 0.56 |
| macOS Version  | High Sierra   |

## Current behavior

I followed the instructions, ran `react-native link`, then went to do a `pod install` inside the ios folder and i'm getting the following error

```
[!] Unable to find a specification for `React` depended upon by `RNDeviceInfo`
```

## Expected behavior

No error?!

**Comment by tclarke-scottlogic** [comment]
I get a different, but related problem:
https://github.com/rebeccahughes/react-native-device-info/issues/515

**Comment by tclarke-scottlogic** [comment]
Try this, hope it helps!
https://stackoverflow.com/questions/52737251/how-do-i-prevent-react-native-device-info-causing-react-ambiguity-on-my-setup/52776146#52776146
