### ISSUE TITLE
Detect Soft Navigation Keys in Android

### ISSUE THREAD

**Issue by kashishgrover** [react-native-community/react-native-device-info#511]
## Description

Implement something like `DeviceInfo.areSoftwareKeysEnabled()` or `DeviceInfo.hasSoftNavigationKeysEnabled()` to detect whether software keys are enabled in an android device.

## Use Case

To detect whether a device has hardware keys enabled or software keys enabled. This can be a bit of an issue when it comes to designing for all kinds of devices. These days with the advent of notches and curved devices, handling this is super important

**Comment by NemanjaManot** [comment]
+1

**Comment by manuhook** [comment]
https://github.com/Sunhat/react-native-extra-dimensions-android
ExtraDimensions.isSoftMenuBarEnabled()

**Comment by mikehardy** [comment]
This looks like a great find @manuhook - nice! I see no reason to duplicate the work in that package, as it seems very thorough and with recent updates. I'm closing this but please holler if you think I'm wrong

**Comment by Bardiamist** [comment]
https://github.com/Sunhat/react-native-extra-dimensions-android wrong on Redmi Note 7 (`isSoftMenuBarEnabled` return `false` when it is should be `true`).

Would be good to have that feature in DeviceInfo. Now I need that for try to improve [some bug workoround](https://github.com/facebook/react-native/issues/23693#issuecomment-571184297) because [got this](https://github.com/facebook/react-native/issues/23693#issuecomment-674644381).

**Comment by mikehardy** [comment]
When I looked at this last time, the referenced package seemed active. Now it seems dead, which is new information from my perspective. I don't want to duplicate work but I won't obstruct making things work, if that makes sense?

I would be open to ingesting that code if you posted an issue there saying "This repository appears dormant, any objections to hosting the functionality in react-native-device-info?" and proposed a PR here. I'd be happy to make any maintainers there maintainers here etc - the idea is friendly maintenance of features people need, not some icky power play in other words, we all have enough to do without maintaining more code and politics is not even on my list of things to dabble in :sweat_smile:

**Comment by roots-ai** [comment]
Any updates here?
