### ISSUE TITLE
FingerprintID || FaceID detection

### ISSUE THREAD

**Issue by tonmanayo** [react-native-community/react-native-device-info#527]
## Description

Check if the device has Fingerprint or FaceID capabilities 

## Use Case

It would help significantly if we were able to make these queries and react to the responses.
Currently there is a library called react-native-touch-id which allows you to implement faceID or touchID but you can't check the responses on android if the device has face ID or touch ID you just get a response of true or false.
Seeing as the core purpose of this library is to check the devices info I think this request belongs here

**Comment by bansalayush** [comment]
Hey @tonmanayo can you explain what do you mean by `responses` . Didn't exactly get you there.

**Comment by mikehardy** [comment]
https://github.com/hieuvp/react-native-fingerprint-scanner

**Comment by ericwrobinson** [comment]
@bansalayush @mikehardy I think what the OP is requesting is checking for whether the device has TouchID or FaceID available. So instead of having to list out all of the iPhones that use FaceID to render content specific to that device, there would be some sort of use function like: 

DeviceInfo.hasFaceId() // would return `true` if it's an iPhone X / iPhone 11 etc.
--or--
DeviceInfo.BiometricsType() if iPhone X would return a string of `"FaceID"` or iPhone 8 would return `"TouchId"`

**Comment by mikehardy** [comment]
You mean, like https://github.com/hieuvp/react-native-fingerprint-scanner#issensoravailable-android-ios

This stays closed

**Comment by ericwrobinson** [comment]
Sure, I could use a completely separate plugin (and probably will) but wouldn't it make sense for 'react-native-device-info' to be the one to give me the info about the device?

Appreciate your thoughtful response though.

**Comment by mikehardy** [comment]
The problem with the general idea of react-native-device-info doing every single device-related thing when other packages do a really good job - especially on APIs that move quickly like biometrics - is that it is both duplication of effort and a stretch of maintainer resources

I encourage you to adopt either that package or this package to change this contribution chart to a checkerboard of green https://github.com/ericwrobinson - then try "wouldn't it make sense for ___ package to be the one to ___" again - and I mean that sincerely, we could use more maintainers and fewer feature requests
