### ISSUE TITLE
how to merge phonegap uuid to react native?

### ISSUE THREAD

**Issue by MingFaiYau** [react-native-community/react-native-device-info#552]
Dear all,

I have an old App write by phonegap and using device.uuid to get the uuid.
Now, we are going to rewrite with react-native , but i find that the uuid of phonegap is different with android.

anyone have idea how to merge them?
Thanks.

**Comment by mikehardy** [comment]
I can't think of any way to merge them. Android and iOS both treat IDs as personally identifiable information, and are very quick to reset them or disallow access. You'll need some app level persistence and mapping from old to old+new then to new
