### ISSUE TITLE
wish set android:exported="false" , OK??

### ISSUE THREAD

**Issue by suwu150** [react-native-community/react-native-device-info#554]
## Summary
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.learnium.RNDeviceInfo">
          
    <application>
        <receiver
            android:name="com.learnium.RNDeviceInfo.RNDeviceReceiver"
            android:enabled="true"
            android:exported="false"
        >
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
        </receiver>
    </application>

</manifest>
```

the device is android,i wish set android:exported="false".

## Current behavior
```
android:exported="true".
```
## Expected behavior

```
android:exported="false"
```

**Comment by machour** [comment]
Why?

**Comment by mayurssoni2456** [comment]
I have the same question - do we need exported to be "true"? any thoughts

**Comment by mikehardy** [comment]
I believe it must be true yes. The docs indicate it has to be true to receive broadcasts from outside the app package, and I believe this is the installer sending a broadcast so you'd only receive if it were true.

But feel free to try it either way, I could be wrong about the installer package specifically?

https://developer.android.com/guide/topics/manifest/receiver-element

**Comment by hpelitebook745G2** [comment]
@mikehardy my app was previously flagged vulnerable with low risk rating specifically on the AndroidManifest.xml since the receiver was `exported="true"`, can I set it to false since I'm only using the library to get the basic info like getVersion()?

**Comment by mikehardy** [comment]
You may do whatever you like.
