### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by machour** [react-native-community/react-native-device-info#558]
Sadly I don't have the time to maintain this project anymore. Anyone wants to step up?

/CC @GantMan

**Comment by GantMan** [comment]
No worries!  I'd love to get @rebeccahughes in here and see about contributing the project to the React Native Community.  That way it can survive forever.

**Comment by mikehardy** [comment]
I could help with grooming android PRs but seems like react-native-community is the spot. I'll wait for any move there...

**Comment by machour** [comment]
Thank you @mikehardy. Dropped you an email to define the workflow we could adopt while waiting for @rebeccahughes decision.

**Comment by rebeccahughes** [comment]
That's fine with me, although I need permission to create repos on that org to move it

**Comment by mikehardy** [comment]
@pvinis sorry to bother you by tagging you in here, but you *just* moved rn-diff-purge into react-native-community. I swear I looked in the docs and googled but I didn't see where you petition to move a repo there. How do you actually do it? Apologies again, and thanks in advance :-)

**Comment by pvinis** [comment]
Hey. :)
Most people did it through the lean core issue.
I got asked to move it to RNC so that it's more "official" or more easy for people to find it.
There are some others too that I'm guessing it was after taking with one of the core contrib people.
Maybe we can tag @cpojer and I can also raise the question with the team.
I think this is a package that should definitely be in the RNC.

**Comment by cpojer** [comment]
Forked it over to here: https://github.com/react-native-community/react-native-device-info

Let me know if you want to maintain it and I'll give you write access.

**Comment by machour** [comment]
@cpojer Thank you so much! How will the subsequent publications to npm be handled? Who should we add as maintainer in npmjs.com?

**Comment by cpojer** [comment]
Once we find a new maintainer, we can transfer it over to them. Feel free to add me (`cpojer`) to the npm package for now,

**Comment by mikehardy** [comment]
@machour for continuity sake if you weren't maintainer I would be afraid - I just showed up here :-), but if you were there for an assist I'd be willing to help

**Comment by machour** [comment]
@cpojer Just added you to the npm package. Could you add me as a maintainer for the new repository as suggested by @mikehardy ? I'll help with what I know until the community own it back.

**Comment by cpojer** [comment]
@machour Done! I gave you access to the repo. Would you be able to redirect this one to the react-native-community repo?

**Comment by machour** [comment]
Thank you, unfortunately I don't have enough karma to do that. 
@rebeccahughes would you please do the redirection? 🙏

**Comment by rebeccahughes** [comment]
Like I said above, I cannot move it because I do not have permissions on react-native-community

**Comment by cpojer** [comment]
Oh I missed that, sorry. @rebeccahughes I gave you access to react-native-community. Would you mind making the transfer? Thank you!

**Comment by rebeccahughes** [comment]
Okay done :)

**Comment by cpojer** [comment]
Amazing, thank you!

**Comment by machour** [comment]
@cpojer could you grant @mikehardy karma on this repo to help triage issues? (labels / close & open on issues and PRs).

Thank you!

PS: let me know if there's a better medium to bug you with this sort of things.

**Comment by cpojer** [comment]
@machour I just gave you admin rights again on this repo so you can do these things on your own :) Added @mikehardy to this repo, too :)
