### ISSUE TITLE
The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated

### ISSUE THREAD

**Issue by gatspy** [react-native-community/react-native-device-info#562]
run app on simulator with 'iPhone X' from xcode, in debug area, show this error info.

## Detail Info
```txt
[NetworkInfo] Descriptors query returned error: Error Domain=NSCocoaErrorDomain Code=4099
 “The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.” 
UserInfo={NSDebugDescription=The connection to service named 
com.apple.commcenter.coretelephony.xpc was invalidated.}
```

## Summary

`react-native info `

```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 88.89 MB / 16.00 GB
      Shell: 5.6.2 - /usr/local/bin/zsh
    Binaries:
      Node: 10.15.0 - ~/./node/v10.15.0/bin/node
      Yarn: 1.13.0 - ~/./node/v10.15.0/bin/yarn
      npm: 6.5.0 - ~/.node/v10.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        Build Tools: 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.3, 24.0.3, 25.0.0, 25.0.3, 26.0.2, 26.0.3, 27.0.3, 28.0.3
        API Levels: 17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.7.0 => 16.7.0
      react-native: 0.57.8 => 0.57.8
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by hemantasapkota** [comment]
Thought I should take a stab at this. Running this fixes the issue:

```
xcrun simctl spawn booted log config --mode "level:off"  --subsystem com.apple.CoreTelephony
```
Source: https://stackoverflow.com/questions/52455652/xcode-10-seems-to-break-com-apple-commcenter-coretelephony-xpc

It simply disables logging for the CoreTelephony framework.

Not sure if this needs a PR.

**Comment by mikehardy** [comment]
Huh - that's some voodoo right there. I notice in the comments linked there (https://stackoverflow.com/questions/52455652/xcode-10-seems-to-break-com-apple-commcenter-coretelephony-xpc#comment92494959_52455652) that this seems to resolve on Mojave?

I personally haven't seen this because I keep my OS up to date on the macOS side which I expect most people do since it's up to date.

So I'd think this response in this issue should be sufficient assuming it is true that it is not present on macOS-current

Can you confirm that you actually saw this error (indicating we need some docs), or did you just go after an issue and find stackoverflow (as it frequently does) had the perfect answer (and we can just close this and let it go)?

**Comment by hemantasapkota** [comment]
I'm on Mojave 10.14.2. The error pops up when you run the example project.

<img width="1552" alt="Screen Shot 2019-03-23 at 2 33 10 am" src="https://user-images.githubusercontent.com/896157/54834317-0a5c0c00-4d14-11e9-8773-20a595e638c6.png">

Running the script fixes the problem. An alternative fix is to set the OS_ACTIVITY_MODE = disable variable to XCode's environment variables, which disables system level logging altogether. But it's something the user has to do.

<img width="1552" alt="Screen Shot 2019-03-23 at 2 41 24 am" src="https://user-images.githubusercontent.com/896157/54834886-2f04b380-4d15-11e9-8673-178a44b53c56.png">

**Comment by mikehardy** [comment]
Huh. Sounds like the perfect thing for the Troubleshooting section then? https://github.com/react-native-community/react-native-device-info/blob/master/README.md#troubleshooting

**Comment by hemantasapkota** [comment]
Sure. I can send a PR. Out of the two, which one do you think is more appropriate ?

**Comment by mikehardy** [comment]
I'd go for this one I think - seems focused?

> xcrun simctl spawn booted log config --mode "level:off"  --subsystem com.apple.CoreTelephony
> ```
> Source: [stackoverflow.com/questions/52455652/xcode-10-seems-to-break-com-apple-commcenter-coretelephony-xpc](https://stackoverflow.com/questions/52455652/xcode-10-seems-to-break-com-apple-commcenter-coretelephony-xpc)
> 
> It simply disables logging for the CoreTelephony framework.
>
