### ISSUE TITLE
getDeviceLocale is not updated when changed on the phone

### ISSUE THREAD

**Issue by jpolo** [react-native-community/react-native-device-info#570]
## Summary

|             |     |
| ----------- | --- |
| Version     | 0.26.2   |
| Affected OS | android   |
| OS Version  | all   |

## Current behavior

1. Read `getDeviceLocale()` in any app
2. Put the app in background mode and change the locale of the phone
3. Go back to the app and read `getDeviceLocale()` it has not changed

## Expected behavior

`getDeviceLocale()`should return the real device at the moment of the call

**Comment by xinfang** [comment]
+1

**Comment by mikehardy** [comment]
+1 comments are spam. Just thumbs up the issue if you have no new info to add please.

**Comment by mikehardy** [comment]
thinking further, there is another react-native-community project that handles localization better and this isn't really device specific, we should remove these completely in device-info 2.0 in favor of this module: https://github.com/react-native-community/react-native-localize

**Comment by mikehardy** [comment]
that project has listeners so it gets updated information - it's what I was thinking of doing here, but...it's already done! go snag it

**Comment by mikehardy** [comment]
Running a poll with a proposal to defer to @react-native-community/react-native-localize package where this is likely handled better https://github.com/react-native-community/react-native-device-info/issues/627

**Comment by jpolo** [comment]
@mikehardy you are totally right. Better not duplicate from localize. Ip address could be moved to netinfo too...

**Comment by mikehardy** [comment]
yes - and there are some things that react-native-carrier-info seem like would be a great place but that package doesn't seem active and the maintainer hasn't responded to me. netinfo will be well-maintained though so would be a good home for APIs. I'll look through them to see where we duplicate, for a similar sort of deprecate/remove proposal. Thanks for mentioning it
