### ISSUE TITLE
getIPAddress() returns old cached ip address

### ISSUE THREAD

**Issue by npreiser** [react-native-community/react-native-device-info#574]
## Summary

|             |     |
| ----------- | --- |
| Version     | ?   |
| Affected OS | ?   |
| OS Version  | ?   |

**Comment by npreiser** [comment]
Using android 9,  latest react-native  I am seeing that if  connected to wifi at 192.168.1.20,   I call getIPAddress(),  it returns, correctly.   Then  I switch my wifi connection to a different host,  and have a ip off 192.168.70.45...  and call getIPAddress(),  but it returns the old ip.... 
Has anyone else seen this,   it appears like its caching the value, and needs to be cleared or reset...

**Comment by jpolo** [comment]
It seems to be the same class of problem as : https://github.com/rebeccahughes/react-native-device-info/issues/570

**Comment by mikehardy** [comment]
indeed the Java module is storing those values in a map and returning it in the overridden implementation of getConstants. I didn't see any listeners that would serve as system callbacks in case the values needed an update

**Comment by mikehardy** [comment]
We're going to work together with react-native-netinfo to get this functionality built in that package - not closing this yet, but keep an eye on that repo as well 

you may want to mention it on the open issue they have with regard to getting the IP address so this is addressed

per our issue here https://github.com/react-native-community/react-native-device-info/issues/635

**Comment by npreiser** [comment]
thanks for the update..

**Comment by inf3rnus** [comment]
Any update on this issue? It's becoming a bit of a problem for a wifi drive project I'm working on. I appreciate all the work everyone has put into this!

**Comment by mikehardy** [comment]
No updates from here - the PR in the netinfo repo is https://github.com/react-native-community/react-native-netinfo/pull/122 and I think there is https://github.com/pusherman/react-native-network-info also which may help? Basically we need more implementors than feature requestors - always the case :-) :man_shrugging:

**Comment by inf3rnus** [comment]
Thanks Mike, I'm taking a look at the module to see if I can figure it out.

**Comment by mikehardy** [comment]
react-native-netinfo is not really ready for this to be removed yet but react-native-network-info looks viable for IP address information.

I'm deprecating this in v3 but not going to purge it yet. That said...What I don't understand is how this can be stale when we are actually retrieving the IP address on demand. This should be working? https://github.com/react-native-community/react-native-device-info/blob/master/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L260

**Comment by mikehardy** [comment]
Resolving this in favor of the netinfo PR that was just merged, their NetInfoState object (returned in response to their fetch() API or via event subscription sending  you new state when connectivity changes) has the IP now in all cases where we had it (read as: wifi only)
