### ISSUE TITLE
Implementing Expo

### ISSUE THREAD

**Issue by mreorhan** [react-native-community/react-native-device-info#576]
## Description

I want to use with Expo.
## Use Case
Maybe you could create a new package. react-native-device-info-with-expo

**Comment by vdlindenmark** [comment]
Use some of those: https://docs.expo.io/versions/v32.0.0/sdk/constants/ or eject your expo app

**Comment by DB1703** [comment]
Sorry so you can´t use this library when developing with Expo?

**Comment by mikehardy** [comment]
@DB1703 this is an issue from 2019. A lot has changed in 3 years
Please read about the various ways of developing Expo apps and think about them. In particular about "managed" style I think, and how you integrate third part modules using config plugins and prebuild etc.

Most importantly, after reading **before asking questions** make little test example apps and try things. Do that before consuming other's time

No one will answer generic questions about Expo like the one you asked.

**Comment by DB1703** [comment]
Ok my bad @mikehardy, it wasn't my intention to "waste someone's time". Thanks for the help and the fast answer anyways!
