### ISSUE TITLE
hasNotch returns false on OnePlus 6t

### ISSUE THREAD

**Issue by Eddie-CooRo** [react-native-community/react-native-device-info#577]
## Summary
Has notch returns false on OnePlus 6t 

|             |     |
| ----------- | --- |
| Version     | 0.26.4   |
| Affected OS | Android   |
| OS Version  | 9   |

**Comment by 357280841** [comment]
"react": "16.6.3",
"react-native": "0.57.8",
"react-native-device-info": "^0.26.4",

react-native-device-info is not work

**Comment by edreyyo** [comment]
@Eddie-CooRo this should be fixed from 0.26.1 onwards. See pull request: https://github.com/rebeccahughes/react-native-device-info/pull/563
