### ISSUE TITLE
hasNotch not working on Pocophone F1

### ISSUE THREAD

**Issue by NemanjaManot** [react-native-community/react-native-device-info#581]
## Summary

**DeviceInfo.hasNotch()** returns false on **PocoPhone F1**

Version: 0.26.4  
Affected OS: Android   
OS Version: 9

**Comment by edreyyo** [comment]
The Poco F1 is in the list of `devicesWithNotch` (see https://github.com/rebeccahughes/react-native-device-info/blob/9d92e55dfe9bc6271887a4637ef0d5b95eb44205/deviceinfo.js#L177) and so should return `true`. What does it show if you call `console.log(DeviceInfo.getModel())` from your Poco F1?

**Comment by NemanjaManot** [comment]
@edreyyo 
'POCOPHONE F1'

**Comment by edreyyo** [comment]
Thanks, I have just submitted a fix @NemanjaManot. It will need to be approved by the repository owner.

**Comment by machour** [comment]
Fixed
