### ISSUE TITLE
IsAirplaneMode Breaks iOS

### ISSUE THREAD

**Issue by Alec321** [react-native-community/react-native-device-info#582]
## Summary

|             |     |
| ----------- | --- |
| Version     |0.26.4  |
| Affected OS | iOS  |
| OS Version  |  React-Native 0.58.5 |

## Current behavior

We are trying to call everything in the device info library functionally. That way we don't have to manually call each individual function to get all of the data. Other non-ios supported functions return not available if they are not iOS supported. isAirplaneMode call breaks iOS as it hangs the rest of the calls. 

## Expected behavior

Expected behavior of DeviceInfo.isAirplanemode() should return Not Available for iOS like other non-ios supported calls.

**Comment by mikehardy** [comment]
Do you have sample code? what version+model of iOS, and is it on an emulator or a real device? I was just testing iOS last night (and re-checked this morning) on real device, iPad 2 with 11.x (current for 11) and it successfully returns false in airplane mode or not when used from javascript code, it does not appear to hang any subsequent calls.

**Comment by Alec321** [comment]
On the ios emulator, I did something similar to this ```DeviceInfo.isAirPlaneMode().then(airPlaneModeOn => {
  // false
}); ```
It just hangs and never resolves

**Comment by mikehardy** [comment]
I've implemented an example that uses the API in #589 - you can try pulling it from the example branch on my fork or wait until it is merged (should be very soon) and try it. If you can get it to reproduce in the example then we have a chance of fixing it, though I haven't seen in the example myself. I'm using pretty current dependencies of everything though (RN0.58.6, Node 11.11.0, npm outdated was empty after building the example)

**Comment by mikehardy** [comment]
The example is merged now, you can git clone then try it to see what happens...
