### ISSUE TITLE
Return raw DeviceId value for iOS (at least)

### ISSUE THREAD

**Issue by rangav** [react-native-community/react-native-device-info#585]
## Description

Current Implementation for `DeviceInfo.getModel()`
```
NSString* deviceName = [deviceNamesByCode objectForKey:self.deviceId];

    if (!deviceName) {
        // Not found on database. At least guess main device type from string contents:

        if ([self.deviceId rangeOfString:@"iPod"].location != NSNotFound) {
            deviceName = @"iPod Touch";
        }
        else if([self.deviceId rangeOfString:@"iPad"].location != NSNotFound) {
            deviceName = @"iPad";
        }
        else if([self.deviceId rangeOfString:@"iPhone"].location != NSNotFound){
            deviceName = @"iPhone";
        }
        else if([self.deviceId rangeOfString:@"AppleTV"].location != NSNotFound){
            deviceName = @"Apple TV";
        }
    }
    return deviceName;
```

Suggested Implementation:
```
 NSString* deviceName = [deviceNamesByCode objectForKey:self.deviceId];
  
  if (!deviceName) {
    // Not found in the list
    deviceName = self.deviceId;
  }
  
  return deviceName;
```
## Use Case
When ever Apple releases new devices we have wait till this library is updated to get device model, currently we get only iPhone or iPad for new versions.

Better to return deviceId as default for new devices, which will be useful in analytics..

**Comment by mikehardy** [comment]
If I understand correctly, this will be a backwards compatible change, yes?

In the future if the device list we have is updated to include a model that previously was just returning the default from your proposed implementation, will the list update contain a different value from the default your proposal returns, implying gaps of time where the data will be inconsistent?

Just trying to think through the impact. I like the idea of future-proofing it though, definitely

**Comment by rangav** [comment]
Yes it should be backwards compatible. (Its not breaking any functionality).

In future after updating the list, instead of returning the model id it will return model name.

I don't see any problem, but lets hear from others also.

**Comment by mikehardy** [comment]
Hmm - If I understand correctly I see a problem. The return value won't be stable for the same device across versions of the module, that is the definition of a breaking change unfortunately, and I'm not going to do a breaking change release every time we update the Apple mapping lookup table.

Also, this would be a breaking change in that we'd change the current behavior of lookups fails to deviate from the current pattern of returning generic but well-defined strings that people may be referencing in exact matches.

So this proposal is not going to happen.

**However**

I see nothing wrong with a parallel function that is a pure getDeviceId, then for those that cannot wait they can reference that.

In cases like this I also reference the "patch-package" package - it's fantastic for integrating tiny patches like this while you wait for an upstream merge (ideally of your patch as a PR), although it puts you at risk of having the PR eventually merged be different than your proposal and requiring you to modify your app code to adapt to upstream once the modified PR goes in. Still is useful

**Comment by rangav** [comment]
Yeah getDeviceId additional function is also good option for both platform.

**Comment by rangav** [comment]
Actually the library has getDeviceId function already that returns raw phone id, that should be good enough i think. We can close this issue.

**Comment by mikehardy** [comment]
Nice, my favorite way to close things -> already implemented ;-)

**Comment by mikehardy** [comment]
FYI - here's how I'm going to maintain the getModel/getDevice APIs for iOS going forward https://github.com/react-native-community/react-native-device-info/pull/618#issuecomment-479661030
