### ISSUE TITLE
Remove React dependency 

### ISSUE THREAD

**Issue by rangav** [react-native-community/react-native-device-info#586]
## Summary

|             |     |
| ----------- | --- |
| Version     |  v0.26.4|
| Affected OS |  iOS|
| OS Version  | iOS 12, RN 0.58.5|

## Current behavior

```
Pod::Spec.new do |s|
  s.name         = "RNDeviceInfo"
  s.version      = "0.21.5"
  s.summary      = "Device Information for react-native"

  s.homepage     = "https://github.com/rebeccahughes/react-native-device-info"

  s.license      = "MIT"
  s.authors      = { "Rebecca Hughes" => "rebecca@learnium.net" }
  s.ios.deployment_target = '8.0'
  s.tvos.deployment_target = '10.0'

  s.source       = { :git => "https://github.com/rebeccahughes/react-native-device-info.git" }

  s.source_files  = "ios/RNDeviceInfo/*.{h,m}"

  s.dependency 'React'
end
```
please remove dependency of react -  still appears - is it not removed yet?

Project build is failing due multiple versions of react

## Expected behavior

Please remove   `s.dependency 'React'`

**Comment by mikehardy** [comment]
I must admit I have very little experience with using Pods. I am only barely able to get my react-native apps working on iOS :-). Can you propose a PR that makes this change, and ideally recruit anyone else that has proposed a PR in this repo for iOS behavior to check it? You can should be able to find someone from looking at closed PRs and tag them and hopefully they'll help

**Comment by rangav** [comment]
I think we don't need pods for this library, as we are not dependent on any 3rd party libraries. I will try and submit a PR if possible.

**Comment by guhungry** [comment]
Technically you don't need it but since all project use this library install React Native in someway but this project use `React` which is React Native to expose native module to JS.
So React should be there.

**Comment by machour** [comment]
@guhungry this issue comes back from time to time. Any final decision you'd make ?

OP seems to have problems: "Project build is failing due multiple versions of react"

Is there anything we can do to enhance this?

**Comment by machour** [comment]
See also #303

**Comment by guhungry** [comment]
Hi @rangav
1) Can you run `react-native info`
2) Which command line that failed
3) Can you provide more specific error message?

**Comment by rafcontreras** [comment]
@rangav 

You can add this code on your own Podfile:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

**Comment by mikehardy** [comment]
I had to read up on Pods yesterday, and I think removing it the react dependency is correct.
@rafcontreras advice is also apparently best practice. If you are not doing that you will apparently be in a world of hurt using Pods with React-Native. That snippet is a great hack in that it is necessary (and therefore great) and a hack (in that it's existence is sort of offensive...but it's still great) :-) 

Once you add that snippet you won't need this module (or any module) to get the React dependency correct but I still think it's correct to remove it - especially if we get some feedback that removing it doesn't break anything

**Comment by machour** [comment]
Removing the React dependency was done in 0.21.1 (https://github.com/react-native-community/react-native-device-info/pull/361) but rolled back in 0.21.5 as users complained about breakages in the PR comments.

**Comment by mikehardy** [comment]
Can't argue with direct experience, that snippet should fix it then. And eventually building everything on ios will hopefully suck less...

**Comment by rangav** [comment]
Hi I did some testing, here is my finding

- When there is no Podfile in the RN project, then `react-native link react-native-device-info` works fine, no issues

- But when there is Podfile in the RN project, then `react-native link react-native-device-info` is adding new pod line in the Podfile - `pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'` this is causing the issue and installing React 0.11.0 when we run pod install.

Dont know why that line added to Podfile, when i linked `react-native-maps` it dosen't put anything is the Podfile.

By Removing the RNDeviceInfo.podspec solving the issue. 

So i think we dont need RNDeviceInfo.podspec as it not depending on any other libraries, we can remove this file from the project.

let us see others comments on this

**Comment by guhungry** [comment]
@rangav Can I see your `Podfile`?

My project is not install React 0.11.0 as your and I have many library that have `s.dependency 'React'`.

Example:
https://github.com/react-native-community/react-native-image-editor/blob/master/react-native-image-editor.podspec
https://github.com/DylanVann/react-native-fast-image/blob/master/react-native-fast-image.podspec
https://github.com/react-native-community/react-native-svg/blob/master/RNSVG.podspec
https://github.com/kmagiera/react-native-screens/blob/master/RNScreens.podspec
https://github.com/react-native-community/react-native-video/blob/master/react-native-video.podspec
https://github.com/jpush/jcore-react-native/blob/master/JCoreRN.podspec
https://github.com/jpush/jpush-react-native/blob/master/JPushRN.podspec
https://github.com/react-native-community/react-native-netinfo/blob/master/react-native-netinfo.podspec
https://github.com/react-native-community/react-native-async-storage/blob/master/react-native-async-storage.podspec
https://github.com/itinance/react-native-fs/blob/master/RNFS.podspec
https://github.com/react-native-community/react-native-image-editor/blob/master/react-native-image-editor.podspec
https://github.com/Microsoft/AppCenter-SDK-React-Native/blob/develop/appcenter-analytics/ios/appcenter-analytics.podspec

Here is mine [Podfile](https://gist.github.com/guhungry/0d6ff632838fb088aa60f5a6abe55661)

**Comment by rangav** [comment]
My Pod File
```
target 'Test591' do

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

end
```

Steps to reproduce the problem:
- Create new test project using `react-native init Test591`
- then `cd ios && pod init`
- then `npm install --save react-native-device-info` and `react-native link react-native-device-info`
- then `cd ios && pod install` -> this will install react 0.11.0
- then `react-native run-ios`

 This is throwing error about react and react-native..

**Comment by guhungry** [comment]
@rangav You need to install React via pod too. https://facebook.github.io/react-native/docs/integration-with-existing-apps

Basically please add
```rb
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
```

**Comment by mikehardy** [comment]
> 3. then `npm install --save react-native-device-info` and `react-native link react-native-device-info`
> 4. then `cd ios && pod install` -> this will install react 0.11.0

It was my understanding that if you are using podfiles you should not link?

**Comment by guhungry** [comment]
> > 1. then `npm install --save react-native-device-info` and `react-native link react-native-device-info`
> > 2. then `cd ios && pod install` -> this will install react 0.11.0
> 
> It was my understanding that if you are using podfiles you should not link?

You almost always link native libraries with `react-native link` regardless of your project setup (pod or project).
If `react-native link` detect pod will try to link with pod first or else via project file.
But for pod to work properly you must install React native via pod too. And also remove React dependencies from project file too or else it will crash with each other.

It's one way or another for linking if you use pod all native libraries need to link with pod.

**Comment by mikehardy** [comment]
react-native-camera is the most popular library I have studied recently and they distribute their Podfile with the "remove react" snippet in it: https://github.com/react-native-community/react-native-camera#mostly-automatic-install-with-cocoapods

I've seen that referenced everywhere as the only way at the moment to reliably mingle Cocoapods into react-native iOS builds. Is there any non-novice at Cocoapods willing to do a documentation PR similar to react-native-camera that shows people how to integrate Cocoapods?

**Comment by mikehardy** [comment]
Okay, I'm learning through development on my own project how this whole Pod thing works. @guhungry thank you so much for the information here, it was a big help.

I believe the Pod contents @guhungry recommends are the standard and are correct, with the addition of the React (and maybe yoga) remove snippet that you frequently see. I have this working locally and it's stable as I add/remove pods and link other modules. I think the react-native-camera doc guidance is sufficient and we could include as ios troubleshooting but with our module name:

### You may need to adjust your Podfile like this if you use Cocoapods and have undefined symbols or duplicate React definitions

```
target 'yourTargetName' do
  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'react-native-info', path: '../node_modules/react-native-device-info'

end

# if you see errors about React duplicate definitions, this fixes it. The same works for yoga.
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

I'd like to add this to docs and close this. Can someone read through and make sure I'm not crazy? Thanks!

**Comment by mikehardy** [comment]
Docs are updated
