### ISSUE TITLE
getSerialNumber - gives wrong serial or unknown

### ISSUE THREAD

**Issue by Couiljer** [react-native-community/react-native-device-info#595]
## Summary

|        getSerialNumber() method     |     |
| ----------- | --- |
| Version     | 1.0.0   |
| Affected OS | Android  |
| OS Version  |8 & 9  |

## Current behavior
I get a strange behavior with the getSerialNumber method and I can't figure why.. 
 - Tests made on samsung tab A 9.7 - android 9 Lineage : returns Unknown
- Tests made on samsung tab A 10.5 - android 8 samsung - returns a wrong serial number / different that the device's one. 

## Expected behavior

Get the serial number, and the real one 😄

**Comment by mikehardy** [comment]
You will not get "the real one" as it is not really possible in Android O and here https://android-developers.googleblog.com/2017/04/changes-to-device-identifiers-in.html

So those numbers are mutable, and in practice not that reliable depending on manufacturer prior to ). They are basically "for informational purposes only"

**Comment by micheleberetta98** [comment]
What do you mean by mutable? Because I've had the same problem, `Build.SERIAL` returning _Unknown_ on Android 9. However, the link provided says that `Build.SERIAL` is deprecated in favour of " Build.getSerial(), which returns the actual serial number, as long as the caller holds the PHONE permission".

**Comment by mikehardy** [comment]
I mean, they can return whatever the device manufacturer wants as if I recall correctly the API says they should return different values for different signing keys etc. There are approved ways to identify devices on iOS and Android, and they all have their drawbacks, it's a difficult / complicated space.
