### ISSUE TITLE
react-native-web empty polyfill may be out of date

### ISSUE THREAD

**Issue by mikehardy** [react-native-community/react-native-device-info#599]
#323 added an empty polyfill for web but it may not be up to date. If any RN4W users can scour it and bring it up to date, that could be useful

**Comment by machour** [comment]
Updating the object signature to match our current API should be enough imho, I'd gladly review your first attempt at this :)

**Comment by machour** [comment]
Just did us a favor in https://github.com/react-native-community/react-native-device-info/commit/652271048391e42b4aa80a66e894ce178ad5b65b, it should help us remember to update these files with every new feature.

**Comment by mikehardy** [comment]
This should be fixed in v3 because I moved platform-selection on platform-specific APIs to the main deviceinfo.js file, with positive platform matching required before the javascript attempts to call into a native module and a standard default value returned otherwise. That way there is a default built in, and there's no need for a separate defaults file to be (un-)maintained. Still needs testing on the web (and via 'dom' for jest) but it should work fine
