### ISSUE TITLE
Use of Wildcards in Search Criteria

### ISSUE THREAD

**Issue by mikeyamato** [react-native-community/react-native-device-info#601]
## Description

Allow the use of wildcards when defining search criteria to encompass multiple devices.

## Use Case

For `getModel`, instead of typing `getModel === 'iPhone X' || getModel === 'iPhone XR' || getModel === 'iPhone XS' || getModel === 'iPhone XS Max'` can it be something like `getModel === 'iPhone X'*` where the asterisk (*) is the wildcard?

**Comment by machour** [comment]
Hi and thank you for the proposal, but this really doesn't fall into this library scope, which is extracting data from the device and handing it back to you.

Your use case could be implemented using a regular expression in your app:

```js
if (device.getModel().match(/iPhone X.*/) {
   // special treatment
}
```
