### ISSUE TITLE
java:lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/util/zzv

### ISSUE THREAD

**Issue by askemeline** [react-native-community/react-native-device-info#603]
Hello, I have a problem, I can't install react-native-device-info 

I've got this error: 
Java exception in 'NativeModules'
java:lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/util/zzv
![qemu-system-x86_64_lVADqr5aRv](https://user-images.githubusercontent.com/33722860/55016616-69a96d00-4fef-11e9-8d41-09457c53d6ec.png)

I have react-native: 0.57.8

Someone had this problem ?
Thanks

**Comment by machour** [comment]
Hi,

There are several issues closed related to this, please check them before opening a new one :)

https://github.com/react-native-community/react-native-device-info/issues?q=is%3Aissue+android%2Fgms%2Fcommon%2Futil+is%3Aclosed

**Comment by mikehardy** [comment]
Maybe we need an FAQ page https://github.com/react-native-community/react-native-device-info/wiki

This one could be missing dependency (from install docs) or a need to switch to MultiDex

**Comment by askemeline** [comment]
Hello, yes I check before, but I didn't resolve my problem, it's seems it's not exactly the same error :/

**Comment by mikehardy** [comment]
If you definitely have the play services defined from the manual:
...
  ext {
    // dependency versions
    googlePlayServicesVersion = "<Your play services version>" // default: "+"
    compileSdkVersion = "<Your compile SDK version>" // default: 23
    buildToolsVersion = "<Your build tools version>" // default: "25.0.2"
    targetSdkVersion = "<Your target SDK version>" // default: 22
  }
...

Then you probably need to do MultiDex in your app (I had to when I integrated Firebase and then tested on old Android APIs). That's a bigger topic but I think this covers the two things you need to make sure are setup https://stackoverflow.com/a/50215721

**Comment by askemeline** [comment]
Ok thanks for your answer :)

**Comment by mikehardy** [comment]
@askemeline once you determine what is required, it would be useful if you could report back (especially if it is multidex) so we could add some troubleshooting for this error and suggest both reasons / solutions for future people

**Comment by askemeline** [comment]
Hello, so I change the value like you write but I can't build there are a lot of errors :/
Here my version
ext {
googlePlayServicesVersion ="11.8.0"
compileSdkVersion = 27
buildToolsVersion = "27.0.3"
targetSdkVersion = 26
}

**Comment by machour** [comment]
Can you share the errors you're encountering now?

**Comment by askemeline** [comment]
Sur, when I changed all value by "", I got this error
```
ERROR: Invalid revision: 
Open File
```

at 
```    
buildToolsVersion rootProject.ext.buildToolsVersion
``` 
in app\build.grade

**Comment by mikehardy** [comment]
There is a full example, you should try it to prove everything works, then adapt your code (android/build.gradle android/app/build.gradle to match)

**Comment by askemeline** [comment]
Hello, I did that you told me but, still same error, I'm new in React native so it's not easy for me :/
In build.grade, I have also this, it's normal ? 
```
    implementation "com.google.android.gms:play-services-base:16.0.1"
```

**Comment by askemeline** [comment]
I resolve problem :D with 
``` 
compile(project(':react-native-device-info')) {
        exclude group: 'com.google.android.gms'
    }

```

**Comment by mikehardy** [comment]
You are only giving us partial information. We'd need to see the whole build.gradle. What you posted is not normal. Please examine the example - check this project out from github and move into the example directory, npm install, npm start, and then react-native run-android (or run-ios)

Everything works and you are having installation errors - the example shows you how to do it.

**Comment by mikehardy** [comment]
Sorry - I just saw your last comment - I will say that your solution is potentially dangerous.

What you really want is the correct versions of things defined in an ext {} block in your app/build.gradle

The example shows how
