### ISSUE TITLE
Empty DeviceInfo.getUniqueID() with Expo.io

### ISSUE THREAD

**Issue by iLyxa3D** [react-native-community/react-native-device-info#612]
## Summary
**Version:** 
react-native-device-info@1.3.0
node v11.12.0
react-native-cli: 2.0.1
react-native: 0.57.1
**Affected OS:** Android
**OS Version:** Windows 10

## Current behavior

1. Setup project from Expo template 
`npm install -g expo-cli`
`expo init project-name`
2. Install react-native-device-info
`npm install --save react-native-device-info`
3. Link it to the react-native
`react-native link react-native-device-info`
4. Add code
`import DeviceInfo from 'react-native-device-info';`
`...`
`<Text>Info: { DeviceInfo.getUniqueID() } </Text>`
5. Run by expo emulator on the device
`npm start`  / `expo start`

**Got empty value of the getUniqueID.**
and no errors in terminal, expo debug window or adb android logs.

## Expected behavior
Get device ID.

**Comment by mikehardy** [comment]
Expo and Native code don't work together.
react-native-device-info uses native code.
