### ISSUE TITLE
I cannot see the any returning value in ios simulator

### ISSUE THREAD

**Issue by maestrolsj** [react-native-community/react-native-device-info#615]
## Description

I would like to see the proper returning value from the function call in IOS simulator
- All function returns empty string on IOS simulator
- Android works well
## Use Case

- IOS simulator
-  "react-native": "0.57.7"
-  "react-native-device-info": "^1.4.1"
- I installed through Pod

[ Pod setting ]
 pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
end
 
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end

**Comment by thomasdsouza** [comment]
same here both on simulator as well as on a device

**Comment by mikehardy** [comment]
This happens a lot. Integrating all this tech (react-native, cocoapods, 3rd party modules with native code) is difficult. But I'm 99.9% sure it's not this module's fault.

Please git clone the repo as of the last commit on master where I added CocoaPods support to the example, then:

`cd example && npm i && cd ios && pod install && cd .. && react-native run-ios`

If it doesn't work, please open an issue related to the example not working for iOS + pods. I just tested that though. it works.

If it does work, there is a problem with your application, examine the example to see how it works and carefully apply the same style to your app
