### ISSUE TITLE
Sync relevant methods from Google-authored flutter device-info package

### ISSUE THREAD

**Issue by mikehardy** [react-native-community/react-native-device-info#622]
https://github.com/flutter/plugins/blob/master/packages/device_info/android/src/main/java/io/flutter/plugins/deviceinfo/DeviceInfoPlugin.java

The whole repo (iOS and android side looks interesting)

At a minimum they have a more thorough Simulator detection heuristic. May have some other neat things

Related to #307

**Comment by Taym95** [comment]
Hey @mikehardy, which methods do you want to sync?

**Comment by mikehardy** [comment]
Hi @Taym95 that's a good question - the analysis is part of the task I think. I would look at their API and ours, and for any API they had propose to include it and why, and for any where the API was present in both, look at how they were doing what they were doing and see if they know some trick that we don't know and are doing it better (Flutter is Google and Android is Google so they may have better implementations?). Ingesting the code is the easy part in other words, but doing a little API-by-API comparison is where I think the mental effort is

**Comment by Taym95** [comment]
I will submit PR with relevant methods from Google-authored flutter.
