### ISSUE TITLE
Could not find manifest-merger.jar (com.android.tools.build:manifest-merger:26.3.2). after update React Native Version to 59.3

### ISSUE THREAD

**Issue by peyman-hakemi** [react-native-community/react-native-device-info#623]
| Affected OS | android  |
| OS Version  | api 26  |
| react  | 16.8.3  |
| react-native  | 0.59.3  |

## Current behavior

**build fail with this error after update my react native and react version**
>A problem occurred configuring project ':react-native-device-info'.
> Could not resolve all artifacts for configuration ':react-native-device-info:classpath'.
   > Could not find manifest-merger.jar (com.android.tools.build:manifest-merger:26.3.2).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/manifest-merger/26.3.2/manifest-merger-26.3.2.jar

this is my buildgradlew

         buildscript {
        ext {
        googlePlayServicesVersion = "+"
        firebaseVersion =  "+"
    
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
    }

     allprojects {
     repositories {
        google()
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
    }

and this is my buildgradlew inside app folder

    android {
     compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.cheshmeh"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
     }

    dependencies {
    implementation project(':react-native-pushe')
    implementation (project(':react-native-device-info')) {
     exclude group: "com.google.android.gms"
    }
    implementation project(':react-native-code-push')
    implementation project(':react-native-picker')
    implementation project(':react-native-blur')
    implementation project(':lottie-react-native')
    implementation project(':react-native-orientation')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-keep-awake')
    implementation project(':react-native-video')
    implementation project(':react-native-linear-gradient')
    implementation project(':react-native-svg')
    implementation project(':react-native-gesture-handler')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
     }

## Expected behavior

im expected to build succefully and everything work fine
thanks in advance

**Comment by mikehardy** [comment]
examine the sample and make sure it works for you then examine your apps build files to find the difference. it is likely a missing / incorrect usage of version pinning in android/build.gradle ext{} block like those '+' signs I see 

example is on 0.59.3
https://github.com/react-native-community/react-native-device-info/blob/master/example/package.json#L12

likely version pin issue
https://github.com/react-native-community/react-native-device-info/blob/master/example/android/build.gradle#L4
