### ISSUE TITLE
Poll: should react-native-device-info defer to react-native-localize for locale APIs?

### ISSUE THREAD

**Issue by mikehardy** [react-native-community/react-native-device-info#627]
# Proposal: Delete all the locale APIs in favor of @react-native-community/react-native-localize

##  Background

Historically there was no package for getting locales except this one, so it was implemented here. And it was good. It is worth mentioning that at that time this was an independent 3rd party package.

This package did a good job of getting the info, but it wasn't perfect. Specifically it considered the locale information static and did not update when the user updated (#215 etc).

## Current status + motivation:
- we have a pile of enhancement requests and issues related to localization that would require significant effort to address (you can see them below) :scream: :cold_sweat: 
- there is a [react-native-localize package](https://github.com/react-native-community/react-native-localize) that does a fantastic job [getting updated locale info](https://github.com/react-native-community/react-native-localize#basic-usage-example) :1st_place_medal: 
- react-native-localize is also part of react-native-community so it is high quality and maintained :handshake:

So in sum, there's a better package for this.

## Proposed Implementation :construction: :hammer_and_pick: 

- for one major release cycle (v2 / #307) deprecate all the locale APIs :warning: :no_good_man: 
- delete all the locale APIs in v3 :boom: 

## Feedback :mega: 

If you disagree, convince us we are wrong! :smile:

**Comment by mikehardy** [comment]
@zoontek might be interested in this :-) 

and as long as I'm tagging you Mathieu - excellent work, just started using i18n-js + react-native-localize in my project at work and it's very nice :clap:

**Comment by mikehardy** [comment]
going to count this comment as a vote in favor from a linked issue: https://github.com/react-native-community/react-native-device-info/issues/570#issuecomment-480037335

**Comment by machour** [comment]
Checked out react-native-localize and this definitely sounds like a good idea.

I don't think you need the transition phase in v2 as it will be full of breaking changes anyway. Let's simplify this and drop those methods in 2.0.

**Comment by zoontek** [comment]
@mikehardy It seems a good idea 🙂
But I will looks for a collaborator on localize first, it's not a good idea to stay a alone on the project.

**Comment by mikehardy** [comment]
@zoontek 
Absolutely - I'm willing to help a bit especially as it doesn't change our burden to simply shift the APIs officially to localize - and I use the module - but I am collaborating on 3 other community modules so that does not add a lot of redundancy to the community as a whole. 

Also maybe worth mentioning for you this chunk of typescript where a real app (your example is excellent but has the view and i18n service in the same module so is cheating ;-) ) is able to do view updates on locale changes - 

https://github.com/react-native-community/react-native-device-info/pull/547#issuecomment-480358294

**Comment by zoontek** [comment]
@mikehardy Yes I know, the example are not perfect 😬 Just got a new job and goes back to RN full time, I might update them with real world usage soon!

**Comment by mikehardy** [comment]
@zoontek I thought the examples truly were great FWIW - hopefully you took that from my comment. A single page example is ideal and that yours demonstrated the listener at all is pretty thorough. I just wanted to offer working code on how to do a singleton for the service, drop a hook into the view and use it :-)

**Comment by zoontek** [comment]
@mikehardy Would you be interested to be a collaborator on `react-native-localize` too? 🙂

**Comment by mikehardy** [comment]
@zoontek I could try to help there sure, but I won't be much help until May or so once my day-job app is launched. At the least I can be a backup "just in case" since you're flying solo there right now :scream: :smile:

**Comment by benoitdion** [comment]
👍 alternatively, you could also deprecate `react-native-localize` and move all functionality here. Both libs are tiny and the api surface area is pretty similar.

**Comment by mikehardy** [comment]
Ok, I'm going to resolve this in favor of react-native-localize. @benoitdion I disagree with the both libs are tiny in the sense that the APIs seems small but just from personal experience, keeping up with the pace of change on device-info, and some of the thorny issues on API changes (like multi-SIM) support is a big enough job. To have have more API surface area would be very difficult for me and would result in a new version maybe every other day (as opposed to every 4-5 days...)
