### ISSUE TITLE
Android getDeviceId return unknown

### ISSUE THREAD

**Issue by vohoangankhanh** [react-native-community/react-native-device-info#632]
|             |     |
|react-native  | 0.59.3 |
| Version     | 1.4.2   |
| Affected OS | Android   |
| OS Version  | 6   |

## Current behavior
I receive unknown when using getDeviceId method in Android
![image](https://user-images.githubusercontent.com/13093106/55702768-cb130800-5a01-11e9-8b1d-33eca0ec6b71.png)

![image](https://user-images.githubusercontent.com/13093106/55702777-d82ff700-5a01-11e9-84eb-75d8dcb19a2a.png)

## Expected behavior
I want to receive my device ID instead

**Comment by mikehardy** [comment]
Hi there! This looks like a clear sign of install failure, you didn't link. read the docs, try the example - it works
