### ISSUE TITLE
RNDeviceInfo is null error when running test

### ISSUE THREAD

**Issue by wollowizard** [react-native-community/react-native-device-info#636]
## Summary

|             |     |
| ----------- | --- |
| Version     | v1.4.3  |
| Affected OS | running tests with jest   |
| OS Version  | ?   |

## Current behavior

When running tests with jest, I get the following
@react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null. To fix this issue try these steps:

However the app runs fine

## Expected behavior

Simply run the test

**Comment by machour** [comment]
This is covered by out troubleshooting section (last item)
https://github.com/react-native-community/react-native-device-info#troubleshooting

**Comment by ronilitman** [comment]
@machour Fix that is suggested in troubleshooting does not work for me. Still getting the error mentioned above. Any suggestions?

**Comment by karimo255** [comment]
@wollowizard you can user  a mock for that.
create a __mocks__ directory in the root project cd to it and create a file react-native-device-info.js file.
put in the file the follwing: 
`export default {
     getIPAddress: () => {},
}`

add the desired items in the object.

**Comment by pavermakov** [comment]
I am exporting a pure function out of component that doesn't use react-native-device-info. Why do I still get this annoying error?

**Comment by mikehardy** [comment]
@pavermakov that comment generated email for everyone on this issue. Is your intention to share your repository so we can trace the javascript execution of your tests to find why the module attempts to load, and answer?

**Comment by YoavSch** [comment]
you can use a mock for that. create a __mocks__ directory in the root project, cd to it and create a file react-native-device-info.js. put in the file the following: export default { getIPAddress: () => {}, }

add the desired items to the object.

**Comment by amouxkin** [comment]
Another way would be to mock the module before tests. _**__esModule**_ is necessary if you've imported using ES6 destructuring.

```javascript
jest.mock('react-native-device-info', () => {
  return {
    __esModule: true,
    default: jest.fn(() => {})
  };
});
```

**Comment by Ekaanth** [comment]
if you would like to mock the `getVersion` or `getBuildNumber` or any other function you can do something like this:
```
jest.mock('react-native-device-info', () => {
  return {
    __esModule: true,
    default: {
      getVersion: jest.fn(() => {}),
      getBuildNumber: jest.fn(() => {}),
    },
  };
});
```
