### ISSUE TITLE
Functions return empty string, 0 or TypeError

### ISSUE THREAD

**Issue by KatsuroNCW** [react-native-community/react-native-device-info#637]
## Summary

|             |     |
| ----------- | --- |
| Version     | 1.4.1 |
| Affected OS | Android   |

## Current behavior

When i run project with expo DeviceInfo functions return empty string (e.g. getBrand or getDeviceCountry) or 0 (e.g. getBuildNumber) or "Unhandled promise rejection: TypeError: RNDeviceInfo.isAutoTimeZone is not a function." when i want to use isAutoTimeZone. Same behavior when i run builded app on android. 

I tried automatic and manual linking - same problem. Any ideas?

This is how i use this package in my project:
```js
import DeviceInfo from 'react-native-device-info';

const brand = DeviceInfo.getBrand();
console.log("brand: " + brand);
DeviceInfo.isAutoTimeZone().then(isAutoTimeZone => {
  console.log("isAutoTimeZone: " + isAutoTimeZone)
});
const deviceCountry = DeviceInfo.getDeviceCountry(); 
console.log("deviceCountry: " + deviceCountry)
const buildNumber = DeviceInfo.getBuildNumber();
console.log("buildNumber: " + buildNumber);```

**Comment by mikehardy** [comment]
Native code and Expo don't mix. https://docs.expo.io/versions/v32.0.0/expokit/eject/#should-i-eject-to-expokit
