### ISSUE TITLE
getTimezone always returns a constant value instead of the current value

### ISSUE THREAD

**Issue by varungupta85** [react-native-community/react-native-device-info#638]
## Summary

|             |     |
| ----------- | --- |
| Version     | 0.24.3   |
| Affected OS | Android. I haven't checked on iOS yet.| 
| OS Version  | All   |

## Current behavior

`getTimezone` returns the timezone that was set when the app was opened. After that, even if I changed the timezone and call `getTimezone` again, it always returns the previous value. I can see that in the code, it is exported as a constant due to which it retains the value when the module is initialized.

But if a user changes timezone and goes back to the app, it will still report the previous timezone which is not correct.

## Expected behavior

The latest value of timezone should be returned.

**Comment by mikehardy** [comment]
Use react-native-localize - it does what you want and our locale-related APIs will likely move there - https://github.com/react-native-community/react-native-device-info/pull/547#issuecomment-479902729
