### ISSUE TITLE
Headphones status

### ISSUE THREAD

**Issue by chenjianfang** [react-native-community/react-native-device-info#643]
How to judge whether the headphones are plugged in, and the headphones are playing sound？？？

**Comment by mikehardy** [comment]
I don't know, I haven't even looked for those APIs on the platforms and the library doesn't support them. Have you searched on stackoverflow, or in the Android or iOS developer documentation to see if it is even possible?

**Comment by machour** [comment]
Seems to be doable for Android, but a bit trickier for iOS. 

https://forums.xamarin.com/discussion/105066/detecting-if-headphones-are-plugged-in-on-android-and-ios (these are xamarin docs but they do mention os based solutions)

**Comment by mikehardy** [comment]
okay - looks possible but it would need someone to implement, marking it as such

**Comment by RWOverdijk** [comment]
https://stackoverflow.com/questions/21292586/are-headphones-plugged-in-ios7

Not sure if this perhaps changed over time, but it looks usable. I'll be implementing this for my project (so not here) but I thought I'd share the link anyway.

**Comment by Taym95** [comment]
I will take this issue over, PR soon!

**Comment by mikehardy** [comment]
Closed in #860
