### ISSUE TITLE
No getPowerState method on Android

### ISSUE THREAD

**Issue by alenoir** [react-native-community/react-native-device-info#647]
## Summary

|             |     |
| ----------- | --- |
| Version     | 1.5.1   |
| Affected OS | Android   |
| OS Version  | 9.0   |

## Current behavior

I can't use getPowerState method (found in doc) on Android. Inside `RNDeviceModule.java` file there aren't method `getPowerState`.

## Expected behavior

I can use method getPowerState.

**Comment by machour** [comment]
getPowerState() is only available on iOS according to README

**Comment by cristianoccazinsp** [comment]
Would be a great idea to provide a dummy implementation for it at least, so you don't get a surprise crash.

**Comment by mikehardy** [comment]
A dummy return would be one way to do it. I believe the library has in general has decided for platform-specific calls to have the API consumer guard for platform inconsistencies or check for undefined. And some of the calls can return undefined on the same platform based on device state IIRC. I believe an undefined test in the API consumer is not a bad design choice then as it is such an easy idiom (`maybeUndefinedReturn && doSomethingWithReturn(maybeUndefinedReturn)`, unless you are experiencing a crash in native code?
