### ISSUE TITLE
Feature Request - Get RAM used by app

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-community/react-native-device-info#650]
Seems like we can know the device RAM info, but not how much was used by the app. Is there a reason to not have that as well?

**Comment by mikehardy** [comment]
No reason in particular we don't have it. Should be promise based vs the constants though as obviously it can change. Doing it via events would probably be too performance-intensive but I guess if someone wanted to make a profiling app and there was a way to configure/throttle event frequency even that could work.

**Comment by cristianoccazinsp** [comment]
Seems like someone has implemented this already, perhaps some ideas could be stolen from there, or even merged into this library which is very comprehensive: https://github.com/robinpowered/react-native-vitals

**Comment by mikehardy** [comment]
Huh - great find - I would just nuke our getStorage API and tell people to use vitals. I loathe duplication and we're trying to organize our API for v2 such that it is coherent, not duplicated, maintainable (i.e., of reasonable size) and works really well #307
