### ISSUE TITLE
Android Error On version 1.6.0

### ISSUE THREAD

**Issue by mohsenomidi** [react-native-community/react-native-device-info#651]
## Summary

|             |     |
| ----------- | --- |
| Version     | 1.6.0  |
| Affected OS | Android   |
| OS Version  | ALL   |

## Current behavior

If you just import this Package Version 1.6.0 to the project you get attached error 
empty project, just import, old version works perfectly. 
![err](https://user-images.githubusercontent.com/47596867/56956925-cb16ab80-6b5a-11e9-8af2-66da2238db32.jpg)

## Expected behavior

i used old version and no error

**Comment by mikehardy** [comment]
What's the old version you used? 1.5.1?

**Comment by mikehardy** [comment]
Also, you don't indicate other versions - what version of react-native are you using? Maybe you could attach your package.json or similar? I tested this prior to release with 0.59.5 react-native and our example project and everything seemed fine

**Comment by mohsenomidi** [comment]
Hi, 
it seems it not related to device info (maybe).
this morning my  project getting failed (it works before), i just init new project and may it related to other updated packages, like net info... 
give me more time to investigate the problem. may i made mistake to reporting this, because when i comment import device info i did not get error, also react-native-netinfo got update 17 hours ago, and may there are some conflict, i dont change any thing and i just init new project and get packages and copy my source(it works in old versions) but suddenly get this error, lets check more to find my exact problem. i will come back to comment here soon.

thanks

**Comment by mikehardy** [comment]
Okay - thanks for checking in - fingers crossed I didn't release something with a problem but if I did, and we find it, I'll get 1.6.1 out immediately...good luck isolating the issue

**Comment by mohsenomidi** [comment]
Dear Mike, 

I find something related to device-info package & Maps (react-native-maps), my they uses different versions of google-play-services or something related to gradle settings 
 
https://github.com/react-native-community/react-native-maps/issues/1300
https://github.com/react-native-community/react-native-maps/issues/1576
https://github.com/react-native-community/react-native-maps/issues/1005


I setup new windows and start clean installation for NPM, React Native CLI & etc.. 
after fresh installation for everything,I init new react native app and after this i just install both react-native-device-info and react-native-maps and import them to the blank project; in this system everything goes fine without error.

but i have the error on other windows system. this error just start from yesterday on that system and i cant find any thing about it, I decided to uninstall everything on my old laptop and reinstall them may this fix my issue. (maybe gradle cache or something like this) 

but for fresh installation everything was okay. 

thanks for your support, i close this issue :)

**Comment by mikehardy** [comment]
Glad you are on a path to working, it seems that for react-native we all still need something like this in our package.json scripts section:

```
    "deep-clean": "npm run clean && (watchman watch-del-all || echo 'watchman is not present on linux') && rm -rf $TMPDIR/react-* && npm cache verify && npm install && rm -rf $TMPDIR/haste-map-metro-* && npx react-native start -- --reset-cache",
    "clean": "\\rm -fr ./node_modules && \\rm -fr dist/* && \\rm -fr ios/build ios/Pods ios/KScoreApp.xcarchive && \\rm -fr android/build android/app/build android/app/src/main/assets/index.android.bundle",

```
