### ISSUE TITLE
Tablet not recongnized

### ISSUE THREAD

**Issue by AnkitPat** [react-native-community/react-native-device-info#653]
Samsung Tab 4
## Current behavior
Its not recognized as a tablet by function isTablet(). Any help.
## Expected behavior
Should be treated as tablet.

**Comment by mikehardy** [comment]
The code used to decide if it is a tablet or not is here:

https://github.com/react-native-community/react-native-device-info/blob/master/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L139

It is based on measurements. You'll need to figure out - based on the code - what measurements your device is returning for the various "is it a tablet" tests, then provide those here, and maybe we can make some adjustments, or maybe we learn the heuristic is incorrect somehow...

**Comment by mouselangelo** [comment]
@AnkitPat Could you please verify if this issue still persists in [v2.3.0](https://github.com/react-native-community/react-native-device-info/releases/tag/v2.3.0)?
