### ISSUE TITLE
Cannot disable unnecessary features

### ISSUE THREAD

**Issue by dhcmega** [react-native-community/react-native-device-info#655]
Hi
Apple is telling me that I need descriptions for:
NSCalendarsUsageDescription
NSBluetoothPeripheralUsageDescription 
NSAppleMusicUsageDescription
NSMotionUsageDescription
NSSpeechRecognitionUsageDescription 

I don't need them and I don't want to come up with a fake excuse on why my app is requesting them.
How can I disable/remove those? I cannot find how to do it.
Thanks!

**Comment by mikehardy** [comment]
Indeed - this causes a problem for react-native-permissions as well, and if I understand correctly Apple will start denying apps that have unused permissions even if they have supplied the codes. There is no way to disable this right now except a fork and commenting out the code.

I believe this will be showstopper soon though - and we are about to do a breaking change but have not started it yet - tagging this for that v2 effort so we can maybe apply the same strategy as react-native-permissions by having sub-modules

**Comment by mikehardy** [comment]
https://github.com/yonahforst/react-native-permissions/tree/2.0.0

**Comment by mikehardy** [comment]
Investigating this, I don't see us using any of these APIs. I don't believe you need to specify those because of this module. If I am wrong please re-open
