### ISSUE TITLE
 @react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null. To fix this issue try these steps:

### ISSUE THREAD

**Issue by tanaymathur001** [react-native-community/react-native-device-info#657]
Not able to retrieve Device Info 
// "react-native-device-info": "^1.6.1",

import DeviceInfo from 'react-native-device-info';

export default class SignUp extends Component {

  constructor(props) {
    super(props);
    this.state = {
      email   : '',
      fullName: '',
      password: '',
      mobileNo: '',
      deviceId: '',
    }
  }

  async componentWillMount(){
    try{
      var id = DeviceInfo.getUniqueID();
      this.setState({ deviceId: id, });
    }
  catch(e){
    console.log('Trouble getting device info ', e);
  }
  }

**Comment by mikehardy** [comment]
If DeviceInfo is null you have not installed correctly. Usually a link failure. Follow the suggested steps, or even better clone this repo so you have access to the example project and follow it's readme

**Comment by Kikketer** [comment]
Using the pod installation throws this same error.  My pod file:
```
project './myproject.xcodeproj'
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'myproject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # https://gist.github.com/brentvatne/b0ea11a36dc423e441b7d36e36eb5a26
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'CxxBridge',
      'DevSupport',
      'RCTText',
      'RCTNetwork',
      'RCTWebSocket',
      'RCTAnimation',
      'RCTImage',
    ]

    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # pod fail:
  # https://github.com/luggit/react-native-config/issues/340
  # pod 'react-native-config', :path => '../node_modules/react-native-config'

  # pod fail:
  # https://github.com/react-native-community/react-native-device-info/issues/657
  # pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

end

```

**Comment by mikehardy** [comment]
Hi there! Sorry, but do not comment on closed issues. There is a template for new issues that asks for exact versions and steps to reproduce. That information is very important for troubleshooting.

As a guess, try to pod install after after you link if you are using pods, but I really can't say without details.
