### ISSUE TITLE
Device Check API (iOS 11+)

### ISSUE THREAD

**Issue by DISKONEKTeD** [react-native-community/react-native-device-info#658]
## Description

Would love to see Device Check API implemented at some point:

https://developer.apple.com/documentation/devicecheck

## Use Case

It uniquely identifies a user, maintaining privacy. This would then be great for preventing a user from doing an action more than once within the app's context or for user administration etc

**Comment by mikehardy** [comment]
Interesting. Pull requests welcome. React-native is an Objective-C environment in general and this module specifically, but for inspiration here is a Swift implementation https://github.com/dayitv89/DCDeviceCheck

Here is more information and another implementation but also Swift https://www.marinosoftware.com/insights/how-to-prevent-fraud-without-compromising-user-privacy-devicecheck-on-ios-11

**Comment by johnhiggs** [comment]
This is my global mock how i get around issues I had with the react-native-device-info library

jest.mock('react-native-device-info', () => {
    return {
        getModel: jest.fn(),
        getReadableVersion: jest.fn(),
        getSystemVersion: jest.fn(),
        getUniqueID: jest.fn(),
        getVersion: jest.fn()
    };
});

**Comment by mikehardy** [comment]
@johnhiggs I think that is covered pretty well in the readme https://github.com/react-native-community/react-native-device-info/blob/master/README.md#troubleshooting but if you can think of improvement, PRs are welcome
