### ISSUE TITLE
react-native run-android return build faild

### ISSUE THREAD

**Issue by sootood** [react-native-community/react-native-device-info#667]
i try to use this library but get this error when isearched  the url it returns 404 error
what can i do?

>What went wrong:
Could not resolve all files for configuration ':react-native-device-info:debugCompileClasspath'. Could not find support-media-compat.jar (com.android.support:support-media-compat:28.0.0).
  Searched in the following locations:
      https://dl.google.com/dl/android/maven2/com/android/support/support-media-compat/28.0.0/support-media-compat-28.0.0.jar

## information
RN version: 0.59.8
platform: android
device_info version: 2.0.0

**Comment by mikehardy** [comment]
1 - is to always try the example app, if it works, it is proof your project has linked or otherwise integrated it incorrectly
2 - my guess (assuming 1 above shows it works) is that you have incorrect gradle dependency versions. Your ext { } block in the top-level gradle should look similar to the examples

**Comment by HadisSharif** [comment]
> 1 - is to always try the example app, if it works, it is proof your project has linked or otherwise integrated it incorrectly
> 2 - my guess (assuming 1 above shows it works) is that you have incorrect gradle dependency versions. Your ext { } block in the top-level gradle should look similar to the examples

The gradle dependencies are the same but I still can not run my project. How can I fix it?

**Comment by mikehardy** [comment]
You may have some other dependency causing problems. The Play Services breaking change is massive and disrupting many people

here is how to find the dependency causing you trouble, then hopefully they will respect a version in android/build.gradle ext{} block https://github.com/react-native-community/react-native-device-info/pull/693#issuecomment-503142535
