### ISSUE TITLE
Can't make this library work in ExpoKit project, IOS

### ISSUE THREAD

**Issue by Luckygirlllll** [react-native-community/react-native-device-info#668]
## Summary

|             |     |
| ----------- | --- |
| Version     | 2.0.0  |
| Affected OS | IOS   |
| OS Version  | 12.2   |

## Current behavior

I added library, after that I did linking, I also tried to add library using cocoa pods, however, I'm still getting an error: 

Module 'react-native-device-info' does not exist in the Hastle module map  

## Expected behavior

I can run the library

**Comment by mikehardy** [comment]
Using native modules with Expo projects (even ejected ones) has been problematic from what I've seen with regard to issue traffic in other repos, but as long as you have ejected, it really should work.

I would first confirm that the example in this repo works for you locally, to make sure everything else is fine

If that still didn't work, that specific error smells like some sort of corrupt local state, and this happens often enough I just tried to implement the necessary "delete all state and start fresh" commands as a plugin over here: https://github.com/pmadruga/react-native-clean-project / https://github.com/pmadruga/react-native-clean-project/pull/12

If you install the master version of that repo (until the PR is released) like so `npm install github:pmadruga/react-native-clean-project` you should be able to run `react-native clean-project-auto` and then attempt to install packages, pod update etc with a fresh start

If that still does it, I'm lost for the moment

**Comment by Luckygirlllll** [comment]
I unlinked and uninstalled library and installed, linked, did pod install, cleaned and rebuild the project  and everything started to work this time. Probably was some cache issue.

**Comment by mikehardy** [comment]
I hate those problems! That's what motivated me to do the clean-project PR above, to at least make it simple to try to fix them, but I wish they didn't happen.

Very glad to hear you got it working though, thanks for reporting back

**Comment by Luckygirlllll** [comment]
@mikehardy thanks  for help! :)
