### ISSUE TITLE
Add AndroidX Support

### ISSUE THREAD

**Issue by bondparkerbond** [react-native-community/react-native-device-info#674]
# Feature Request

Android Q(currently in Beta) will only support [AndroidX](https://android-developers.googleblog.com/2018/05/hello-world-androidx.html) support libraries. Additionally React Native 0.60 will include default AndroidX support. As such, it would be helpful to have a new version with AndroidX support soon after RN 60 is released. We may want to do this as a major version bump in case we want to keep supporting the current version with minor fixes.

Edit: Google Play Services latest version uses AndroidX as well

## Why it is needed

Once AndroidX support lands in RN 60, there will be a need for all RN packages to add AndroidX support as you can only have one or the other and Jetifier doesn't work with 3rd party dependencies.

## Possible implementation

Use [Jetifier](https://developer.android.com/studio/command-line/jetifier#custom_config_file) to migrate support lib to androidx if we're already on support lib version 28.0.0

### Code sample

[Migration Guide](https://developer.android.com/jetpack/androidx/migrate#migrate)

**Comment by mikehardy** [comment]
Haha @bondparkerbond Bond, Parker Bond - we meet again!

I want to brainstorm with the react-native-community on how to do this best, in a way that supports end users that have very reasonable reasons why they are slow (or cannot) upgrade, while hopefully still delivering features and fixes to them. I have engaged the community on Discord to that end

At the same time, there will be some easy-to-use mechanism for RN0.60, definitely. Even if it's a `@next` tag or something on npmjs

We can use this issue to track progress and communicate with library consumers, I will post proposals / tentative plans here as they form

**Comment by bondparkerbond** [comment]
Haha. [This blog post](https://ncorti.com/blog/jetifier-reverse) lists some options for AndroidX adoption, and it seems the one that would be best for the community would be to maintain two variants of the library(one with and one without AndroidX). Please let me know how I can help with this process.

**Comment by mikehardy** [comment]
That's a great explanation of de-jetification. I'm actually hoping that something like the 'bob' package along with de-jetifier can auto-generate AARs and CLI can add support to link the correct one.

I have a feeling the AndroidX schism will last for a very long time and I do not want to support two code line.s

**Comment by mikehardy** [comment]
We have some successful AndroidX reverse-dejetifier test results. We're getting close to resolution - https://github.com/react-native-community/discussions-and-proposals/issues/129#issuecomment-498776701

I will likely do a test AndroidX conversion here soon. It will be a breaking change and I'll probably do a beta first tagged as next on npm, @bondparkerbond would you be willing to help test it prior to general release? I'll guinnea pig first on the example of course, but always better to have more eyes.

**Comment by benoitdion** [comment]
heads up that the latest gms librairies are now out (https://developers.google.com/android/guides/releases) so the `+` in https://github.com/react-native-community/react-native-device-info/blob/master/android/build.gradle#L44 will likely start breaking some builds.

**Comment by mikehardy** [comment]
If you must use AndroidX then you can try https://github.com/mikehardy/jetifier

It works on linux and macOS at least, but should be compatible with GNU sed or BSD sed so I would assume it works on windows with proper tooling as well?

**Comment by mikehardy** [comment]
The last thing required here is to integrate bob+jetifier and generate a reverse-jetified AAR during the build process along with the necessary instructions for non-AndroidX users to use it as a dependency. Then we can move forward

**Comment by KingAmo** [comment]
this lib's `build.gradle `contain :
```implementation "com.google.android.gms:play-services-gcm:${safeExtGet('googlePlayServicesVersion', '+')}"```

however, the latest version of `play-services-gcm` (17.0.0) uses AndroidX，which lead my project a error
```
Manifest merger failed : Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core: core:1.0.0-beta01] AndroidManifest.xml:22:18-86
is also present at [com.android.support:support-compat:28.0.0-alpha3] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:11:5-49:19 to override.
```

i think this lib should use a specific version of `play-services-gcm` that before `17.0.0`

**Comment by mikehardy** [comment]
@KingAmo resolved yesterday in 2.1.2 please update, also, pin your dependency in ext{}

**Comment by ShaoGongBra** [comment]
请问是在哪个版本加入了android支持的？

**Comment by mikehardy** [comment]
I'm sorry @ShaoGongBra I only speak English, and Spanish badly :-), and github does not have any built-in translators. Can you paste in a google translate version here for communication?

**Comment by ShaoGongBra** [comment]
Which version is added to the support of AndroidX? @mikehardy

**Comment by mikehardy** [comment]
@ShaoGongBra it is your choice - in android/build.gradle you put the version you want in your ext {} block - similar to the example, but with the play services version and support version you want: https://github.com/react-native-community/react-native-device-info/blob/master/example/android/build.gradle#L4

**Comment by ShaoGongBra** [comment]
Hello, excuse me, I used squareup before, but this component uses androidx, how do I make this component use squareup?
```
+--- project :react-native-image-crop-picker
|    +--- com.facebook.react:react-native:+ -> 0.58.4 (*)
|    \--- com.github.yalantis:ucrop:2.2.2-native
|         +--- com.android.support:appcompat-v7:27.1.0 -> 28.0.0 (*)
|         \--- com.squareup.okhttp3:okhttp:3.8.1 -> 3.12.1 (*)
+--- project :react-native-image-picker
|    \--- com.facebook.react:react-native:+ -> 0.58.4 (*)
+--- project :react-native-device-info
|    +--- com.facebook.react:react-native:+ -> 0.58.4 (*)
|    +--- com.google.android.gms:play-services-gcm:+ -> 17.0.0
|    |    +--- androidx.collection:collection:1.0.0
|    |    |    \--- androidx.annotation:annotation:1.0.0
|    |    +--- androidx.core:core:1.0.0
|    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    +--- androidx.collection:collection:1.0.0 (*)
|    |    |    +--- androidx.lifecycle:lifecycle-runtime:2.0.0
|    |    |    |    +--- androidx.lifecycle:lifecycle-common:2.0.0
```

**Comment by ShaoGongBra** [comment]
@mikehardy 
Hello, excuse me, I used squareup before, but this component uses androidx, how do I make this component use squareup?

```
+--- project :react-native-image-crop-picker
|    +--- com.facebook.react:react-native:+ -> 0.58.4 (*)
|    \--- com.github.yalantis:ucrop:2.2.2-native
|         +--- com.android.support:appcompat-v7:27.1.0 -> 28.0.0 (*)
|         \--- com.squareup.okhttp3:okhttp:3.8.1 -> 3.12.1 (*)
+--- project :react-native-image-picker
|    \--- com.facebook.react:react-native:+ -> 0.58.4 (*)
+--- project :react-native-device-info
|    +--- com.facebook.react:react-native:+ -> 0.58.4 (*)
|    +--- com.google.android.gms:play-services-gcm:+ -> 17.0.0
|    |    +--- androidx.collection:collection:1.0.0
|    |    |    \--- androidx.annotation:annotation:1.0.0
|    |    +--- androidx.core:core:1.0.0
|    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    +--- androidx.collection:collection:1.0.0 (*)
|    |    |    +--- androidx.lifecycle:lifecycle-runtime:2.0.0
|    |    |    |    +--- androidx.lifecycle:lifecycle-common:2.0.0
```

**Comment by mikehardy** [comment]
I'm sorry @ShaoGongBra but this is not related to react-native-device-info. react-native-device-info does not use androidx unless you are on a version older than 2.1.2  and you fail to specify a specific play services version. You will have to fix your project to get the versions you want

**Comment by ShaoGongBra** [comment]
@mikehardy Sorry, I didn't look carefully. I understand the meaning of googlePlayServicesVersion. Please ask me if I want to go to the above place to find this version.

**Comment by thecodecafe** [comment]
Just to add to @mikehardy 's solution about using jetifier, remember to update react-native device info to 2.1.2 or higher and then add the following to `android/build.gradle`
```
allprojects {
    ...
    configurations.all {
        resolutionStrategy {
            ...
            force "com.android.support:support-v4:26.1.0"
            force "com.android.support:support-media-compat:26.1.0"
        }
    }
}
```
The ellipsis there are for brevity in the code you probably have some more forced dependencies there. this is because some other library is using other versions of support-v4 and support-media-compat.

Now clean and run `react-native run-android` and hopefully you're good to go.

**Comment by gh7800** [comment]
project/build.gradle    
...... 
ext {
        googlePlayServicesVersion = "16.0.0"
        firebaseVersion = "17.0.0"
    }

**Comment by Marcello168** [comment]
> googlePlayServicesVersion = "16.0.0"
> firebaseVersion = "17.0.0"
it`s works good

**Comment by se-bastiaan** [comment]
Could someone enlighten me with the need for this package to depend upon the support library and AndroidX in the future? I'm unable to find any `android.support.*` imports.

**Comment by jameslporter** [comment]
I'm using jetify and my app builds but fails at runtime, stacktrace in the console seems to blame rn-device-info.

https://gist.github.com/jameslporter/54f711ccfada44c559764f43a4976065

**Comment by mikehardy** [comment]
It does look that way. `cd android && ./gradlew :app:dependencies` might show why it was still linking against the support libraries. My guess is the library name or version or similar? 

In fact I think these library names: https://github.com/react-native-community/react-native-device-info/blob/master/android/build.gradle#L44  may need the treatment of replacing the entire library name as I mentioned myself in the jetifier docs.

If someone is willing to try a patch to the build.gradle here that implements that, it would likely fix it and be useful for others as a PR and/or as a patch to use via patch-package until we can do a release
