### ISSUE TITLE
crashed in ios 8.0 simulator

### ISSUE THREAD

**Issue by BestKai** [react-native-community/react-native-device-info#679]
# Bug
 
Crashed in ios 8.0 simulator

## Environment info

xcode:12.2.1
ios simulator:8.0

dyld: Symbol not found: ___NSArray0__
  Referenced from: /Library/Developer/CoreSimulator/Devices/694952E0-C8AF-44A1-9291-004253850B81/data/Containers/Bundle/Application/9F28D544-F918-4B34-91E7-BA861B48B725/example.app/example
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 8.1.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 in /Library/Developer/CoreSimulator/Devices/694952E0-C8AF-44A1-9291-004253850B81/data/Containers/Bundle/Application/9F28D544-F918-4B34-91E7-BA861B48B725/example.app/example

**Comment by mikehardy** [comment]
didn't follow the template, I have no idea what versions of react-native-device-info etc you are using

Maybe paste in a `react-native -v` but first, run the example app from a clone of this repo. It works (or should work), so this is a project problem I think

**Comment by mikehardy** [comment]
Oh, and iOS 8 is **not** supported by react-native. 9+
