### ISSUE TITLE
Xiaomi Redmi Note 7 has notch

### ISSUE THREAD

**Issue by Gguigre** [react-native-community/react-native-device-info#681]
# Bug

[Redmi Note 7](https://www.mi.com/fr/redmi-note-7/) should be in the list of devices with notch

brand : xiaomi
model : Redmi Note 7

**Comment by mikehardy** [comment]
Done!

https://github.com/react-native-community/react-native-device-info/releases/tag/v2.0.4

Thanks for your contribution
