### ISSUE TITLE
Unable to compile on Android. Giving "error: cannot find symbol"

### ISSUE THREAD

**Issue by hdrabs** [react-native-community/react-native-device-info#687]
# Bug

## Unable to successfully Compile the code on Android when run `react-native run-android`

ERROR LINE (in terminal):

```
/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceMo
dule.java:394: error: cannot find symbol
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                                                      ^
  symbol:   variable P
  location: class VERSION_CODES
```
```
/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceMo
dule.java:396: error: cannot find symbol
        locationEnabled = mLocationManager.isLocationEnabled();
                                          ^
  symbol:   method isLocationEnabled()
  location: variable mLocationManager of type LocationManager
```

## Environment info

```
React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
      Memory: 87.72 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.4.0 - ~/.nvm/versions/node/v8.4.0/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 5.3.0 - ~/.nvm/versions/node/v8.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.1 => 0.57.1

Library Version using:
    "react-native-device-info": "^2.1.1",
```

## Steps To Reproduce

1. Install the Library using `yarn add react-native-device-info`
2. Run: `react-native link react-native-device-info`
3. Run `react-native run-android`

## What I have tried

1. I have tried to comment the aforementioned lines from the code. Complies successfully but app crashes on launch.
2. I have returned `true` for `locationEnabled` from the code. Same result.
3. Deleted the entire function, as I was unable to find it anywhere in the code. Same result.

### Describe what you expected to happen:

Expected to build the debug release to run on the device or emulator installed using Android Studio on Mac OSX, like it is building and working on iOS (Working Perfectly for iOS on the same project)

**Comment by hdrabs** [comment]
@mikehardy any suggestions? I have tried a couple of more things.

1. Updated build version to 29.0.0, sdkVersion to 29 as well, but nothing.
2. I am downgrading library version and getting the error for NativeModules.

Any suggestions? Sorry but time is clutch for me right now.

**Comment by mikehardy** [comment]
Do exactly as the example does, it works. That includes android versions (compile sdk especially, that fixes your unknown symbol)

The other errors are unrelated to our library. Looks like a multidex problems or something, or maybe you don't have an ext { } block in your android/build.gradle with versions pinned

For all of these things, I recommend you look at the example, and run it locally, then do what it does

**Comment by ManigandanRaamanathan** [comment]
@hdrabs  How did you fix this error? I'm facing the same issue.

**Comment by ManigandanRaamanathan** [comment]
@mikehardy @hdrabs  
![image](https://user-images.githubusercontent.com/22089729/59330029-e90f2880-8d22-11e9-8d83-b0e5d8ca9e3e.png)

**Comment by mikehardy** [comment]
You are for some reason compiling against and android sdk that is less than 29. You must compile against android sdk 29 from react-native-device-info 2.0.0 and higher

Every project is different so I don't know why that's happening for you, but as mentioned above, look at the example here and do what it does.

**Comment by jsmile1994** [comment]
Anyone can fix this issue?
I do all these above steps, but still fail to build.
Currently, I'm using:
react-native: 0.57.8
And this is my build.gradle:
ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"

        googlePlayServicesVersion = "17.0.0" // default: "16.1.0" - pre-AndroidX, override for AndroidX
        mediaCompatVersion = '1.0.1' // Do not specify if using old libraries, specify '1.0.1' or similar for androidx.media:media dependency
        supportV4LibVersion = '1.0.0' // Do not specify if using old libraries, specify '1.0.0' or similar for androidx.legacy:legacy-support-v4 dependency
    }
Thank you!

**Comment by mikehardy** [comment]
Please open a new issue if still having problems. This original issue would be solved if you're targetSdkVersion = 28 was working correctly so maybe you need to do something like `npm i react-native-clean-project && react-native clean-project-auto` then try again, but you should post a new issue with full template information and full error message

**Comment by jgtoriginal** [comment]
I'm sorry @mikehardy but this just doesn't work by following the example.

I'm pretty sure there's something else missing, cause adding this to it's corresponding file doesn't make those symbols available.

```
ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
```

When posting braking changes, many packages maintainers publish also a step-by-step guide on how to upgrade. If you provide enough details to overcome this issue I'm happy to help you write a guide. I just don't want to migrate library just because of a silly error.

**Comment by mikehardy** [comment]
No upgrade guide is needed, the reference in the changelog should be sufficient, it's just that change https://github.com/react-native-community/react-native-device-info/releases/tag/v2.0.0

It looks like I may have had think-o there though, it says (or said, I will edit)
'breaking: note that isLocationEnabled requires minCompileSdk 28'

It should say
'breaking: note that isLocationEnabled requires compileSdkVersion 28'

That said, looks like your ext block is correct

There will be [one instance of compileSdkVersion in your project](https://github.com/react-native-community/react-native-device-info/blob/master/example/android/build.gradle#L7) (or there should be)

And it will be [referenced in your android/app/build.gradle](https://github.com/react-native-community/react-native-device-info/blob/master/example/android/app/build.gradle#L123) (or it should be)

Check out this repository from github
Run the example
It works
?

Perhaps you are not referencing the variable and it is hard coded in android/app/build.gradle

One thing to note. starting Aug 1st,  [you can't even publish a new APK on Play Store without targetSdkVersion of 28 anymore](https://support.google.com/googleplay/android-developer/answer/113469#targetsdk), and you can't target that without compiling against that, so I have no idea how you will be able to publish? I guess if it's just an update you have a couple more months, but you need to move to 28. And this will work

**Comment by jgtoriginal** [comment]
cool @mikehardy will check and keep you posted at some point today.
Cheers!

**Comment by singhaishwarya** [comment]
Try using /react-native-device-info@1.7.0 as it works for buildToolsVersion<=28
for higher versions of react-native-device-info(>1.7.0)  one needs to have buildToolsVersion>=29

**Comment by mikehardy** [comment]
That is not good advice and also seems to have imprecise versioning.

Use most current build tools.
Use at least target SDK 28
