### ISSUE TITLE
'React/RCTUtils.h' file not found

### ISSUE THREAD

**Issue by VitorBrangioni** [react-native-community/react-native-device-info#688]
I changed xcode 10 to 9, now i have this issue. Do you know any solution?

"react": "16.8.3",
"react-native": "^0.59.5",
"react-native-device-info": "^1.5.1"

**Comment by mikehardy** [comment]
No, sorry, using old Xcode version isn't something I can check since staying up to date is the general recommendation in the iOS ecosystem. The example compiles no problem with Xcode 10.2

**Comment by JulioOrellana** [comment]
I am using xCode 10.2 and this is failing

**Comment by mikehardy** [comment]
I am using XCode 10.2 on the example app and it is working via the documentation in this repo, if you can reproduce this by cloning our repo, and having a build failure on the example app, we have a problem. Otherwise I can't reproduce

**Comment by brkrtp** [comment]
+1 ı have same problem

**Comment by mikehardy** [comment]
Hi there @brkrtp 

+1s in open source are spam, please provide a repro or on a closed issue, open a new issue with full details. We have an example that works fine so this is a project issue most likely

**Comment by alexstoyanov** [comment]
Anyone found a solution on this? Having the exact same issue. The library worked for me until now. I added a new pod library and device info stopped working giving me 'React/RCTUtils.h' file not found.

**Comment by midnightcodr** [comment]
On xcode 11.3 having the same issue.
