### ISSUE TITLE
getMacAddress

### ISSUE THREAD

**Issue by Tiger-man** [react-native-community/react-native-device-info#689]
getMacAddress方法中少请求了一个权限android.permission.ACCESS_WIFI_STATE
android小米中会报错
WifiService: Neither user 10690 nor current process has android.permission.ACCESS_WIFI_STATE

**Comment by mikehardy** [comment]
we have an issue template, and it was not followed https://github.com/react-native-community/react-native-device-info/blob/master/.github/issue_template.md

Also, you should check permissions for the app in use, to make sure it actually has the permissions

You can try the example app in this repo
