### ISSUE TITLE
@react-native-community/react-native-device-info:NativeModule.RNDeviceinfo is null. To fix this issue try these steps

### ISSUE THREAD

**Issue by nikhil-tayal** [react-native-community/react-native-device-info#690]
I have tried everything available on the Net. Link all the libraries including ( react-native-device-info) but it is throwing the same error. Even I uninstalled the app but unable to resolve the issue

android version : 9
react-native : 0.59.9
react-native-device-info : 2.1.1

Also tried on the simulator with android 9 and Android API 29

**Comment by mikehardy** [comment]
But, the example works perfectly? Show me a reproduction in a clean repo and I will believe it, in the meantime the example included in this repo works every time?

You might try react-native-clean-project and run `npx react-native clean-project-auto` in your app to clean *everything* then retry what you're doing

**Comment by apptopdev** [comment]
nikhil-tayal, hi, I try to fix this problem very long time, but I understand that this package (react-native-device-info) justi DON'T work with expo, I don't know whym but it's really true. My advice to you: you can just to use expo for getting information about your device, for this you should (import * as Expo from 'expo' ) after use this ( Expo.Constants.deviceName ).
It's should solved your problem, please try this it's work 100% !
Good luck 👍

**Comment by mikehardy** [comment]
It doesn't work with expo because expo is all about *not* using new native modules. This is a native module. It's a fundamental expo fact and will affect your react-native work with lots and lots of modules. Documented on expo site

**Comment by apptopdev** [comment]
Yes, it's absolutely right, but I want to say that he can user Expo functions for getting information about user device

**Comment by nikhil-tayal** [comment]
@apptopdev Actually I was taking build on the local device , not on expo. Should I still  import the Expo function?

**Comment by miracledan** [comment]
For Android:
You should add some code.
```
in MainApplication.java:
+ import com.learnium.RNDeviceInfo.RNDeviceInfo;

  public class MainApplication extends Application implements ReactApplication {
    //......

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
+         new RNDeviceInfo(),
          new MainReactPackage()
      );
    }

    ......
  }
```

**Comment by unilogica** [comment]
> For Android:
> You should add some code.
> 
> ```
> in MainApplication.java:
> + import com.learnium.RNDeviceInfo.RNDeviceInfo;
> 
>   public class MainApplication extends Application implements ReactApplication {
>     //......
> 
>     @Override
>     protected List<ReactPackage> getPackages() {
>       return Arrays.<ReactPackage>asList(
> +         new RNDeviceInfo(),
>           new MainReactPackage()
>       );
>     }
> 
>     ......
>   }
> ```

After 4 days I found your solution and solved my problem. Thanks

**Comment by mikehardy** [comment]
@unilogica for react-native projects greater than version 0.60+ this is not a great solution, this indicates you have a problem with auto-linking in your project and it bears examination. This package should auto-link successfully in all cases for RN 0.60+

**Comment by mxt305** [comment]
Thank for the answer from @apptopdev 
If you use expo.
You can also use [expo-device](https://docs.expo.io/versions/latest/sdk/device/).
