### ISSUE TITLE
play-services-gcm latestVersion7.0.0 use androidx 

### ISSUE THREAD

**Issue by zhangyugehu** [react-native-community/react-native-device-info#696]
# Bug

when run: gradlew assembleXXX get error:
Manifest merger failed : Attribute application@appComponentFactory XXX
...

because of the  play-services-gcm get v7.0.0，case support.v4 with androidx error

## Environment info
"react": "16.8.3",
"react-native": "0.59.4",
"react-native-device-info": "^1.5.0"

suggestion:
put googlePlayServicesVersion = "16.1.0" into [androidRoot]/build.gradle like:
````
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "16.1.0"
    }
}
````

**Comment by shopshow** [comment]
same issue +1

**Comment by mikehardy** [comment]
Play services releasing a breaking change as they converted to AndroidX, #696 which we don't support #693 but will support in the future #674 - so you should upgrade to react-native-device-info 2.1.2 and try again.

If you must use AndroidX then you can try https://github.com/mikehardy/jetifier
