### ISSUE TITLE
main.jsbundle:1:933', reason: 'Unhandled JS Exception: undefined is not an object (evaluating 'n.model.toLowerCase')

### ISSUE THREAD

**Issue by TylerPin** [react-native-community/react-native-device-info#698]
# Bug
-main.jsbundle:1:933', reason: 'Unhandled JS Exception: undefined is not an object (evaluating 'n.model.toLowerCase')

## Environment info
-Release

Library version: 2.1.2

## Steps To Reproduce
-Run React Native in release mode will hit this error in iOS

Error log from main.jsbundle:
hasNotch:function(){return-1!==r.findIndex(function(e){return e.brand.toLowerCase()===n.brand.toLowerCase()&&e.model.toLowerCase()===n.model.toLowerCase()})},

**Comment by mikehardy** [comment]
Hi there! Sorry you've run into trouble

This doesn't happen in the example (or in my app), so something is wrong with your module linkage in your ios release profile somehow? This is going to be a project specific error. 

Please try the example in release mode and it should work fine. Note the example is built programmatically so you can follow the example and it should work? https://github.com/react-native-community/react-native-device-info/blob/master/refresh-example.sh

If you can reproduce this with a change to the example somehow I can reopen

**Comment by pavermakov** [comment]
This happened to me as well. I ran into an issue with new androidx support. I have unlinked this package, reinstalled it and then linked again. Android works fine, but ios build fails.

**Comment by mikehardy** [comment]
I would revert from source control to before you unlinked it, and just upgrade the version to 2.1.2, but really for android  you should have the play services version specified in android/build.gradle ext{} block the way the example does

**Comment by pavermakov** [comment]
I have managed to resolve the issue. I opened deviceinfo.js from node_modules/react-native-device-info folder. Then, I looked for `hasNotch()` method. Inside, i commented out `&& item.model.toLowerCase() === this.getModel().toLowerCase()`, ran the app, and it worked. Then I undone all my changes and it still worked. Not sure if old files were cached or something.

**Comment by mikehardy** [comment]
in the future you might try `npm i react-native-clean-project && react-native clean-project-auto` to clear out all state. It will force a network download of packages and pods, but it clears out all state

Glad you got things working!

**Comment by bliang** [comment]
You basically just need to recompile your project (after linking < RN 60, autolinks after compile >= RN 60).
