### ISSUE TITLE
react-native link override the exclude group.

### ISSUE THREAD

**Issue by RajeshKumDev** [react-native-community/react-native-device-info#699]
# Bug
Android recently updated "`com.google.android.gms:play-services-gcm`" library to latest version: **17.0.0**.

And this NPM package uses the latest version of google library, as:
`implementation "com.google.android.gms:play-services-gcm:+"`

So when we run the app or creates builds, then we got this error:
**Android dependency 'com.google.android.gms:play-services-base' has different version for the compile (16.0.1) and runtime (17.0.0) classpath. You should manually set the same version via DependencyResolution**

similar issue also mentioned here:
https://stackoverflow.com/questions/56648263/android-dependency-com-google-android-gmsplay-services-stats-has-different-ve

And what workaround mentioned in this link is working fine.

The only issue is, If I run:
```
npm install
react-native link
```
then this code:
```
compile (project(':react-native-device-info'),  {
      exclude group: "com.google.android.gms"
    })
```
automatically turns to:
`compile project(':react-native-device-info')`

And we are staring getting same error.

## Environment info

  React Native Environment Info:
    System:
      OS: Linux 4.4 Ubuntu 16.04.1 LTS (Xenial Xerus)
      CPU: x64 Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz
      Memory: 985.60 MB / 7.62 GB
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 10.8.0 - /usr/bin/node
      npm: 6.2.0 - /usr/bin/npm
    IDEs:
      Android Studio: 3.1 AI-173.4670197
    npmPackages:
      react: ^16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: ^0.57.4 => 0.57.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1

Library version: Current version: **0.24.3** Also tried latest version 2.1.2

## Steps To Reproduce

```
npm install
react-native link
```
Describe what you expected to happen:

1. We are expecting, after above two commands, `exclude group` line should remains in code.

**Comment by mikehardy** [comment]
You are a day late :-), this explosion happened yesterday  #674 

#694  #695  #696 

We released 2.1.2 that fixes it

**Comment by HighSoftWare96** [comment]
@mikehardy  I've installed the 2.1.2 but I have already the 
`com.google.android.gms:play-services-stats' has different version for the compile (16.0.1) and runtime (17.0.0) classpath.` problem... In the app/build.gradle have I to set something different than
`implementation project(':react-native-device-info')` ??

**Comment by mikehardy** [comment]
You can find where the other version is coming in by doing `cd android && ./gradlew :app:dependencies` and searching. It is no longer this library if you have specified the version or you are using 2.1.2
