### ISSUE TITLE
hasNotch() return false on Pixel 3 XL emulator

### ISSUE THREAD

**Issue by nicolashemonic** [react-native-community/react-native-device-info#700]
# Bug

hasNotch() return false on Pixel 3 XL emulator.

## Environment info

Run on Mac OS.
React Native 0.59.8 and RN Device Info 2.1.2.

## Expected

hasNotch() should return true on Pixel 3 XL emulator.

**Comment by mikehardy** [comment]
Probably just missing that model - feel free to propose a PR https://github.com/react-native-community/react-native-device-info/blob/master/deviceinfo.js#L29

**Comment by nicolashemonic** [comment]
This model exist in devicesWithNotch list.
hasNotch should work on emulator too right ?

**Comment by mikehardy** [comment]
:thinking: I don't know - I think so? I suppose it depends on how the emulator reports itself. If you use the example app I believe the App.js in there just dumps *everything* to the screen, so you can see what the emulator is reporting. If it's not working right still, then certainly - that's a bug, but also hopefully easy to fix with a PR

**Comment by nicolashemonic** [comment]
The model returned by RN Device Info exemple is "Android SDK built for x86" so it's normal that hasNotch return false.

I think Android emulator are just a set of technical specs and the skin of the emulator the only thing of Pixel 3 XL.

I'm curious how to test my app with a notch 😅

**Comment by mikehardy** [comment]
You could use jest to mock the results of that function so it returns what you need? Or maybe have a dev switch somewhere where you can toggle the modes? This is an interesting problem. I'm going to close this issue, but if you have good ideas about it, you could propose a PR to the readme for this method call that mention the emulator return value doesn't work like you expect on emulators and for testing you might try ...
