### ISSUE TITLE
getUniqueID() documentation seems incorrect

### ISSUE THREAD

**Issue by dmytro-dish** [react-native-community/react-native-device-info#706]
There is a note in [getUniqueID() docs](https://github.com/react-native-community/react-native-device-info/blob/master/README.md#getuniqueid) :
> iOS: This is IDFV so it will change if all apps from the current apps vendor have been previously uninstalled.

But if you go to the [code](https://github.com/react-native-community/react-native-device-info/blob/3a53b139b603147d57aee096b4977bf2b72956ca/ios/RNDeviceInfo/DeviceUID.m#L37) you will see that is incorrect:

> /*! Returns the Device UID.
>     The UID is obtained in a chain of fallbacks:
>       - Keychain
>       - NSUserDefaults
>       - Apple IFV (Identifier for Vendor)
>       - Generate a random UUID if everything else is unavailable
>     At last, the UID is persisted if needed to.
>  */

Please, clarify the way how it works and update docs if needed

**Comment by mikehardy** [comment]
Please propose a PR that clarifies based on your understanding
