### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by james1888** [react-native-community/react-native-device-info#708]
## Summary

|             |     |
| ----------- | --- |
| Version     | 2.1.3   |
| Affected OS | Android    |
| OS Version  | ?   |

## Current behavior
Got error when run `./gradlew assembleRelease`

![image](https://user-images.githubusercontent.com/8617506/60254130-8b203a80-98f7-11e9-8525-db21eb0d8412.png)

**Comment by mikehardy** [comment]
That’s the nature of a breaking change - please check release notes for major version bumps:

https://github.com/react-native-community/react-native-device-info/releases/tag/v2.0.0

(note sdk moved to 28)

**Comment by james1888** [comment]
@mikehardy 

I have already set `compileSdkVersion = 28` in `android/build.gradle`. I still got the same error.

![image](https://user-images.githubusercontent.com/8617506/60312887-3e844000-9987-11e9-85c7-cbbff9bae157.png)

**Comment by mikehardy** [comment]
Something isn’t the way you expect then, I can’t say what’s wrong with your local state but I know that symbol, it exists in 28 https://developer.android.com/reference/android/os/Build.VERSION_CODES.html#P

Maybe try `npm i —save-dev react-native-clean-project && react-native clean-project-auto`, but this is a project problem, not the module, sorry

**Comment by Xesme** [comment]
I too am experience this issue with compiledSDKVersion 28 

Android/build.gradle
`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 19
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "16.0.0"
        firebaseVersion = "17.0.0"
    }
    repositories {
        google()
        mavenLocal()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:3.4.1')

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        maven { url 'https://jitpack.io' }
        google()
        jcenter()
    }
}

// Specified to graddle to ignore the other flavors of RNN provided. 
// *** Needs to be updated as more variants become available. ***
subprojects { subproject ->
    afterEvaluate {
        if ((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                variantFilter { variant ->
                    def names = variant.flavors*.name
                    if (names.contains("reactNative51") || names.contains("reactNative56")) {
                        setIgnore(true)
                    }
                }
            }
        }
    }
}

subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support' && !details.requested.name.contains('multidex') ) {
                details.useVersion "27.1.1"
            }
        }
    }
    afterEvaluate {
        android {
            compileSdkVersion 27
            buildToolsVersion "27.0.3"
            defaultConfig {
                targetSdkVersion 27
            }
        }
    }
}`

**Comment by mikehardy** [comment]
Pattern off the example perhaps https://github.com/react-native-community/react-native-device-info/blob/master/example/android/build.gradle

**Comment by mikehardy** [comment]
for forammint what you want is likely a triple-tick and groovy, the code, then another tripletick like:

```groovy
allprojects {
  repositories {
     etc
  }
}
```

**Comment by mikehardy** [comment]
Since the second time it's happened though people have tried to set to 28, there may be something in the tools that is leaving old/broken state behind? Or something else to it? If I could pin down what is causing it to be hard (it's supposed to be easy! but isn't everything...) we could add some docs.

In the meantime when I am having strange build problems I usually do a full purge before attempting deep inspection:

`npm i --save-dev react-native-clean-project && npx react-native clean-project-auto`

it'll cause a pod refetch and npm module re-fetch so might be network transfer expensive, but you will know you have clean state afterwards

**Comment by Xesme** [comment]
Thanks for your help. I really appreciate it. I have been banging my head against the wall upgrading everything to RN 60 and AndroidX. 

I am in the process of cleaning everything, re-installing, and then I will invalidate my caches for AndroidStudio and report back.

**Comment by mikehardy** [comment]
No problem - I’m also the jetifier person (https://github.com/mikehardy/jetifier) - written because yes, it can be super frustrating. It is possible though! Unless your libraries have not moved to AndroidX *and* have one of the problems in the troubleshooting section of jetifier. Good luck

**Comment by GreanBeetle** [comment]
Receiving the same `error: cannot find symbol variable P`

react-native 0.60.0-rc
react-native-device-info 2.2.0

I've tried 

`rm -r node_module`
`npm i --save-dev react-native-clean-project && npx react-native clean-project-auto`
`npm install`
`react-native start -- --reset-cache`
Android Studio > File > Invalidate Caches / Restart 

```
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 19
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "16.0.0"
        firebaseVersion = "17.0.0"
    }
    repositories {
        google()
        mavenLocal()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:3.4.1')

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        maven { url 'https://jitpack.io' }
        // google()
        jcenter()
    }
}

// Specified to graddle to ignore the other flavors of RNN provided. 
// *** Needs to be updated as more variants become available. ***
subprojects { subproject ->
    afterEvaluate {
        if ((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                variantFilter { variant ->
                    def names = variant.flavors*.name
                    if (names.contains("reactNative51") || names.contains("reactNative56")) {
                        setIgnore(true)
                    }
                }
            }
        }
    }
}

subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support' && !details.requested.name.contains('multidex') ) {
                details.useVersion "27.1.1"
            }
        }
    }
    afterEvaluate {
        android {
            compileSdkVersion 27
            buildToolsVersion "27.0.3"
            defaultConfig {
                targetSdkVersion 27
            }
        }
    }
}
```

Any more advice on this?

**Comment by mikehardy** [comment]
If it’s set correctly, and you’re current, it’s going to work: https://github.com/react-native-community/react-native-device-info/blob/master/android/build.gradle#L19

**Comment by Xesme** [comment]
Ah and the example app is using RN v60 with AndroidX?

**Comment by mikehardy** [comment]
Not yet - I haven’t updated it. RN0.60 came out just this morning and I merged 2 PRs instead

**Comment by mikehardy** [comment]
But you can run ‘refresh-example.sh’ in the repo and try it - the entire example is actually constructed dynamically - https://github.com/react-native-community/react-native-device-info/blob/master/refresh-example.sh

**Comment by andrewsadowski** [comment]
@mikehardy, After running the scripts you recommended and then building our project in Android Studio, all of our Sync's have been stuck at `Evaluate Settings` for roughly an hour.  Is this what you meant when you said it was 'Network Intensive'?

**Comment by mikehardy** [comment]
Hmm deoends on speed I think? And how many npm packages and how big I think? I have a small 4mbit connection in Ecuador and it's usually just 10 to 20 minutes to get a new machine set up even with pod download if they already have xcode and android studio downloaded. So that seems odd

**Comment by Xesme** [comment]
It's been a long day... 
![image](https://user-images.githubusercontent.com/24839005/60627330-96191600-9da2-11e9-8622-57661282a193.png)

**Comment by Xesme** [comment]
It has been a long day... 
![image](https://user-images.githubusercontent.com/24839005/60627443-f019db80-9da2-11e9-9c96-edf9a0cc925e.png)

**Comment by mikehardy** [comment]
You're welcome! Hopefully it all eventually worked out for you and I guess if anything this will server as a good indicator of which libraries to use or avoid from a maintenance perspective and we can all limp along jetifying until then. Cheers
