### ISSUE TITLE
Error: cannot find symbol variable P (RN v60 & AndroidX) 

### ISSUE THREAD

**Issue by Xesme** [react-native-community/react-native-device-info#712]
I am currently running into this error within Android Studio. We are forced to update to RN 60 and AndroidX on a project. Has anyone been able to use this library with RN 60 and AndroidX?
<img width="792" alt="Screen Shot 2019-07-03 at 11 52 15 AM" src="https://user-images.githubusercontent.com/24839005/60617761-47ab4d80-9d89-11e9-9a9a-aa15eb0fa58b.png">

Any help is appreciated. Thanks!

**Comment by mikehardy** [comment]
dupe #708
