### ISSUE TITLE
In test ONLY: @react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null.

### ISSUE THREAD

**Issue by emclab** [react-native-community/react-native-device-info#717]
# Bug

The error above happens when running `yarn test`. The app have been updated with the latest release of 2.2.2. But the tricky is that my app works fine when launching with `react-native run-android`. I can load the `Event` component without error.

## Environment info

React native info output:

```bash
 PS C:\d\code\js\emps_fe> react-native link react-native-device-info
info iOS module "react-native-device-info" is already linked
info Android module "react-native-device-info" is already linked
PS C:\d\code\js\emps_fe> yarn test
yarn run v1.15.2
$ jest
 FAIL  __tests__/App-test.js
  ● Test suite failed to run

    @react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null. To fix this issue try these steps:
      • Run `react-native link react-native-device-info` in the project root.
      • Rebuild and re-run the app.
      • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
      If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-device-info

      2 | import { SectionList, View, Image, StyleSheet, Text, TouchableOpacity, Platform, TouchableHighlight, AppRegistry } from 'react-native';
      3 | import moment from 'moment';
    > 4 | import DeviceInfo from 'react-native-device-info';
        | ^
      5 | import helper from "../../lib/helper";
      6 | import GLOBAL from "../../lib/global";
      7 |

      at Object.<anonymous> (node_modules/react-native-device-info/deviceinfo.js:19:11)
      at Object.<anonymous> (src/components/event/Event.js:4:1)

 FAIL  __tests__/Event.test.js
  ● Test suite failed to run

    @react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null. To fix this issue try these steps:
      • Run `react-native link react-native-device-info` in the project root.
      • Rebuild and re-run the app.
      • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
      If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-device-info

      2 | import { SectionList, View, Image, StyleSheet, Text, TouchableOpacity, Platform, TouchableHighlight, AppRegistry } from 'react-native';
      3 | import moment from 'moment';
    > 4 | import DeviceInfo from 'react-native-device-info';
        | ^
      5 | import helper from "../../lib/helper";
      6 | import GLOBAL from "../../lib/global";
      7 |

      at Object.<anonymous> (node_modules/react-native-device-info/deviceinfo.js:19:11)
      at Object.<anonymous> (src/components/event/Event.js:4:1)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        6.493s
Ran all test suites.
error Command failed with exit code 1.
```

Library version: x.x.x
Here is the package.json:
[
"dependencies": {
    "moment": "^2.24.0",
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-cli": "^2.0.1",
    "react-native-confirmation-code-field": "^3.6.0",
    "react-native-device-info": "^2.2.2",
    "react-native-elements": "^1.1.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-gifted-chat": "^0.9.11",
    "react-native-keychain": "^3.1.3",
    "react-native-linear-gradient": "^2.5.4",
    "react-native-modal": "^11.0.2",
    "react-native-modal-datetime-picker": "^7.4.2",
    "react-native-paper": "^2.16.0",
    "react-native-segmented-control-tab": "^3.4.0",
    "react-native-vector-icons": "^6.5.0",
    "react-navigation": "^3.11.0",
    "socket.io-client": "2.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/runtime": "^7.4.5",
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.54.1",
    "react-test-renderer": "16.8.3"
  },](url)

## Steps To Reproduce

1.
2.
...

Describe what you expected to happen:

1.
2.

## Reproducible sample code
Here is the test code:

import 'react-native';
import React from 'react';
import App from '../App';

// Note: test renderer must be required after react-native.
import renderer from 'react-test-renderer';

it('renders correctly', () => {
  const tree = renderer.create(<Event />).toJSON();
  expect(tree).toMatchSnapshot();
});

**Comment by machour** [comment]
Hi

Could you have a look at the fifth item in the Troubleshooting section ? https://github.com/react-native-community/react-native-device-info#troubleshooting

**Comment by dimlksin2** [comment]
@react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null. To fix this issue try these steps:
      • Run `react-native link react-native-device-info` in the project root.
      • Rebuild and re-run the app.
      • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
      If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-device-info

**Comment by Obrazcoff** [comment]
Same issue for my project after upgrading it to react-native 0.60+ version.

**Comment by mikehardy** [comment]
It works in the example. I need a reproduction based on the example

**Comment by SparkleFaerieCoder** [comment]
Running into this issue as well, RN 0.60.4. Works in iOS. The module seems to have been brought into the android project and builds fine in Android studio, but fails running `react-native run-android`

**Comment by dimlksin2** [comment]
● Test suite failed to run

    @react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null. To fix this issue try these steps:
      • Run `react-native link react-native-device-info` in the project root.
      • Rebuild and re-run the app.
      • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
      If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-device-info

      1 | import firebase from 'react-native-firebase';
    > 2 | import DeviceInfo from 'react-native-device-info';

**Comment by mikehardy** [comment]
How is jest possibly going to run native code? I mock device-info in my testing

Examine the tests documentation in the troubleshooting section: https://github.com/mikehardy/jetifier/blob/master/mapping/androidx-class-mapping.csv#L1404

**Comment by YoavSch** [comment]
you can use a mock for that. create a __mocks__ directory in the root project, cd to it and create a file react-native-device-info.js. put in the file the following: export default { getIPAddress: () => {}, }

add the desired items to the object.

**Comment by tmaly1980** [comment]
@YoavSch There really should be a mock file in the project that contributors/developers maintain. Especially since there are breaking changes each major version. It should be as simple as developers using the library to import the mock as a one-liner into jest's config.

**Comment by mikehardy** [comment]
@tmaly1980 there really should be! I look forward to your contributed mock file pull request and will merge it happily

**Comment by gazialankus** [comment]
I'm getting this in my test output even though I have a `__mocks__/@react-native-community/react-native-device-info.js` with the following content: 

```
jest.mock('react-native-device-info', () => {
    return {
        getModel: jest.fn(),
    };
});
// also tried these:
// jest.mock('react-native-device-info', () => {
//     return {
//         __esModule: true,
//         default: jest.fn(() => {})
//     };
// });
// export default { getIPAddress: () => {}, }
```

```
