### ISSUE TITLE
NativeModules.RNDeviceInfo is null

### ISSUE THREAD

**Issue by lifan-github** [react-native-community/react-native-device-info#718]
react-native: 0.60
react-native-device-info: 2.2.2
![屏幕快照 2019-07-11 09 23 37](https://user-images.githubusercontent.com/17446427/61016198-6761f780-a3c1-11e9-8ac1-a6f553897f09.png)

**Comment by Taym95** [comment]
Did you try the fixing steps?

**Comment by machour** [comment]
Please have a look at the closed issues, read the troubleshooting section, use the new issue template, .. :)
