### ISSUE TITLE
Not compatible with RN 0.60 autolinking

### ISSUE THREAD

**Issue by redeguzman-gbf** [react-native-community/react-native-device-info#720]
# Bug

## Environment info

React native info output:

```bash
 // error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-device-info (to unlink run: "react-native unlink react-native-device-info")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers
```

Library version: 2.2.2

## Steps To Reproduce

1. Create an app using `react-native init project`
2. Install the package
...

Describe what you expected to happen:

1. The app should run without error

**Comment by mrigo** [comment]
Same for me as well.
I must use 
```
'react-native-device-info': {
        platforms: {
          ios: null
        }
      }
```
in react-native.config.js to make it work on both ios and android.
But still have the error
```
 // error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-device-info (to unlink run: "react-native unlink react-native-device-info")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers
```

**Comment by mikehardy** [comment]
If you nulled android too that warning would likely go awsy

**Comment by hussainhspl** [comment]
got any solution ?

**Comment by redeguzman-gbf** [comment]
waiting for a solution too

**Comment by mikehardy** [comment]
The solution is in the comments here?

**Comment by manjeets12** [comment]
@mrigo are u able to run it on android

**Comment by mikehardy** [comment]
I am running this fine on android, there is no auto-linking problem, the "error message" in this issue is not actually an error. It is a result of manually linking instead of just installing the package and letting it run

**Comment by mikehardy** [comment]
I am updating the README to be specific about this

**Comment by HarshitMadhav** [comment]
@mikehardy you are right! I think it should be labeled as "warning" instead "error".

**Comment by mikehardy** [comment]
open an issue with the react-native-community/cli repo if you like, it's from them

**Comment by HarshitMadhav** [comment]
Yes, I know it's from them. For this much small issue, I don't think it will be right to open an issue.

**Comment by shanishah215** [comment]
Try to this solution.
create react-native.config.js and add below lines.

 module.exports = {
        dependencies: {
          "react-native-device-info": { platforms: { android: null, ios: null } }
        },
      };

**Comment by umesh40047** [comment]
> "react-native-device-info": { platforms: { android: null, ios: null } }

same issue bro,
