### ISSUE TITLE
cant not link succefully

### ISSUE THREAD

**Issue by bigkrys** [react-native-community/react-native-device-info#722]
# Bug

## Environment info
"react": "16.8.3",
 "react-native": "^0.58.6",
"react-native-device-info": "^2.2.2",

React native info output:

```bash
android\app\src\main\java\com\egame_android\MainApplication.java:36: 错误: 找不到符号
import com.learnium.RNDeviceInfo.RNDeviceInfo;
                                ^
  符号:   类 RNDeviceInfo
  位置: 程序包 com.learnium.RNDeviceInfo
D:\egame_android\egame_android\android\app\src\main\java\com\egame_android\MainApplication.java:53: 错误: 找不到符号
             new RNDeviceInfo(),
                 ^
  符号: 类 RNDeviceInfo
2 个错误
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

Describe what you expected to happen:

1.
2.

**Comment by Navidhp** [comment]
+1

**Comment by mikehardy** [comment]
I believe the example is working fine, can this be reproduced in the example? Please note that the example is built dynamically so should be easy to verify version variations if you like: https://github.com/react-native-community/react-native-device-info/blob/master/refresh-example.sh

**Comment by bigkrys** [comment]
> I believe the example is working fine, can this be reproduced in the example? Please note that the example is built dynamically so should be easy to verify version variations if you like: https://github.com/react-native-community/react-native-device-info/blob/master/refresh-example.sh

hi,this problem has been solved,i detele the node_module dir,and run npm install,then link succefully

**Comment by bigkrys** [comment]
> +1

hi,this problem has been solved,i detele the node_module dir,and run npm install,then link succefully
