### ISSUE TITLE
Export ES6 compatible module

### ISSUE THREAD

**Issue by NikhilVerma** [react-native-community/react-native-device-info#723]
# Feature Request

Export react-native-device-info to be compatible with destructured ES6 imports

## Why it is needed

It will make it less verbose to use React Native device info

## Possible implementation

Just need to add additional exports to the deviceinfo.js

### Code sample

```js
import { getDeviceLocale } from 'react-native-device-info';
```

**Comment by Taym95** [comment]
@mikehardy what do you think? I can work on this!

**Comment by mikehardy** [comment]
I like the idea - how would it affect backwards compatibility? Or more directly: would this be a breaking change? Or would all existing codebases be fine no matter how they were importing?

I am not against breaking changes at all, I just want to know what a release with ES6 compatibility would mean to installed users and I am still coming up to speed on javascript (with it's seemingly infinite variations...) as a language

**Comment by Taym95** [comment]
Yes, will be backwards compatible only old version can not use destructured ES6 imports.

**Comment by mikehardy** [comment]
OK, thanks for explaining it and verifying, I'd be willing to take a pr like this, please be sure to update pr template as this would be another thing to do in PRs right? If people add something
