### ISSUE TITLE
'React/RCTUtils.h' file not found in iOS project

### ISSUE THREAD

**Issue by lutakyn** [react-native-community/react-native-device-info#725]
# Bug

After installing,linking the library, the error I get is  'React/RCTUtils.h' file not found
## Environment info

     React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
      Memory: 23.73 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
      Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
      SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 26.0.2, 27.0.3, 28.0.3
        System Images: android-27 | Google Play Intel x86 Atom
     IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
       react: ^16.8.3 => 16.8.6 
      react-native: ^0.59.10 => 0.59.10 
     npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
    React native info output:

```bash
 // paste it here
```

  "react-native-device-info": "^2.2.2"

## Steps To Reproduce

   1. npm i react-native-device-info
   2. react-native link react-native-device-info
   3. Podfile Info below

    platform :ios, '9.0'

    use_frameworks!

    target 'ProjectX' do
   
    pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
    pod 'react-native-config', :path => '../node_modules/react-native-config'
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
    pod 'react-native-maps', :path => '../node_modules/react-native-maps'
    pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-   
    info/RNDeviceInfo.podspec'
      target 'ProjectXTests' do
    inherit! :search_paths
      # Pods for testing
     end

      end

Describe what you expected to happen:

1. I expected to see device information just like how I see in Android device

**Comment by tunm1228** [comment]
I followed https://github.com/nartc/rndeviceinfo-reproduce/blob/master/ios/Podfile fixed.
