### ISSUE TITLE
is24Hours

### ISSUE THREAD

**Issue by ramya123coder** [react-native-community/react-native-device-info#728]
# Question

If the time preference is changed while the app is running then is24Hours does not return correct value.Is this the behaviour?

**Comment by mikehardy** [comment]
I don't believe it will - you can check the code, but if it is part of the getConstants() method then no, none of that updates dynamically.

Having those be dynamic and return Promises is part of the goal for the next major version

**Comment by mikehardy** [comment]
These are moving to react-native-localize for v3 I think https://github.com/react-native-community/react-native-localize/pull/65
