### ISSUE TITLE
isTablet() returns wrong value for Android Phablets such as the Huawei Mate 20 X

### ISSUE THREAD

**Issue by mouselangelo** [react-native-community/react-native-device-info#729]
# Bug

The [current logic](https://github.com/react-native-community/react-native-device-info/blob/05d485d48a6cabab0f8e1c10811ab9783511cddc/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L204-L218) uses the physical size (in Inches) to determine whether the `DeviceType` is a Tablet.

This results in some of the newer phablets sometimes being determined as “Tablets” in React-Native, but not in Native Android.

### Example:

The [Huawei Mate 20 X](https://www.gsmarena.com/huawei_mate_20_x-9369.php) is a 7.2” phablet. It’s large size is due to a very wide aspect ratio (**18.7:9**), it is however not a tablet due to its form-factor. Native apps on this device are rendered with *Phone layouts*.

### Screenshot 

The [test app](https://github.com/machour/react-native-device-info-test) running on an emulator for this device:

![isTablet-for-huawei-mate-20-x](https://user-images.githubusercontent.com/11625008/61707205-33d08700-ad4a-11e9-8bc3-f9c5d424e1b6.png)

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 24.38 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.12.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 26, 27, 28
      Build Tools: 27.0.3, 28.0.3, 29.0.0
      System Images: android-25 | Google APIs ARM EABI v7a, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5056338
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

Library version: 2.2.2

## Steps To Reproduce
1. Create an Emulator based on the [Huawei Mate 20 X](https://www.gsmarena.com/huawei_mate_20_x-9369.php) device (or similar). Refer [this AVD Hardware profile](https://gist.github.com/mouselangelo/2b8ffcd452efdaf41ff698d85aea7614) 
2. Run the [recommended example app](https://github.com/machour/react-native-device-info-test) 
3.  `isTablet()` is `true` (see screenshot)

Describe what you expected to happen:

1. `isTablet()` should be `false` for this device.

## Reproducible sample code
[GitHub - machour/react-native-device-info-test](https://github.com/machour/react-native-device-info-test).

## Developer Documentation / Reference

Native Android recommends using the **smallest width dp** to determine the size, rather than the physical size of the device. 

Excerpt from the official Android Developer documentation:[Support different screen sizes](https://developer.android.com/training/multiscreen/screensizes)

> The smallest width qualifier specifies the smallest of the screen's two sides, regardless of the device's current orientation, so it's a simple way to specify the overall screen size available for your layout.
> Here's how other smallest width values correspond to typical screen sizes
> • 320dp: a typical phone screen (240x320 ldpi, 320x480 mdpi, 480x800 hdpi, etc).
> • 480dp: a large phone screen ~5" (480x800 mdpi).
> • 600dp: a 7” tablet (600x1024 mdpi).
> • 720dp: a 10” tablet (720x1280 mdpi, 800x1280 mdpi, etc).

Excerpt from a post from  the Android Developers Blog that introduced these new features (in Android 3.2)  [New Tools For Managing Screen Sizes](https://android-developers.googleblog.com/2011/07/new-tools-for-managing-screen-sizes.html)

> …**smallest width dp** is the most important. It replaces the old screen-size buckets with a continuous range of numbers giving the effective size.

**Comment by mikehardy** [comment]
I'm traveling right now but if you have time to propose a PR (the research looks good...) I could probably get it merged and released

**Comment by mouselangelo** [comment]
> I'm traveling right now but if you have time to propose a PR (the research looks good...) I could probably get it merged and released

Thanks @mikehardy 👍
I am proposing a PR for this right now!

**Comment by mouselangelo** [comment]
@mikehardy - when you have the time :)
https://github.com/react-native-community/react-native-device-info/pull/730

**Comment by mouselangelo** [comment]
fixed by #730

**Comment by badaz** [comment]
Hi, considering the multiple issues and merged PR's on this subject, is the function isTablet truly reliable on Android now? I would like to use it to change the size of some elements in my app when used on a tablet but I don't see how I could test it on every available devices (tablets and phones included).  I'm not ready to take the chance to use it in my app and distribute it to my users afterwards either if I'm not sure that it won't break my layout on some devices.

**Comment by mikehardy** [comment]
@badaz it is not reliable nor has it ever been. It's a heuristic. What you really want is something like https://github.com/th3rdwave/react-native-safe-area-context and to make your own decisions based on the insets in effect

**Comment by badaz** [comment]
Thanks for the link, but then why is it even available in the lib ? Or maybe should it be named looksLikeTablet?

**Comment by mikehardy** [comment]
@badaz this module, started in 2015. That module, started last October. History :shrug: - if you'd like to propose a breaking change PR removed the API and code along with a quick migration document ("document", like, one good sentence is best) explaining how to use react-native-safe-area-context to achieve the same result by default but with flexibility available as the positive change, that works for me. I don't like duplication or vague implementations myself

**Comment by badaz** [comment]
Ok, sorry, I did not mean to sound harsh, mine was just a naive question :) , I'm only just tackling this problem now, so I don't even know how I could use that lib in order to achieve tablet detection. But I'm going to look into it, I'll come back here if I find a better solution

**Comment by mikehardy** [comment]
No worries - I maintain a pile of repos and deal with issues and PRs in a mish-mash of languages etc so I've learned to be more direct and prescriptive than ever to cut down on back and forth, but "really matter of fact" doesn't always sound friendly :-). Good luck with your project
