### ISSUE TITLE
AndroidX Support doc issue

### ISSUE THREAD

**Issue by elkinjosetm** [react-native-community/react-native-device-info#738]
# AndroidX Installation Doc Issue

There is a typo in [AndroidX Support section](https://github.com/react-native-community/react-native-device-info#androidx-support) in the README file. Or a typo in `android/build.gradle`, either way, by following the docs, it'll break the Android build.

Solutions:
- **supportV4LibVersion** -> **supportV4Version** in the README file

OR

- **supportV4Version** -> **supportV4LibVersion** in `android/build.gradle` file

## Why it is needed
It's breaking the Android build in the latest version of the library v2.3.0

**Comment by mikehardy** [comment]
The build.gradle is code, changing a name that's already "out there" (and people may be using after reading it and seeing what to use) is a breaking change, so if there's another option (there is, the README), that's the one to pick. I'll fix it there - good catch!

**Comment by elkinjosetm** [comment]
Yeah, you’re right, I didn’t want to do a PR for both solutions. Thanks for the quick response.
