### ISSUE TITLE
getFreeDiskStorage export as method not constant

### ISSUE THREAD

**Issue by brenwell** [react-native-community/react-native-device-info#743]
# Feature Request

Hey guys, nice library here. So thanks

I would like to propose exporting `getFreeDiskStorage` as  method an not a constant. I am using it to show a user their current free space after downloading things, but as this is a constant on iOS (I haven't checked android) it will never change to show the current free space

## Possible implementation

Before

```js
 getFreeDiskStorage: function() {
    return RNDeviceInfo.freeDiskStorage;
  },

```

After

```js
 getFreeDiskStorage: function() {
    return RNDeviceInfo.getfreeDiskStorage();
  },
```

iOS changes

```objc
...
             @"totalDiskCapacity": @(self.totalDiskCapacity),
//           @"freeDiskStorage": @(self.freeDiskStorage),
             @"deviceType": [DeviceTypeValues objectAtIndex: [self getDeviceType]],
             @"supportedABIs": @[[self getCPUType]],
             };
}


RCT_EXPORT_METHOD(getFreeDiskStorage:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
{
    resolve(@(self.freeDiskStorage));
}
```

What do you think?

**Comment by mikehardy** [comment]
This is in general the same as the goal of converting the entire library from constants (it's constant for nearly everything on ios and android) to Promises.

It is actually not that big a task as a piece of coding work - I just haven't had time. It'd be a breaking change, but one that about everyone wants.

If you want to propose a PR I would *love* it! I don't want to do it one API at a time though - it's a pretty mechanical conversion but I don't want to have a string of breaking changes for the same reason

I'm going to close this in favor of #307 which has the plan. At this point I'd take a pure Promise PR that didn't separate to namespaces, one is important, one is just sugar

**Comment by brenwell** [comment]
Ok that sounds all very reasonable. If I can find some time, I will have a go at the iOS side.
