### ISSUE TITLE
RNDeviceInfo is null issue on react-native 0.60.4

### ISSUE THREAD

**Issue by patrice4github** [react-native-community/react-native-device-info#747]
# Bug

RNDeviceInfo is null issue on react-native 0.60.4. Importing it fails with version 2.3.2.

## Environment info

React native info output:

```
 System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 13.90 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.8.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.2
      System Images: android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.1 AI-173.4907809
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

```

Library version: x.x.x

## Steps To Reproduce

1. Create a new app **react-native init MyTestApp**
2. In App.js, import DeviceInfo:

`import DeviceInfo from 'react-native-device-info';`

3. npm install it:

`npm install react-native-device-info --save`

4. Run with **react-native run-ios**

<img width="409" alt="Screen Shot 2019-08-08 at 3 36 01 PM" src="https://user-images.githubusercontent.com/1727358/62732748-1b6f9600-b9f3-11e9-9154-3bb6dbc9bd22.png">

Describe what you expected to happen:

1. I would expect the app to start normally.
2. To be coherent, I would have expected react-native-device-info to be installed in ./node_modules/@react-native-community/react-native-device-info. Rather it's installed in ./node_modules/react-native-device-info

## Reproducible sample code

The app created by init is sufficient after importing DeviceInfo in App.js.

**Comment by mikehardy** [comment]
The example is using RN0.60.4 https://github.com/react-native-community/react-native-device-info/blob/master/example/package.json#L12

It is built dynamically in much the way you describe, and works fine?

Maybe you didn't run pod install?

Re-open if you check out this module, run refresh-example.sh then inside example you do a pod install and react-native run-ios and it still doesn't work

**Comment by patrice4github** [comment]
pod install helped in my sample, thanks. 
I can see why but I have never done this before in my project. That would make the installation instruction incomplete on the project's home page.

**Comment by mikehardy** [comment]
@patrice4github Cocoapods is now the default for RN60, everything RN60 requires a pod install, so it's just assumed now - any time you do anything with RN60 that touches native code, you'll have to pod install after. At the same time, even though it should be assumed if you want to propose a PR to the README that makes it clear, it might save future people time and I'd be willing to merge

**Comment by patrice4github** [comment]
Thanks for the feedback! Cheers! PR?  Not sure what that is...

-Patrice

**Comment by anniewey** [comment]
@mikehardy I'm getting this on Android, running RN 0.60.0. Do I need to link it manually? Seems like the auto linking isn't working in Android. It's working fine in iOS

**Comment by mikehardy** [comment]
auto-linking works fine on android. There's something wrong with your RN60 conversion maybe? Maybe not including the CLI auto-linking part in your build.gradle? I'm not sure but we experience perfect execution on RN60 without manual linking - this is all we do in testing and it works https://github.com/react-native-community/react-native-device-info/blob/master/refresh-example.sh#L29

**Comment by anniewey** [comment]
@mikehardy You're right. I've missed out some part during the RN 0.60 upgrading process. Thanks for pointing that out.
