### ISSUE TITLE
Android cannot build

### ISSUE THREAD

**Issue by xclidongbo** [react-native-community/react-native-device-info#752]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class android.support.v4.app.AppLaunchChecker found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-utils:27.0.2)
  Duplicate class android.support.v4.app.FrameMetricsAggregator found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-utils:27.0.2)
  Duplicate class android.support.v4.app.FrameMetricsAggregator$FrameMetricsApi24Impl found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-utils:27.0.2)
  Duplicate class android.support.v4.app.FrameMetricsAggregator$FrameMetricsApi24Impl$1 found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-utils:27.0.2)
  Duplicate class android.support.v4.app.FrameMetricsAggregator$FrameMetricsBaseImpl found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-utils:27.0.2)
  Duplicate class android.support.v4.app.FrameMetricsAggregator$MetricType found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-utils:27.0.2)
  Duplicate class android.support.v4.app.NavUtils found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-utils:27.0.2)
  Duplicate class android.support.v4.app.TaskStackBuilder found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-utils:27.0.2)
  Duplicate class android.support.v4.app.TaskStackBuilder$SupportParentable found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-utils:27.0.2)
  Duplicate class android.support.v4.content.FileProvider found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-utils:27.0.2)
  Duplicate class android.support.v4.content.FileProvider$PathStrategy found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-utils:27.0.2)
  Duplicate class android.support.v4.content.FileProvider$SimplePathStrategy found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-utils:27.0.2)
  Duplicate class android.support.v4.content.MimeTypeFilter found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-utils:27.0.2)
  Duplicate class android.support.v4.content.PermissionChecker found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-utils:27.0.2)
  Duplicate class android.support.v4.content.PermissionChecker$PermissionResult found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-utils:27.0.2)
  Duplicate class android.support.v4.graphics.ColorUtils found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-utils:27.0.2)
  Duplicate class android.support.v4.graphics.drawable.RoundedBitmapDrawable found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-utils:27.0.2)
  Duplicate class android.support.v4.graphics.drawable.RoundedBitmapDrawable21 found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-utils:27.0.2)
  Duplicate class android.support.v4.graphics.drawable.RoundedBitmapDrawableFactory found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-utils:27.0.2)
  Duplicate class android.support.v4.graphics.drawable.RoundedBitmapDrawableFactory$DefaultRoundedBitmapDrawable found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-utils:27.0.2)
  Duplicate class android.support.v4.math.MathUtils found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-utils:27.0.2)
  Duplicate class android.support.v4.view.NestedScrollingChildHelper found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-ui:27.0.2)
  Duplicate class android.support.v4.view.NestedScrollingParentHelper found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-ui:27.0.2)
  Duplicate class android.support.v4.widget.AutoScrollHelper found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-ui:27.0.2)
  Duplicate class android.support.v4.widget.AutoScrollHelper$ClampedScroller found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-ui:27.0.2)
  Duplicate class android.support.v4.widget.AutoScrollHelper$ScrollAnimationRunnable found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-ui:27.0.2)
  Duplicate class android.support.v4.widget.ContentLoadingProgressBar found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-ui:27.0.2)
  Duplicate class android.support.v4.widget.ContentLoadingProgressBar$1 found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-ui:27.0.2)
  Duplicate class android.support.v4.widget.ContentLoadingProgressBar$2 found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-ui:27.0.2)
  Duplicate class android.support.v4.widget.ListViewAutoScrollHelper found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-ui:27.0.2)
  Duplicate class android.support.v4.widget.NestedScrollView found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-ui:27.0.2)
  Duplicate class android.support.v4.widget.NestedScrollView$AccessibilityDelegate found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-ui:27.0.2)
  Duplicate class android.support.v4.widget.NestedScrollView$OnScrollChangeListener found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-ui:27.0.2)
  Duplicate class android.support.v4.widget.NestedScrollView$SavedState found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-ui:27.0.2)
  Duplicate class android.support.v4.widget.NestedScrollView$SavedState$1 found in modules classes.jar (com.android.support:support-compat:28.0.0) and classes.jar (com.android.support:support-core-ui:27.0.2)

**Comment by mikehardy** [comment]
please check out this repo, and reproduce with the example - if you can reproduce with the example app, I can see why it's happening, but I suspect a project-specific issue

**Comment by xclidongbo** [comment]
Because the project did not introduce androidx, version 2.1.1 was installed

some error:
```
Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:7:5-117 to override.
```

**Comment by mikehardy** [comment]
incomplete jetification I think, @xclidongbo and whether you *want* to move to AndroidX or not, you'll need to sooner or later. It looks like some other of your dependencies has already done so.

This module works with or without androidx so it's not a problem with this module.

Supporting androidx transitions (or attempting to *not* use androidx) is outside of the scope of this module though - I prove it works here with androidx or not with my two example scripts and that's as much as this module can reasonably be expected to do
