### ISSUE TITLE
Too many exports, stops after getDeviceType

### ISSUE THREAD

**Issue by nschild** [react-native-community/react-native-device-info#754]
# Bug
It appears that there is a limit of 62 exports per js file as these methods are coming up as undefined for me:
- isAutoDateAndTime
- isAutoTimeZone
- supportedABIs
- supported32BitAbi
- supported64BitAbis
- hasSystemFeature
- getSystemAvailableFeatures
- isLocationEnabled
- getAvailableLocationProviders

## Environment info

React native info output:

```bash
React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 44.40 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.11.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 25, 26, 27, 28
        Build Tools: 25.0.2, 26.0.2, 28.0.3
        System Images: android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.8.6 
      react-native: 0.59.2 => 0.59.2 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

Library version: 2.3.2
React Native Debugger: 0.9.10

## Steps To Reproduce
Not sure if related to #517 and not sure if the issue happens on release builds or just an incompatibility with React Native Debugger.

1. Run the debug version of the app on a real android device
2. In the `React Native Debugger`, right-click the DeviceInfo object log entry and `save as local variable`
3. You will notice that `isLocationEnabled` is not in the list of available methods
4. Open `node_modules/react-native-device-info/deviceinfo.js` and move the `isLocationEnabled` function to the top of the exports object. 
5. Repeat steps 1-2 and you will notice that `isLocationEnabled` is now there.
...

Describe what you expected to happen:

1.
2.

## Reproducible sample code

```
...
import DeviceInfo from 'react-native-device-info';
...
console.log('deviceinfo', DeviceInfo);
DeviceInfo.isLocationEnabled().then(console.log); // JS says isLocationEnabled is undefined but TSlint says it is valid.
...
```

**Comment by mikehardy** [comment]
but...everything works in the example - I check it before release. clone this repo, npm i for the example, run it - if you can reproduce it of course we can reopen and investigate
