### ISSUE TITLE
getReadableVersion is returning the versionCode/buildNumber

### ISSUE THREAD

**Issue by ricbermo** [react-native-community/react-native-device-info#755]
# Bug

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 274.65 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.0
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.0 => 0.60.0

```

Library version: 2.3.2

## Steps To Reproduce

1. just call `DeviceInfo.getReadableVersion()`
...

Describe what you expected to happen:

1. My app versionName on Android and Version on iOS is `1.0.1`
2. My versionCode on Android and buildVersion on iOS is `1`
3. `getReadableVersion` is returning `1.0.1.1`
4. I'm expecting `1.0.1` only.

**Comment by mikehardy** [comment]
might be a doc bug or an implementation issue depending on point of view.

would be a breaking change to alter it at any rate

how do getBuildId() and getVersion() suit you?

**Comment by ricbermo** [comment]
@mikehardy thanks for your reply.
`getVersion` does return `1.0` as in the example, but I'd not be sure where to change that value.
`getBuildId` is not an option for me.
BTW, on a previous app, I used version 0.24.3 and I got the expected result. I know it's an old version but the example output is the same: `1.0.1`.

**Comment by mikehardy** [comment]
I dunno, looks like it's just concatenating them https://github.com/react-native-community/react-native-device-info/blame/master/deviceinfo.js#L432

I'm 99% tempted to call this "not a bug" except the docs are definitely not clear on the point, which is certainly not great. Care to make a docs PR that clarifies in the README how this works, in a way that you'd expect what you get?

**Comment by haseebeqx** [comment]
It is a bug. It doesn't match with android's view of versioning https://developer.android.com/studio/publish/versioning

**Comment by mikehardy** [comment]
no response

**Comment by ricbermo** [comment]
@mikehardy thanks for your patience. `getVersion` doesn't work for me, because I want to display the version like `1.0.0`.
IDK if I should open a PR to change the docs since it may be a bug.

**Comment by mikehardy** [comment]
Your response makes me feel as if you weren't listening, or I wasn't explaining myself well.

getReadableVersion is implemented as getVersion() + '.' + getBuildNumber() effectively https://github.com/react-native-community/react-native-device-info/blob/master/deviceinfo.js#L432

So I don't believe you have a bug. You want getVersion(). You might just want to PR an update to the docs.

**Comment by ricbermo** [comment]
@mikehardy the last time I tried `getVersion` it returned `1.0` and my app's version used to be `1.0.0`. I just tried it and now it returned `1.0.0` so, I think `getVersion` does work for me. Thank you so much.

**Comment by mikehardy** [comment]
whew :-), glad it works
