### ISSUE TITLE
Support for checking if dark mode is on/off?

### ISSUE THREAD

**Issue by ThomasLarge** [react-native-community/react-native-device-info#758]
# Feature Request

A function where you can check if the user has dark mode on or off

## Why it is needed

As dark mode is being pushed a lot on iOS I think it will be a good extension to the great package we have now 

## Possible implementation

I don’t know the full information but Apple have just released the SDK for this so maybe hook into this?

**Comment by mikehardy** [comment]
You want this https://github.com/expo/react-native-appearance

Until you can have this https://github.com/facebook/react-native/pull/26172

It will be baked in to the platform and not implemented here, with a workaround available now

**Comment by ThomasLarge** [comment]
Thank you for the fast response and links!!!
