### ISSUE TITLE
library version 2.3.2 Recompile with -Xlint:deprecation for details. issue

### ISSUE THREAD

**Issue by sikeeoh** [react-native-community/react-native-device-info#761]
# Bug
I started an android release build and got an error

/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:
uses or overrides a deprecated API.
Recompile with -Xlint:deprecation for details.

"react-native-device-info": "2.3.2",

**Comment by mikehardy** [comment]
Please include the relevant output of compilation '-Xlint:deprecation' and post the details.

**Comment by sikeeoh** [comment]
@mikehardy 
I'm sorry.
It was an issue with a library reactotron.
