### ISSUE TITLE
UIWebView Deprecated API Usage - iOS App Store submission warning

### ISSUE THREAD

**Issue by jpamarohorta** [react-native-community/react-native-device-info#763]
# Bug

When submitting to App Store you receive a warning that the app is using a deprecated API `UIWebView`.

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

The issue is in [RNDeviceInfo.m#L118](https://github.com/react-native-community/react-native-device-info/blob/cf042da403353605ff5ceae5e28dda787eb5857f/ios/RNDeviceInfo/RNDeviceInfo.m#L118) where `UIWebView` is used.

Library version: 2.3.2

## Steps To Reproduce

1. Submit an app to App Store/TestFlight using this library
2. Apple automatic review process will give this warning

Describe what you expected to happen:

1. No warning should be received

## Related issues

[react-native-webview#819](https://github.com/react-native-community/react-native-webview/issues/819)
[react-native#26255](https://github.com/facebook/react-native/issues/26255)

**Comment by mikehardy** [comment]
it's a pinned issue in the repo right at the top, please search before spending time
https://github.com/react-native-community/react-native-device-info/issues
 https://github.com/react-native-community/react-native-device-info/issues/756

Duplicate.

**Comment by jpamarohorta** [comment]
I'm sorry, looked at the issues list, didn't notice the pinned one. My bad.
