### ISSUE TITLE
Could not resolve com.google.android.gms:play-services-iid:[16.0.1].

### ISSUE THREAD

**Issue by xclidongbo** [react-native-community/react-native-device-info#764]
Platform: android

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.google.android.gms:play-services-iid:[16.0.1].
     Required by:
         project :app > project :react-native-device-info > com.google.android.gms:play-services-gcm:16.1.0
      > Failed to list versions for com.google.android.gms:play-services-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-iid/maven-metadata.xml.
            > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-iid/maven-metadata.xml'.
               > Connection reset

**Comment by mikehardy** [comment]
The example app shows usage, and there is a react-native59 script that shows non-AndroidX usage even.

It definitely works

Your project has some sort of gradle dependency resolution issue and solving those is tricky, it's outside the scope of this project

You may find this interesting https://github.com/react-native-community/react-native-device-info/blob/master/refresh-example-rn59.sh

**Comment by mikehardy** [comment]
instance-id is fetched asynchronously from the internet as part of google play services

**Comment by mikehardy** [comment]
(or at least, I believe it is...)

**Comment by dskusuma** [comment]
hmmm make sense. Thanks!

**Comment by ditas3004** [comment]
Thanks sense.
