### ISSUE TITLE
NativeModule.RNDeviceInfo is NULL on RN 0.59.8 (Expo SDK 34)

### ISSUE THREAD

**Issue by Feijo** [react-native-community/react-native-device-info#766]
# Bug
Trying to use react-native-device-info for the first time and I'm getting this error when the application tries to start up: 

node_modules\react-native\Libraries\Core\ExceptionsManager.js:74 @react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null. 

## Environment info

expo: 34.0.4
react: 16.8.3
react-native: 0.59.8

React native info output:

```bash
System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 21.36 GB / 31.88 GB
  Binaries:
    Node: 10.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.11.2 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
info React Native v0.60.0 is now available (your project is running on v0.59.8).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.60.0.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.59.8.
info To upgrade, run "react-native upgrade".
```

Library version: 2.3.2

## Steps To Reproduce

1. Create a basic RN + Expo application
2. Install the package by running `npm install --save react-native-device-info`
3. Run `react-native link react-native-device-info` to create link
4. Execute the application via expo by running `expo start --android`

I've also created a react-native.config.js and placed it in the root of my project:

```js
module.exports = {
  dependency: {
    'react-native-device-info': {
      platforms: {
        android: {
          packageInstance: 'new RNDeviceInfo(false)'
        }
      }
    },
    assets: ['./assets/fonts']
  }
};
```

I also tried removing the folder node_modules and package-lock.json and reinstalling everything, same result.

**Comment by mikehardy** [comment]
No idea. I have terrible luck troubleshooting expo things. Definitely looks like a linkage failure. You might read how to manually link and examine your files from that perspective to see if there was a link failure of some sort

**Comment by Feijo** [comment]
After I posted here I continued my research and I found out that Expo and native code don't work well. Apparently the only way to get it to work with expo is by ejecting it. 

Probably worth adding a note in setup guide in this regards so people using Expo don't waste time trying to get it to work.

**Comment by mikehardy** [comment]
Feel free to post a PR to the Troubleshooting section of the readme to dissuade people. This is widely known though - https://duckduckgo.com/?q=can+I+use+expo+with+native+modules&ia=web and well-documented https://docs.expo.io/versions/latest/introduction/why-not-expo/

**Comment by ahmedALKATTAN** [comment]
how to solve react-native-device-info: NativeModule.RNDeviceInfo is null when importing import { getFirstInstallTime } from "react-native-device-info";
