### ISSUE TITLE
[v3] Memoize most methods

### ISSUE THREAD

**Issue by janicduplessis** [react-native-community/react-native-device-info#767]
# Feature Request

Now that v3 doesn't use constants anymore I think it would be a good idea to memoize values in JS to avoid having to go through the bridge for each repeated call. Most values returned by this library never change so it would work well.

## Why it is needed

This would lead to better performance for repeated calls to the same method. The performance characteristics would be closer to v2 since it used to be only a js property access and not a bridge call.

## Possible implementation

- Add a field per method to store the value returned, then use that value for subsequent calls instead of going through the bridge. Main benefit of this is we can use the same cached value for the sync and async method.

- Use some memoization library or create our own higher order function.

### Code sample

```js
let _deviceId;

export async function getDeviceId() {
  if (_deviceId === undefined) {
    if (OS === 'android' || OS === 'ios' || OS === 'windows') {
      _deviceId = await RNDeviceInfo.getDeviceId();
    } else {
      _deviceId = 'unknown';
    }
  }
  return _deviceId;
}

export function getDeviceIdSync() {
  if (_deviceId === undefined) {
    if (OS === 'android' || OS === 'ios' || OS === 'windows') {
      _deviceId = RNDeviceInfo.getDeviceIdSync();
    } else {
      _deviceId = 'unknown';
    }
  }
  return _deviceId;
}
```

**Comment by mikehardy** [comment]
A good idea. I'll let 3.0.0-rc.2 shake out to make sure the API really is stable (should be, but rc.1->rc.2 was a big change) then probably add this for things that are truly constant.

**Comment by mikehardy** [comment]
For the async function should I not return Promise.resolve(variable) ?

**Comment by janicduplessis** [comment]
@mikehardy It is not needed for async functions, you can just return the value directly (Async functions implicitly wrap values with Promise.resolve).

**Comment by mikehardy** [comment]
I have begun the process https://github.com/react-native-community/react-native-device-info/pull/760/commits/49791912cc19ddb72f3d9354e2e7c9445691a5e9

I'll finish it while I wait for any other feedback on v3 then release this thing...

**Comment by mikehardy** [comment]
And I learned something about async return values, default promise-boxing, interesting

**Comment by mikehardy** [comment]
3.0.0-rc.4 includes memoization on all return values that I reasoned are 100% static
