### ISSUE TITLE
Method getSystemNameSync() return "unknown" on Android and iOS

### ISSUE THREAD

**Issue by cmpayc** [react-native-community/react-native-device-info#771]
Bug in deviceinfo.js:
```JavaScript
export function getSystemNameSync() {
  if (!systemName) {
    if (OS === 'ios') {
      systemName = RNDeviceInfo.getSystemNameSync();
    } else if (OS === 'android') {
      systemName = 'Android';
    }
    if (OS === 'windows') {
      systemName = 'Windows';
    } else {
      systemName = 'unknown';
    }
  }
  alert(systemName);
  return systemName;
}
```
```if (OS === 'windows') {``` must be ```else if (OS === 'windows') {```

**Comment by mikehardy** [comment]
Thanks for reporting this! I'll scan the rest too - it was a great deal of fast typing to go from rc.2 to .3 and .4 - clearly an oversight here

**Comment by mikehardy** [comment]
Fixed in https://github.com/mikehardy/react-native-device-info/commit/ba62f8873ec480ad09f6ca05f9b87a88deafaf12 - plus there were a few others similar that a full API pass picked up, thanks again
