### ISSUE TITLE
undefined is not a function, js engine: hermes

### ISSUE THREAD

**Issue by ethanneff** [react-native-community/react-native-device-info#772]
# Bug
Upgrading from `react-native-device-info  2.3.2  →  3.0.0`

![Screenshot_20190910-164235](https://user-images.githubusercontent.com/2933593/64657853-0dde6f00-d3ea-11e9-8c46-bd08e1ce1a58.png)

## Environment info

```bash
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 535.45 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3
      System Images: android-19 | Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
```

Library version: 3.0.0

## Steps To Reproduce

https://github.com/react-native-community/react-native-device-info/releases/tag/v3.0.0
https://github.com/facebook/create-react-app
https://facebook.github.io/react-native/docs/hermes/

**Comment by leandrosimoes** [comment]
@ethanneff this issue was fixed? I'm having the same problem here =/

**Comment by ethanneff** [comment]
I realized the entire API changed for `react-native-device-info`, so I decided against upgrading and reverted back to the old version.

**Comment by mikehardy** [comment]
This is not a constructive answer but it is my understanding that hermes is not quite ready yet - it is hearsay on my part but from a person that is normally very quality oriented in a library that is very complicated (react-native-firebase) https://github.com/invertase/react-native-firebase/issues/2469#issuecomment-532182627 - so I've filed hermes as "soon but not now" personally.

**Comment by mikehardy** [comment]
also - I'll note that other than #776 the API moved quite a bit but every previous use case is supported, and hopefully #776 will be supported good-enough as well. The wiki has a migration guide that can hopefully help you through it - I'm sorry to have pushed through breaking change but hopefully your eventual migration isn't too difficult

**Comment by leandrosimoes** [comment]
@mikehardy I totally agree with you, seems like hermes needs more time to be used without any or with a minimum of problem.

@ethanneff @mikehardy  Yeah, the API changed all to promises since 3.0.0 and some API was removed like `getDeviceLocation` that was the one that was causing my problem. Well, I just add the `react-native-localize` package for that and solve my problem for now.

Thanks a lot for the answers!

**Comment by mikehardy** [comment]
Yeah - the react-native-localize API move was the biggest thing but I coordinated with the maintainer there to make sure every API existed with the same semantics. It's a great package and should serve us all well. Cheers

**Comment by Kailash23** [comment]
[18:54:28] E | ReactNativeJS ▶︎ TypeError: undefined is not a function, js engine: hermes

[18:54:28] E | ReactNativeJS ▶︎ Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
                             └ This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
                             
  Yeah, Hermes needs improvement.

**Comment by Kailash23** [comment]
I need to find whether the device is an emulator or not.
But I can't use this library because assemble release is crashing while opening.
Can anyone help me know how to detect device is an emulator or not without using this library?
