### ISSUE TITLE
Parallel calls to getUserAgent() cause a runtime exception

### ISSUE THREAD

**Issue by cormander** [react-native-community/react-native-device-info#774]
# Bug

Hello. I've used this package for years and I really like it. Thanks for your hard work!

Today I updated to the 3.0.0 version. I noticed some odd behavior, and have narrowed it down to the fact that parallel calls to the DeviceInfo.getUserAgent() function cause one of them to throw an exception.

I think I'm to a point where I'm no longer calling duplicate functions at the same time with the help of async await, so I've worked around the issue .... here's my end-result commit of going from 2.3.2 to 3.0.0 for reference : https://github.com/OurVoiceUSA/HelloVoter/commit/4cb41e3538f73932cfec411b7f03bd1e42bbb42e

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 374.36 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    npm: 6.11.3 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 28.0.3, 29.0.1, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.9.0 
    react-native: ^0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 3.0.0

## Steps To Reproduce

Call the same function twice before the promise resolves, like this:

```bash
  componentDidMount() {
    DeviceInfo.getUserAgent().then(i => this.setState({UserAgent: i})).catch(e => console.warn(e));
    DeviceInfo.getUserAgent().then(i => this.setState({UserAgent: i})).catch(e => console.warn(e));
  }
```

Describe what you expected to happen:

No exception should be thrown.

## Reproducible sample code

You can init a new project like so 

```bash
react-native init AwesomeProject
cd AwesomeProject
npm install react-native-device-info
react-native link react-native-device-info
(cd ios && pod install)
```

Have `App.js` be the following:

```bash
import React, {PureComponent} from 'react';
import {
  View,
  Text,
} from 'react-native';
import DeviceInfo from 'react-native-device-info';

export default class App extends PureComponent {

  constructor(props) {
    super(props);
    this.state = {
      UserAgent: "unknown",
    };
  }

  componentDidMount() {
    DeviceInfo.getUserAgent().then(i => this.setState({UserAgent: i})).catch(e => console.warn(e));
    DeviceInfo.getUserAgent().then(i => this.setState({UserAgent: i})).catch(e => console.warn(e));
  }

  render() {
    const { UserAgent } = this.state;
    return (
      <View style={{flex: 1, margin: 50}}>
        <Text>Hello DeviceInfo! UserAgent => {UserAgent}</Text>
      </View>
    );
  }
};
```

And finally `react-native run-ios` and you'll see the warning from the caught exception. In this example it's complaining about WKErrorDomain, and at some point the message said something about thread safety, and I didn't capture the message in detail.

**Comment by cristianoccazinsp** [comment]
Out of curiosity, how do you achieve "Parallel" execution? On the JS side, there's only one thread running. On the native side, all bridge calls are dispatched in a single thread as well (correct me if I'm wrong). So although it looks like parallel execution, it is only concurrent, but still serial / single threaded.

**Comment by mikehardy** [comment]
like this https://github.com/react-native-community/react-native-device-info/blob/master/ios/RNDeviceInfo/RNDeviceInfo.m#L680

**Comment by cristianoccazinsp** [comment]
Isn't the main/UI thread/queue also serial? Even if you fire that twice, they should not run in parallel.

`The main dispatch queue is a globally available serial queue that executes tasks on the application’s main thread`

https://developer.apple.com/library/archive/documentation/General/Conceptual/ConcurrencyProgrammingGuide/OperationQueues/OperationQueues.html#//apple_ref/doc/uid/TP40008091-CH102-SW2

**Comment by mikehardy** [comment]
`This queue works with the application’s run loop (if one is present) to interleave the execution of queued tasks with the execution of other event sources attached to the run loop`

So perhaps it's because the javascript is execution is async itself inside the webview (it should be, right?) and the webview is I believe a separate process (at least it is on android - I confess ignorance on ios) so the main queue schedules the next work - which is the second call to execute javascript - and then it blows up?

I'm hand-waving here but the repro is clean - try it

**Comment by cristianoccazinsp** [comment]
You are right, I totally overlooked the fact that there's also a webview involved! So although the initial RN call doesn't run in parallel, it may still run like that in the web view.

Just trying to learn a bit more about iOS, not an expert neither, and it this seemed interesting.

**Comment by mikehardy** [comment]
this is definitely the nitty gritty. Also a great example of the pathetic apple documentation (just being honest). Google for WkErrorDomain and check the official API doc. :disappointed:

**Comment by charlyBerthet** [comment]
FYI I cannot repro with:
```
System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 571.01 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /opt/local/bin/node
    Yarn: 1.16.0 - /opt/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.3 => 0.61.3
```
I tried library version: 3.0.0 and 5.X.X

From fresh react repo:
```
componentDidMount() {
    DeviceInfo.getUserAgent().then(i => this.setState({UserAgent: i})).catch(e => console.warn(e));
    DeviceInfo.getUserAgent().then(i => this.setState({UserAgent: i})).catch(e => console.warn(e));
    DeviceInfo.getUserAgent().then(i => this.setState({UserAgent: i})).catch(e => console.warn(e));
}
```

I only got warnings
`WARN  [Error: The WKWebView was invalidated]`

**Comment by romainbraun** [comment]
Any news regarding this issue?

**Comment by mikehardy** [comment]
None sorry - non open source work has been hopping for me the last few months so my queue is pretty deep at the moment, no one has proposed a PR, and it's (to me) a rare corner case based on interest here (small, though I understand it's important to the interested parties) vs user base (massive). I'm open to solutions but won't have time do anything myself for a while

**Comment by elashpear** [comment]
The user agent shouldn't really change at runtime, right? Could you just make this module check once during main queue setup and cache the value so it can be accessed synchronously?

**Comment by mikehardy** [comment]
"during main queue setup" - would that add to app startup time? This method was by far the slowest method in the library and kicked off much of the async/sync/constants ruckus

Regardless, the problem is - if I understand correctly - two calls going in to the native code at the same time and racing somehow. Some sort of synchronization / mutex to stop that from happening and cache the result seems like a reasonable way to repair it

**Comment by elashpear** [comment]
Yes that sounds like a good idea if there is noticeable performance overhead.

**Comment by mikehardy** [comment]
it was more than a second in some situations (!)

**Comment by lbelavoir** [comment]
Any way to bypass this issue ?

**Comment by mikehardy** [comment]
We don't have a solution yet that avoids the problem at the lower layers, so you'll need to make sure that only one caller ever goes into the code path at once, using some sort of exclusive calling mechanism in your app.

For me I use ReSub which is sort of like redux, and I have one service that populates all my device info, with consumers asking that service for info. That service gates access the API, and triggers a state update when it's done so everyone that wanted it gets the value (but only the service goes and does it)

Not the most ideal - ideal is to never ever crash of course - but most state management solutions should allow for the pattern?

**Comment by RoJoHub** [comment]
@cormander  @mikehardy
The reason is that wkwebview is released abnormally by apple
So,I can do

```diff
@implementation RNDeviceInfo
{
-    #if !(TARGET_OS_TV)
-    WKWebView *webView;
-    #endif
    bool hasListeners;
}

RCT_EXPORT_METHOD(getUserAgent:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject) {
#if TARGET_OS_TV
    reject(@"not_available_error", @"not available on tvOS", nil);
#else
    
    __weak RNDeviceInfo *weakSelf = self;
    dispatch_async(dispatch_get_main_queue(), ^{
        __strong RNDeviceInfo *strongSelf = weakSelf;
        if (strongSelf) {
+            // Save WKWebView (it might deallocate before we ask for user Agent)
+      __block WKWebView *webView=[[WKWebView alloc] init];
-      strongSelf->webView = [[WKWebView alloc] init];
+            [webView evaluateJavaScript:@"window.navigator.userAgent;" completionHandler:^(id _Nullable result, NSError * _Nullable error) {
-             [strongSelf->webView evaluateJavaScript:@"window.navigator.userAgent;" completionHandler:^(id _Nullable result, NSError * _Nullable error) {
                if (error) {
                    reject(@"getUserAgentError", error.localizedDescription, error);
                    return;
                }
                resolve([NSString stringWithFormat:@"%@", result]);
                // Destroy the WKWebView after task is complete
                webView = nil;
            }];
        }
    });
#endif
}
```
