### ISSUE TITLE
Sync API: undefined is not an object (evaluating 'N.startsWith')

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-community/react-native-device-info#780]
# Bug

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 1.59 GB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
```

Library version: 3.0.0

## Steps To Reproduce
Getting the above error on some devices while on production and using the sync API.

My code:
```_deviceString = `${DeviceInfo.getBrandSync()};${DeviceInfo.getModelSync()};${DeviceInfo.getUniqueIdSync()}`;```

The error:
```
Error · Failed to get device string: undefined is not an object (evaluating 'N.startsWith')
```

Device:
```
osName iOS
osVersion 12.4.1
iPad Mini (5 Gen)
```

Any ideas?

**Comment by rbscott** [comment]
It looks like this isn't actually a race condition. The issue is that the variable `device` isn't initialized until you call `getDevice` or `getDeviceSync`. This means if you call `getModel` before calling one of those two methods, the whole thing crashes. This only happens on devices that are not inside of `deviceNamesByCode`. Currently for instance, `iPad11,3` isn't in that list, so if you launch on the _iPad Air 3rd gen_ in the simulator an app will instantly crash.

**Comment by mikehardy** [comment]
Very interesting - thanks for the extra information. I'm staring at the getModelSync() method right now and I can't see how it could crash but I'm must be missing something obvious, I suppose I'll see with your PR :-)

https://github.com/react-native-community/react-native-device-info/blob/master/deviceinfo.js#L568

**Comment by cristianoccazinsp** [comment]
Awesome!

**Comment by mikehardy** [comment]
it's out in 3.1.2 already :muscle:
