### ISSUE TITLE
Documentation for getDeviceType missing .then()

### ISSUE THREAD

**Issue by Krayen** [react-native-community/react-native-device-info#782]
Not sure this is the way to go about it regarding documentation issues, but I found a small thing, which I hastily ran into when lazily copy/pasted it and then wondered why it was not working as expected :) 

**getDeviceType()**
Returns the device's type as a string, which will be one of:

- Handset
- Tablet
- Tv
- Unknown

**Examples**
```
DeviceInfo.getDeviceType(type => {
  // 'Handset'
});
```

should be:

```
DeviceInfo.getDeviceType().then(type => {
  // 'Handset'
});
```

**Comment by mikehardy** [comment]
funny - regarding the copy/paste error, and sorry the doc isn't up to date. For doc stuff github is actually fantastic about letting you just hit the edit button and auto-creating a fork/branch for the patch so you can make a pull request easily. Then you get internet fame and credit for the fix in the commit history :-). Give it a shot!

**Comment by mikehardy** [comment]
it even proposes (after it's merged) to delete the branch and then if no other PRs are open, the fork, to keep your github account nice and clean)

**Comment by Krayen** [comment]
Thanks for the info! Closing
