### ISSUE TITLE
_reactNativeDeviceInfo.default.getUniqueID is not a function

### ISSUE THREAD

**Issue by Sleepful** [react-native-community/react-native-device-info#785]
# Bug

_reactNativeDeviceInfo.default.getUniqueID is not a function

Library version: 3.0.0

## Steps To Reproduce

just use DeviceInfo.getUniqueID() in your app

## Workaround

Downgrading:

`yarn add react-native-device-info@2.3.2 `

**Comment by mikehardy** [comment]
The name of the method changed, please see the migration guide https://github.com/react-native-community/react-native-device-info/wiki/V2-to-V3-Migration-Guide

**Comment by akhilsanker** [comment]
Still facing issue.
"react-native-device-info": "2.3.2",

**Comment by mikehardy** [comment]
That version is old and I will not troubleshoot it, sorry. The migration guide and the docs contain how to do it for the current release. If you need information on older releases you will have to ask github to show you the code for older releases then look at the docs https://github.com/react-native-community/react-native-device-info/tree/v2.3.2

**Comment by NeerajaaG** [comment]
you can use getUniqueId instead of getUniqueID

**Comment by mikerodham** [comment]
Still getting the same issue `^5.3.1`, calling `DeviceInfo.getUniqueId().then(uid => info.uid = uid)`

**Comment by NeerajaaG** [comment]
Try this

import DeviceInfo from 'react-native-device-info';
constructor(props)
   {
      super(props);
      this.state = {
         deviceId:''
       };
    }
getId()
{
         var id = DeviceInfo.getUniqueId();
           this.setState({ deviceId: id, });
          console.log("Device Id",this.state.deviceId)
}
Thanks
G.Neeraja

**Comment by alexsanderlauffer** [comment]
> you can use getUniqueId instead of getUniqueID

This work for me!!

**Comment by dhruvkumarsood** [comment]
Use getUniqueI**d** insted of getUniqueI**D** . It will work.
