### ISSUE TITLE
RN 0.59.10 - error while converting to cocoapods dependency in IOS 

### ISSUE THREAD

**Issue by mailyokesh** [react-native-community/react-native-device-info#786]
# Bug

I have been using this library for over a year with dependency directly part of xcode project. Now we are changing to cocoapods due to a requirement of third party vendor library. I have tried the instructions for using this library with cocoa pods with RN 0.59.10 but none of them solved my issue. Also I have looked through the issue for similar issue but none of them solves my issue. Also currently I cannot migrate to RN 0.60.5 since one of our dependency has a need to use_frameworks from podFile which is not supported in RN 0.60.5. So am in the middle where we have deep dependency with react native device info library.

 I get one of the following error
1. If my move my podfile out and do react-native link react-native-device-info, i get 'React/RCTUtils.h' file not found. Below is a screenshot of how this dependency is with respect to pod file
![image](https://user-images.githubusercontent.com/12601748/64899646-0d481180-d652-11e9-9deb-cd8f81dfaa2f.png)

2. If I use the dependency through pod file by uncommenting the line from PodFile and then do pod install I get a run time error. 

## Environment info

React native info output:

```bash
 React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 3.53 GB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.10.1 - /usr/local/Cellar/node/11.10.1/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 22, 23, 25, 26, 27, 28
        Build Tools: 22.0.1, 23.0.1, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.3, 27.0.3, 28.0.3
        System Images: a... | Intel x86 Atom_64, a...google_apis | Google APIs Intel x86 Atom Sys..., a...gle_apis | Google APIs Intel x86 Atom_64 ..., a...google_apis | Google APIs Intel x86 Atom Sys..., a...google_apis | Google APIs Intel x86 Atom Sys..., a...s_playstore | Google Play Intel x86 Atom Sys...
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.10 => 0.59.10
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.2.2
      svg-to-react-native-cli: 0.0.3
```

Library version: "react-native-device-info": "^3.0.0"

PodFile
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

# ignore all warnings from all pods
inhibit_all_warnings!

plugin 'cocoapods-art', :sources => [
  'master',
  'mobile-sdk-ios'
]

target 'MyProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTImage',
    'RCTAnimation',
    'RCTCameraRoll',
    'RCTPushNotification',
    'RCTActionSheet',
    'RCTBlob',
    'RCTGeolocation',
    'RCTLinkingIOS',
    'RCTSettings',
    'RCTVibration'
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-fast-image', :podspec => '../node_modules/react-native-fast-image'
  pod 'BVLinearGradient', :podspec => '../node_modules/react-native-linear-gradient'
  pod 'RNVectorIcons', :podspec => '../node_modules/react-native-vector-icons'
  pod 'react-native-video', :podspec => '../node_modules/react-native-video'
  pod 'react-native-splash-screen', :podspec => '../node_modules/react-native-splash-screen'
  pod 'RNSound', :podspec => '../node_modules/react-native-sound'
  pod 'react-native-image-picker', :podspec => '../node_modules/react-native-image-picker'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'react-native-orientation-locker', :podspec => '../node_modules/react-native-orientation-locker'
  pod 'lottie-ios', :podspec => '../node_modules/lottie-ios'
  pod 'lottie-react-native', :podspec => '../node_modules/lottie-react-native'
  pod 'BugsnagReactNative', :podspec => '../node_modules/bugsnag-react-native'
  pod 'react-native-webview', :podspec => '../node_modules/react-native-webview'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'react-native-uuid-generator', :path => '../node_modules/react-native-uuid-generator'
  pod 'react-native-clear-app-cache', :path => '../node_modules/react-native-clear-app-cache'
  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios/RNCPushNotificationIOS.podspec'

  pod 'SwiftLint'
  pod 'react-native-bluetooth-status', :path => '../node_modules/react-native-bluetooth-status'

  pod 'react-native-connectivity-status', :path => '../node_modules/react-native-connectivity-status'

  # pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

end

pre_install do |installer|
	installer.analysis_result.specifications.each do |s|
    s.swift_version = '5.0'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

**Comment by mikehardy** [comment]
I don't know - if I were you I would move to the react-native 0.61 release candidates. they are getting close to being final (next week?), and it works with use_frameworks so you aren't in this mess. Requiring use_frameworks to work is basically a show-stopper that isn't going to work for you until 0.61

**Comment by mailyokesh** [comment]
thanks @mikehardy little iffy going to rc version of react native for our production app. if rn 0.61.0 is close to getting release next week then its fine. I wasnt sure when the release dates were. Thanks for the update.

**Comment by mikehardy** [comment]
Well things can always change, and normally I would never recommend an RC except just to play around, but use_frameworks is a big deal - it is just broken in < 61. I guess worst case you can try it (really quickly - it's not a painful upgrade like 59->60, upgrade-helper site already has the RCs), and if that doesn't just untangle everything for you I can look more closely

**Comment by mikehardy** [comment]
Oh - and also worth noting that I never used a Podfile for react-native-device-info with RN0.59, if you determine that version is better for your needs, then focus on getting the link to work while your Podfile is out of the way (move Podfile, link, move Podfile back)

**Comment by mikehardy** [comment]
I've just got the RN59 script working again, it shows that it is possible and for older versions that's the most time I've got available for support, I do hope it helps
