### ISSUE TITLE
README: There is no need to use promises

### ISSUE THREAD

**Issue by matinzd** [react-native-community/react-native-device-info#788]
As you said in README there is no need to use promises for getting those values I think!

**Comment by Johan-dutoit** [comment]
Can you elaborate on what you mean/what you think the issue is?

**Comment by matinzd** [comment]
> Can you elaborate on what you mean/what you think the issue is?
It is not an issue but it confuses.

**Comment by Johan-dutoit** [comment]
The library recently underwent a transformation, which introduced promise based API's (see: https://github.com/react-native-community/react-native-device-info/pull/760).  This would improve startup time, etc.

That being said, if you don't want to use the promise based API's, then you are able to use synchronous variants i.e. `xxxSync()`.  However, there is a known issue with using the synchronous API's (see: https://github.com/react-native-community/react-native-device-info/issues/776).
