### ISSUE TITLE
can not compile android with RN0.59 and rn-device info 3.1.1

### ISSUE THREAD

**Issue by maxkomarychev** [react-native-community/react-native-device-info#789]
# Bug

The app with rn0.59 is not compileable for android

```
/****/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:34: error: cannot find symbol
import androidx.annotation.Nullable;
                          ^
  symbol:   class Nullable
  location: package androidx.annotation
/****node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:916: error: cannot find symbol
                         @Nullable Object data) {
                          ^
  symbol:   class Nullable
  location: class RNDeviceModule
Note: /****/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
3 warnings
```

## Environment info

1.
2.
...

Describe what you expected to happen:

1.
2.

**Comment by Johan-dutoit** [comment]
Read the readme.

**Comment by maxkomarychev** [comment]
🤦‍♂ apologies. thanks!

**Comment by maxkomarychev** [comment]
ok actually it's not quite clear how to use this section: https://github.com/react-native-community/react-native-device-info#androidx-support

my host android project is not yet updated for android target sdk 28, is there a way to get it compiled with rn-device-info 3.1.1 ?

**Comment by mikehardy** [comment]
I think so? https://github.com/mikehardy/jetifier#to-reverse-jetify--convert-node_modules-dependencies-to-support-libraries

**Comment by mikehardy** [comment]
...but you are straddling a tough divide. It might be time... :-)

**Comment by mikehardy** [comment]
only a month and a half left for updates even: https://developer.android.com/distribute/best-practices/develop/target-sdk

**Comment by maxkomarychev** [comment]
@mikehardy ok fair point. thanks a lot!

**Comment by CptFabulouso** [comment]
Iam having this problem and I think I have build.gradle setup right?
I am using `googlePlayServicesVersion = "16.0.0"` because of https://github.com/react-native-community/react-native-device-info/issues/802
```
buildscript {
    ext {
        googlePlayServicesVersion = "16.0.0"
        buildToolsVersion = "28.0.3"
        minSdkVersion = 19
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.0'
        classpath 'com.google.gms:google-services:4.2.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```

also I think  these two values in the readme
```
compileSdkVersion = "28" // default: 28 (28 is required for AndroidX)
targetSdkVersion = "28" // default: 28 (28 is required for AndroidX)
```
 should be numbers and not strings
```
compileSdkVersion = 28 // default: 28 (28 is required for AndroidX)
targetSdkVersion = 28 // default: 28 (28 is required for AndroidX)
```

**Comment by Jaessun** [comment]
Same issue for me. I'm using RN 0.59.10, react-native-device-info 3.1.4 and my `targetSdkVersion` is 28.
And I am using `googlePlayServicesVersion = "16.0.0"` because of #802 too. Maybe that's the real issue ?

**Comment by mikehardy** [comment]
could be @Jaessun and @CptFabulouso - I intended to troubleshoot this today but the refresh-example-rn59.sh script is no longer working owing to some changes in the underlying react-native-community/cli package so I'm having a hard time reproducing. First step is to get the example re-building for rn59 then I/we can say for sure

**Comment by maxkomarychev** [comment]
just to close the loop on this issue, maybe helpful to someone else:

1. I did automatic migration to android x in android studio
2. I added `npx jetify` in `postinstall` in package.json.

**Comment by Jaessun** [comment]
I found a workaround for the issue, my app now builds and works after adding the following in `android/gradle.properties` :
```
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by mikehardy** [comment]
Please note that is step 1 of the associated documentation - https://github.com/mikehardy/jetifier#to-jetify--convert-node_modules-dependencies-to-androidx - putting that there so people don't forget that it is well documented but very very detail oriented

**Comment by mikehardy** [comment]
I've just got the RN59 example script working again if you want to clone it and see how exact steps showing how to get current release (4.0.1-beta.3 at time I write this) working with RN59

**Comment by mklb** [comment]
Had problems with this as well using:

react-native-device-info: "^5.5.1"
react-native": "0.61.5"

I fixed it with the code below. What really made the change was that I set the `minSdkVersion` to 28 as well. (It was 16 bevore):

```
ext {
        googlePlayServicesIidVersion = "17.0.0"
        compileSdkVersion = 28 // default: 28 (28 is required for AndroidX)
        targetSdkVersion = 28 // default: 28 (28 is required for AndroidX)
        minSdkVersion = 28
    }
```

**Comment by mikehardy** [comment]
@mklb that's terrible advice. The library works fine down to minSdk 16, and I'm sure you've got users that are on APIs lower than 28?

**Comment by mklb** [comment]
I am porting an app to android so there is no "old userbase". I can see your point but somehow this did the trick to compile ¯\_(ツ)_/¯ so I shared it. Did not try any numbers between 16 and 28 though. But 16 did not work for me.

**Comment by mikehardy** [comment]
I believe you are misunderstanding what minSdk does. It does not mean you are orphaning an existing set of users. It means no new user with an even barely-old (one year) phone can use your app. Seems like a bad decision to me, but it's your app

**Comment by mklb** [comment]
I just looked up the adoption rate of the API levels.. I am a bit shocked coming from the iOS world where the adoption of the latest OS is so much higher. BTW: Bought a 1 year old Android Nokia phone for 120$ (new) and it runs already Pie (28). But yeah 28 as a minimum is nothing good. Thanks!

**Comment by mikehardy** [comment]
Closed system vs open system, they are totally different worlds. Closed has some terrible aspects to it but with control of the hardware Apple does get the updates out on the devices, which is nice. My biggest Android app still supports down to API15 and has more than a thousand users on that API level. It is shocking :-)
