### ISSUE TITLE
getUniqueId - Different values after re-install?

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-community/react-native-device-info#790]
# Question

I'm wondering if it is possible to get an actual real device ID (I would guess something like the phone's IMEI). As it is right now, getUniqueId doesn't seem to be that unique at all and will also be different after each reinstall.

**Comment by mikehardy** [comment]
No. What you want (a real device ID) is the root of all the privacy problems everyone has had for the last few years. A real device ID enabled completely persistent tracking.

So all of those IDs are available in the past, and all are restricted now.

Search around for discussions on (and API / return value) the android Build.SERIAL value for instance. Or the various mechanisms in iOS.

You can't even get a MAC address anymore

**Comment by cristianoccazinsp** [comment]
So how unique is the ID returned by getUniqueId? It would be good to have
better info about how unique it is, does it survive app updates? Does it
survive phone restarts, phone updates? Not complaining or anything, just
want to know the scope of it so code that uses that value can behave
accordingly.

My real use case is really detecting whether or not a user uses the same
account on more than two devices at the "same time" or close in time.

**Comment by mikehardy** [comment]
If you have professional-grade needs, I can only recommend code inspection and documents:

https://github.com/react-native-community/react-native-device-info/blob/master/deviceinfo.js#L350

https://github.com/react-native-community/react-native-device-info/blob/master/deviceinfo.js#L350

https://developer.android.com/reference/android/provider/Settings.Secure#ANDROID_ID

For android anyway. iOS may be different.

There is also instance ID but it is limited to people with play services (so, no China users, e.g.) https://github.com/react-native-community/react-native-device-info/blob/master/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L763

I won't comment further as this specific area of the mobile ecosystem moves quickly in response to any new scandal and the vendors are racing each other to change it each platform release (android or ios version) - you have to be very careful and stay tuned.

Also, to work around the whole thing and provide stable guarantees you might look at our issues list (and a PR even, not merged yet, I think) where we intend to make a new API that scraps the whole idea and just generates a GUID on first app run and uses local storage. However with that we'll likely have to also have a "delete that GUID" method and if you use it you'll have to attest to the App Store etc that you respect privacy preferences by deleting that identifier if users want to be forgotten.
