### ISSUE TITLE
How to get DeviceCountry?

### ISSUE THREAD

**Issue by leon2835** [react-native-community/react-native-device-info#792]
Hi there, since version3.0 removed is24Hour, getTimezone, isAutoTimeZone and isAutoDateAndTime, getDeviceLocale, getDeviceCountry, getPreferredLocales. How am i suppose to get device country as well? Thank You.

**Comment by Taym95** [comment]
Hey, you can check the [CHANGELOG](https://github.com/react-native-community/react-native-device-info/blob/master/CHANGELOG.md):

BREAKING CHANGE: remove is24Hour, getTimezone, isAutoTimeZone and isAutoDateAndTime, getDeviceLocale, getDeviceCountry, getPreferredLocales
This was the result of a survey. It removes API duplication in the react-native-community modules its part of [react-native-localize](https://github.com/react-native-community/react-native-localize).

**Comment by leon2835** [comment]
Thank You. I miss out that.
