### ISSUE TITLE
NativeModule.RNDeviceInfo is null on sdk-34

### ISSUE THREAD

**Issue by selvassn** [react-native-community/react-native-device-info#795]
Dear all,

I have created a new RN expo project and included deviceinfo package into that and ran the `react-native link react-native-device-info`. I am facing the issue NativeModule.RNDeviceInfo is null. How can i resolve it. 

**Package.Json:**
`{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "accounting": "^0.4.1",
    "buffer": "^5.4.2",
    "cheerio": "^1.0.0-rc.3",
    "events": "^3.0.0",
    "expo": "^34.0.1",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-device-info": "^3.1.3",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-inappbrowser-reborn": "^3.0.1",
    "react-native-web": "^0.11.4",
    "react-native-webview": "^7.0.1",
    "react-navigation": "^3.11.0",
    "stream": "0.0.2",
    "superagent": "^5.1.0",
    "util": "^0.12.1",
    "xtend": "^4.0.2"
  },
  "devDependencies": {
    "babel-preset-expo": "^6.0.0"
  },
  "private": true
}
`

**Comment by mikehardy** [comment]
Expo does not work with native modules.
https://docs.expo.io/versions/latest/introduction/why-not-expo/
