### ISSUE TITLE
getReadableVersion causes runtime exception for react-native-web projects

### ISSUE THREAD

**Issue by tvanlaerhoven** [react-native-community/react-native-device-info#796]
# Bug

When calling getReadableVersion() or getReadableVersionSync() from a react-native-web platform, an exception is thrown because undefined functions RNDeviceInfo.getAppVersion() and RNDeviceInfo.getBuildVersion() are called. 
Other DeviceInfo methods are correcly guarded by a platform check.

## Environment info

```bash
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 34.84 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.14.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.2, 25.0.0, 25.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.0
      System Images: android-19 | Google APIs Intel x86 Atom, android-22 | Android TV Intel x86 Atom, android-22 | Intel x86 Atom_64, android-22 | Google APIs Intel x86 Atom, android-24 | Android TV Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-27 | Android TV Intel x86 Atom, android-28 | Android TV Intel x86 Atom
      Android NDK: 15.2.4203891
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native-tvos:  0.60.4-6 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    create-react-native-tizen-app: 0.0.1
    react-native-cli: 2.0.1
    react-native-device-info: 0.24.3
    react-native-fast-image: 5.1.2
    react-native-firebase: 5.2.0
    react-native-git-upgrade: 0.2.7
    react-native-keep-awake-tvos: 2.0.4
    react-native-screens: 1.0.0-alpha.22
```
Library version: 3.1.3

## Steps To Reproduce

Create a react-native-web project and request `await DeviceInfo.getReadableVersion()` results in: 
```
Uncaught (in promise) TypeError: o.getAppVersion is not a function
```
No exception should be thrown.

## Reproducible sample code

Run this from a react-native-web project:
```
import DeviceInfo from 'react-native-device-info';
const deviceVersion = await DeviceInfo.getReadableVersion();
```

**Comment by Johan-dutoit** [comment]
Having a brief look at the code, I can see why the problem exists.

In my opinion, `getReadableVersion` & `getReadableVersionAsync` should use the wrapped (read JS) variants, which has the guards in place.

i.e. changing

`return (await RNDeviceInfo.getAppVersion()) + '.' + (await RNDeviceInfo.getBuildNumber());`

to 

`return (await getVersion()) + '.' + (await getBuildNumber());`

**Comment by mikehardy** [comment]
Interesting - try v3.1.4 - I'm not sure an unknown.unknown is better or worse than an unknown but I chose to close it that way by chaining through JS

**Comment by mikehardy** [comment]
(because this shouldn't really be called via web anyway - web is effectively unmaintained and just there as a polyfill so it doesn't crash for people, but no one has stepped up to actually do anything with it)

**Comment by mikehardy** [comment]
And @Johan-dutoit you are on it! :-) :-)

**Comment by tvanlaerhoven** [comment]
I added a PR that adds a platform check. As all other methods includes such a check, I assume it's better to add it here and return an 'undefined' instead of 'undefined.undefined'.
