### ISSUE TITLE
Could not find com.google.android.gms:play-services-iid:16.1.0.

### ISSUE THREAD

**Issue by grit96** [react-native-community/react-native-device-info#802]
In commit ea570d2bbe26b631681bfcc0572d71cc14a7c186, the gradle dependency `play-services-gcm` was swapped to `play-services-iid` but still uses `googlePlayServicesVersion` to determine the package version.

This causes a problem `play-services-gcm` and `play-services-iid` versions differ.

See extract below from https://dl.google.com/dl/android/maven2/index.html:

```
play-services-gcm
16.0.0
16.1.0
17.0.0

play-services-iid
16.0.0
16.0.1
17.0.0
```

`16.1.0` in `play-services-gcm`, but `16.0.1` in `play-services-iid`.

So by setting `googlePlayServicesVersion` to `16.1.0` for pre-AndroidX (as per the README), it actually breaks the Android build with `Could not find com.google.android.gms:play-services-iid:16.1.0.`

**Comment by grit96** [comment]
As a workaround I am now setting `googlePlayServicesVersion` to `16.0.0`

**Comment by mikehardy** [comment]
Very interesting - a more precise patch (which I'll commit later) will be to first check for googlePlayServicesIidVersion first (from the ext{} block in your android/build.gradle) and then fall back to googlePlayServicesVersion.

That will allow more precise control but not break installed base

Sorry it caused you to step back in versions

**Comment by mikehardy** [comment]
@Johan-dutoit I'm going to do a 4.0.2 that has a fix for this once you've settled #801

**Comment by mikehardy** [comment]
Okay the PR is ready - should merge soon. The chunk you want (if you want to use patch-package until it's merged+released is https://github.com/react-native-community/react-native-device-info/pull/804/files#diff-7ae5a9093507568eabbf35c3b0665732R46 )

**Comment by beisert1** [comment]
We upgraded to react native 0.60.5 and updated this package from 0.21.5 to 3.1.4 and we are getting this "Could not find com.google.android.gms:play-services-iid:16.1.0" error.

Any update on when this fix will be officially released?

**Comment by mikehardy** [comment]
Sorry - we're blocked on release for a moment while we ingest a conversion to typescript #144 and work through #776 - this one is a really trivial patch and I would use patch-package without delay so you are unblocked

**Comment by mikehardy** [comment]
released as `@next` on NPM or 4.0.1-beta.2

**Comment by Maushundb** [comment]
I'm getting this also on 5.3.0, is this expected?

**Comment by Maushundb** [comment]
For posterity, adding `googlePlayServicesIidVersion = "16.0.1"` in `android/build.gradle` seems to have fixed it:
```
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28

        googlePlayServicesVersion = "16.1.0" // default: "+"
        googlePlayServicesIidVersion = "16.0.1"
        firebaseVersion = "15.0.2" // default: "+"

    }
    ...
}
```
