### ISSUE TITLE
getUniqueID Not Same If Difference Application

### ISSUE THREAD

**Issue by dhamdani666** [react-native-community/react-native-device-info#803]
# Bug

Hi , how to create unix code using getUniqueID same if difference application but on the same device

sample :
if i'm using device xiaomi redmi 4 and difference application unix code remains the same ,
is it possible ? because for this unix code not same and i want unix code same but difference application.
because if i'm using getAndroidId() this function not support for IOS

thanks

**Comment by mikehardy** [comment]
What you want is what the manufacturers specifically don't want.

This library sits on the borderline between getting info, and violating privacy by allowing tracking. It's not our intention to circumvent the privacy protections put in place by the various vendors.

It is your responsibility to develop solutions that let you responsibly identify users while respecting platform limits and user choices, and keeping up with changes in the platforms.

I don't mean to be rude but I will be direct - you have to do this research yourself
