### ISSUE TITLE
目前项目未升级到Andridx,怎样拉取升级至Androidx之前的版本呢？谢谢！

### ISSUE THREAD

**Issue by joelany** [react-native-community/react-native-device-info#809]
# Question

**Comment by Johan-dutoit** [comment]
I translated it to english, and I got the following, which is somewhat a confusing question:

> Currently the project has not been upgraded to Andridx, how to pull the upgrade to the version before Androidx? Thank you!

You can setup `[jetifier](https://github.com/mikehardy/jetifier)`, to either upgrade everything to AndroidX or to 'downgrade' everything to pre-AndroidX (aka support libraries).

Let me know if this answers your question.

**Comment by joelany** [comment]
I want to be downgraded to the previous version of AndroidX, but I don't quite understand the downgrading process. Ask for advice! Thank you

**Comment by joelany** [comment]
The error message is as follows:
Manifest merger failed : Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86
	is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:7:5-117 to override.

**Comment by 7laria** [comment]
same issue

**Comment by mikehardy** [comment]
AndroidX issues are outside the scope of this package. They are difficult and incredibly project specific, we won't troubleshoot them here.

The jetifier package is what you want, in either forward or reverse mode depending on your needs

**Comment by whenmoon** [comment]
I am also getting this error and don't know how to fix it. I don't want to use jetifier.

**Comment by mikehardy** [comment]
"I don't want to use jetifier". Then you don't want to solve your problem. Make sure you only use outdated versions of all your libraries and dependencies. But please don't post here.

**Comment by KingAmo** [comment]
@mikehardy 
 i am using `react native 0.59.10` and facing `Manifest merger failed` when build release apk ,
as jetifier [troubleshooting](https://github.com/mikehardy/jetifier#troubleshooting) says:
> You have a dependency that packages things in violation of Android packaging rules, like including an extra AndroidManifest.xml or similar: https://github.com/acaziasoftcom/react-native-bottomsheet/pull/23 - this will lead to dex merger issues about duplicate entries. Open pull requests with the libraries that do this.

but i see `react-native-device-info` do have a `AndroidManifest.xml` file
![image](https://user-images.githubusercontent.com/29938227/71612656-bfddb900-2bdc-11ea-989a-296369fe7462.png)

could you please  help me?

**Comment by mikehardy** [comment]
Sure, and having that file is not a problem. But if you have an incomplete AndroidX transition in your project or something then your build can fail. That's a project-specific problem and I can't really troubleshoot it sorry. Just carefully examine your project and it's AndroidX status and use jetifier correctly either in forward or reverse mode and it will work.

**Comment by KingAmo** [comment]
@mikehardy  i use `jetifier` in my project and run `npx jetify -r`  and then build apk and meet  `Manifest merger failed`

**Comment by mikehardy** [comment]
@KingAmo it is futile, in my opinion, to avoid AndroidX as you are attempting with the jetifier reverse mode. Go forward -> use Android Studio to convert to AndroidX and use jetifier in forward mode, it is a new decade after all ;-)

**Comment by TylerPin** [comment]
I fixed it by adding in build.gradle
`buildscript {
    ext {
        ....

        // these were added so third party libs do not use androidx dependencies for these, might need others
        googlePlayServicesVisionVersion = "17.0.2"
        googlePlayServicesVersion = "16.+"
        firebaseVersion = "17.3.4"
    }`
https://github.com/react-native-community/react-native-netinfo/issues/107#issuecomment-503651116
