### ISSUE TITLE
rename getCameraPresence() to isCameraPresent()

### ISSUE THREAD

**Issue by ethanneff** [react-native-community/react-native-device-info#810]
All other `boolean` endpoints are prefixed with `is` or `has`. `getCameraPresence()` is the only one that is not prefixed.

https://github.com/react-native-community/react-native-device-info#api

**Comment by mikehardy** [comment]
Quite true - the breaking changes boat for v4 has sailed, so this will have to sit for the next round as I'd like to let v4 settle in the userbase for a little bit, it's still on the beginning of the adoption curve I believe.
