### ISSUE TITLE
getDeviceCountry() is not working in latest version. How to find Device Country and Locale in the latest version?

### ISSUE THREAD

**Issue by shivamtiwari8736** [react-native-community/react-native-device-info#815]
getDeviceCountry() is not working in the latest version. It is showing undefined. I checked inside library but didn't find such method. Is it removed? If yes then what is the alternate to find current country of the device?

**Comment by Johan-dutoit** [comment]
https://github.com/react-native-community/react-native-device-info/blob/master/CHANGELOG.md#300-beta1

**Comment by shivamtiwari8736** [comment]
Thanks @Johan-dutoit

**Comment by Brad19** [comment]
@Johan-dutoit . Thanks for the update. I see that getDeviceCountry() and getDeviceLocale() has been removed from 3.0.0-beta.1.  But just wanna know what is alternative that is widely prevailing. Please advise.

**Comment by mikehardy** [comment]
@Brad19 thanks for the update...from September last year 😮 - I think you want the migration guides linked at the top of the readme? They explain all (or should)
