### ISSUE TITLE
Not satisfied about the v3.0 release

### ISSUE THREAD

**Issue by Fantasim** [react-native-community/react-native-device-info#816]
Hi,

I just leave this "issue" which is not really one, just to give a feedback of the new release that in my opinion brings to much complexity in the using of the library.
Even if the library is well developed and is really clear for its using, I think it's a very bad choice to have put all the values accessible through a promise especially at the launch on the app when many constants in an app depend on a simple value which is always the same (example: hasNotch() and many others).

This single update just broke the working processes of my entire app and I had no other choice than downgrading to the 2.3.4 version.

I really hope that the contributors will fix this in the future and realize that a constant value doesn't have to be called with a promise, it's a non-sense.

Thank you.

**Comment by mikehardy** [comment]
Use the sync APIs

And if you still want to use the chrome debugger maybe wait a week and this #776 will be sorted out

But no whining.

**Comment by mikehardy** [comment]
Alternative to whining, read docs.

`If you must have a synchronous call (like during app bootstrap), use the parallel synchronous APIs labelled xxxSync()`

https://github.com/react-native-community/react-native-device-info/wiki/V2-to-V3-Migration-Guide

**Comment by Fantasim** [comment]
LOL.

@mikehardy I read it, and I also saw this line, but it changes nothing of what I said earlier.

```
This was required to improve module load speed, handle dynamic values, and release the main queue for iOS
```

1) I didn't notice a significant difference in performances with my app between the new and old version. At least when you improve the performances side make sure to not destroy the developer experience side, because it's exactly what happened. 
Example : When you create some constants you use in all your project based on the device informations, with async you can't delay the initial fetching of your project, because the main component (fetching itself others children components) will always be imported and fetched before the device information file.

So if you work by this method, that is simple, efficient and the most minimalist in term of code and scalability (avoinding importing react native device info everywhere), to adapt to the v3 you have to multiply your number of lines of code by many.


2) Split dynamic and static value, a static value doesn't need to have a promise, whatever it takes, it's fucking static.


3) Why close this so soon, don't you want to see if others persons are agree with this ? Why don't you let critics be expressed, even if you don't like the form.

**Comment by mikehardy** [comment]
No, I don't have time for whining. I await your pull requests with new and useful contributions

**Comment by Fantasim** [comment]
You call it whining, I call it debate.

**Comment by Fantasim** [comment]
You call it whining, I call it debate, that's what happens before any pull requests.

**Comment by mikehardy** [comment]
You will notice I have not locked the thread Louis. You may continue to demonstrate your debating skills for all of your future collaborators at your leisure.

**Comment by Fantasim** [comment]
But you closed it.

**Comment by mikehardy** [comment]
Haven't seen any good debate yet. I just see a failure to use the Sync API which handles your use case. So it is not actionable and it is closed. But please continue.
