### ISSUE TITLE
iOS - detect iPhone 11

### ISSUE THREAD

**Issue by LuongTruong** [react-native-community/react-native-device-info#818]
## Summary

|             |     |
| ----------- | --- |
| Version     | 2.1.2   |
| Affected OS | iOS   |
| OS Version  | 13.0   |

## Current behavior

When I use the getModel() function on the iPhone X, I am able to get the model "iPhone X". However, when I use it on the iPhone 11, the returned string is "iPhone" only.

## Expected behavior

I think it should be "iPhone 11"/"iPhone 11 Pro"/"iPhone 11 Pro Max"

If you know anyway to detect the iPhone 11, please let me know. Thank you!

**Comment by mikehardy** [comment]
https://github.com/react-native-community/react-native-device-info/pull/794
