### ISSUE TITLE
RNDeviceInfo is null

### ISSUE THREAD

**Issue by Miyaguisan** [react-native-community/react-native-device-info#819]
# Bug

Trying to run a clean project on Android causes the red error screen with the message:

```bash
Error: @react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null.
```

## Environment info

React native info output:

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 154.95 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.14.1 - ~/.nvm/versions/node/v10.14.1/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v10.14.1/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.14.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 26, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.1 => 0.61.1
```

Library version: 3.1.4

## Steps To Reproduce

1. create clean project with (RN 0.61.1):
```bash
react-native init test
```
2. yarn add react-native-device-info
3. cd ios && pod install && cd .. (with success message)
4. add code:
```bash
import DeviceInfo from 'react-native-device-info';
...
DeviceInfo.isTablet().then(isTablet => {
    console.log(isTablet);
});
```
5. Project presents red screen on Android.
6. Project runs just fine on iOS.

(Oddly enough, if I perform the manual linking steps [despite running RN0.61.1] the Android project runs fine then)

Describe what you expected to happen:

1. Both iOS and Android runs should fine and log wether if the device is a tablet or not.

**Comment by mikehardy** [comment]
Can you reproduce it by cloning this repo and running the example? Because I usually nuke + refresh the example programmatically each time and it runs fine...

https://github.com/react-native-community/react-native-device-info/blob/master/refresh-example.sh

**Comment by Miyaguisan** [comment]
Your example seems to run without problems.
I'll continue to investigate further.

Thanks for your time.

**Comment by sagargulati** [comment]
I'm still getting the issue and tried with refresh install, any help is appreciated.

**Comment by mikehardy** [comment]
@sagargulati you are getting the same issue, while attempting to reproduce with the example? Because so far the example seems to work, indicating the module works fine, so these are project integration issues (which are difficult to troubleshoot because each project is different...)

**Comment by gustavoisensee** [comment]
I'm getting the same issue, but running from xcode worked, when running from `react-native run-ios` it doesn't instance the object properly.

**Comment by sagargulati** [comment]
@mikehardy : Yes, similar, it shows me the same error in Android, haven't tested with iOS

**Comment by johnhiggs** [comment]
i'm also running into same bug iOS

**Comment by mikehardy** [comment]
posting me-toos does not work. I need someone to clone this repo, run the example, and tell me it does not work.

Here's what I did

```
git clone git@github.com:react-native-community/react-native-device-info.git
cd react-native-device-info
./refresh-example.sh
cd example
yarn ios
```

It works. Any evidence to the contrary I/we all over it. In the meantime, something is wrong with project integration at the project-specific level and that's not something we can control or even really troubleshoot effectively, which is why we provide not only an example but an example built by a script you may inspect to make sure you can reproduce actual example construction

I'm not sure what more I/we can do?

**Comment by johnhiggs** [comment]
Im having an issue trying to use a private repo with the new testing-library for react-native (.59)

My hunch is that if we can upgrade to .61 the issue will go away, ive tried performing manual link, xcode build, pod install etc

**Comment by cspicuzza** [comment]
@mikehardy I was having issues getting this package to work in Android with RN 0.61.0.  Which lead me to this issue page.

I tested the example project in both ios and android:
```
git clone git@github.com:react-native-community/react-native-device-info.git
cd react-native-device-info
./refresh-example.sh
cd example
yarn ios (yarn android)
```

Both are platforms are showing the following error:
```
TypeError: null is not an object (evaluating '_RNGestureHandlerModule.default.Direction')

<global>
    Directions.js:3:38
loadModuleImplementation
    require.js:322:6
<global>
    GestureHandler.js:2
loadModuleImplementation
    require.js:322:6
<global>
    Swipeable.js:10
loadModuleImplementation
    require.js:322:6
<global>
    index.js:1
loadModuleImplementation
    require.js:322:6
<global>
    index.js:1
loadModuleImplementation
    require.js:322:6
guardedLoadModule
    require.js:201:45
global code
    index.bundle?platform=ios&dev=true&minify=false:232245:4
```

**Comment by sagargulati** [comment]
Seems another major bug with AndroidX and GCM for device-info

![image](https://user-images.githubusercontent.com/2825887/66270056-c625f880-e86c-11e9-8e77-02e8147a21e8.png)

**Comment by mikehardy** [comment]
@sagargulati lacks any context details required to troubleshoot

I think what you are referring to is #802 fixed by #804 

released just now as `@next` on NPM or 4.0.1-beta.2

Use the new iid-specific version property in your android/build.gradle::ext{} block and you can specify IID and Play Services versions independently, as they are versioned separately in the AndroidX world (IID is at 17.0.0 while Play Services moved to 17.1.0), leading to this error

**Comment by miscel** [comment]
Same trouble! Does anyone know how to solve it?

Error: @react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null. To fix this issue try these steps:
  • For react-native <= 0.59: Run `react-native link react-native-device-info` in the project root.
  • Rebuild and re-run the app.
  • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
  If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-device-info

<global>
    nativeInterface.ts:20:10
loadModuleImplementation
    require.js:322:6
<global>
    index.ts:5
loadModuleImplementation
    require.js:322:6
<global>
    Login.js:12
loadModuleImplementation
    require.js:322:6
<global>
    route.js:5
loadModuleImplementation
    require.js:322:6
<global>
    App.js:3
loadModuleImplementation
    require.js:322:6
<global>
    index.js:6
loadModuleImplementation
    require.js:322:6
guardedLoadModule
    require.js:201:45
global code
    index.bundle?platform=ios&dev=true&minify=false:166842:4

**Comment by miscel** [comment]
> Same trouble! Does anyone know how to solve it?

Error: @react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null. To fix this issue try these steps:
• For react-native <= 0.59: Run react-native link react-native-device-info in the project root.
• Rebuild and re-run the app.
• If you are using CocoaPods on iOS, run pod install in the ios directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-device-info
nativeInterface.ts:20:10 loadModuleImplementation require.js:322:6 index.ts:5 loadModuleImplementation require.js:322:6 Login.js:12 loadModuleImplementation require.js:322:6 route.js:5 loadModuleImplementation require.js:322:6 App.js:3 loadModuleImplementation require.js:322:6 index.js:6 loadModuleImplementation require.js:322:6 guardedLoadModule require.js:201:45 global code index.bundle?platform=ios&dev=true&minify=false:166842:4

**Comment by mikehardy** [comment]
Here is how to integrate react-native-device-info with react-native <= 0.59, step by step: https://github.com/react-native-community/react-native-device-info/blob/master/refresh-example-rn59.sh

**Comment by fsobh** [comment]
> > Same trouble! Does anyone know how to solve it?
> 
> Error: @react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null. To fix this issue try these steps:
> • For react-native <= 0.59: Run react-native link react-native-device-info in the project root.
> • Rebuild and re-run the app.
> • If you are using CocoaPods on iOS, run pod install in the ios directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
> If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-device-info
> nativeInterface.ts:20:10 loadModuleImplementation require.js:322:6 index.ts:5 loadModuleImplementation require.js:322:6 Login.js:12 loadModuleImplementation require.js:322:6 route.js:5 loadModuleImplementation require.js:322:6 App.js:3 loadModuleImplementation require.js:322:6 index.js:6 loadModuleImplementation require.js:322:6 guardedLoadModule require.js:201:45 global code index.bundle?platform=ios&dev=true&minify=false:166842:4

same issue here

**Comment by lyudad** [comment]
Same issue

**Comment by mikehardy** [comment]
Any time you use a native module in react-native and you integrate it improperly, this will happen.
Always look for the example project in any native react-native module you use, and run it, to prove it works. Once you see it works, then if the module is null in your project you have a project-specific issue and you need to integrate it correctly.


My previous comment includes a script that shows how to do so
