### ISSUE TITLE
Which version is compatible with react-native 0.59.8

### ISSUE THREAD

**Issue by karimkhamwani** [react-native-community/react-native-device-info#820]

**Comment by mikehardy** [comment]
They both are. But we have AndroidX symbols in v3 so if you want to use it with react-native 0.59 you'll have to decide for yourself whether to convert to AndroidX or not and then act accordingly. That's out of scope for this project but the jetifier project has instructions for both cases https://github.com/mikehardy/jetifier

**Comment by mikehardy** [comment]
I've just got the RN59 example script working again if you want to clone it and see how exact steps showing how to get current release (4.0.1-beta.3 at time I write this) working with RN59
