### ISSUE TITLE
Crash when device brand undefined

### ISSUE THREAD

**Issue by Pingou** [react-native-community/react-native-device-info#821]
Hi guys, 
Thank you for this great library. I've noticed the app is crashing when launching from a generic Android simulator (API 19).
In v3.1.4 in deviceinfo.js, functions hasNotchSync() and hasNotch(), item.brand can be undefined, attempting to call toLowerCase() on it will produce the crash.
I am not 100% sure the bug is only limited to simulators, but I guess so.

**Comment by mikehardy** [comment]
"generic simulator" - what do you mean? By that I mean - with steps detailed enough that I could create a simulator and trigger the crash. And if you had a stack trace so I could make 100% sure that would help too

**Comment by Pingou** [comment]
By generic Simulator I meant a simulator that has no name (not Nexus, not Pixel, etc).
On Android Studio, create a simulator, for example I used 10.1 WXGA (tablet), set it to API 19, app crashes.

**Comment by mikehardy** [comment]
Using 4.0.1-rc.1 following your instructions I can no longer reproduce - hopefully fixed during the v3->v4 flux
