### ISSUE TITLE
canOverrideExistingModule = true ?

### ISSUE THREAD

**Issue by ozgunsandal** [react-native-community/react-native-device-info#823]
Hello,
React native gives me an error like this;

`Native module TimePickerAndroid tried to override com.facebook.react.modules.timepicker. TimePickerDialogModule. Check the getPackages() method in mainApplication.java, it might be that module is being created twice. If this was your intention, set canOverrrideExistingModule=true`

And here is my getPackages function in MainApplication.java;

```
@Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
       packages.add(new LinearGradientPackage());
       packages.add(new RNFirebaseAuthPackage());
       packages.add(new RNFirebaseDatabasePackage());
       packages.add(new RNFirebaseStoragePackage());
       packages.add(new MainReactPackage());
       //packages.add(new RNFirebasePackage());
       packages.add(new RNFirebaseFirestorePackage());
      return packages;
    } 
```

There are no duplicated packages. What is the problem i dunno.

**Comment by mikehardy** [comment]
Native module TimePickerAndroid tried to override com.facebook.react.modules.timepicker. TimePickerDialogModule

Please open an issue in that repo
