### ISSUE TITLE
Support wifi IP address on Apple TV

### ISSUE THREAD

**Issue by gcesarmza** [react-native-community/react-native-device-info#824]
# Feature Request

Currently this module returns "0.0.0.0" when the Apple TV is connected to a wifi network.

## Why it is needed

The reason the current implementation is not working is that the network interface names are different for iPhone (`en0`) and Apple TV (`en1`)

**Comment by mikehardy** [comment]
This is published as 4.0.1-beta.3 or @next on npmjs.com - hope to have a stable v4.x release shortly
