### ISSUE TITLE
Native module TimePickerAndroid tried to override com.facebook.react.modules.timepicker. TimePickerDialogModule

### ISSUE THREAD

**Issue by ozgunsandal** [react-native-community/react-native-device-info#826]
Hello,
React native gives me an error like this;

Native module TimePickerAndroid tried to override com.facebook.react.modules.timepicker. TimePickerDialogModule. Check the getPackages() method in mainApplication.java, it might be that module is being created twice. If this was your intention, set canOverrrideExistingModule=true

And here is my getPackages function in MainApplication.java;

@Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
       packages.add(new LinearGradientPackage());
       packages.add(new RNFirebaseAuthPackage());
       packages.add(new RNFirebaseDatabasePackage());
       packages.add(new RNFirebaseStoragePackage());
       packages.add(new MainReactPackage());
       //packages.add(new RNFirebasePackage());
       packages.add(new RNFirebaseFirestorePackage());
      return packages;
    } 
There are no duplicated packages. What is the problem i dunno.

**Comment by mikehardy** [comment]
TimePickerAndroid has nothing to do with this module that I know of

**Comment by Desintegrator** [comment]
same issue. There are no duplicated packages. There are no references to TimePickerAndroid or TimePickerDialogModule

**Comment by mikehardy** [comment]
@Desintegrator I repeat: TimePicker has nothing to do with this module.

Open a new issue with a public repo based off the example demonstrating the problem, if that's possible. But it should not be, because TimePicker has nothing to do with this module.
