### ISSUE TITLE
README is outdated

### ISSUE THREAD

**Issue by ikesyo** [react-native-community/react-native-device-info#827]
The sentence 

> AndroidX is supported in a non-breaking / backwards-compatible way by using overrides in your android/build.gradle file's "ext" block

is wrong now due to #775.

Context: https://github.com/react-native-community/react-native-device-info/commit/50793700a0a1868684ca7215a4da4ec3034ce0fc#r35166027

**Comment by mikehardy** [comment]
enjoy
