### ISSUE TITLE
isEmulator returns true when testing on an actual device.

### ISSUE THREAD

**Issue by alvaro1728** [react-native-community/react-native-device-info#830]
**My dependencies:**
```
    "react": "16.9.0",
    "react-native": "0.61.2",
    "react-native-device-info": "^3.1.4",
```
**My code:**

```
import {Alert} from "react-native";
import {isEmulator} from "react-native-device-info";
...
if (isEmulator()) {
      Alert.alert("Not Supported", "This feature is not available in the simulator.");
}
```
**The problem:**

When I run this from Xcode with my iPhone connected to it, isEmulator returns true.  I'm expecting it to return false since I'm running on an actual device.

Thanks,
Alvaro

**Comment by mikehardy** [comment]
You either want to use isEmulatorSync() in the style you are using, or try { if (await isEmulator()) { /* something */ } catch (e) {console.err}

Note that isEmulator may return to being a constant shortly as there was an unfortunate interaction with the xxxSync() APIs and the chrome debugger #776 but the APIs won't move that much. As such I'd recommend you use isEmulatorSync for this one unless #776 is an issue for you
