### ISSUE TITLE
getBundleId misplaced

### ISSUE THREAD

**Issue by imkojima** [react-native-community/react-native-device-info#839]
# Bug

Hi, I'm trying 4.0.1-beta.7 on my project. I found `getBundleId` return OS build identifier now.

After checking few commit changes, Is that supposed to be `getBundleId` instead of `getBuildId`?
https://github.com/react-native-community/react-native-device-info/blame/v4.0.1-beta.7/ios/RNDeviceInfo/RNDeviceInfo.m#L61

**Comment by mikehardy** [comment]
Thank you for reporting this @imkojima - you are correct and your diagnosis of root cause is perfect, beta.8 is out now with this change

**Comment by mikehardy** [comment]
4.0.1-rc.1 is out and the migration guide is up, unless bugs are found I will release it tomorrow

https://github.com/react-native-community/react-native-device-info/releases/tag/v4.0.1-rc.1

react-native-community/react-native-device-info/wiki/V3-to-V4-Migration-Guide

Please test it, and edits / improvements to the migration guide are always welcome.

Thanks!
