### ISSUE TITLE
Error: While trying to resolve module `react-native-device-info` after installing v4

### ISSUE THREAD

**Issue by stage88** [react-native-community/react-native-device-info#840]
# Bug

After installing v4, I get the following error. Anyone else get this?
```
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   /Users/sam/Projects/test-mobile-client 

warning: the transform cache was reset.
Loading dependency graph, done.
error: bundling failed: Error: While trying to resolve module `react-native-device-info` from file `/Users/sam/Projects/test-mobile-client/js/env.js`, the package `/Users/sam/Projects/test-mobile-client/node_modules/react-native-device-info/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/sam/Projects/test-mobile-client/node_modules/react-native-device-info/src/index.js`. Indeed, none of these files exist:

  * /Users/sam/Projects/test-mobile-client/node_modules/react-native-device-info/src/index.js(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * /Users/sam/Projects/test-mobile-client/node_modules/react-native-device-info/src/index.js/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
    at ResolutionRequest.resolveDependency (/Users/sam/Projects/test-mobile-client/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:65:15)
    at DependencyGraph.resolveDependency (/Users/sam/Projects/test-mobile-client/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at Object.resolve (/Users/sam/Projects/test-mobile-client/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at dependencies.map.result (/Users/sam/Projects/test-mobile-client/node_modules/metro/src/DeltaBundler/traverseDependencies.js:426:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/sam/Projects/test-mobile-client/node_modules/metro/src/DeltaBundler/traverseDependencies.js:423:18)
    at /Users/sam/Projects/test-mobile-client/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/sam/Projects/test-mobile-client/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
    at _next (/Users/sam/Projects/test-mobile-client/node_modules/metro/src/DeltaBundler/traverseDependencies.js:107:9)
 BUNDLE  [ios, dev] ./index.js ▓░░░░░░░░░░░░░░░ 6.3% (31/243), failed.

```

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1. Install v4
2. react-native start --reset-cache
...

Describe what you expected to happen:

1.
2.

**Comment by web-mobile0308** [comment]
After upgrade react native version 0.61.2, I got this issue on metro bundler loading.
Could someone let me know how to fix this issue asap?
Thanks

Looking for JS files in
   /Users/sam/Projects/test-mobile-client 

warning: the transform cache was reset.
Loading dependency graph, done.
error: bundling failed: Error: While trying to resolve module `react-native-device-info` from file `/Users/sam/Projects/test-mobile-client/js/env.js`, the package `/Users/sam/Projects/test-mobile-client/node_modules/react-native-device-info/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/sam/Projects/test-mobile-client/node_modules/react-native-device-info/src/index.js`. Indeed, none of these files exist

**Comment by mikehardy** [comment]
You may need to do a deeper clean, everyone reporting this, please run a clean from the react-native-clean-project package (the only one I trust...)

This comes up often enough in other packages I maintain and use that at this point my only 100% reliable CI builds come when I call 'deep-clean' which is defined in my package.json like so

```json
    "deep-clean": "./node_modules/.bin/react-native-clean-project --keep-node-modules --remove-iOS-build --keep-brew --keep-pods --remove-iOS-pods --remove-android-build && yarn clean",
    "clean": "\\rm -fr ./node_modules && \\rm -fr dist/* && \\rm -fr ios/build ios/Pods ios/KScoreApp.xcarchive && \\rm -fr android/build android/app/build",
```

Every single part of it that does a delete is important, and the parts that interact between react-native-clean-project and manual deletes are tuned carefully to (for instance) delete local pods but not delete your system's entire pod cache. So it should be fairly performant as far as full purges go.

I can't reproduce this on the example or in my app so my inclination would be to close this but of course there may be a real issue so please purge out all your caches and report back

Thanks!

**Comment by mikehardy** [comment]
(if you want to keep it simple and are on a fast network you can just `npx react-native-clean-project clean-project-auto` and be squeaky clean as well)

**Comment by web-mobile0308** [comment]
Hi, Mike
Thanks for your kindly answer.
I hope it will help me.
:)

**Comment by mikehardy** [comment]
Unrelated I just ran the example clean trying to reproduce things and I could not, it appears to be a project-specific issue

**Comment by afilp** [comment]
I have exactly the same problem. It looks for `src\index.js` but the package only has a TypeScript file there: `src\index.ts`. 

So, the problem seems to be that react-native looks for `.tsx` files and not for `.ts`?

**Comment by mikehardy** [comment]
This still strikes me as some sort of caching. I continue to recommend my cleaning method outlined in detail above. If someone will confirm that they have *BOTH* run the clean as I mentioned above and are still seeing the problem, then we have a problem.

But if that's the case I'll need a lot more details - `npx react-native info` output at minimum plus the version of react-native-device-info in use and that you've run the clean

But we have a [transpilation step from typescript to javascript](https://github.com/react-native-community/react-native-device-info/blob/master/package.json#L31) prior to upload, so there is an index.js and it should look for it if it needs to https://github.com/react-native-community/react-native-device-info/blob/master/package.json#L7

**Comment by stage88** [comment]
Hi @mikehardy, I have the same problem as @afilp, the src directory in node_modules/react-native-device-info does not have index.js. I'll do a clean install to if I can reproduce

**Comment by stage88** [comment]
Ok, my bad, sorry everyone.

Please use `npm install react-native-device-info@4.0.1-rc.1 --save` instead of `npm install react-native-device-info --save`.

The later installs version 4.0.0 which for some reason fails with above. So far 4.0.1-rc.1 is working great for me, thanks all.

I'll be closing this...

**Comment by mikehardy** [comment]
Ah ha! That's not really your bad, we had a release issue where we thought typescript (the other big change in v4) was ready to go but as you found it was not because of the issue you described. We unpublished that on npmjs.com so it should not have gotten you, but either referencing react-native-device-info@next or @4.0.1-rc.1 would work.

Just to put a nail in it, I haven't gotten any other bug reports so I'm going to make an official release of 4.0.1 today that will bring everyone past the broken 4.0.0, and I feel more confident doing so since you reported success with the new rc.1 - thank you!

**Comment by ricbermo** [comment]
I just came across with this issue and I noticed I was missing `ts` in my `metro.config.js`
```javascript
module.exports = {
  resolver: {
    sourceExts: ['jsx', 'js', 'ts'],
  },
};

**Comment by mikehardy** [comment]
That's an interesting point, but it should not be necessary? The react-native template does not come with that: https://github.com/facebook/react-native/blob/master/template/metro.config.js

yet the example (which I auto-refresh via script so it always gets just the template) works?  https://github.com/react-native-community/react-native-device-info/blob/master/refresh-example.sh (and indeed it is the raw template file, no .ts in there https://github.com/react-native-community/react-native-device-info/blob/master/example/metro.config.js) 🤔

**Comment by ricbermo** [comment]
Well, when I started the project, like 3month ago, I had to make some adjustments to the metro config file. I guess I just forgot to add the `ts` extension back then.

**Comment by mikehardy** [comment]
@ricbermo that's the opposite of what I mean - there should be no need for the '.ts' extension. It is not in the template, it is not in our example app, yet the example app works.

**Comment by ricbermo** [comment]
@mikehardy maybe RN loads TS files by default and once I adjusted my metro config to load only JS and JSX files, v4.0.1 stopped working for me.

**Comment by mikehardy** [comment]
@ricbermo good thinking! I checked and I think you're right - as long as you don't override it to a specific list (which excludes .ts), the default will include it apparently https://github.com/facebook/metro/blob/master/packages/metro-config/src/defaults/defaults.js#L52
