### ISSUE TITLE
Is there anyway to detect whether a device has a physical home button?

### ISSUE THREAD

**Issue by nenjamin2405** [react-native-community/react-native-device-info#842]
# Question

Hi guys, currently I'm doing the styling for my app on iPad devices and my app has a bottom navigator. The problem is I cannot detect whether a specific iPad has a virtual vertical bar or not, in order to increase the bottom padding for my bottom navigator, you guys can see details in the image below:

This is iPad Pro (12.9-inch) (3rd Generation) without a physical home button (has a virtual vertical bar) --> the additional bottom padding is reasonable in this case
![image](https://user-images.githubusercontent.com/16648769/66729321-d6ddfc00-ee74-11e9-8be8-f08668026b8a.png)

This is iPad Pro (9.7-inch) with the physical home button --> the additional bottom padding is unreasonable in this case
![image](https://user-images.githubusercontent.com/16648769/66729363-1e648800-ee75-11e9-9c39-f10ef8ddb663.png)

**Comment by mikehardy** [comment]
I think what you really want is a more powerful solution, and this libraries current hacky/lookup-table based solution even for 'hasNotch()' is frankly not a good idea :-). https://github.com/th3rdwave/react-native-safe-area-context is the full-powered solution, you'd want to get the insets and behave accordingly if I understand correctly - I've been chatting in another issue https://github.com/react-native-community/react-native-device-info/issues/594#issuecomment-527729365 with @janicduplessis about some way to shift our current and desired APIs about safe area (which is what hasNotch is about, really) to that library and I think this is another case where it's useful. Might be just a simple PR even to expose the info you need. Until then though I'm not sure how you'd accomplish it

**Comment by nenjamin2405** [comment]
@mikehardy Thanks a lot for your details explanation!!!
