### ISSUE TITLE
DeviceInfo.getUniqueId()  is not a function

### ISSUE THREAD

**Issue by godwin12345** [react-native-community/react-native-device-info#844]
I have added this project manually.
I'm getting error while calling directly this DeviceInfo.getUniqueId()

Error was function not defined
	
DeviceInfo.getUniqueId().then(uniqueId => {
			
			Alert.alert(uniqueId.toString());
			
     });
When i use the above way i can alert the value.

**Comment by mikehardy** [comment]
What version? What is the actual problem?

**Comment by godwin12345** [comment]
Actually it is a version issue i reinstalled again it's worked!!!

**Comment by mikehardy** [comment]
That was my hunch :-), that changed just yesterday with the current release. Glad you're working now
