### ISSUE TITLE
Devices with notch don't match the value returned by getModel() method 

### ISSUE THREAD

**Issue by ddxxtony** [react-native-community/react-native-device-info#854]
# Feature Request

I have a moto g7 play, but I when I was using the DeviceInfo.hasNotch() feature I was getting false despite my device is in the list of devices with notch, 
so I was debugging this library  and I realized that this function getModel() is returning this Model "moto g(7) play" and in the Devices list is like this "Moto g7 play".

## Possible implementation

So I am not sure if adding the missing parenthesis to the Moto g models In the Devices with notch List will be a solution or not.
Also I was thinking that a solution could be to remove all the especial characters from the strings at the moment of check if the model exits in the devices list . see the below example: 

original code
   764   devicesWithNotch.findIndex(
        item =>
          item.brand.toLowerCase() === _brand.toLowerCase() &&
          item.model.toLowerCase() === _model.toLowerCase()
      ) !== -1;

remove especial characters implemented 

  764   devicesWithNotch.findIndex(
        item =>
          item.brand.toLowerCase().replace(/[^a-zA-Z0-9 ]/g, "") === _brand.toLowerCase().replace(/[^a-zA-Z0-9 ]/g, "") &&
          item.model.toLowerCase().replace(/[^a-zA-Z0-9 ]/g, "") === _model.toLowerCase().replace(/[^a-zA-Z0-9 ]/g, "")
      ) !== -1;

**Comment by mikehardy** [comment]
I would just add another entry for the string you know works, without perturbing the other ones. That way you know it will work and I know it won't break anyone else. I can release those as patch versions pretty much immediately if you submit a PR

sorry for the delay reviewing this!

**Comment by mikehardy** [comment]
The getNotch list is user-supported but I merge things quickly, following my advice above if this is still needed for you just submit a PR that adds a specific test for you
