### ISSUE TITLE
DeviceInfo.getManufacturer() on TestFlight does not say "apple"

### ISSUE THREAD

**Issue by smalbois-panoptio** [react-native-community/react-native-device-info#857]
# Bug

We are in the middle of testing our app on TestFlight and DeviceInfo.getManufacturer() provides the following output: ```{'_40': 0, '_65': 0, '_55': None, '_72': None}```

The deviceID is a well formatted apple device id.

## Environment info

React native info output:

```bash
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
      Memory: 17.50 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
      Android SDK:
        API Levels: 23, 26, 28
        Build Tools: 26.0.3, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-Q | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-rename: 2.4.1

```

Library version: x.x.x

## Steps To Reproduce

1. Install the app in TestFlight
...

Describe what you expected to happen:

1. Expected to see apple as the manufacturer.

**Comment by smalbois-panoptio** [comment]
Sorry this is related to upgrading the lib last week to the latest and greatest and NOT testflight. I will investigate further.

**Comment by mikehardy** [comment]
That is the most excellent gobbledy-gook that represents the actual javascript state of a Promise, if you print it out. So I'm guessing you just aren't using the new API correctly - you should look at the v2->v3 migration guide with an eye towards either choosing your current execution style (sync) and thus using getDeviceManufacturerSync(), or use it as a promise with await or getDeviceManufacturer().then(mfr => {})

From the v3->v4 migration guide you'll see a few things are available as constants, but I will say for just getting the platform ("apple", which really is equivalent to "ios") you can get that from the react-native platform api

I'm closing this, but with the idea that you have the information you need, hopefully it helps

**Comment by smalbois-panoptio** [comment]
Thank you Mike - you were right. Wasn't calling it the right way in v4 after moving from v1. Thanks for your help.

**Comment by mikehardy** [comment]
No problem - it was a bit of fast + bumpy ride on the way to v4, glad you made it :-)
