### ISSUE TITLE
Cannot resolve "../../web"

### ISSUE THREAD

**Issue by wmonk** [react-native-community/react-native-device-info#878]
# Bug

When using `react-native-web` I get this error:
```
./node_modules/react-native-device-info/lib/module/internal/nativeInterface.js
Module not found: Can't resolve '../../web' in '/<redacted>/app/node_modules/react-native-device-info/lib/module/internal'
```

## Environment info (web)
Tried with library versions: 5.0.0, 5.1.0, 5.2.0

## Steps To Reproduce
1. `react-scripts start`
2. Compiler error

Describe what you expected to happen:
1. Compilation works fine

## Fix
Change import to `../../../web`. Not sure of the effect of this as haven't explored the codebase.

**Comment by mikehardy** [comment]
I am actually *just* integrating this project into a web project myself and I noticed the same. There was a transition with style of web integration between v1 and v2 where web no longer was a polyfill that may have affected it. And there was a transition between v3 and v4 where we went to typescript and altered how the build happened that may have caused it.

If you were able to switch to adding one more parent I'm guessing it was the typescript / build style transition.

Either way, definitely want to support web and I can reproduce this locally so I'll get it patched up pretty quickly

**Comment by mikehardy** [comment]
oh - if you haven't used patch-package, use that package to make your local change persistent and easy to use in your project (across machines, CI, etc) and it'll warn you when I have a new version with a fix so you can remove the patch.
