### ISSUE TITLE
React Native firebase issues

### ISSUE THREAD

**Issue by manoj1kumar1** [react-native-community/react-native-device-info#882]
# Question
When i installed react-native firebase i got an error 
$ react-native run-android
info JS server already running.
info Building and installing the app on the device (cd android && gradlew.bat app:installDebug)...

> Configure project :react-native-firebase
react-native-firebase: using React Native prebuilt binary 
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> The library com.google.android.gms:play-services-basement is being requested by various other libraries at [[15.0.1,15.0.1]], but resolves to 16.1.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: gradlew.bat app:installDebug. Run CLI with --verbose flag for more details.

How can i fix this

**Comment by mikehardy** [comment]
So you install react-native-firebase and it has an error but you are logging it here? Please open an issue there following their template.

I work on that repo a lot, so odds are I will be the person responding as well but the issue template on that repo is really helpful and will have what we need to resolve.

As a first take I'd say you need to make sure your dependencies for react-native-firebase are up to date, and you will probably need to specify the versions in android/build.gradle::ext{} block

https://github.com/react-native-community/react-native-device-info/blob/13d9c2ad3c48b932bce6af3c233c39fc62765661/example/android/build.gradle#L4-L9

**Comment by manoj1kumar1** [comment]
I done this things which you replied but no solution found,still i got an error  build is failed.

**Comment by mikehardy** [comment]
No you haven't

> So you install react-native-firebase and it has an error but you are logging it here? Please open an issue there following their template.

You might try `cd android && ./gradlew :app:dependencies` to see what's requesting the old version of play services. But I want to be clear: this is a local project setup issue. It might have a root cause in incompatible versions of modules being used together but I'd bet that being fully upgraded and specifying the right things in the ext{} block will get things building.
