### ISSUE TITLE
getDeviceId return unknow on Android

### ISSUE THREAD

**Issue by sidneycorreia** [react-native-community/react-native-device-info#883]
The getDeviceId method return unknow word on Android device, I try in two different devices. What I can do?

...
"react-native": "0.61.2",
"react-native-device-info": "^5.2.1",

Android version: 8 and 6

**Comment by mikehardy** [comment]
Try the example here and see if you can reproduce it

I'm guessing it's this missing though https://github.com/react-native-community/react-native-device-info/blob/master/example/android/build.gradle#L4

**Comment by sidneycorreia** [comment]
getDeviceId() still returns "unknown". May be a device's feature?
getUniqueId() works fine.

**Comment by mikehardy** [comment]
https://github.com/react-native-community/react-native-device-info/blob/master/src/index.ts#L141

https://github.com/react-native-community/react-native-device-info/blob/master/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L162

Maps to Build.BOARD https://developer.android.com/reference/android/os/Build#BOARD

I've seen it return non-unknown. Right now it is saying "msms8998" on my OnePlus 5. It'll say goldfish for most emulators.

So probably a device feature? I'm happy to discuss more but as I can't reproduce and it seems to be functioning for me I'm going to provisionally close
