### ISSUE TITLE
Get "unknown" from getSerialNumber()

### ISSUE THREAD

**Issue by wendy-peiwen** [react-native-community/react-native-device-info#884]
I use react-native-device-info version 2.2.2 , i can get my serial number. After i update to version 5.2.1, i get "unknown". Anyone face this problem before? How to solve it?

**Comment by mikehardy** [comment]
This was a sensitive hardware identifier, and the world moved on

It used to map to this: https://developer.android.com/reference/android/os/Build.html#SERIAL (https://github.com/react-native-community/react-native-device-info/blob/v2.2.2/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L492) note the warning in the documentation: "always set to Build.UNKNOWN"

So we moved to the new API, but in general your app will not be a privileged app ("privileged" in this conext is rooted, or a carrier installed app)
https://github.com/react-native-community/react-native-device-info/blob/master/README.md#getserialnumber

So it's "unknown" for now, for nearly everyone.

You can always target lower APIs or use the deprecated version but it's not supported here anymore

This will be a theme for any sensitive hardware identifiers you attempt to access, they are all either shut down already or will be shortly. Use the identity-service based uniqueId instead
