### ISSUE TITLE
Failed to process /Users/apple/.gradle/caches/transforms-2/files-2.1/xxx/jars/classes.jar

### ISSUE THREAD

**Issue by HHuiHao** [react-native-community/react-native-device-info#885]
After the integration of react-native-device-info, the cloud will report an error. How can I solve it?

```
Environment：
system: android 
react-native-cli: 2.0.1
react-native: 0.61.2
"react-native-device-info": "^5.2.1"
```

![image](https://user-images.githubusercontent.com/8486113/68563572-ec9d0c00-0488-11ea-96ac-25390c36ba33.png)

**Comment by mikehardy** [comment]
Please post text, not graphics - it's easier to cut and paste
However, I don't see the string "react-native-device-info" in here anywhere. I don't think this is related to the module. Though it might be a problem in the setup of the module.

Try the example in this repo. If you can reproduce it with the example, there might be a problem with this module vs your project

**Comment by HHuiHao** [comment]
```
error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
注: /Users/apple/Desktop/xxx/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDevicNDeviceModule.java Used or overridden obsolete APIs
```

**Comment by mikehardy** [comment]
A report of a deprecated API is not an error
I consider this an incomplete error report, and still can't reproduce.

Post THE ENTIRE run of attempting to install the example locally.

**Comment by varunwilson6** [comment]
> ```
> error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
> Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
> 注: /Users/apple/Desktop/xxx/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDevicNDeviceModule.java Used or overridden obsolete APIs
> ```

Same Issue

**Comment by sksinghdev** [comment]
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/xxx/.gradle/caches/transforms-2/files-2.1/2aaf7abc79f1b52f09b2bc4f0e01f9a1/jars/classes.jar

in gradle.properties 
android.enableBuildCache=false

android.enableR8.fullMode=true

android.enableD8.desugaring=true

in module build. gradle 

classpath 'com.android.tools.build:gradle:3.2.1'

in App build.gradle

implementation(name:'abc', ext:'aar')

getting error sinnce two days please any body know please help me 

thanks 
Santosh Kumar

**Comment by mikehardy** [comment]
If you can reproduce with the example app, the module has a problem, if you cannot, your project has a problem.
My bet is your project has a problem @sksinghdev 
My guess is out of date software, why such an old gradle, for instance?
