### ISSUE TITLE
getManufacturerSync()  Android problem

### ISSUE THREAD

**Issue by mykhailo-melnyk** [react-native-community/react-native-device-info#889]
# Bug

react-native-device-info = 5.3.0

getManufacturerSync() works perfectly on ios but on android I have next error:
<img width="440" alt="Bildschirmfoto 2019-11-13 um 14 24 14" src="https://user-images.githubusercontent.com/14886932/68774812-50186c80-0636-11ea-9a2a-57561fc7d77d.png">

**Comment by mikehardy** [comment]
I'm not sure how to fix it fully https://github.com/react-native-community/react-native-device-info/issues/776

If it's all constants-based and default sync as an API, there are startup performance problems.
If it's all async then you have to do gymnastics to use the API during bootstrap in an app

If some are constants, and some are async, there are always some bits of info that people want sync. But then the debugger breaks.
