### ISSUE TITLE
/node_modules/react-native-device-info/src/internal/nativeInterface.ts: Unexpected token, expected ;

### ISSUE THREAD

**Issue by cubois-anirudha** [react-native-community/react-native-device-info#891]
## Summary

| Version    | "^4.0.1-rc.1"   |
| Affected OS |Android|

## Current behavior

error: bundling failed: SyntaxError in /Users/macbook/Desktop/ProjectName/ProjectName/node_modules/react-native-device-info/src/internal/nativeInterface.ts: /Users/macbook/Desktop/ProjectName/node_modules/react-native-device-info/src/internal/nativeInterface.ts: Unexpected token, expected ; (25:28)
  23 | }
  24 | 
> 25 | export default RNDeviceInfo as DeviceInfoNativeModule

## Expected behavior

Bundling Should be done Successfully

**Comment by mikehardy** [comment]
Hi there! Posting a semver range does not tell me what version you are actually on. Current is 5.3.0 https://github.com/react-native-community/react-native-device-info/blob/master/package.json#L3

Use the current version and if you can reproduce I will reopen and we can fix it

**Comment by cubois-anirudha** [comment]
Hi Mike ,Thanks for Reply

Same issue on latest version,

Version -  "react-native-device-info": "^5.3.0",
                  "react-native": "0.54.0",
                   compileSdkVersion = 27 
                   targetSdkVersion = 26 
                  googlePlayServicesVersion = "15.0.1"
Affected OS - Android

Still getting same issue

error: bundling failed: SyntaxError in /Users/macbook/Desktop/projName/node_modules/react-native-device-info/src/internal/nativeInterface.ts: /Users/macbook/Desktop/projName/node_modules/react-native-device-info/src/internal/nativeInterface.ts: Unexpected token, expected ; (25:28)
  23 | }
  24 | 
> 25 | export default RNDeviceInfo as DeviceInfoNativeModule;
     |                             ^
  26 | 
 BUNDLE  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

**Comment by mikehardy** [comment]
This looks like a project setup issue. I think you should probably have babel set to not process node_modules? You should check out the example in this project, look at the babel and metro configs and see if you have any significant differences?

I will also mention that with a targetSdkVersion below 28, I don't think you will be able to publish new apps or even updates to old apps to the Google Play Store anymore as of Nov 1 https://developer.android.com/distribute/best-practices/develop/target-sdk

**Comment by cubois-anirudha** [comment]
Ok Thanks :)

**Comment by sundariragavan** [comment]
@cubois-anirudha  Did you fixed this issue ? I'm also facing this now

**Comment by sundariragavan** [comment]
@mikehardy Hi i'm facing this issue. any update ?

**Comment by mikehardy** [comment]
Nothing to update. This module is downloaded 175,000 times a week apparently and it works for everyone else. Perhaps there is something wrong with your local project? Clone the repo, run the example and see how it is supposed to work?

**Comment by sundariragavan** [comment]
error: bundling failed: SyntaxError: /Users/WorkSpaces/mobile/node_modules/react-native/node_modules/react-native-device-info/src/internal/nativeInterface.ts: Unexpected token, expected ";" (28:28)

  26 | }
  27 | 
> 28 | export default RNDeviceInfo as DeviceInfoNativeModule;
     |                             ^
  29 | 
    at Object._raise (/Users/WorkSpaces/mobile/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:742:17)
    at Object.raiseWithData (/Users/WorkSpaces/mobile/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:735:17)
    at Object.raise (/Users/WorkSpaces/mobile/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:729:17)
    at Object.unexpected (/Users/WorkSpaces/mobile/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:8757:16)
    at Object.semicolon (/Users/WorkSpaces/mobile/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:8739:40)
    at Object.parseExportDefaultExpression (/Users/WorkSpaces/mobile/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:12284:12)
    at Object.parseExportDefaultExpression (/Users/WorkSpaces/mobile/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:2589:18)
    at Object.parseExport (/Users/WorkSpaces/mobile/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:12185:31)
    at Object.parseExport (/Users/WorkSpaces/mobile/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:2748:24)
    at Object.parseStatementContent (/Users/WorkSpaces/mobile/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:11185:27)

I think the issue with babel package version. Can you check this issue. let me know you have any idea to resolve this error.

"devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/runtime": "^7.3.1",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^24.1.0",
    "eslint": "6.8.0",
    "babel-preset-react-native": "^4.0.1",
    "eslint-config-prettier": "^3.3.0",
    "eslint-plugin-flowtype": "^3.2.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-prettier": "^3.0.0",
    "eslint-plugin-react": "^7.11.1",
    "eslint-plugin-react-native": "^3.5.0",
    "flow-bin": "^0.87.0",
    "jest": "^24.1.0",
    "jest-cli": "^23.6.0",
    "jetifier": "^1.6.5",
    "metro-react-native-babel-preset": "^0.54.1",
    "prettier": "^1.15.3",
    "react-test-renderer": "16.11.0"
  },

**Comment by mikehardy** [comment]
How did it go when you ran the example in this repo? If it went fine, you'll have to find the problem in  your project but it's not a module bug.

**Comment by rishabhyadavv** [comment]
@sundariragavan did you find solution? I am using below versions
  "@babel/preset-env": "^7.8.4",
  "@babel/runtime": "^7.8.4",
  "@babel/core": "^7.8.4",
 "babel-loader": "^8.0.5",

**Comment by mikehardy** [comment]
The only thing I can think of that rhymes with this (but may not be the same) is the version of typescript. It was determined in a different issue that we inadvertently required a higher level of typescript than some people have 

https://github.com/react-native-device-info/react-native-device-info/commit/c50b1b93621e6241331e5422c28ec774845a304a

https://github.com/react-native-device-info/react-native-device-info/issues/1167

**Comment by douglasjunior** [comment]
I encountered this issue when I updated a project from React Native 0.61.5 to 0.64.2 and also updated DeviceInfo to 8.1.3.

I'm not using TypeScript, and default Babel setting. 

After deleting `yarn.lock` and creating again the problem is gone, so I believe it is some transient dependency that needs to be updated.

**Comment by onebuck-code** [comment]
[PROBLEM] I have the similar issue after I upgrade from yarn1 to yarn3. 

React Native Version: 0.64.4
DeviceInfo: 8.1.7

Hit below issue when I run the app: 

```import type {
     |             ^
  13 |   AsyncHookResult,
  14 |   DeviceType,
  15 |   LocationProviderInfo,```

It was fine when I'm still on classic yarn.
