### ISSUE TITLE
 NativeModule.RNDeviceInfo is null

### ISSUE THREAD

**Issue by Surile** [react-native-community/react-native-device-info#894]
# Question

React-Native 0.61.4 Android cannot be automatically introduced

![image](https://user-images.githubusercontent.com/28652894/68997349-68131900-08e0-11ea-85ef-adf9358a9c4a.png)

**Comment by mikehardy** [comment]
This is always a local setup issue - there are 28 closed issues with the same error, the solutions are in there https://github.com/react-native-community/react-native-device-info/issues?q=is%3Aissue+sort%3Aupdated-desc+RNDeviceInfo+is+null+is%3Aclosed
