### ISSUE TITLE
NativeModule.RNDeviceInfo is null on iOS 10.x (works on iOS 13.x)

### ISSUE THREAD

**Issue by LinusU** [react-native-community/react-native-device-info#900]
# Bug

Getting the following error when running our app in the simulator for iOS 10.3.1:

> @react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null.

On iOS 13.2.2 it works.

I've cleaned out the build and ran `pod install` again. Also, just switching targets between my "iPhone 5 (iOS 10.3.1)" and "iPhone 11 Pro (iOS 13.2.2)" makes it work/not work.

## Environment info

React native info output:

```bash
$ react-native info
info Fetching system and libraries information...

System:
    OS: macOS 10.15.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 294.21 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - node_modules/.bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4
```

Library version: 5.3.1

## Steps To Reproduce

1. Run an app using react-native-device-info on iOS 13
  1. Notice it working
1. Run an app using react-native-device-info on iOS 10
  1. See the error

Describe what you expected to happen:

1. It work on every iOS version between 9.0 and 13.2

## Reproducible sample code

```js
import DeviceInfo from 'react-native-device-info'

console.log(DeviceInfo.getBundleId())
```

**Comment by mikehardy** [comment]
"you have cleaned out the build" -> `npx react-native-clean-project clean-project-auto` and try again - let me know if you still see it? (hypothesis: stale DerivedData)

**Comment by LinusU** [comment]
Wow, that fixed it, thank you so much! 👏

**Comment by mikehardy** [comment]
react-native-clean-project, the silver bullet cure for iOS build woes from @pmadruga :-), spread the word to anyone else suffering 💪

**Comment by yaronlevi** [comment]
For days I struggled with this.
I've created a clean project!
1. react-native init (@0.61.5)
2. Did `npm install --save react-native-device-info `
3. Got the dreaded NativeModule.RNDeviceInfo 😡

I looked all over and could not find a solution until I came here and found:
`npx react-native-clean-project clean-project-auto`

It worked!
I am going to frame it as a picture on the wall here. Got a feeling it can be a life saver in many cases.

**Comment by mikehardy** [comment]
Maybe a nice cross-stitch pattern of it :-) 

![Screenshot from 2019-12-10 10-07-10](https://user-images.githubusercontent.com/782704/70541359-dd1aec80-1b34-11ea-9b7a-d1fa94bccdc1.png)

I recommend it daily, and use it as part of my CI commands even. It's the only way I know of to be sure every time.

**Comment by yaronlevi** [comment]
@mikehardy Nice pattern 😄
I am going to add the command to our Bitrise flow.
