### ISSUE TITLE
RNDeviceInfo (from `../node_modules/react-native-device-info`) was resolved to 2.3.2, which depends on React

### ISSUE THREAD

**Issue by whittlem** [react-native-community/react-native-device-info#906]
# Bug

Since the last iOS/Xcode update my project no longer builds.

The error I'm receiving is this:

ios % pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "React":
  In Podfile:
    RNDeviceInfo (from `../node_modules/react-native-device-info`) was resolved to 2.3.2, which depends on
      React

Specs satisfying the `React, React (< 1.0.0, >= 0.13.0)` dependency were found, but they required a higher minimum deployment target.

I have tried several things to solve this...

1. Upgraded React Native using this:
https://react-native-community.github.io/upgrade-helper/?from=0.59.5&to=0.61.5

2. Removed "node_modules" and re-installed with yum

3. Tried increasing minimum deployment versions (even to the max) in the Podfile and in the Xcode project and no luck

I'm stuck now and hoping you will know what is wrong as the issue seems to be specifically related to your package.

## Environment info

% react-native info
warn Your project is using deprecated "rnpm" config that will stop working from next release. Please use a "react-native.config.js" file to configure the React Native CLI. Migration guide: https://github.com/react-native-community/cli/blob/master/docs/configuration.md
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-vector-icons: https://github.com/oblador/react-native-vector-icons
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
info Fetching system and libraries information...
System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 11.39 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.2.0 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

Library version: ^2.3.2

## Steps To Reproduce

A simple "pod update" causes the error to happen.

Describe what you expected to happen:

The pod to update without the React minimum deployment error.

**Comment by mikehardy** [comment]
That's a very old version
Reproduce with current 5.3.1 https://github.com/react-native-community/react-native-device-info/blob/master/package.json#L3
Preferably showing via a small reproducible repository how it fails, our example script may serve as a usable basis https://github.com/react-native-community/react-native-device-info/blob/master/refresh-example.sh
