### ISSUE TITLE
Pass installerPackageName on Android

### ISSUE THREAD

**Issue by sattaman** [react-native-community/react-native-device-info#912]
# Feature Request

Pass through installerPackageName on Android so the market the package came from can be identified.

## Why it is needed

We have an app which can be installed via the playstore, via an apk , and also via various stores in China. For analytics, and for our forced updates screen, we need to be able to determine which market place the app was installed from

## Possible implementation

Add a method `getInstallerPackageName()` which would be implemented on Android only, and would pass the result of https://developer.android.com/reference/android/content/pm/PackageManager.html#getInstallerPackageName(java.lang.String) through. 

### Code sample

`console.log("Device Model", DeviceInfo.getInstallerPackageName()); // e.g. com.android.vending`

**Comment by mikehardy** [comment]
I would be willing to accept a PR like this - not sure how this will work out with the deprecation mentioned in #909 - may not be relevant but if it is then it should be noted in the accompanying change to README documenting the new feature

**Comment by mikehardy** [comment]
@codecog code looks like exactly what I'd expect for Java, great! Seems the administrivia (README, example etc) will be most of the work per usual on this module (since the device APIs are usually trivial) :-). Thanks for doing this

**Comment by codecog** [comment]
@mikehardy will write the docs for this with example usage as well and submit all in the same PR. 👍

**Comment by codecog** [comment]
PR opened: https://github.com/react-native-community/react-native-device-info/pull/946

**Comment by codecog** [comment]
@mikehardy think we can close this issue now.

**Comment by codecog** [comment]
@sattaman reply to this issue once you've used the new method and verify it's what you're after.

**Comment by mikehardy** [comment]
I think you're right - closing preliminarily but obviously we can chat more, cheers
