### ISSUE TITLE
excuse me how do i get mac address in ios > 11

### ISSUE THREAD

**Issue by GuiltyKirito** [react-native-community/react-native-device-info#915]
how do i get mac address in ios > 11,help me ,please

**Comment by mikehardy** [comment]
You don't. It's a device identifier that Apple doesn't let you access for privacy reasons

https://stackoverflow.com/a/18911557/9910298

**Comment by GuiltyKirito** [comment]
> You don't. It's a device identifier that Apple doesn't let you access for privacy reasons
> 
> https://stackoverflow.com/a/18911557/9910298

thank you ^ ^
