### ISSUE TITLE
DeviceInfo.hasNotch() crashes internally

### ISSUE THREAD

**Issue by Pyroboomka** [react-native-community/react-native-device-info#918]
# Bug

DeviceInfo.hasNotch() crashes internally, because somehow  
```let _model = getModel();```
on line 776 in index.ts return undefined, so findIndex crashes with
```TypeError: Cannot read property 'toLowerCase' of undefined```
on next line.

## Environment info
Tested on iPhone 11 emulator for now.

React native info output:

```bash
System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
    Memory: 185.12 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.2.0 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.13.1 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.12.0 => 16.12.0 
    react-native: 0.61.5 => 0.61.5
```

Library version: 5.4.0

## Steps To Reproduce

1. Run DeviceInfo.hasNotch() :)

**Comment by mikehardy** [comment]
If you can reproduce using the example I will reopen, but I believe this is an install failure such that the native module is not there. I definitely can't reproduce this locally. Make sure pods are installed and all that after adding this module

**Comment by Pyroboomka** [comment]
I rechecked on a fresh expo eject project, and yes, it seems to work normally. Will dig into bundling I guess.

**Comment by Pyroboomka** [comment]
![DeviceInfo](https://user-images.githubusercontent.com/14130945/71014538-235ae780-2103-11ea-9d30-533699954e33.jpg)
Actually I feel very lost for now. I logged RNDeviceInfo from both apps and they look vastly different. Look like incorrect/outdated version for me. Guess need to dig more :)
