### ISSUE TITLE
Confusing Documentation: AndroidX Support

### ISSUE THREAD

**Issue by buschco** [react-native-community/react-native-device-info#920]
# Question
I think [this](https://github.com/react-native-community/react-native-device-info#androidx-support) readme section is very unclear.
So the first section defines the options we have for `deviceId`. This is very straight forward. I just have to choose one and react-native-device-info will be satisfied. 

Also `compileSdkVersion` and `targetSdkVersion` is very clear.

So for `supportLibVersion` I have three options (similar for `mediaCompatVersion` and `supportV4Version`)
- The best option is using `1.0.2` or above.
- If I am using 'old libraries' (I think that means like other dependencies that require `supportLibVersion` at `28.0.0`) I use `28.0.0`
- I do not mention `supportLibVersion` at all (this package does not need `supportLibVersion`?)

I think I get something wrong here. Can someone please clarify this documentation?

**Comment by mikehardy** [comment]
You don't really *need* any of them unless the defaults aren't working for you. In general I would specify the most specific ones you can (supportV4 vs supportLib for instance) as pre-AndroidX it was bundled into one bug library and now with AndroidX it is all split apart.

In general though, for AndroidX support it is just confusing, sorry. Best thing to do is for any module integrate, check their dependencies and specify what you want after directly inspecting: https://github.com/react-native-community/react-native-device-info/blob/master/android/build.gradle#L49

PRs for documentation happily accepted!
