### ISSUE TITLE
Battery monitoring?

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-community/react-native-device-info#921]
# Feature Request

How difficult would be to extend the battery-related API to include a callback function that will fire when battery state changes? That is, plugged/unplugged, power saving / normal, critically low warning, etc..

## Why it is needed
If there are code paths based on if the device is charging or not, it is not ideal to poll for the battery status periodically, but rather get an event when it changes.

**Comment by mikehardy** [comment]
https://github.com/react-native-community/react-native-device-info/blob/master/README.md#hooks--events :thinking:

**Comment by cristianoccazinsp** [comment]
Totally did not see that! Thanks!
