### ISSUE TITLE
DeviceInfo.getUniqueID() is same in multiple iPads registered with same Apple IDs

### ISSUE THREAD

**Issue by kmvkrish** [react-native-community/react-native-device-info#922]
# Bug

The method `DeviceInfo.getUniqueID()` returns the same value for iPads that use the same Apple Account and have iCloud sync enabled.

## Environment info

React native info output:

```bash
React-Native: 0.59.10
ReactJS: 16.8.3
React-native-Device-Info: 0.24.0
```

Library version: **0.24.0**

## Steps To Reproduce

1. Register all the iPads with the same Apple IDs.
2. Enable iCloud Sync on all the devices. Enable Keychain Sync also.
3. Check for the `DeviceInfo.getUniqueID()` return value.
...

Describe what you expected to happen:

1. The UniqueID (UUID) should not be synced across multiple devices using the same Apple ID.

**Comment by mikehardy** [comment]
We're just exposing what the native API gives us. Have you consulted the upstream documentation to see how it behaves?

https://github.com/react-native-community/react-native-device-info/blob/master/ios/RNDeviceInfo/DeviceUID.m#L37

Alternatively you may be content with using async-storage and UUIDv4 packages in an easy combo to uniquely identify installs if that's the goal

**Comment by kmvkrish** [comment]
Hi @mikehardy 

> https://github.com/react-native-community/react-native-device-info/blob/master/ios/RNDeviceInfo/DeviceUID.m#L37

In this line, the code checks for the UniqueID in the following sequence:
1. Keychain.
2. If not found in Keychain, checks in UserDefaults.
3. If not found in UserDefaults, checks for AppleIFV - `UIDevice.current.identifierForVendor`.
4. If not found, then returns a new UUID generated.

From iOS 6,` identifierForVendor` will always be returned and that is unique per device per vendor. Due to this, the AppleIFV is always being returned when queried for the first time and the same is being saved in Keychain and UserDefaults - [Persist UID to NSUserDefaults and Keychain, if not yet saved](https://github.com/react-native-community/react-native-device-info/blob/master/ios/RNDeviceInfo/DeviceUID.m#L56)

I have also seen the code for saving the UniqueID for iOS in Keychain [https://github.com/react-native-community/react-native-device-info/blob/master/ios/RNDeviceInfo/DeviceUID.m#L71](https://github.com/react-native-community/react-native-device-info/blob/master/ios/RNDeviceInfo/DeviceUID.m#L71).  In the code DeviceUID.m, the `save` method didn't use this attribute.

From the [Apple Docs](https://developer.apple.com/documentation/security/ksecattrsynchronizable), if they keychain data doesn't have the attribute `kSecAttrSynchronizable` or set to `false`, they Keychains would not sync across devices. 

But we see the same value returned in multiple devices. Can you please clarify on this?

**Comment by mikehardy** [comment]
I don't use this method myself, and it was implemented before I began my tenure as maintainer here, sorry - you have already dug into more than I ever have

To be clear about possible changes I'd accept you can look at the PR that is here where we propose clearing this whole gunk out and doing essentially the UUID + async-storage thing I mention - https://github.com/react-native-community/react-native-device-info/pull/358

That one is mostly stagnant just for lack of personal interest - like I said, I'm not relying on anything device-specific in my projects - but if there was a great async-storage+UUID new API implemented here that was cross-platform (at least android+ios) I'd merge it

**Comment by karthikpala** [comment]
I am also facing similar issues- if customers are using same apple id with different devices - the unique id is returning same value.

According to [apple's documentation](https://developer.apple.com/documentation/security/ksecattrsynchronizable) the value ksecattrsynchronizable defaults to false. The documentation says

> If the key is not supplied, or has a value of kCFBooleanFalse, then no synchronizable items are added or returned. Use kSecAttrSynchronizableAny to query for both synchronizable and non-synchronizable results.

I'm not understanding even when the above value is not used in react-native-device-info - why the id is synching across the devices.

Can you please help?

**Comment by karthikpala** [comment]
#519

**Comment by karthikpala** [comment]
#519 

I think there is already same issue raised.

**Comment by blueberry6401** [comment]
Same here. I have 2 iPhone, the second one is restored from iCloud backup of the first one, and they have the same device id.

**Comment by mikehardy** [comment]
Hi @blueberry6401 !

> To be clear about possible changes I'd accept you can look at the PR that is here where we propose clearing this whole gunk out and doing essentially the UUID + async-storage thing I mention - #358

> That one is mostly stagnant just for lack of personal interest - like I said, I'm not relying on anything device-specific in my projects - but if there was a great async-storage+UUID new API implemented here that was cross-platform (at least android+ios) I'd merge it

I look forward to any future PR

**Comment by Bardiamist** [comment]
I think nothink better then to update `uniqueId` in `Keychain` and `NSUserDefaults`. I created PR #967 with `syncUniqueId()` method for that.

**Comment by Bardiamist** [comment]
My PR will helpfull for users who already synchronized keychain. But we need to be sure that DeviceInfo items not synchronizable. I can't do it because don't have two iOS devices.

But maybe items not synchronizable now.
> But we see the same value returned in multiple devices. Can you please clarify on this?

Maybe that not synchronization. Maybe restored/initialized from iCloud backup?

If items really siyncrhonizable now then need to try explicitly specify `kSecAttrSynchronizable `. Who have couple iOS devices.

**Comment by balavishnu** [comment]
Hi, facing same issue in Android as well. When we uninstall & re-install different unique ids get generated.

**Comment by mikehardy** [comment]
@balavishnu so you're facing the same issue but it's not the same issue as all? That's not helpful. Please open a separate issue if you like. But in general actually binding a unique ID to a device is extraordinarily problematic because people have an expectation of privacy. This is not something this module can solve, as the underlying libraries are protecting privacy and we're just showing you the IDs they generate.

**Comment by sharma-megha** [comment]
Is there any update on this issue? I am trying to get specifically the identifierForVendor so that I can match it against my other apps (by same developer) in the app store

**Comment by mikehardy** [comment]
@Bardiamist has been very diligent keeping the PR for syncUniqueId() / #967  up to date - I just merged it and released 5.6.0 - sorry for the delay on that, @sharma-megha that should help?

**Comment by mikehardy** [comment]
closing this tentatively? I'm not sure what else we can do but if anyone has an idea for another PR feel free to propose it

**Comment by Lunziyuan** [comment]
getUniqueId() and syncUniqueId() return the same thing, so it doesn't help
