### ISSUE TITLE
Program type already present: org.unimodules.adapters.react.ReactAdapterPackage

### ISSUE THREAD

**Issue by shubhamdeol** [react-native-community/react-native-device-info#923]
# Bug

 I have a project with react-native-unimodules installed. If I try to install react-native-device-info package to my project I am having build fail with exception saying 
**program type already present: org.unimodules.adapters.react.ReactAdapterPackage**
## Environment info

```bash
  react-native version :  0.62,
  Platform: android,
 "react-native-unimodules": "^0.7.0-rc.1",
 "react-native-device-info": "^5.4.0",
```

Error: 

```
Caused by: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Program type already present: org.unimodules.adapters.react.ReactAdapterPackage


Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: org.unimodules.adapters.react.ReactAdapterPackage

```

**Comment by mikehardy** [comment]
Sorry, I can't support problems with unimodules. I've integrated them once and I got things working (including with react-native-device-info) so I know it is possible, but unimodules are an involved enough integration I can't support them here meaning if you have problems while using it you'll need to look them up for support

**Comment by shubhamdeol** [comment]
@mikehardy  I do not have much knowledge of android, I guess this should be fixed with some hack. should I open issue on react-native-unimodules i.e expo repo?

**Comment by mikehardy** [comment]
In my experience integrating with unimodules, no hacks were needed. I suspect this is some sort of more normal installation failure and if you retried it from previous git checkpoint and the directions handy, it might come out okay the second time. It is not a problem with this module though. This module worked with unimodules just fine.
