### ISSUE TITLE
NativeModule.RNDeviceInfo is null

### ISSUE THREAD

**Issue by h-github** [react-native-community/react-native-device-info#925]
**# Bug**

ran expo start to test my app (react-native: 0.61.4) in an ios phone. I got the error below in the 
RN debugger.

**## Environment info**

"dependencies": {
    "@expo/samples": "~36.0.0",
    "@expo/status-bar-height": "0.0.1",
    "@expo/vector-icons": "~10.0.0",
    "@react-navigation/web": "~1.0.0-alpha.9",
    "@types/node": "~12.12.17",
    "expo": "~36.0.0",
    "expo-ads-admob": "~8.0.0",
    "expo-asset": "~8.0.0",
    "expo-blur": "~8.0.0",
    "expo-constants": "~8.0.0",
    "expo-device": "~2.0.0",
    "expo-font": "~8.0.0",
    "expo-web-browser": "~8.0.0",
    "hoist-non-react-statics": "~3.3.1",
    "lodash": "^4.17.14",
    "moment": "^2.22.2",
    "prop-types": "~15.7.2",
    "react": "~16.9.0",
    "react-devtools": "~4.2.1",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-device-info": "5.4.0",
    "react-native-dropdownalert": "~4.2.0",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-picker-select": "~6.3.3",
    "react-native-reanimated": "~1.4.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-svg": "9.13.3",
    "react-native-swipeout": "~2.3.6",
    "react-native-web": "~0.11.7",
    "react-navigation": "4.0.10",
    "react-navigation-stack": "1.10.3",
    "react-navigation-tabs": "2.6.2",
    "react-redux": "~7.1.3",
    "redux": "~4.0.4",
    "redux-logger": "~3.0.6",
    "redux-saga": "~1.1.3"
  }

**React native info output:**

Error: @react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null. To fix this issue try these steps:
  • For react-native <= 0.59: Run `react-native link react-native-device-info` in the project root.
  • Rebuild and re-run the app.
  • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.

**Comment by gochinj** [comment]
Same issue running RN: 0.59.8, and react-native-device-info: ^5.4.0

**Comment by mikehardy** [comment]
I don't support expo, sorry. Expo and native modules aren't happy together

If you can reproduce it with the example from this project, then we can examine and fix
