### ISSUE TITLE
Jest setup not valid when importing ES6 modules

### ISSUE THREAD

**Issue by jefflewis** [react-native-community/react-native-device-info#926]
# Bug

When importing functions with ES6 modules and running jest tests, `NativeModules.RNDeviceInfo` is not defined. 

## Environment info

React native info output:

```bash
info Fetching system and libraries information...
System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 1.27 GB / 16.00 GB
    Shell: 2.7.1 - /usr/local/bin/fish
  Binaries:
    Node: 10.14.0 - ~/.config/fnm/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-git-upgrade: 0.2.7
```

Library version: 5.4.0

## Steps To Reproduce

1. Install the library
2. Use in a component and create a jest test for it.
3.  Use the device info library, importing a function as an ES6 module.
...

Describe what you expected to happen:

1. Test to not error for NativeModules error

**Comment by mikehardy** [comment]
https://github.com/react-native-community/react-native-device-info/issues?q=is%3Aissue+sort%3Aupdated-desc+jest+is%3Aclosed ?

**Comment by mikehardy** [comment]
(jest will always require mocking for native things)

**Comment by jefflewis** [comment]
Yea, I mocked it for my project. But that answer seems to go against the idea behind this change.

https://github.com/react-native-community/react-native-device-info/pull/375

It would be nice if those functions were stubbed inside this project instead of having each consumer do so.

**Comment by mikehardy** [comment]
Wow, that was all a long time ago. I remember now though. I did not like the empty polyfill as a separate file because people that made PRs always forgot to include that one in API changes. It was a "DX" (developer-experience) trap here. So I like the combined file much more but I suppose it is not handling testing now for some reason? At the same time, all the methods that go native should be wrapped in platform check logic, so I'm not sure why it isn't working.

**Comment by jefflewis** [comment]
Yea, I couldn't figure out why it _didn't_ work. Maybe a simple DX approach would be to add a "Testing with Jest" section to the readme that has the mock ready for copy/pasting? I grabbed the export from that commit and dropped it into my project and was ready to go. 

It would still require some additional maintenance, but would maybe encourage some helpful PRs to update the readme instead of Issues that complain about it failing the test? 

Either way, this issue should stay closed. Thanks for taking a look!

**Comment by mikehardy** [comment]
PRs to the README happily accepted :sweat_smile: :pray:
