### ISSUE TITLE
App crashes after npm install

### ISSUE THREAD

**Issue by diegoaraujolima** [react-native-community/react-native-device-info#928]
# Bug

## Environment info

React native info output:

```bash
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    Memory: 5.84 GB / 15.89 GB
  Binaries:
    Node: 13.1.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 24.0.3, 25.0.0, 25.0.1, 25.0.2, 26.0.1, 27.0.3, 28.0.1, 28.0.3, 29.0.0, 29.0.2
      System Images: android-24 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.4 => 0.61.4
```

Library version: 5.4.0

## Steps To Reproduce

1. Run npm install package
2. Run react-native run-android
...

Describe what you expected to happen:

1. Application open normally.

**Comment by Johan-dutoit** [comment]
Can't see why your issue is related to this package.
Also no information about the error, etc.

**Comment by diegoaraujolima** [comment]
But the error occour after install react-native-device-info. On run react-native run-android the app crashes.

**Comment by mikehardy** [comment]
what did logcat say about the crash?
can you reproduce with the example app?

If you were troubleshooting, in other words, would you have the information you needed to help?

**Comment by diegoaraujolima** [comment]
I try view logcat and show only this:

--------- beginning of crash
--------- beginning of system
--------- beginning of main
01-09 12:15:51.352 16651 16651 D ReactNative: ReactInstanceManager.ctor()

**Comment by mikehardy** [comment]
no stack trace is suspicious. likely a filtered logcat instead of raw (like just running `adb logcat` from the terminal)

I want to be clear though: this project is used by hundreds of thousands of people. I use it personally (not just maintain it). And it works. You have a project-related problem, there is not a problem with the module. We're attempting to help you troubleshoot it here, but you'll have to be resourceful with your use of debugging tools, and with comparing to the example etc to find where in your project the integration went wrong.

**Comment by mikehardy** [comment]
posting a reproducible example via a fresh github repo might help as well, but I'd start with trying the example project here first to show it works

**Comment by diegoaraujolima** [comment]
Of course, I understand.  if I upload the whole project here can this help?  I'm new to ReactNative, so I don't know how to use all the tools.

**Comment by mikehardy** [comment]
I would go for a minimal example. The thing is, this module already sort of includes one - and in a way that if you clone this module and run this script https://github.com/react-native-community/react-native-device-info/blob/master/refresh-example.sh it actually rebuilds the whole thing from scratch anyway - and it runs? So I'd really start with trying that sort of thing - just creating a sample app from the built-in react-native template and doing a test integration of react-native-device-info before going further

It should work

Then you'll have something to compare with your project to see what the differences are

**Comment by diegoaraujolima** [comment]
Ok, I will try.

**Comment by diegoaraujolima** [comment]
I created a new project and re-installed the package. Now the application no longer crashes, but now when I run and paste import it gives the message "undefined Unable to solve module 'react-native-device-info.'"

**Comment by diegoaraujolima** [comment]
I created a new project and re-installed the package. Now the application no longer crashes, but now when I run and paste import it gives the message "Error: @react-native-community/react-native-device-info: NativeModule.RNDDeviceInfo is null."

**Comment by mikehardy** [comment]
@diegoaraujolima I am sorry but I can't help developers troubleshoot their own integration issues. The example works, and you should study it to see how so that your project can work. 

Honestly I'm not sure how that even works as the dependency should not have the react-native-community in the name

yarn add react-native-device-info is it

**Comment by diegoaraujolima** [comment]
Hello, I discovered the error. The problem happened when I tried to install the react-native-navigation library. After her installation no package worked anymore. The point is that I did all the procedures to install it correctly. However this is no longer your problem anymore. Anyway thank you for your help.
