### ISSUE TITLE
Cannot use this Librairy

### ISSUE THREAD

**Issue by JCHEG** [react-native-community/react-native-device-info#930]
I am beginning with using React-native and I didn't manage to display the android id on android studio emulator.
My config is 
- react-native-cli: 2.0.1
- node  v12.13.1
- react-native: 0.61.4

My package.json
`{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/masked-view": "0.1.5",
    "expo": "~36.0.0",
    "moment": "^2.24.0",
    "numeral": "^2.0.6",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-device-info": "^5.4.1",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-reanimated": "~1.4.0",
    "react-native-safe-area-context": "0.6.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-web": "~0.11.7",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^2.0.14",
    "react-navigation-tabs": "^2.7.0",
    "react-redux": "^7.1.3",
    "redux": "^4.0.5"
  },
  "devDependencies": {
    "@babel/core": "^7.8.0",
    "babel-preset-expo": "~8.0.0"
  },
  "private": true
}`
I typed "react-native link react-native-device-info" but it didn't help me.

The component is 
`import React from 'react'
import { StyleSheet, Text } from 'react-native'
import FilmList from './FilmList'
import { connect } from 'react-redux'
import DeviceInfo from 'react-native-device-info';

class Favorites extends React.Component {

  render() {
    DeviceInfo.getAndroidId().then(androidId => {
      console.log(androidId);
    });
    return (
      <FilmList
        films={this.props.favoritesFilm}
        navigation={this.props.navigation}
        favoriteList={true}
      />
    )
  }
}

const styles = StyleSheet.create({})

const mapStateToProps = state => {
  return {
    favoritesFilm: state.favoritesFilm
  }
}

export default connect(mapStateToProps)(Favorites)`

I don't know why i have an error displayed:
"NativeModule.RNDeviceInfo is null"

Thanks alot for your help

JC

**Comment by mikehardy** [comment]
Hi there!

You haven't installed the library correctly.

https://github.com/react-native-community/react-native-device-info/blob/master/src/internal/nativeInterface.ts#L20

If you look at the example in this project (and attempt to build+run it) you will see it works, but installing native modules in react-native is an art that takes a little bit of time to master as a beginner - I do remember that.
