### ISSUE TITLE
Warning: Possible Unhandled Rejection (id: 0) blocking UI from rendering on iOS emulator

### ISSUE THREAD

**Issue by RageBill** [react-native-community/react-native-device-info#931]
# Bug

I got this warning: "Possible Unhandled Promise Rejection (id: 0)" (note: not the red error screen) and either the app freezes at splash screen on app startup or get a blank screen with the warning stated on reload.

I have singled out the problem and found that this problem (blocking my UI from rendering) is because of some of the methods I used from react-native-device-info:

```javascript
Device.deviceHasNotch = DeviceInfo.hasNotch();
Device.deviceId = DeviceInfo.getUniqueId();
Device.deviceModel = DeviceInfo.getDeviceId();
Device.deviceName = await DeviceInfo.getDeviceName();
Device.deviceCarrier = await DeviceInfo.getCarrier();
```

You can suppose that I have a class called "Device" just to save these information called from react-native-device-info.

However, not all method blocks the UI from rendering, for example, this one below does not cause a problem for me:

```javascript
Device.deviceManufacturer = await DeviceInfo.getManufacturer();
```

This error, as far as I believe, seems to be similar issue as [#793](https://github.com/react-native-community/react-native-device-info/issues/793#issue-494557857) which was marked as closed. However, the problem still persists for me even though I am using the latest release v5.4.1.

## Environment info

React native info output:

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 2.82 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.13.0 - ~/.nvm/versions/node/v11.13.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.11.2 - ~/.nvm/versions/node/v11.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.0, 29.0.1
      System Images: android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
      Android NDK: 20.1.5948944
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 5.4.1

## Steps To Reproduce

This problem only exists when:

[1] The app is in dev environment on an iOS emulator (not for Android).

[2] This only happens when the project is run from "react-native run-ios" using command line. If you run it from Xcode using the play button, this problem does not happen.

1. Create a top-level component, with the following componentDidMount method:

```javascript
async componentDidMount() {
    try {
        Device.deviceHasNotch = DeviceInfo.hasNotch();
        Device.deviceId = DeviceInfo.getUniqueId();
        Device.deviceModel = DeviceInfo.getDeviceId();
        Device.deviceName = await DeviceInfo.getDeviceName();
        Device.deviceCarrier = await DeviceInfo.getCarrier();
    } finally {
        SplashScreen.hide();
    }
}
```

Here, I was using a class called "Device" exported in another file to store these information, sample code could be:

```javascript
export class Device {
   public static deviceHasNotch = false;
   public static deviceId = "";
   public static deviceModel = "";
   public static deviceName = "";
   public static deviceCarrier = "";
}
```

2. Put this component inside `AppRegistry.registerComponent()`.

3. Run the app using `react-native run-ios` (note: do not run the app directly from Xcode workspace).

4. The app freezes at the splash screen without any feedback / warnings / errors.

5. To see the warning stated, first, we need to comment out the codes inside componentDidMount we mentioned in step (1).

6. After the UI renders normally, uncomment the code and do a reload.

7. This time, since we are already past the splash screen, the app shows a blank screen instead with the warning of "Possible Unhandled Rejection (id: 0)".

## Describe what you expected to happen:

The UI renders normally without freezing at the splash screen / showing a blank screen.

**Comment by mikehardy** [comment]
It looks like you are using APIs that return a Promise but not using them in an async way?

Examine the example to see how to use the APIs - they all work

**Comment by mikehardy** [comment]
(worth mentioning perhaps: I also use a splash screen and load lots of device info prior to rendering anything - I also run as run-ios from command line all the time - none of that is actually material I do not think - I am pretty certain this is just APIs not being used correctly and the example will show how to use correctly)
