### ISSUE TITLE
@react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null

### ISSUE THREAD

**Issue by irohitb** [react-native-community/react-native-device-info#935]
# Bug

## Environment info

React native info output:

```bash
System:
    OS: macOS Mojave 10.14
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 51.29 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v10.15.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    Android SDK:
      API Levels: 21, 23, 26, 27, 28
      Build Tools: 23.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
      System Images: android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5014246
    Xcode: 10.0/10A255 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 5.4.1

## Steps To Reproduce

**Steps ** 

1. npx react-native init {project-name} 
2. npm install --save react-native-device-info
3. cd ios 
4. pod install 
5. in my app.js, imported the following line `import DeviceInfo from 'react-native-device-info';`

**Error** 
Error: @react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null. To fix this issue try these steps:
  • For react-native <= 0.59: Run `react-native link react-native-device-info` in the project root.
  • Rebuild and re-run the app.
  • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
  If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-device-info
reportException @ ExceptionsManager.js:44

Describe what you expected to happen:

1. Wasn't expecting any error

## Reproducible sample code

 **Minimal Repo With Bug**

https://github.com/irohitb/dummy-info-bug-repo

**Comment by AbhijeetShinde1** [comment]
can you share the solution? If you resolve this

**Comment by irohitb** [comment]
@AbhijeetShinde1 it's been long time, I would say open a new issue and add the url in comment. If I can recall anything, I will help you out.

**Comment by mikehardy** [comment]
If native modules are null, it is always and forever a project specific issue, specifically the module is not integrated correctly. There is an example in this repo, clone it and run it, then do what it does in order to integrate it successfully into your project.
