### ISSUE TITLE
Build throwing warning on @available

### ISSUE THREAD

**Issue by codecog** [react-native-community/react-native-device-info#937]
Forcing pods to use iOS 11 as the deployment target, produces this warning during build:

`react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:380:9: @available does not guard availability here; use if (@available) instead [-Wunsupported-availability-guard]`

**Comment by mikehardy** [comment]
PRs welcome :-)

**Comment by codecog** [comment]
Will see if i can get to it. Just flagging for now.

**Comment by codecog** [comment]
PR Opened: https://github.com/react-native-community/react-native-device-info/pull/938

**Comment by mikehardy** [comment]
will be in the next release -> +10 internet points for @codecog  😄
