### ISSUE TITLE
Adding Huawei P Smart to the Devices.hasNotch List

### ISSUE THREAD

**Issue by sanborN93** [react-native-community/react-native-device-info#944]
# Question

Please add the Huawei P Smart to the List of Devices with Notch.

https://media.real-onlineshop.de/images/items/1024x1024/b40c48dc68ff4ca2ad56188fc07f4b45.jpg

The device has a front camera which should be recognized as Notch. I am using the device as a test device and have some bugs because the device has the front camera and is not recognized as a notch by your system.

**Comment by mikehardy** [comment]
Hi, please provide a PR and I'll merge it

**Comment by sanborN93** [comment]
I'm actually not sure where i need to implement it.

Is adding this to the devicesWithNotch.ts enough?
{
    brand: 'Huawei',
    model: 'POT-LX1',
  },

**Comment by mikehardy** [comment]
it should be, then you should test it to make sure it works (you should be able to hack on the file directly in node_modules and run the 'build' target to check it)

**Comment by sanborN93** [comment]
It works!

**Comment by mikehardy** [comment]
Excellent, propose a PR for it and you get all the CHANGELOG credit and internet points 🏆  😄

**Comment by sanborN93** [comment]
I am not working with github right now. I am working on my own git environment. Would be a pain in the ass to set this up, just for adding these 2 lines of code, am i right?

**Comment by sanborN93** [comment]
alright i got it. I proposed a PR.

**Comment by mikehardy** [comment]
You can actually just edit files like this directly in the github UI then install from your github in your package.json to test if that's easier, but sounds like you got it - thanks
