### ISSUE TITLE
java.lang.InternalError: Invoking <init> with bad arg 1, type 'Lcom/facebook/react/bridge/WritableNativeMap;' not instance of 'Ljava/lang/String;'

### ISSUE THREAD

**Issue by luckyzwei** [react-native-community/react-native-device-info#948]
# Bug

When I add react-native-device-info , and not use it.

02-02 17:36:01.513  2199  2199 E AndroidRuntime: java.lang.InternalError: Invoking <init> with bad arg 1, type 'Lcom/facebook/react/bridge/WritableNativeMap;' not instance of 'Ljava/lang/String;'
02-02 17:36:01.513  2199  2199 E AndroidRuntime:        at com.learnium.RNDeviceInfo.RNDeviceModule.sendEvent(RNDeviceModule.java:825)
02-02 17:36:01.513  2199  2199 E AndroidRuntime:        at com.learnium.RNDeviceInfo.RNDeviceModule.access$500(RNDeviceModule.java:67)
02-02 17:36:01.513  2199  2199 E AndroidRuntime:        at com.learnium.RNDeviceInfo.RNDeviceModule$1.onReceive(RNDeviceModule.java:104)
02-02 17:36:01.513  2199  2199 E AndroidRuntime:        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:881)
02-02 17:36:01.513  2199  2199 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
02-02 17:36:01.513  2199  2199 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
02-02 17:36:01.513  2199  2199 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
02-02 17:36:01.513  2199  2199 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5539)
02-02 17:36:01.513  2199  2199 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-02 17:36:01.513  2199  2199 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
02-02 17:36:01.513  2199  2199 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)

## Environment info
"react-native": "0.61.5",
"react-native-device-info": "^5.4.4",

React native info output:
None

**Comment by mikehardy** [comment]
Hi there! Thanks for reporting this. I just fixed it with 1f1ed2b and it is released as 5.5.1 - please test and confirm?

**Comment by mikehardy** [comment]
should be testable by registering the listener then plugging in or unplugging I think

**Comment by luckyzwei** [comment]
> Hi there! Thanks for reporting this. I just fixed it with [1f1ed2b](https://github.com/react-native-community/react-native-device-info/commit/1f1ed2b4c9fbc7a14c70caa31038277ea71a4dff) and it is released as 5.5.1 - please test and confirm?

I test it, and it's ok now, tks very much
