### ISSUE TITLE
TypeError: _reactNativeDeviceInfo.default.getTimezone is not a function. (In '_reactNativeDeviceInfo.default.getTimezone()',

### ISSUE THREAD

**Issue by preethypt** [react-native-community/react-native-device-info#949]
After upgrading the react-native-device-info I am getting the below warning. Can anyone let me know how to fix this using this package?

```
react-native-cli: 2.0.1
react-native: 0.59.8

```

**Upgraded version from** 

 ` "react-native-device-info": "^2.3.1",  to     "react-native-device-info": "^5.4.3",`

 **Possible Unhandled Promise Rejection (id: 0):
TypeError: _reactNativeDeviceInfo.default.getTimezone is not a function. (In '_reactNativeDeviceInfo.default.getTimezone()', '_reactNativeDeviceInfo.default.getTimezone' is undefined)**

**Comment by mikehardy** [comment]
Looks like you haven't upgraded in a while. If you go through major version numbers that implies breaking changes, consultation of the changelog will explain https://github.com/react-native-community/react-native-device-info/blob/master/CHANGELOG.md#300-beta1

Also there are migration guides linked in the readme, please use the docs
