### ISSUE TITLE
Task :react-native-device-info:generateDebugBuildConfig FAILED

### ISSUE THREAD

**Issue by iamir4g** [react-native-community/react-native-device-info#951]
# Bug

when i update from version 2 to current version after run react-native run-android 
get this error :

`Task :react-native-device-info:generateDebugBuildConfig FAILED`

## Environment info

React native info output:

```bash
 //  * What went wrong:
Execution failed for task ':react-native-device-info:generateDebugBuildConfig'.
> java.nio.file.AccessDeniedException: .../node_modules/react-native-device-info/android/build/generated/source/buildConfig/debug/com/learnium/RNDeviceInfo/BuildConfig.java
```
last version : 2.3.2
Library version: 5.5.1
"react": "16.9.0",
"react-native": "0.61.5",

**Comment by iamir4g** [comment]
I fix this issue 
cd android
```
sudo ./gradlew clean
cd ..
react-native run-android
```

**Comment by dev-louis-2022** [comment]
Thank you, I couldn't solve it for an hour, but I solved it this way. But I still don't know what gradlew clean does. I will study!
