### ISSUE TITLE
How to get android market model name?

### ISSUE THREAD

**Issue by franmio** [react-native-community/react-native-device-info#954]
Im using a Samsung Galaxy S9 and I dont find any way to get that name. How can I do it? Thanks!

**Comment by mikehardy** [comment]
Please run the example and examine the code + output

**Comment by ChauVV** [comment]
Example: i use Samsung s10

DeviceInfo.getModel()
log: 
SM-G973F

some device:
i can not get device model name.
it return device model number.

**Comment by mikehardy** [comment]
@ChauVV as an open source module, you can see the exact methods we are calling against the Android SDK. If there is some deficiency in those, we welcome PRs to correct them. If there is some odd vendor choice on implementation, that's mobile development in my experience
