### ISSUE TITLE
[5.5.0] getInstallReferrer reqiure READ_PHONE_STATE and WRITE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by Bardiamist** [react-native-community/react-native-device-info#955]
# Question
Hello my app was to require `READ_PHONE_STATE` and `WRITE_EXTERNAL_STORAGE` permissions on Android after update to `5.5.0`.

I checked in [this commit](https://github.com/react-native-community/react-native-device-info/commit/ce8a85196990e2739410a5c9752eaf8190421ab8) extra permissions not required.
Then can't build [this commit](https://github.com/react-native-community/react-native-device-info/commit/be42ff860b47c5f8899d8075e03c682ba7db2f9b) and after build [next commit](https://github.com/react-native-community/react-native-device-info/commit/d63f18a47247b98e9cc4cdad9b43c3270acba459) in my `android/app/build/intermediates/bundle_manifest/debug/processDebugManifest/bundle-manifest/AndroidManifest.xml` added:
```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_PHONE_STATE" />
```

I don't use `getInstallReferrer` and don't want request extra permissions form user. Can it be excluded?

**Comment by mikehardy** [comment]
So you want something like this in your AndroidManifest:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" 
  xmlns:tools="http://schemas.android.com/tools" package="com.kullki.kscore">

  <uses-permission tools:node="remove" android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission tools:node="remove" android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

```

**Comment by mikehardy** [comment]
(for the permissions you care about though of course - that's just the "how" to do it)

**Comment by Bardiamist** [comment]
Yea, I'm just trying to use `tools:node="remove"`.

Is it good solution enough? And will not cut permissions if other dependencies are required this permissions? So no ideas to remove these permissions from `react-native-device-info` by default?

Thank you.

**Comment by Bardiamist** [comment]
@mikehardy 

Note, that also added:
```
<uses-permission android:name="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

**Comment by mikehardy** [comment]
everyone's project is different. making them optional is a possibility, sure, I'm always open to PRs

**Comment by Bardiamist** [comment]
I rolled back to 5.4.4 because can't remove `com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE` permission. Have crash if try.

Unfortunelly I'm not Android developer and don't know how to make these permissions optional.

@skantus Please pay attention on this issue.
Not good to request extra permissions from user:( Hope it gets better soon.

**Comment by mikehardy** [comment]
https://issuetracker.google.com/issues/78380811#comment22

You should be able to remove it yes. @skantus perhaps you could check for the permission before attempting to use it, and only attempt to use it after verifying the permission is granted?

**Comment by mikehardy** [comment]
I could not reproduce a crash @Bardiamist when I altered the example to remove the permission. Could you post a stack trace or a public github repo based on the example that demonstrates the crash?

**Comment by Bardiamist** [comment]
@mikehardy 

### Steps to reproduce
1. `react-ntaive init`
2. `yarn add react-native-device-info`
3. `<uses-permission android:name="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE" tools:node="remove" />`
4. Build by Android studio on device (no emulator)

Or you can clone [this repo](https://github.com/Bardiamist/rn_device_info_permissions)

[Screenshots of stack trace and device info](https://imgur.com/a/sO0PLuW)

**Comment by mikehardy** [comment]
Thanks for the repro steps - the real device was the key - I was able to see it just not on an emulator strangely enough. Should have a fix soon

**Comment by mikehardy** [comment]
v5.5.2 is out now with the fix, give it a whirl and please let me know if that works for you, cheers @Bardiamist

**Comment by Bardiamist** [comment]
Yes, I can to remove all unused permissions now
```
<!-- https://github.com/react-native-community/react-native-device-info/issues/955 -->
    <uses-permission android:name="android.permission.READ_PHONE_STATE" tools:node="remove" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="remove" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" tools:node="remove" />
    <uses-permission
      android:name="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE"
      tools:node="remove" />
```

It would be nice to not have these permissions by default but it's ok now.

Thank you, you are one of the best maintainers in the community:)
