### ISSUE TITLE
Not compatible with react-native-file-share-intent

### ISSUE THREAD

**Issue by nschild** [react-native-community/react-native-device-info#957]
# Bug

I'm not sure why, but this is not compatible with react-native-device-info.

I have an environments.ts file that calls a few of the methods:
```
export const ENVIRONMENT_APP_VERSION = DeviceInfo.getVersion();
export const ENVIRONMENT_APPLICATION_ID = DeviceInfo.getBundleId() || '';
export const ENVIRONMENT_BUILD_ENVIRONMENT: 'DEV' | 'STAGE' | 'PROD' = BUILD_ENVIRONMENT;
export const ENVIRONMENT_DEVICE_UNIQUE_ID =DeviceInfo.getUniqueId();
```
And when I bring up the share intent, it self closes within miliseconds.

If I comment out the DeviceInfo methods and replace them with an empty string, it opens just fine.

Has anyone else had this issue, and how do I fix it?

Cross-posting here: https://github.com/ajith-ab/react-native-file-share-intent/issues/23

## Environment info

React native info output:

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 53.29 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.11.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.2, 26.0.2, 27.0.3, 28.0.1, 28.0.3
      System Images: android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: 19.2.5345600
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```
react-native-device-info: 5.5.1
react-native-file-share-intent: 1.1.2

iPhone XR: 13.3.1

## Steps To Reproduce

1. Create a new RN project
2. Install react-native-device-info & react-native-file-share-intent
3. In your Share.js, make use of a device info method (ie: DeviceInfo.getVersion())
4. Compile a release build on IOS and run

Describe what you expected to happen:

1.  It to open and render correctly

## Reproducible sample code

I'll post if needed

**Comment by mikehardy** [comment]
If I understand correctly, getUniqueId should be async/await or you'll want to use getUniqueIdSync

Either way, I'll definitely need to see a clean minimal reproduction of this

react-native-file-share-intent has 40 downloads a week. There are 140,000+ downloads a week here. I'm pretty sure this module works in almost all cases, but I'm prepared to be surprised

**Comment by mikehardy** [comment]
I think you're missing async. Either way no feedback.
