### ISSUE TITLE
How to avoid multi-accounting

### ISSUE THREAD

**Issue by losheredos** [react-native-community/react-native-device-info#960]
Hello! 

Thanks for this nice library, helps me a lot in my projects! As React Native developer I have my apps mostly text based games. In my games players try to cheat with multi accounting etc. 

I normally use unique device id to identify if they are unique players but after many cheaters I noticed that programs like parallel space just clons the app let them use multi accounts. In this case I switched to server controlls checking their IP adresses in API requests but still may not be enough(cuz they may change it with different programs I suppose).

In this case is there a any tested API of this library to avoid multi accounting, programs like parallel-space? Is anyone had issue like I have? I would be very happy to learn or get any ideas/methods.

**Comment by joshuakoh7** [comment]
What did you settle for?

**Comment by cryptic-dev** [comment]
Hello, I had a similar problem developing an app some time ago and came up with a solution for it on android.

basically all you have to do is check where the app is installed. 

- Your app running regularly will have a path of ....../com.your.app
- Your app inside parallel space or similar will have a path of ....../com.parallel.space/com.your.app

All I did was get the installation path of my app and using regex detect patterns of com(dot)string(dot)string. If
the regex matches more than one result then its inside parallel apps or similar
