### ISSUE TITLE
Using the library on web

### ISSUE THREAD

**Issue by m0hamm3d-ac** [react-native-community/react-native-device-info#961]
Hi Folks,

I have a project which is using common code for native and web. I am trying to use this library to pull the userAgent information on the 3 platforms - iOS, Android and Web.
My project has been setup to use 'metro-react-native-babel-preset'. 

When I run the code i get the following error - 
Module../node_modules/react-native-device-info/lib/module/internal/nativeInterface.js
TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
   5 | 
   6 | // @ts-ignore
   7 | if (Platform.OS === 'web' || Platform.OS === 'dom') {
>  8 |   RNDeviceInfo = require('../web');
   9 | }
  10 | 
  11 | if (!RNDeviceInfo) {

Is there any configuration I am missing to use this on web?

thanks,
mohammed

**Comment by mikehardy** [comment]
@m0hamm3d-ac sorry - this library under my maintainership has not had a good web focus at all, as I don't use it that way personally yet so I sometimes miss that it is completely broken even. If you'll look at the PR queue here you'll see there are a couple from @robertherber which look great and are on-deck for merge but I haven't had time yet and am actually traveling now for the next week, so won't have time for a while either. If you could check them to see if they address your concern and/or potentially collaborate with Robert, I'm definitely to anything that helps with the web support, including taking on anyone that is willing to commit to it as a maintainer here - the more people helping the merrier

**Comment by m0hamm3d-ac** [comment]
@mikehardy  thanks for your response. I will have a look at @robertherber 's PRs and see if I can fix the issue and raise a pull request. I will close this issue and add an update if required.

**Comment by VasilUrda** [comment]
I am having same issue now.
