### ISSUE TITLE
make getModel() value shorter name in iOS

### ISSUE THREAD

**Issue by rangav** [react-native-community/react-native-device-info#963]
# Feature Request

The getModel() value is very longer for some devices.

## Why it is needed

For Analytics the device model names are very long, its better to make them shorter.

## Possible implementation
example model name: **iPad Pro 12.9-inch (3rd generation)**
replace **generation** with **gen** keyword
and remove **-inch** keyword

### Code sample
we can modify is js or ios obj-c code

```
export function getModel() {
  if (!model) {
    if (Platform.OS === 'ios' || Platform.OS === 'android' || Platform.OS === 'windows') {
      model = RNDeviceInfo.model;
    } else {
      model = 'unknown';
    }
  }

// here the modification done
  return model.replace("generation", "gen").replace("-inch", "");
}
```

**Comment by mikehardy** [comment]
All the analytics libraries I know track device type for you. That said is it actually overflowing a field? This module is in wide use and it's the first we've heard of this as a problem which seems odd

**Comment by rangav** [comment]
In google analytics it dosen’t track the device model, so I have to pass a custom dimension value, 

So I am using this getModel func. The names appeared to be very long. 

So it’s just a suggestion.

**Comment by mikehardy** [comment]
If they overflow I can understand it, but long is inconsequential I think
