### ISSUE TITLE
hasNotch return false in samsung A30

### ISSUE THREAD

**Issue by ShuKTan** [react-native-community/react-native-device-info#968]
I am using react-native-device-info in my react native app. Testing in Samsung A30 (Real Device). And it returns false while calling hasNotch().

**Comment by mikehardy** [comment]
Can you propose a patch for it? There are merged PRs that show roughly how to do it, like this - it's really easy https://github.com/react-native-community/react-native-device-info/pull/959/files

If you alter the .ts file, I believe all you need to do is to call the react-native-device-info build which should work inside node_modules - https://github.com/react-native-community/react-native-device-info/blob/master/package.json#L32 to make sure it is tested + working

**Comment by braandl** [comment]
Same on basically all OnePlus and Huawei Devices :(

**Comment by mikehardy** [comment]
I look forward to a PR implementing the correct detection

**Comment by braandl** [comment]
I do not have a PR for you yet, but comparing screen with window size does the trick.

**Comment by danieltran3110** [comment]
I have the same issues with my Nokia x7 when calling hasNotch()

**Comment by mikehardy** [comment]
hasNotch failures require PRs that toggle it on for specific modules. Please send PRs
