### ISSUE TITLE
Using RNDeviceInfo on React Native 0.37.0

### ISSUE THREAD

**Issue by nHiRanZ** [react-native-community/react-native-device-info#970]
We're using RNDeviceInfo 0.24.3 in our Project. It's based on React Native 0.37.0 and React 15.3.1.

Since it's a huge just from 0.24.3 to the latest version, we thought of removing the library altogether and reinstalling it.

We ran the following commands.

```
react-native unlink react-native-device-info
npm uninstall --save react-native-device-info
```

And then used the following commands to reinstall the library.

```
npm install --save react-native-device-info
react-native link react-native-device-info
```

Once we do all this and try to run the app, we get `'React/RCTUtils.h' file not found` error. We tried to eliminate these by updating them as follows.

```
#import <React/RCTUtils.h> ----> #import "RCTUtils.h"
#import <React/RCTBridgeModule.h> ----> #import "RCTBridgeModule.h"
#import <React/RCTEventEmitter.h> ----> #import "RCTEventEmitter.h"
#import <React/RCTLog.h> ----> #import "RCTLog.h"
```

This eliminated the import issues. But then the following errors came up.

> Showing All Errors Only
> /Users/apptizer/projects/order-ahead-app/ios-retail-template/node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:415:9: Implicit declaration of function 'RCTUnsafeExecuteOnMainQueueSync' is invalid in C99
> 
> /Users/apptizer/projects/order-ahead-app/ios-retail-template/node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:135:12: Use of undeclared identifier 'self'
> 
> /Users/apptizer/projects/order-ahead-app/ios-retail-template/node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:303:1: Redefinition of 'RCT_EXPORT_BLOCKING_SYNCHRONOUS_METHOD'
> 
> /Users/apptizer/projects/order-ahead-app/ios-retail-template/node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:304:12: Use of undeclared identifier 'self'
> 
> /Users/apptizer/projects/order-ahead-app/ios-retail-template/node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:330:1: Redefinition of 'RCT_EXPORT_BLOCKING_SYNCHRONOUS_METHOD'
> 
> /Users/apptizer/projects/order-ahead-app/ios-retail-template/node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:331:12: Use of undeclared identifier 'self'
> 
> /Users/apptizer/projects/order-ahead-app/ios-retail-template/node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:363:1: Redefinition of 'RCT_EXPORT_BLOCKING_SYNCHRONOUS_METHOD'
> 
> /Users/apptizer/projects/order-ahead-app/ios-retail-template/node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:364:14: Use of undeclared identifier 'self'
> 
> /Users/apptizer/projects/order-ahead-app/ios-retail-template/node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:436:1: Redefinition of 'RCT_EXPORT_BLOCKING_SYNCHRONOUS_METHOD'
> 
> /Users/apptizer/projects/order-ahead-app/ios-retail-template/node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:437:14: Use of undeclared identifier 'self'
> 
> /Users/apptizer/projects/order-ahead-app/ios-retail-template/node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:448:1: Redefinition of 'RCT_EXPORT_BLOCKING_SYNCHRONOUS_METHOD'
> 
> /Users/apptizer/projects/order-ahead-app/ios-retail-template/node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:449:14: Use of undeclared identifier 'self'
> 
> /Users/apptizer/projects/order-ahead-app/ios-retail-template/node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:467:1: Redefinition of 'RCT_EXPORT_BLOCKING_SYNCHRONOUS_METHOD'
> 
> /Users/apptizer/projects/order-ahead-app/ios-retail-template/node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:468:14: Use of undeclared identifier 'self'
> 
> /Users/apptizer/projects/order-ahead-app/ios-retail-template/node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:486:1: Redefinition of 'RCT_EXPORT_BLOCKING_SYNCHRONOUS_METHOD'
> 
> /Users/apptizer/projects/order-ahead-app/ios-retail-template/node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:487:14: Use of undeclared identifier 'self'
> 
> /Users/apptizer/projects/order-ahead-app/ios-retail-template/node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:505:1: Redefinition of 'RCT_EXPORT_BLOCKING_SYNCHRONOUS_METHOD'
> 
> /Users/apptizer/projects/order-ahead-app/ios-retail-template/node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:506:12: Use of undeclared identifier 'self'
> 
> /Users/apptizer/projects/order-ahead-app/ios-retail-template/node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:545:1: Redefinition of 'RCT_EXPORT_BLOCKING_SYNCHRONOUS_METHOD'
> 
> Too many errors emitted, stopping now

How to resolve this?

**Comment by mikehardy** [comment]
Did you also update react-native or not? I have no idea what to do with a version that old. I wouldn't even attempt to support react-native below 0.59 since you couldn't release it to the play store anyway and honestly I think rn0.60+ will be required in a few weeks because you need to build with Xcode11 / support iOS13 in order to release in April right?

So directly to the point: how to resolve this -> get current I believe, then the symbols you need will exist

**Comment by mikehardy** [comment]
I am going to close this, because in both the examples (rn59 / rn60) everything works. There is no problem with the module

**Comment by nHiRanZ** [comment]
> Did you also update react-native or not? I have no idea what to do with a version that old. I wouldn't even attempt to support react-native below 0.59 since you couldn't release it to the play store anyway and honestly I think rn0.60+ will be required in a few weeks because you need to build with Xcode11 / support iOS13 in order to release in April right?
> 
> So directly to the point: how to resolve this -> get current I believe, then the symbols you need will exist

Fair enough. Was trying to figure a way around the upgrade due to our timelines. :P
