### ISSUE TITLE
TypeError: Cannot read property 'disconnect' of undefined  react-native-bluetooth-serial next 

### ISSUE THREAD

**Issue by theali13** [react-native-community/react-native-device-info#979]
I imported the library as stated and performed linking however an error prevent the code from compiling
As soon as I comment the import line the compilation is complete
Can someone tell me what the issue is or if it has something to do with the library? 
Thank you in advance.

![Screenshot (195)](https://user-images.githubusercontent.com/43322124/77106621-11515380-6a28-11ea-8cff-b94954934c07.png)

**Comment by mikehardy** [comment]
Error shows react-native-bluetoot-serial-next?

**Comment by mikehardy** [comment]
Also: *please* post text. Images are difficult.

**Comment by theali13** [comment]
> Error shows react-native-bluetoot-serial-next?
Yes
after using npm install react-native-bluetooth-serial --save 
and import BluetoothSerial from "react-native-bluetooth-serial-next";

i get :


TypeError: Cannot read property 'disconnect' of undefined
Module.D:\Bluetooth\node_modules\react-native-bluetooth-serial-next\index.js
D:/Bluetooth/node_modules/react-native-bluetooth-serial-next/index.js:70
  67 | 
  68 | // Overloading
  69 | const {
> 70 |   disconnect,
  71 |   isConnected,
  72 |   readFromDevice,
  73 |   readUntilDelimiter,
View compiled
__webpack_require__
D:/Bluetooth/webpack/bootstrap:726
  723 | };
  724 | 
  725 | // Execute the module function
> 726 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  727 | 
  728 | // Flag the module as loaded
  729 | module.l = true;
View compiled
fn
D:/Bluetooth/webpack/bootstrap:100
   97 | 		);
   98 | 		hotCurrentParents = [];
   99 | 	}
> 100 | 	return __webpack_require__(request);
      | ^  101 | };
  102 | var ObjectFactory = function ObjectFactory(name) {
  103 | 	return {
View compiled
Module.D:\Bluetooth\src\containers\bluetooth-list.js
http://192.168.1.24:19006/static/js/bundle.js:145054:93
__webpack_require__
D:/Bluetooth/webpack/bootstrap:726
  723 | };
  724 | 
  725 | // Execute the module function
> 726 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  727 | 
  728 | // Flag the module as loaded
  729 | module.l = true;
View compiled
fn
D:/Bluetooth/webpack/bootstrap:100
   97 | 		);
   98 | 		hotCurrentParents = [];
   99 | 	}
> 100 | 	return __webpack_require__(request);
      | ^  101 | };
  102 | var ObjectFactory = function ObjectFactory(name) {
  103 | 	return {
View compiled
Module.D:\Bluetooth\src\scenes\AppStart.js
http://192.168.1.24:19006/static/js/bundle.js:145205:85
__webpack_require__
D:/Bluetooth/webpack/bootstrap:726
  723 | };
  724 | 
  725 | // Execute the module function
> 726 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  727 | 
  728 | // Flag the module as loaded
  729 | module.l = true;
View compiled
fn
D:/Bluetooth/webpack/bootstrap:100
   97 | 		);
   98 | 		hotCurrentParents = [];
   99 | 	}
> 100 | 	return __webpack_require__(request);
      | ^  101 | };
  102 | var ObjectFactory = function ObjectFactory(name) {
  103 | 	return {
View compiled
Module.D:\Bluetooth\src\App.js
http://192.168.1.24:19006/static/js/bundle.js:144561:75
__webpack_require__
D:/Bluetooth/webpack/bootstrap:726
  723 | };
  724 | 
  725 | // Execute the module function
> 726 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  727 | 
  728 | // Flag the module as loaded
  729 | module.l = true;
View compiled
fn
D:/Bluetooth/webpack/bootstrap:100
   97 | 		);
   98 | 		hotCurrentParents = [];
   99 | 	}
> 100 | 	return __webpack_require__(request);
      | ^  101 | };
  102 | var ObjectFactory = function ObjectFactory(name) {
  103 | 	return {
View compiled
Module.D:\Bluetooth\node_modules\expo\AppEntry.js
D:/Bluetooth/node_modules/expo/AppEntry.js:1
__webpack_require__
D:/Bluetooth/webpack/bootstrap:726
  723 | };
  724 | 
  725 | // Execute the module function
> 726 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  727 | 
  728 | // Flag the module as loaded
  729 | module.l = true;
View compiled
fn
D:/Bluetooth/webpack/bootstrap:100
   97 | 		);
   98 | 		hotCurrentParents = [];
   99 | 	}
> 100 | 	return __webpack_require__(request);
      | ^  101 | };
  102 | var ObjectFactory = function ObjectFactory(name) {
  103 | 	return {
View compiled
0
http://192.168.1.24:19006/static/js/bundle.js:14453:18
__webpack_require__
D:/Bluetooth/webpack/bootstrap:726
  723 | };
  724 | 
  725 | // Execute the module function
> 726 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  727 | 
  728 | // Flag the module as loaded
  729 | module.l = true;
View compiled
(anonymous function)
D:/Bluetooth/webpack/bootstrap:793
  790 | 
  791 | 
  792 | // Load entry module and return exports
> 793 | return hotCreateRequire(0)(__webpack_require__.s = 0);
      | ^  794 | 
View compiled
(anonymous function)
http://192.168.1.24:19006/static/js/bundle.js:797:10

**Comment by theali13** [comment]
> Also: _please_ post text. Images are difficult.

Sorry, I never posted an issue here before ....

Can you please help me resolve it ?

**Comment by mikehardy** [comment]
this is the react-native-device-info module. I have no idea about bluetooth-serial-next

**Comment by theali13** [comment]
> this is the react-native-device-info module. I have no idea about bluetooth-serial-next

I see... Do you know where can i post this issue ?

**Comment by theali13** [comment]
I see sorry I posted in the wrong place..

**Comment by mikehardy** [comment]
https://duckduckgo.com/?q=react-native-bluetooth-serial-next&ia=software
https://github.com/nuttawutmalee/react-native-bluetooth-serial-next
