### ISSUE TITLE
 Error: @react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null. To fix this issue try these steps:   • For react-native <= 0.59: Run `react-native link react-native-device-info` in the project root.   • Rebuild and re-run the app.   • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.anyway,not work

### ISSUE THREAD

**Issue by lidiwen** [react-native-community/react-native-device-info#981]
# Bug

## Environment info

`react-native info` output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

Describe what you expected to happen:

1.
2.

**Comment by mikehardy** [comment]
The error message is clear, the template is not followed, there is an example -> please give the example a try and after seeing it works, examine your project integration

**Comment by lidiwen** [comment]
> The error message is clear, the template is not followed, there is an example -> please give the example a try and after seeing it works, examine your project integration

Thank your reply

**Comment by kostiantyn-solianyk** [comment]
it's weird, but just simple install of `react-native-device-info` and on android got the same error.

**Comment by mikehardy** [comment]
@kostiantyn-solianyk clone the repo, run the example - works. Or if not, that's a problem, open a ticket

**Comment by Dagger05** [comment]
@mikehardy i am still getting the error:::
ExceptionsManager.js:82 Unhandled JS Exception: @react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null.
<img width="1260" alt="Screen Shot 2020-06-18 at 16 51 47" src="https://user-images.githubusercontent.com/46191541/85013361-299a5100-b184-11ea-8ac6-bd48a8e65510.png">

**Comment by mikehardy** [comment]
@Dagger05 then you are still not integrating the module successfully. If you have not successfully installed it, it can't work. Clone the repo and run the example, it will prove it works and also demonstrates how to integrate, as does the example construction script: https://github.com/react-native-community/react-native-device-info/blob/master/refresh-example.sh

Note that you have provided zero information about your project so it's impossible to really help. As a guess if you are using Expo managed workflow it will never work, as Expo is incompatible with native modules when in managed workflow
