### ISSUE TITLE
Android app has stopped 

### ISSUE THREAD

**Issue by co2nut** [react-native-community/react-native-device-info#982]
after running npm install --save react-native-device-info 

build successful but the simulator showing "Unfortunately, appName has stopped "

**Comment by mikehardy** [comment]
We have an issue template, you ignored it completely?
What does adb logcat say?
If you were debugging this, you'd need information like that to help, yes?

**Comment by Nuruzzamancse** [comment]
I am facing same issue.

**Comment by co2nut** [comment]
@Nuruzzamancse what is your simulator Android API version?

**Comment by mikehardy** [comment]
And the logcat says?

**Comment by co2nut** [comment]
hi, @mikehardy the log was too ling. 

I start it with a new project and running with a android simulator(Genymotion) with API(9.0).

1 thing to add on is to add a line for file
projectFolder/android/app/build.gradle

```js
defaultConfig {
        ...
        multiDexEnabled true
    }
```
