### ISSUE TITLE
Reduce dead code in a final bundle file

### ISSUE THREAD

**Issue by retyui** [react-native-community/react-native-device-info#984]
# Feature Request

```js
// Now
import {
    getSystemName,
    getSystemVersion,
    isTablet,
    getFreeDiskStorage,
    getUniqueId,
} from 'react-native-device-info';

// Need
import getSystemName from 'react-native-device-info/src/getSystemName';
import getSystemVersion from 'react-native-device-info/src/getSystemVersion';
import isTablet from 'react-native-device-info/src/isTablet';
import getFreeDiskStorage from 'react-native-device-info/src/getFreeDiskStorage';
import getUniqueId from 'react-native-device-info/src/getUniqueId';
```

## Why it is needed

I an example above I use only 5 functions but after in a final bundle would be all functions that declareted in [src/index.ts](https://github.com/react-native-community/react-native-device-info/blob/master/src/index.ts) **40Kb** 

## Possible implementation

Move all small functions to separate files and update `src/index.ts`
```js
import {default as getSystemName} from './getSystemName'
```

### Code sample

...

**Comment by mikehardy** [comment]
That seems like a massive code re-organization and number-of-files expansion. 40kb is 40kb but how do other projects handle this? Seems like a good bundler should handle this?

**Comment by retyui** [comment]
metro bundler can't optimize it

How to test:

```sh
react-native init codeSplitting
cd codeSplitting
yarn add react-native-device-info 
```
Create a file:
```js
// test.js
import {getUniqueId} from 'react-native-device-info';

getUniqueId();
```
Then create bundle:

```js
react-native bundle --entry-file test.js --bundle-output test.min.js --minify true --dev false --reset-cache
npx prettier --write test.min.js
```
And if you check result you will find that all code was still in bundle

```js
  function(g, r, i, a, m, e, d) {
    var t = r(d[0]);
    Object.defineProperty(e, "__esModule", { value: !0 }),
      (e.getUniqueId = oe),
      (e.getInstanceId = se),
      (e.getInstanceIdSync = ce),
      (e.getSerialNumber = ie),
      (e.getSerialNumberSync = fe),
      (e.getAndroidId = de),
      (e.getAndroidIdSync = le),
      (e.getIpAddress = Se),
      (e.getIpAddressSync = me),
      (e.isCameraPresent = pe),
      (e.isCameraPresentSync = ge),
      (e.getMacAddress = ye),
      (e.getMacAddressSync = Pe),
      (e.getDeviceId = be),
      (e.getManufacturer = we),
      (e.getManufacturerSync = Oe),
      (e.getModel = xe),
      (e.getBrand = ke),
      (e.getSystemName = ve),
      (e.getSystemVersion = he),
      (e.getBuildId = Ie),
      (e.getBuildIdSync = Ae),
      (e.getApiLevel = Be),
      (e.getApiLevelSync = Le),
      (e.getBundleId = Me),
      (e.getInstallerPackageName = Te),
      (e.getInstallerPackageNameSync = De),
      (e.getApplicationName = Fe),
      (e.getBuildNumber = Ce),
      (e.getVersion = Ne),
      (e.getReadableVersion = He),
      (e.getDeviceName = Ue),
//      ...
```

**Comment by mikehardy** [comment]
This still seems like a bundling fail to me. Unused code should be stripped, is my expectation. Going through unnatural contortions in code organization to help a bundler seems like the wrong direction. Have you chatted with the metro people about this? I'd really like to know why the bundler isn't stripping this before fracturing the library into one file for each function, that is not palatable

**Comment by retyui** [comment]
@mikehardy 
I found not resolved issue, where told that Metro don't support tree shaking
https://github.com/facebook/metro/issues/227#issuecomment-583358386

**Comment by mikehardy** [comment]
There are several compatible bundlers that do I believe? I did some research on this semi-recently and it looked like there were at least a couple, with webpack being one of them I think (there are also things like tsickle and google has a few things as well)

I hate to do this because dead code bothers me as well, but I can't in good conscious fracture the source this way - I'm going to close it wontfix and recommend using a bundler that can do what you want

**Comment by retyui** [comment]
@mikehardy That sad!
I found alternative bundler Haul but, his [limitations](https://github.com/callstack/haul#limitations) do not allow using it on a real project
