### ISSUE TITLE
getUserAgent() and getUserAgentSync() return different results

### ISSUE THREAD

**Issue by emeraldsanto** [react-native-community/react-native-device-info#985]
# Bug

When calling `getUserAgent()` and `getUserAgentSync()` on an iOS13.4 Simulator, I get the following results: 

- `unknown`
- `Mozilla/5.0 (iPhone; CPU iPhone OS 13_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`

## Environment info

```bash
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 327.73 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.12.0 - ~/.nvm/versions/node/v12.12.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.12.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tv
OS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.11.0 => 16.11.0 
    react-native: ^0.62.0 => 0.62.0 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.5.3

## Steps To Reproduce

1. Simply call both the async and sync methods
2. Log the results

Describe what you expected to happen:

Receive the same result from both functions.

## Reproducible sample code

```js
export default () => {
    useEffect(() => {
        console.log(DeviceInfo.getUserAgentSync());
        DeviceInfo.getUserAgent().then(agent => console.log(agent));
    }, []);

    return (
        <Fragment />
    );
}
```

**Comment by emeraldsanto** [comment]
I checked source code and it seems `getUserAgentSync` is not available on iOS and therefore defaults to `unknown`. Closing this as that's by design.

**Comment by njt1982** [comment]
Should probably mention that in the docs 😉 Just spent 30 mins wondering why my getUserAgentSync was unknown...

The tickbox grid indicates it it supported by ios
![image](https://user-images.githubusercontent.com/384976/143597960-e7f4eab4-ee80-4c12-98ec-e8e434c6520d.png)

(I appreciate that is the async, but there is nothing to indicate Sync behaves differently).

**Comment by mikehardy** [comment]
@njt1982 smack the edit pencil at the top of the doc and post a docs PR :-) :pray:

**Comment by demedos** [comment]
there you go 😄
