### ISSUE TITLE
isEmulator not work on Nox

### ISSUE THREAD

**Issue by daiquangduy** [react-native-community/react-native-device-info#987]
Hello. isEmulator() function can't detect when app run on Nox Emulator (return false).
How do I detect Emulator correctly? Thank you.

**Comment by mikehardy** [comment]
You may take up the work here perhaps, respond the comments and bring it to completion: https://github.com/react-native-community/react-native-device-info/pull/721 - the original author did not respond

**Comment by wellmonge** [comment]
@daiquangduy still not working at Nox?

**Comment by Great-hijack** [comment]
Still no solution?

**Comment by mikehardy** [comment]
@Great-hijack I look forward to your PR! I will happily merge it



> You may take up the work here perhaps, respond the comments and bring it to completion: #721 - the original author did not respond
