### ISSUE TITLE
I can't re-build my app after installing this module

### ISSUE THREAD

**Issue by Bayramito** [react-native-community/react-native-device-info#995]
Hi,

i just installed this module to my project but  somehow i can't re-build my app again.

Getting this error while building:

`FAILURE: Build failed with an exception.

* Where:
Build file '\node_modules\react-native-device-info\android\build.gradle' line: 60

* What went wrong:
A problem occurred evaluating project ':react-native-device-info'.
> Could not find method testImplementation() for arguments [org.junit.jupiter:junit-jupiter-api:5.5.2] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.`

and this is how my `android/build.gradle` looks like:

`buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion   = "28.0.0"
         playServicesVersion = "16.1.0" // or set latest version
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.2")

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}`

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}
`

**Comment by mikehardy** [comment]
If you can reproduce with the example and/or publish a reproducible example, I can look into it. But it builds and works both in my project and the example, so there's no way for me to know why it's failing in your project

**Comment by Bayramito** [comment]
what 

> If you can reproduce with the example and/or publish a reproducible example, I can look into it. But it builds and works both in my project and the example, so there's no way for me to know why it's failing in your project

what you do mean with reproducible example?   And what do you mean with "the example" ?

**Comment by mikehardy** [comment]
I mean this module comes with an example packaged into the source tree. You can see it. You can check it out and run it. It works.

A reproducible example would be you making a new react-native project, including this module, and that project did not work in some way, and you post that to github

**Comment by Bayramito** [comment]
Yes, i will do that now, but i dunno how this will help to me if it's not working on my own project :/

**Comment by mikehardy** [comment]
what you will (or should) see is that the example works.
what that will show you is that looking here (in the module) is not the problem
so it will focus your effort on looking at how your project is *different* then the module, which should lead you to find your project's problem

For me, that would simultaneously mean no action required, because the module works fine

**Comment by Bayramito** [comment]
I alredy didn't meant that the module isn't working. 

I just opened this thread becouse its not working on my project, and wanted to share some information about the error that i'm getting so, maybe you can find whats wrong. 

But seems like i have a major mistake or error somewhere in my own project.

Btw, thank you for quick response.

**Comment by Bayramito** [comment]
Now...

i have comment outed the lines 60 and 61 

 ```
  // testImplementation 'org.junit.jupiter:junit-jupiter-api:5.5.2'
    //testImplementation "org.mockito:mockito-core:2.28.2"
```
 
 in the `node_modules/react-native-device-info/android/build.gradle`

**Comment by mikehardy** [comment]
Unsure, those are standard test libraries, freely available to anyone. I've never hard a report of this problem despite 174,000 downloads a *month* (and I would assume more rebuilds than that). So with that as fairly strong evidence I can assert that the library works in 173,999 of the cases a month and you're the 1 it doesn't, which makes me argue there is something unknown wrong with your project.

If you can reproduce this with the example, or post a reproduction I can help. As stated before, if you cannot, I cannot help
