### ISSUE TITLE
some error.

### ISSUE THREAD

**Issue by xclidongbo** [react-native-community/react-native-device-info#997]
# Bug

## Environment info

`react-native info` output:

```bash
$ react-native info
info
  React Native Environment Info:
    System:
      OS: macOS 10.15.3
      CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
      Memory: 249.36 MB / 8.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.2 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29
        Build Tools: 27.0.3, 28.0.3
        System Images: android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: ^0.59.10 => 0.59.10
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-fast-image: 7.0.2
```

Library version: x.x.x

## Steps To Reproduce

return some function, not true or false. 
```
function (){for(var o=arguments.length,l=new Array(o),f=0;f<o;f++)l[f]=arguments[f];return new Promise(function(o,f){u.enqueueNativeCall(n,t,l,function(n){return o(n)},function(n){return f(h(n))})})}
```

1.
2.
...

Describe what you expected to happen:

isEmulator() return a correct value.
1.
2.

**Comment by mikehardy** [comment]
Strange. isEmulator works perfectly in the example, I just checked it: - fix: getModel on iOS now returns generic device type (e.g. "iPhone") if the specific model is unrecognized (@TheAlmightyBob)


If you can post a minimal reproducible example on github (start with `react-native init sample-project` then add device info and edit the App.js to show the problem) then I can take a look, but I think it works

**Comment by xclidongbo** [comment]
@mikehardy 
"react-native-device-info": "^2.3.2"
````
_reactNativeDeviceInfo.default.isEmulator(...).then is not a function
```

**Comment by mikehardy** [comment]
Current version v5.5.5 https://github.com/react-native-community/react-native-device-info/blob/master/CHANGELOG.md#555

Upgrade

**Comment by xclidongbo** [comment]
@mikehardy   my project can not support androidx, can I install it?

**Comment by mikehardy** [comment]
You should really update your project. AndroidX is the only way in the future.
However, I recognize people need a bridge between old support libraries and AndroidX so I wrote one. Behold the jetifier: https://github.com/mikehardy/jetifier

It's actually integrated directly into the react-native CLI now, but that's only in versions 0.61+

You'll want reverse mode.
