### ISSUE TITLE
DeviceInfo.getUniqueId() and DeviceInfo.getDeviceId() always returns unknown

### ISSUE THREAD

**Issue by artmerlop** [react-native-community/react-native-device-info#998]
My code:

```
let uid = DeviceInfo.getUniqueId()
console.log(uid)
```

Te value is always unknown on iOS.

**Comment by mikehardy** [comment]
How'd it go when you ran the example?

**Comment by karthikmandava7** [comment]
@artmerlop do you have found the fix for this issue

**Comment by mikehardy** [comment]
@karthikmandava7 have you checked to see if this varies on newer iOS devices? It's possible they've changed the behaviour here or require more permissions, I'm not sure https://github.com/react-native-community/react-native-device-info/blob/master/README.md#getuniqueid
