### ISSUE TITLE
some device model is not right in devicesWithNotch.ts

### ISSUE THREAD

**Issue by chj-damon** [react-native-community/react-native-device-info#999]
# Bug

I use `getBrand()` and `getModel()` method to test different devices, I found out that it is different from the deviceinfo in `devicesWithNotch.ts`.
for example:
	Huawei Mate 20 Pro, `getBrand()` returns 'HUAWEI', `getModel()` returns `LYA-AL00`, but in `devicesWithNotch.ts`, model is `Mate 20 Pro`.

I don't know if this is a common mistake which happens in other devices.
[deviceDetectApp.apk.zip](https://github.com/react-native-community/react-native-device-info/files/4490693/deviceDetectApp.apk.zip)

## Environment info

`react-native info` output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1. upzip this attachment
2. install this app in different devices, it will display the brand and model of this phone.
...

Describe what you expected to happen:

the brand and model should match with `devicesWithNotch.ts`

**Comment by mikehardy** [comment]
PRs always welcome
